src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CategoryAreaSIM__c</fullName>
        <inlineHelpText>Category Area wiht highest spend with this supplier</inlineHelpText>
        <label>Category Area</label>
        <picklist>
            <picklistValues>
                <fullName>DELIVERY OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not defined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICES PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDIRECT PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRODUCT PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enterprise_Id__c</fullName>
        <encrypted>true</encrypted>
        <label>Enterprise  Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Supplier Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Supplier Manager</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Unit__c</fullName>
        <inlineHelpText>The lead supplier manager&apos;s unit</inlineHelpText>
        <label>Lead Unit</label>
        <picklist>
            <picklistValues>
                <fullName>DO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSCM AMS PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nokia_as_a_Customer__c</fullName>
        <inlineHelpText>Supplier&apos;s view on Nokia as a customer (estimation)</inlineHelpText>
        <label>Supplier View</label>
        <picklist>
            <controllingField>Supplier_Segmentation__c</controllingField>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exploit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nuisance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not defined</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier_Segmentation__c</fullName>
        <inlineHelpText>Supplier Segmentation based on Kraljic Matrix</inlineHelpText>
        <label>Supplier Segmentation</label>
        <picklist>
            <picklistValues>
                <fullName>Strategic Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manage Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shop</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <label>Total Risk Assesment Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/riskSummaryTest.cls
@isTest
public class riskSummaryTest{
    static testMethod void riskTest() {
      
        User testUser = new User(FirstName = 'test', LastName = 'user', Email = 'test.user@gmail.com', Alias = 'test', ProfileID = '00eU0000000UGZX', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', LocaleSidKey='en_US', 
             TimeZoneSidKey='America/Los_Angeles', UserName='testUser@SPEorg.com');
        insert testUser;
        system.debug('User insersted !!!!!'+testUser);
        
        
        List<Account> accTestList = new List<Account>();
        for(integer i = 1;i<6;i++){
        Account accTest = new Account(Name = 'Test Supplier'+string.valueOf(i),Enterprise_Id__c = 'SupplierTest123'+string.valueOf(i), CategoryAreaSIM__c= 'Delivery Operations (DO)', LSM__c = testUser.id, Supplier_Segmentation__c = 'Shop', Nokia_as_a_Customer__c = 'Core',Total_Score__c = 100*i, Lead_Unit__c = 'PPO');
        accTestList.add(accTest);
        }
        for(integer i = 10;i<16;i++){
        Account accTest = new Account(Name = 'Test Supplier'+string.valueOf(i),Enterprise_Id__c = 'SupplierTest123'+string.valueOf(i), CategoryAreaSIM__c= 'Delivery Operations (DO)', LSM__c = testUser.id, Supplier_Segmentation__c = 'Shop', Nokia_as_a_Customer__c = 'Core',Total_Score__c = 20*i, Lead_Unit__c = 'SPO');
        accTestList.add(accTest);
        }
        for(integer i = 20;i<26;i++){
        Account accTest = new Account(Name = 'Test Supplier'+string.valueOf(i),Enterprise_Id__c = 'SupplierTest123'+string.valueOf(i), CategoryAreaSIM__c= 'Delivery Operations (DO)', LSM__c = testUser.id, Supplier_Segmentation__c = 'Shop', Nokia_as_a_Customer__c = 'Core',Total_Score__c = 10*i, Lead_Unit__c = 'IPO');
        accTestList.add(accTest);
        }                
        for(integer i = 31;i<35;i++){
        Account accTest = new Account(Name = 'Test Supplier'+string.valueOf(i),Enterprise_Id__c = 'SupplierTest123'+string.valueOf(i), CategoryAreaSIM__c= 'Delivery Operations (DO)', LSM__c = testUser.id, Supplier_Segmentation__c = 'Shop', Nokia_as_a_Customer__c = 'Core',Total_Score__c = 20*i, Lead_Unit__c = 'GSCM AMS PO');
        accTestList.add(accTest);
        }
        
        insert accTestList;
        System.debug('Account inserted!!!!!'+accTestList);

        
       system.runAs(testUser)
    {
        Test.startTest();
        riskSummaryController data1 = new riskSummaryController();
        riskSummaryController.summaryData data = new riskSummaryController.summaryData();
        
        List<riskSummaryController.summaryData> dataSummary = riskSummaryController.getSummaryData();
        Test.stopTest();
    }
       }
       }