src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Procurement Category with highest spend with this supplier</inlineHelpText>
        <label>Category</label>
        <picklist>
            <controllingField>CategoryGroupSIM__c</controllingField>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building investment/CAPEX without Rents and Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Management services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental/Lease/Transactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure Services &amp; Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workplace Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associated Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coaching &amp; Other Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial, Tax &amp; Insurances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Intellectual Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Communications Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Peripheral Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Auxiliaries and Consumables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Incubation Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EnterpriseId__c</fullName>
        <encrypted>true</encrypted>
        <label>EncryptedEnterprise Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_Report_Configs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used for controlling Scope filters for Spend and Volume weight calculation</description>
    <fields>
        <fullName>Market_Filter_For_Volume__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Market Filter For Volume</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Filter_For_Spend__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Product Filter For Spend</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Filter_For_Volume__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Product Filter For Volume</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Report Configs</label>
</CustomObject>

src/objects/SPE_Stop__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Stop_trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Stop  KPI Recursoin</label>
</CustomObject>

src/objects/SPE_SurveyAnswer__c.object
<CustomObject>
    <description>For each Survey Question this object defines multiple Answers. The Answers have different types (Ex. Free text, Picklist, single answer etc.).</description>
    <fields>
        <fullName>Choices__c</fullName>
        <description>Choices for the particular question.</description>
        <inlineHelpText>User can have choices for a particular question.</inlineHelpText>
        <label>Choices</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <description>To show answers in order.</description>
        <inlineHelpText>To show answers in order.</inlineHelpText>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrimarySurvey_Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PrimarySurvey Answer</label>
        <referenceTo>SPE_SurveyAnswer__c</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Survey_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>Based on the answer it will update the Score.</description>
        <inlineHelpText>Based on users answer it will update the Score.</inlineHelpText>
        <label>Values</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Secondary_Language__c</fullName>
        <description>To store secondary Language</description>
        <label>Secondary Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <description>Automatically captures Questions while creating answers under Question Object.</description>
        <inlineHelpText>User can select questions for which they are creating answers.</inlineHelpText>
        <label>SurveyQuestion</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipName>SPE_SurveyAnswers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>Ans-{00000}</displayFormat>
        <label>Answers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_SurveyQuestion__c.object
<CustomObject>
    <customHelpPage>SPE_QuestionBank_Survey_Help_Page</customHelpPage>
    <description>SurveyQuestion object contains Question banks for the survey.</description>
    <fields>
        <fullName>AnswerType__c</fullName>
        <description>Answer type is required to base on Questions</description>
        <inlineHelpText>Select appropriate type of answer</inlineHelpText>
        <label>Answer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Free Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checkbox is TRUE to show question on survey page.</description>
        <inlineHelpText>It will show question on survey page if it is true</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>QuestionAbbreviation__c</fullName>
        <label>Question Abbreviation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Language__c</fullName>
        <label>Alternate Language</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <description>Question which will appear on Survey page</description>
        <inlineHelpText>Enter your question</inlineHelpText>
        <label>Survey Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question Bank</label>
    <nameField>
        <label>Questions ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DeleteAnswerTrggr_test.cls
@isTest(seeAllData=false)
public class DeleteAnswerTrggr_test{
    public static testmethod void DeleteAnswerTrggr_test_tst1(){
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';
        
        picklistObj.Business_Unit__c = 'ffff';
        picklistObj.Business_Line__c = 'nnnn';        
        picklistObj.Project__c = 'bbbb';
        
        picklistObj.Category_Area__c = 'rrrrr';
        picklistObj.Category_Group__c = 'ppppp';
        picklistObj.Category__c = 'qqqqq';               
        
        picklistObj.Market__c = 'sssssAts';
        picklistObj.Market_Unit__c = ' Market Units';
        picklistObj.Country__c = ' Countries';       
        picklistObj.Product__c = 'Products';
        
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
        
        SPE_Report_Configs__c Rconfig = new SPE_Report_Configs__c();
        Rconfig.Name= 'Test Report COnfig';
        Rconfig.Market_Filter_For_Volume__c = true;
        Rconfig.Product_Filter_For_Spend__c= true;
        Rconfig.Product_Filter_For_Volume__c= true;
        insert Rconfig;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@abctestorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing User', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testabcorg.com');
       
        insert u;     
       System.RunAs(u){ 
        list<Account> Acclist = new list<Account>();
            Account acc1 = new Account();
            acc1.Name = '3M';
            acc1.EnterpriseId__c = '3M';
            
        insert acc1;
        Acclist.add(acc1);
        Contact con = new Contact();
        con.LastName = 'Test Contact';
        con.AccountId = acc1.Id;
        con.Email = 'Deep.Banerjee@atos.net';
        insert con;
        
        Contact CCcon1 = new Contact();
        CCcon1.LastName = 'Test Contact1';
        CCcon1.AccountId = acc1.Id;
        CCcon1.Email = 'Deep.Banerjee1@atos.net';
        insert CCcon1;
        
        Contact CCcon2 = new Contact();
        CCcon2.LastName = 'Test Contact2';
        CCcon2.AccountId = acc1.Id;
        CCcon2.Email = 'Deep.Banerjee2@atos.net';
        insert CCcon2;
        
        Contact CCcon3 = new Contact();
        CCcon3.LastName = 'Test Contact3';
        CCcon3.AccountId = acc1.Id;
        CCcon3.Email = 'Deep.Banerjee3@atos.net';
        insert CCcon3;
        
        
        
        SPE_SurveyQuestion__c surQue = new SPE_SurveyQuestion__c();
        surQue.Name = 'SPE_Test Question';
        surQue.SurveyQuestion__c = 'What color is your hair?';
        surQue.AnswerType__c = 'Picklist';
        surQue.IsActive__c = true;
        surQue.QuestionAbbreviation__c = 'SPE_Que';
        insert surQue;
        
        SPE_SurveyAnswer__c surAns = new SPE_SurveyAnswer__c();
        surAns.Choices__c = 'ffff';
        surAns.OrderNumber__c = 12;
        surAns.PrimarySurvey_Answer__c = surAns.id;
        surAns.Secondary_Language__c = 'ffff';
        surAns.SurveyQuestion__c = surQue.id;
        surAns.Score__c = 1;
        insert surAns;
        
        delete surAns;
        
    }
    
    }
   }