src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CategoryArea__c</fullName>
        <label>Category Area</label>
        <picklist>
            <picklistValues>
                <fullName>Direct Services Procurement (DSP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indirect Procurement (INP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Networks Product Procurement (NPP)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <picklist>
            <picklistValues>
                <fullName>Antennas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Workforce Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Hardware and Care Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Services (NO &amp; NPO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Services (EMS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mechanics (MEC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI Installation &amp; Construction Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI Site Materials &amp; Power Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D and IT Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF Customized Components (RFC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF Products &amp; Castings (RFP&amp;C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software and System Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard &amp; Interconnect Components (STC, INT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems and Embedded Power (SEP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel &amp; Fleet</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Procurement Category with highest spend with this supplier</inlineHelpText>
        <label>Category</label>
        <picklist>
            <controllingField>CategoryGroupSIM__c</controllingField>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building investment/CAPEX without Rents and Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Management services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental/Lease/Transactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure Services &amp; Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workplace Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associated Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coaching &amp; Other Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial, Tax &amp; Insurances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Intellectual Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Communications Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Peripheral Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Auxiliaries and Consumables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Incubation Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EnterpriseId__c</fullName>
        <encrypted>true</encrypted>
        <label>EncryptedEnterprise Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_CategoryInfo__c.object
<CustomObject>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Categories_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Categories_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope Tag</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Category Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_ConsequenceManagement__c.object
<CustomObject>
    <fields>
        <fullName>CategoryArea__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>SPE</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Consequence_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Consequence Managements</relationshipLabel>
        <relationshipName>Consequence_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SupplierManagerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PPM/CM</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Consequence Managements (Supplier Manager Contact)</relationshipLabel>
        <relationshipName>Consequence_Managements1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Supplier that is the focus of this case</inlineHelpText>
        <label>Enterprise ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consequence Managements</relationshipLabel>
        <relationshipName>Consequence_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Consequence Management</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Consequence Management ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consequence Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_ConsequenceMngtAddContactExt.cls
public with sharing class SPE_ConsequenceMngtAddContactExt 
{
    private SPE_ConsequenceManagement__c speConsequenceMngt;
    public String contactName {get;set;}
    public Boolean isSupplierManager{get;set;}
    public List<Contact> contactSearchResult{get; set;}
    public List<User> userSearchResults {get;set;}
    
  //*******************Changes For Encryption*************************//  
    private String EID;
    private ID EIDEncrypted;
  //******************************END************************************//  
    
    private String defaultQuery; 
     
    public SPE_ConsequenceMngtAddContactExt(Apexpages.Standardcontroller st)
    {
        speConsequenceMngt = [SELECT Id, CategoryManager__c,CategoryArea__c, CategoryGroup__c, CategoryCluster__c, Supplier__c, Supplier__r.EnterpriseId__c, SupplierManagerContact__c, Contact__c
                                              FROM SPE_ConsequenceManagement__c 
                                              WHERE Id =: st.getId()];
        
     //*******************Changes For Encryption*************************//   
        EID = speConsequenceMngt.Supplier__r.EnterpriseId__c;
        EIDEncrypted = speConsequenceMngt.Supplier__c;
     //******************************END************************************//  
        
        isSupplierManager = false;
        if (Apexpages.currentPage().getParameters().get('supplierManager') != null)
        {
            isSupplierManager = true;
        }
        else
        {
          //*******************Changes For Encryption*************************//  
            //defaultQuery = 'SELECT Id, Email, FirstName, LastName, Account.EnterpriseId__c, (SELECT Category__c, CategoryCluster__c, CategoryGroup__c FROM Categories_Info__r ) FROM Contact WHERE Account.EnterpriseId__c =: EID';
            defaultQuery = 'SELECT Id, Email, FirstName, LastName,AccountId, Account.EnterpriseId__c, (SELECT Category__c, CategoryCluster__c, CategoryGroup__c FROM Categories_Info__r ) FROM Contact WHERE AccountId =: EIDEncrypted';
          //******************************END************************************//
            
            contactSearchResult = database.query(defaultQuery);
        }
        contactName ='';
    }   
    
    public void doSearch()
    {
        String whereCond = ' Where ';
        String query;
        
        String searchString = contactName;
        
        if  (searchString !=null && searchString.containsIgnoreCase('*'))
        {
            searchString = searchString.replaceAll('[*]', '%');
        }
        
        if(isSupplierManager)
        {
            userSearchResults = new list<User>();
            if(!string.isBlank(searchString))
            {
                query = 'SELECT Id, Email, Name, Username, Profile.Name, IsActive FROM User WHERE Name LIKE : searchString ';
            }
            
            if(query != null){
                userSearchResults = Database.query(query);
            }
            if(userSearchResults.isEmpty()){
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Either you have not mentioned User name or there are no existing records exists for selected user name'));
            }
        }
        else
        {
           
           //*******************Changes For Encryption*************************//
            query = 'SELECT Id, Email, FirstName, LastName,AccountId, Account.EnterpriseId__c, (SELECT Category__c, CategoryCluster__c, CategoryGroup__c FROM Categories_Info__r ) FROM Contact ';
           //******************************END************************************//
            
            contactSearchResult = new list<Contact>();
            if(string.isBlank(searchString))
            {
                if(speConsequenceMngt.Supplier__r.EnterpriseId__c !=null){
                    query = defaultQuery;
                }
            }
            else
            {
                query = query+ ' WHERE (FirstName LIKE : searchString  OR LastName LIKE : searchString) And AccountId != null';     
            }
            contactSearchResult = database.query(query);
            if(contactSearchResult.isEmpty())
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'There are no records exists for the given contact name'));
            }         
        }
    }
    
    public Pagereference addContact()
    {       
        if (isSupplierManager == false)
        {
            speConsequenceMngt.Contact__c = Apexpages.currentPage().getParameters().get('contactId');
        }   
        else
        {
            speConsequenceMngt.CategoryManager__c = Apexpages.currentPage().getParameters().get('contactId');            
        }
        
        update speConsequenceMngt;
        
        Pagereference pr = new Pagereference('/'+speConsequenceMngt.Id);
      
        return pr;
    }
    
    
    public Pagereference cancel()
    {
        Pagereference pr = new Pagereference('/'+speConsequenceMngt.Id);
      
        return pr;
    }
    
  }