src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Supplier Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Supplier Manager</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Category_Manager__c</fullName>
        <formula>LSM__r.FirstName+&quot; &quot;+LSM__r.LastName</formula>
        <label>Lead Category Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAM_Innovation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Innovation Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Executive Sponsor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Governance_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Governance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PI_Param__c.object
<CustomObject>
    <fields>
        <fullName>Commercial__c</fullName>
        <label>Commercial</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Delivery__c</fullName>
        <label>Delivery</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Innovation__c</fullName>
        <label>Innovation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Quality__c</fullName>
        <label>Quality</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <label>Supplier Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PI Params</relationshipLabel>
        <relationshipName>PI_Params</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sustainability__c</fullName>
        <label>Sustainability</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>PI Param</label>
    <nameField>
        <displayFormat>PI Param - {0}</displayFormat>
        <label>PI Param ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Params</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StrategicSupplierOverviewController.cls
public class StrategicSupplierOverviewController{
    public List<RadarData> data {get;set;}
    public static String id;
    Public Map<String,Decimal> radraMap;
    public StrategicSupplierOverviewController(){
        id=userinfo.getuserId();
    radraMap = new Map<String,Decimal>();
        List<PI_Param__c> piPramaList = new List<PI_Param__c>();
        for(Account acc : [select id,Name,LSM__c,Supplier_Governance_Manager__c,Business_Owner__c,SAM_Innovation_Manager__c,Sponsor__c,(select Delivery__c,Innovation__c,Quality__c,Relationship__c,Commercial__c,Sustainability__c FROM PI_Params__r ORDER BY CreatedDate desc limit 1 ) from Account where (LSM__c=:id OR SAM_Innovation_Manager__c=:id OR Supplier_Governance_Manager__c=:id OR Sponsor__c=:id or Lead_Category_Manager__c=:id) and Unique_Id__c != NULL]){
            if(!acc.PI_Params__r.isEmpty()){  
                PI_Param__c  param = acc.PI_Params__r;
              if(param.Delivery__c != null || param.Innovation__c != null || param.Quality__c != null
                 || param.Relationship__c != null || param.Commercial__c != null || param.Sustainability__c != null){
                     piPramaList.add(acc.PI_Params__r) ;
                 }
                
            }

        }

        radraMap.put('Quality',0);
        radraMap.put('Commercial',0);
        radraMap.put('Delivery',0);
        radraMap.put('Innovation',0);
        radraMap.put('Relationship',0);
        radraMap.put('Sustainability',0);
          system.debug('test$$$$$$');
        for(PI_Param__c acc : piPramaList ){
system.debug('Param record......'+acc);
            if(acc.Quality__c != null)
        radraMap.put('Quality', radraMap.get('Quality')+acc.Quality__c);
            
            if(acc.Commercial__c != null)
          radraMap.put('Commercial', radraMap.get('Commercial')+acc.Commercial__c);
            
            if(acc.Delivery__c != null)
          radraMap.put('Delivery', radraMap.get('Delivery')+acc.Delivery__c);
            
            if(acc.Innovation__c != null)
          radraMap.put('Innovation', radraMap.get('Innovation')+acc.Innovation__c);
            
            if(acc.Relationship__c != null)
          radraMap.put('Relationship', radraMap.get('Relationship')+acc.Relationship__c);
             if(acc.Sustainability__c != null)
          radraMap.put('Sustainability', radraMap.get('Sustainability')+acc.Sustainability__c);
          system.debug('radraMap.....'+radraMap);
        }
 try{       
        for(String str : radraMap.keyset()){
            radraMap.put(str,radraMap.get(str)/piPramaList.size());
        }
        system.debug('after avg.....'+radraMap);
        data = new List<RadarData> ();
        for(String str : radraMap.keyset()){
            data.add(new RadarData(str, radraMap.get(str),100));
        }
                  
}
    catch(Exception ex){
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'No data available');
            ApexPages.addMessage(myMsg);
    }
     //system.debug('datadatadata'+data[0].finalparam);                 
    }
    
    public class RadarData {
        Public String performanceParam{get;set;}
        Public Decimal percentage{get;set;}
        Public String finalparam{get;set;}
        public Decimal maxLimit { set; get; }
        
        public RadarData(String performanceParam, Decimal percentage, Decimal maxLimit) {
            this.performanceParam= performanceParam;
            this.percentage= percentage;
            this.finalparam = performanceParam + ':' + percentage;
            this.maxLimit = maxLimit;
        }
    }
}