src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <picklist>
            <picklistValues>
                <fullName>Antennas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Workforce Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Hardware and Care Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Services (NO &amp; NPO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Services (EMS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mechanics (MEC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI Installation &amp; Construction Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI Site Materials &amp; Power Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D and IT Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF Customized Components (RFC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF Products &amp; Castings (RFP&amp;C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software and System Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard &amp; Interconnect Components (STC, INT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems and Embedded Power (SEP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel &amp; Fleet</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Procurement Category with highest spend with this supplier</inlineHelpText>
        <label>Category</label>
        <picklist>
            <controllingField>CategoryGroupSIM__c</controllingField>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building investment/CAPEX without Rents and Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Management services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental/Lease/Transactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure Services &amp; Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workplace Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associated Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coaching &amp; Other Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial, Tax &amp; Insurances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Intellectual Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Communications Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Peripheral Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Auxiliaries and Consumables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Incubation Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_CategoryInfo__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Role__c</fullName>
        <label>Business Role</label>
        <picklist>
            <picklistValues>
                <fullName>Category Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Category Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier Manager</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Categories_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Categories_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Role__c</fullName>
        <label>System Role</label>
        <picklist>
            <picklistValues>
                <fullName>Developed Ticket Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase Out Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PI Uploader</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scorecard Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey Respondent</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Scope Tag</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Category Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_Stop__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Stop_trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Stop  KPI Recursoin</label>
</CustomObject>

src/classes/SPE2_CategoryInfoExtTest.cls
@isTest(SeeAllData = false)
private class SPE2_CategoryInfoExtTest{
        
     static testMethod void createNewCatInfoForSaveTest1(){ 
      LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Market__c= 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Project__c = 'All Projects';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c ='All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Product__c = 'All Products';
        picklistObj.Name = 'Picklist Default Values';
    
        lstpicklistObj.add(picklistObj);
        insert lstpicklistObj;
    
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
        
        PicklistDefaultValues__c defaultPicklist = SPE_TestObjectCreator.CreateDefaultPicklist();
        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        insert testAccount;
         
        Contact cont = new Contact();
        cont.FirstName='Test';
        cont.LastName='Test';
        cont.Accountid= testAccount.id;
        cont.Email= 'abc@gmail.com';       
        insert cont;
        
        Account supplier = SPE_TestObjectCreator.CreateSupplier('ABC');
        insert supplier; 
        
        SPE_CategoryInfo__c catInfo = new SPE_CategoryInfo__c ();
        catInfo.Supplier__c = supplier.ID;
        catInfo.BusinessLine__c = 'All Business Lines';
        catInfo.Business_Role__c = 'System Administrator';
        catInfo.BusinessUnit__c ='All Business Units';
        catInfo.Category__c ='All Categories';
        catInfo.CategoryCluster__c ='All Category Areas';
        catInfo.CategoryGroup__c = 'All Category Groups';
        catInfo.Contact__c = cont.ID;
        catInfo.Country__c = 'All Countries'; 
        catInfo.Region__c ='All Markets';
        catInfo.SubRegion__c = 'All Market Units';
        catInfo.Product__c = 'All Products';
        catInfo.Project__c = 'All Projects';
       // catInfo.System_Role__c = 'User'
        insert catInfo;
        
        Test.StartTest();  
        PageReference pageRef = Page.SPE2_SPECategoryInfo;
        Test.setCurrentPage(pageRef);                      
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(catInfo);
        SPE2_CategoryInfoEXT catInfo1 = new SPE2_CategoryInfoEXT(stCon);
        catInfo1.getMarketValues();
        catInfo1.getMarketUnitValues();
        catInfo1.fillMarketUnit();
        catInfo1.getCountryValues();
        catInfo1.fillCountry();
        catInfo1.getProjectValues();
        catInfo1.fillProject();
        catInfo1.getBusinessUnitValues();
        catInfo1.getBusinesLineValues();
        catInfo1.fillBusinessLine();
        catInfo1.getProductValues();
        catInfo1.showProdVals();
        catInfo1.fillProduct();
        catInfo1.getCategoryAreaValues();
        catInfo1.getCategoryGroupValues();
        catInfo1.fillCategoryGroup();
        catInfo1.getCategoryValues();
        catInfo1.fillCategory();
        catInfo1.blankMethod();
        catInfo1.save();
        catInfo1.cancel();
        
        Test.StopTest();
    }
    
    static testMethod void createNewCatInfoForSaveTest2(){ 
      LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Market__c= 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Project__c = 'All Projects';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c ='All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Product__c = 'All Products';
        picklistObj.Name = 'Picklist Default Values';
    
        lstpicklistObj.add(picklistObj);
        insert lstpicklistObj;
    
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
        
        PicklistDefaultValues__c defaultPicklist = SPE_TestObjectCreator.CreateDefaultPicklist();
        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        insert testAccount;
         
        Contact cont = new Contact();
        cont.FirstName='Test';
        cont.LastName='Test';
        cont.Accountid= testAccount.id;
        cont.Email= 'abc@gmail.com';       
        insert cont;
        
        Account supplier = SPE_TestObjectCreator.CreateSupplier('ABC');
        insert supplier; 
        
        SPE_CategoryInfo__c catInfo = new SPE_CategoryInfo__c ();
        catInfo.Supplier__c = supplier.ID;
        catInfo.BusinessLine__c = 'All Business Lines';
        catInfo.Business_Role__c = 'System Administrator';
        catInfo.BusinessUnit__c ='All Business Units';
        catInfo.Category__c ='All Categories';
        catInfo.CategoryCluster__c ='All Category Areas';
        catInfo.CategoryGroup__c = 'All Category Groups';
        catInfo.Contact__c = cont.ID;
        catInfo.Country__c = 'All Countries'; 
        catInfo.Region__c ='All Markets';
        catInfo.SubRegion__c = 'All Market Units';
        catInfo.Product__c = 'All Products';
        catInfo.Project__c = 'All Projects';
       // catInfo.System_Role__c = 'User'
        insert catInfo;
        
        Test.StartTest();  
        PageReference pageRef = Page.SPE2_SPECategoryInfo;
        Test.setCurrentPage(pageRef);                      
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(new SPE_CategoryInfo__c());
        SPE2_CategoryInfoEXT catInfo1 = new SPE2_CategoryInfoEXT(stCon);
        catInfo1.getMarketValues();
        catInfo1.getMarketUnitValues();
        catInfo1.fillMarketUnit();
        catInfo1.getCountryValues();
        catInfo1.fillCountry();
        catInfo1.getProjectValues();
        catInfo1.fillProject();
        catInfo1.getBusinessUnitValues();
        catInfo1.getBusinesLineValues();
        catInfo1.fillBusinessLine();
        catInfo1.getProductValues();
        catInfo1.showProdVals();
        catInfo1.fillProduct();
        catInfo1.getCategoryAreaValues();
        catInfo1.getCategoryGroupValues();
        catInfo1.fillCategoryGroup();
        catInfo1.getCategoryValues();
        catInfo1.fillCategory();
        catInfo1.blankMethod();
        catInfo1.save();
        catInfo1.cancel();
        
        Test.StopTest();
        
     }
      static testMethod void createNewCatInfoForSaveTest3()
      { 
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Market__c= 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Project__c = 'All Projects';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c ='All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Product__c = 'All Products';
        picklistObj.Name = 'Picklist Default Values';
    
        lstpicklistObj.add(picklistObj);
        insert lstpicklistObj;
    
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
        
        PicklistDefaultValues__c defaultPicklist = SPE_TestObjectCreator.CreateDefaultPicklist();
        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        insert testAccount;
         
        Contact cont = new Contact();
        cont.FirstName='Test';
        cont.LastName='Test';
        cont.Accountid= testAccount.id;
        cont.Email= 'abc@gmail.com';       
        insert cont;
        
        Account supplier = SPE_TestObjectCreator.CreateSupplier('ABC');
        insert supplier; 
        
        SPE_CategoryInfo__c catInfo = new SPE_CategoryInfo__c ();
        catInfo.Supplier__c = supplier.ID;
        catInfo.BusinessLine__c = 'All Business Lines';
        catInfo.Business_Role__c = 'System Administrator';
        catInfo.BusinessUnit__c ='All Business Units';
        catInfo.Category__c ='All Categories';
        catInfo.CategoryCluster__c ='All Category Areas';
        catInfo.CategoryGroup__c = 'All Category Groups';
        catInfo.Contact__c = cont.ID;
        catInfo.Country__c = 'All Countries'; 
        catInfo.Region__c ='All Markets';
        catInfo.SubRegion__c = 'All Market Units';
        catInfo.Product__c = 'All Products';
        catInfo.Project__c = 'All Projects';
       // catInfo.System_Role__c = 'User'
        insert catInfo;
        
        Test.StartTest();  
        PageReference pageRef = Page.SPE2_SPECategoryInfo;
        Apexpages.currentPage().getParameters().put('caVal', 'All Categories');
        
        Test.setCurrentPage(pageRef);                      
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(catInfo);
        SPE2_CategoryInfoEXT catInfo1 = new SPE2_CategoryInfoEXT(stCon);
        
        catInfo1.getCategoryGroupValues();
        
        
        Apexpages.currentPage().getParameters().put('caVal', 'All Categories');
        
        Test.setCurrentPage(pageRef);                      
        Apexpages.Standardcontroller stCon1 =  new Apexpages.Standardcontroller(catInfo);
        SPE2_CategoryInfoEXT catInfo2 = new SPE2_CategoryInfoEXT(stCon1);
        
        catInfo2.getMarketUnitValues();
        catInfo2.getCountryValues();
        catInfo2.fillCountry();
        
        Test.StopTest();
        }
        
 static testMethod void createNewCatInfoForSaveTest4()
      { 
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Market__c= 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Project__c = 'All Projects';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c ='All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Product__c = 'All Products';
        picklistObj.Name = 'Picklist Default Values';
    
        lstpicklistObj.add(picklistObj);
        insert lstpicklistObj;
    
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
        
        PicklistDefaultValues__c defaultPicklist = SPE_TestObjectCreator.CreateDefaultPicklist();
        
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
        insert testAccount;
         
        Contact cont = new Contact();
        cont.FirstName='Test';
        cont.LastName='Test';
        cont.Accountid= testAccount.id;
        cont.Email= 'abc@gmail.com';       
        insert cont;
        
        Account supplier = SPE_TestObjectCreator.CreateSupplier('ABC');
        insert supplier; 
        
        SPE_CategoryInfo__c catInfo = new SPE_CategoryInfo__c ();
        catInfo.Supplier__c = supplier.ID;
        catInfo.BusinessLine__c = 'All Business Lines';
        catInfo.Business_Role__c = 'System Administrator';
        catInfo.BusinessUnit__c ='All Business Units';
        catInfo.Category__c ='All Categories';
        catInfo.CategoryCluster__c ='All Category Areas';
        catInfo.CategoryGroup__c = 'All Category Groups';
        catInfo.Contact__c = cont.ID;
        catInfo.Country__c = 'All Countries'; 
        catInfo.Region__c ='All Markets';
        catInfo.SubRegion__c = 'All Market Units';
        catInfo.Product__c = 'All Products';
        catInfo.Project__c = 'All Projects';
       // catInfo.System_Role__c = 'User'
        insert catInfo;
        
        Test.StartTest();  
        PageReference pageRef = Page.SPE2_SPECategoryInfo;        
        Test.setCurrentPage(pageRef);  
        Apexpages.currentPage().getParameters().put('caVal', 'All Categories');
        Apexpages.currentPage().getParameters().put('cgVal', 'All Category Groups');
        Apexpages.currentPage().getParameters().put('ctVal', 'All Category Areas');
        Apexpages.currentPage().getParameters().put('marketVal', 'All Markets');
        Apexpages.currentPage().getParameters().put('marketUnitVal', 'All Market Units');
        Apexpages.currentPage().getParameters().put('countryVal', 'All Countries');
        Apexpages.currentPage().getParameters().put('buVal', 'All Business Units');
        Apexpages.currentPage().getParameters().put('blVal', 'All Business Lines');
        Apexpages.currentPage().getParameters().put('setCatVal', 'NAM');
        Apexpages.currentPage().getParameters().put('rerenderForm11', 'NAM');
                           
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(catInfo);
        SPE2_CategoryInfoEXT catInfo1 = new SPE2_CategoryInfoEXT(stCon);
        
        catInfo1.getCategoryGroupValues();

        Test.setCurrentPage(pageRef);                      
        Apexpages.Standardcontroller stCon1 =  new Apexpages.Standardcontroller(catInfo);
        SPE2_CategoryInfoEXT catInfo2 = new SPE2_CategoryInfoEXT(stCon1);
        
        catInfo2.getMarketUnitValues();
        catInfo2.getCountryValues();
        catInfo2.fillCountry();
        catInfo2.blankMethod();
        
        
        Test.StopTest();
        }

}