src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EnterpriseId__c</fullName>
        <encrypted>true</encrypted>
        <label>EncryptedEnterprise Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPEPlanSupplierMap__c.object
<CustomObject>
    <fields>
        <fullName>SPEPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>SPE Plan Supplier Maps</relationshipLabel>
        <relationshipName>SPE_Plan_Supplier_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SPE Plan Supplier Maps</relationshipLabel>
        <relationshipName>SPE_Plan_Supplier_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SPE Plan Supplier Map</label>
    <nameField>
        <displayFormat>SPSMI-{00000}</displayFormat>
        <label>SPE Plan Supplier Map Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plan Supplier Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPETracker__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>SPEPlan__c</fullName>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>SPE Trackers</relationshipLabel>
        <relationshipName>SPE_Trackers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SPE Tracker</label>
    <nameField>
        <label>SPE Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SPE_SPETrackerBatch.cls
global class SPE_SPETrackerBatch implements Database.Batchable<sObject>
{
    
    global Id speTrackerIds;
    global Id spePlanIds;
    
    public SPE_SPETrackerBatch (String speTrackerId, Id spePlanId)
    {
        speTrackerIds = speTrackerId;
        spePlanIds = spePlanId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        Id speTrackerIds = this.speTrackerIds;
        Id spePlanIds = this.spePlanIds;
        
        String query = 'SELECT Id, Supplier__c, Supplier__r.EnterpriseId__c FROM SPE_SPEPlanSupplierMap__c WHERE SPEPlan__c =: spePlanIds ';
        
        return Database.getQueryLocator(query);
   }
    
    global void execute(Database.BatchableContext BC, list<SPE_SPEPlanSupplierMap__c> scope) 
    {
        //*****************Changes are done as part of Encryption ***************************//
        //SPE_TrackerExecutionExt.SPETrackerExecutionBatch(speTrackerIds, spePlanIds, scope[0].Supplier__r.EnterpriseId__c, scope[0].Supplier__c);
        SPE_TrackerExecutionExt.SPETrackerExecutionBatch(speTrackerIds, spePlanIds, scope[0].Supplier__r.EnterpriseId__c, scope[0].Supplier__c);
        
        //*****************End ***************************//
    }
    
    global void finish(Database.BatchableContext BC) 
    {
       
        Set<Id> trackerId = new Set<Id>();
        trackerId.add(speTrackerIds);
        SPE_TrackerExecutionExt.aggregateScore(trackerId);
        SPE_SPETrackerBatch1 b1 = new SPE_SPETrackerBatch1(speTrackerIds);
        Database.executeBatch(b1, 1);
        /*String userEmail =String.valueof(Userinfo.getUserEmail()); 
        String trackerName= [select Name from SPE_SPETracker__c where Id=: speTrackerIds].name;
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
        
        String[] toAddresses = new String[] {userEmail}; 
        mail.setToAddresses(toAddresses); 
        mail.setSubject(System.Label.SPE_MailSubjectBatch5); 
        String body = 'SPE Tracker-'+ trackerName +' scheduled by '+String.valueof(UserInfo.getFirstName())+' '+String.valueof(UserInfo.getLastName())+ ' is scheduled Successfully.'+ ''+'Please Find The Link:';
        body = body + '  '+URL.getSalesforceBaseUrl().toExternalForm() + '/'+speTrackerIds; 
        mail.setPlainTextBody(body); 
        Messaging.sendEmail(new Messaging.SingleEMailMessage[]{mail});*/
    }
    

}