src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Procurement Category with highest spend with this supplier</inlineHelpText>
        <label>Category</label>
        <picklist>
            <controllingField>CategoryGroupSIM__c</controllingField>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building investment/CAPEX without Rents and Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Management services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental/Lease/Transactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure Services &amp; Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workplace Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associated Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coaching &amp; Other Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial, Tax &amp; Insurances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Intellectual Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Communications Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Peripheral Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Auxiliaries and Consumables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Incubation Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EnterpriseId__c</fullName>
        <encrypted>true</encrypted>
        <label>EncryptedEnterprise Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_BUBL__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductCode__c</fullName>
        <label>Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>BU BL</label>
    <nameField>
        <displayFormat>BBP-{0000}</displayFormat>
        <label>BU BL Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BU BL</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_Category_Transform_Table__c.object
<CustomObject>
    <fields>
        <fullName>FromValue__c</fullName>
        <label>From Value</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ToValue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ToValue</label>
        <referenceTo>SPE_CategoryMaster__c</referenceTo>
        <relationshipLabel>Category Transform Table</relationshipLabel>
        <relationshipName>Category_Transform_Table</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Category Transform Table</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Category Transform Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Transform Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_CategoryMaster__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CategoryMaster</label>
    <nameField>
        <displayFormat>CAT-{00000}</displayFormat>
        <label>CategoryMaster Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categories Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_EnterpriseIDTransformTable__c.object
<CustomObject>
    <fields>
        <fullName>FromValue__c</fullName>
        <label>From Value</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>EnterpriseID Transform Table</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EnterpriseID Transform Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_Geo_Transform_Table__c.object
<CustomObject>
    <fields>
        <fullName>FromValue__c</fullName>
        <label>From Value</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Geo Transform Table</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Geo Transform Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Geo Transform Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_PiValueTemp__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <encrypted>true</encrypted>
        <label>Enterprise ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketUnit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE_PiValueTemp</label>
    <nameField>
        <displayFormat>PV-{0000}</displayFormat>
        <label>SPE_PiValueTemp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE_PiValueTemps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_Product_Transform_Table__c.object
<CustomObject>
    <fields>
        <fullName>FromValue__c</fullName>
        <label>From Value</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Product Transform Table</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Product Transform Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Transform Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_ProjectMaster__c.object
<CustomObject>
    <fields>
        <fullName>CBT__c</fullName>
        <label>CBT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CT__c</fullName>
        <label>CT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketUnit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project Master</label>
    <nameField>
        <label>Project Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_PiValueTempValidateRecordsTest.cls
@IsTest(SeeAllData=false)

    public with sharing class SPE_PiValueTempValidateRecordsTest{
    static testmethod void SPE_PiValueTempValidateRecordsTest()
    {
    
     PicklistDefaultValues__c PickdefVal = new PicklistDefaultValues__c();
     PickdefVal.Name='Test';
     PickdefVal.Business_Line__c='test';
     PickdefVal.Business_Unit__c='test';
     PickdefVal.Category__c='test';
     PickdefVal.Category_Area__c='test';
     PickdefVal.Category_Group__c='test';
     PickdefVal.Country__c='test';
     PickdefVal.Market__c='test';
     PickdefVal.Market_Unit__c='test';
     PickdefVal.Product__c='test';
     PickdefVal.Project__c='test';
     
     insert PickdefVal;
    
     SPE_ProjectMaster__c promaster = new SPE_ProjectMaster__c();
     promaster.Name='test';
     promaster.CBT__c='test';
     promaster.Country__c='test';
     promaster.CT__c='test';
     promaster.Market__c='test';
     promaster.MarketUnit__c='test';
     promaster.Project__c='test';
     promaster.Region__c='test';
     
     
     insert promaster;
     
     
     SPE_BUBL__c bubl = new SPE_BUBL__c();
     bubl.BusinessLine__c='test';
     bubl.BusinessUnit__c='test';
     bubl.Product__c='test';
     bubl.ProductCode__c='test';
     insert bubl;
     
     
     SPE_CategoryMaster__c Catmaster = new SPE_CategoryMaster__c();
     Catmaster .Category__c='test';
     Catmaster .Cluster__c='test';
     Catmaster .Group__c='test';
     
     insert Catmaster;
     
     
     account acc= new account();
     acc.name='testing account';
     acc.enterpriseid__c='MO';
     
     insert acc;
     
     
/**************************************Enterprise Transform Table*******************************************************************************/      
     
     SPE_EnterpriseIDTransformTable__c EntTranstbl = new SPE_EnterpriseIDTransformTable__c();
     EntTranstbl .FromValue__c='test';
     EntTranstbl .ToValue__c=acc.id;
     
     insert EntTranstbl;
     
/**************************************Geo Transform Table*******************************************************************************/ 
     SPE_Geo_Transform_Table__c GeoTransTbl = new SPE_Geo_Transform_Table__c ();
     GeoTransTbl.FromValue__c='test';     
     GeoTransTbl.ToValue__c=promaster.id;
     GeoTransTbl.Transform__c='Market';
     insert GeoTransTbl;
     
     SPE_Geo_Transform_Table__c GeoTransTbl1 = new SPE_Geo_Transform_Table__c ();
     GeoTransTbl1.FromValue__c='test axa1';     
     GeoTransTbl1.ToValue__c=promaster.id;
     GeoTransTbl1.Transform__c='Market Unit';
     insert GeoTransTbl1;
     
     
     SPE_Geo_Transform_Table__c GeoTransTbl2 = new SPE_Geo_Transform_Table__c ();
     GeoTransTbl2.FromValue__c='test axa2';     
     GeoTransTbl2.ToValue__c=promaster.id;
     GeoTransTbl2.Transform__c='Country';
     insert GeoTransTbl2;
     
      SPE_Geo_Transform_Table__c GeoTransTbl3 = new SPE_Geo_Transform_Table__c ();
     GeoTransTbl3.FromValue__c='test axa3';     
     GeoTransTbl3.ToValue__c=promaster.id;
     GeoTransTbl3.Transform__c='Project';
     insert GeoTransTbl3;



/**************************************Category Transform Table*******************************************************************************/ 

     SPE_Category_Transform_Table__c CatTransTbl = new SPE_Category_Transform_Table__c();
     CatTransTbl .FromValue__c='test';     
     CatTransTbl .ToValue__c=Catmaster.id;
     CatTransTbl .Transform__c='Category Area';
     insert CatTransTbl ;
     
     
     SPE_Category_Transform_Table__c CatTransTbl1 = new SPE_Category_Transform_Table__c();
     CatTransTbl1 .FromValue__c='test 11';     
     CatTransTbl1 .ToValue__c=Catmaster.id;
     CatTransTbl1 .Transform__c='Category Group';
     insert CatTransTbl1 ;
     
     
     
     SPE_Category_Transform_Table__c CatTransTbl2 = new SPE_Category_Transform_Table__c();
     CatTransTbl2 .FromValue__c='test 12';     
     CatTransTbl2 .ToValue__c=Catmaster.id;
     CatTransTbl2 .Transform__c='Category';
     insert CatTransTbl2 ;
     
     

/**************************************Product  Transform Table*******************************************************************************/      
     
     SPE_Product_Transform_Table__c ProdTransTbl = new SPE_Product_Transform_Table__c ();
     ProdTransTbl .FromValue__c='test 11';     
     ProdTransTbl .ToValue__c=bubl.id;
     ProdTransTbl .Transform__c='Business Unit';
     insert ProdTransTbl ;
     
     SPE_Product_Transform_Table__c ProdTransTbl1 = new SPE_Product_Transform_Table__c ();
     ProdTransTbl1 .FromValue__c='test 12';     
     ProdTransTbl1 .ToValue__c=bubl.id;
     ProdTransTbl1 .Transform__c='Business Line';
     insert ProdTransTbl1 ;
     
     SPE_Product_Transform_Table__c ProdTransTbl2 = new SPE_Product_Transform_Table__c ();
     ProdTransTbl2 .FromValue__c='test 13';     
     ProdTransTbl2 .ToValue__c=bubl.id;
     ProdTransTbl2 .Transform__c='Product';
     insert ProdTransTbl2 ;
          
     
     
/**************Category='Category' & category__c!=null , GeoScope__c='Project' & project__c!= null******************************************/
     
     
     SPE_PIDefinition__c pd1= new SPE_PIDefinition__c();
     
   //**********************Changes For Encryption******************//  
     //pd1.name= 'test pd1';
     pd1.PI_Title__c = 'test pd1';
   //**********************END******************//  
     
     pd1.PIAbbreviation__c='pabb';   
     pd1.ValuesType__c='Number';
     pd1.UoM__c='number';
     pd1.DataAcquisitionMethod__c='Survey Question';
     pd1.GeoScope__c='Project';
     pd1.CategoryScope__c='Category';
     pd1.BUScope__c='Product';
     
     insert pd1;
     
  //**********************Changes For Encryption******************//
     //system.assertequals(pd1.name,'test pd1');
     system.assertequals(pd1.PI_Title__c,'test pd1');
  //**********************END******************//
     
       SPE_PiValueTemp__c PIvalTemp1 = new SPE_PiValueTemp__c();    
        PIvalTemp1 .CurrencyIsoCode='EUR';
        PIvalTemp1 .PIDefination__c=Pd1.Id;
        PIvalTemp1 .EnterpriseId__c='MO';
        PIvalTemp1 .project__c='test';
        //PIvalTemp1 .country__c='test';
        //PIvalTemp1 .Cluster__c='test';
        PIvalTemp1 .Category__c='test';
        PIvalTemp1 .product__c='test';
        PIvalTemp1 .BusinessUnit__c='test';
        PIvalTemp1 .BusinessLine__c='test';        
        PIvalTemp1 .ValidateCategory__c =false;
        PIvalTemp1 .Verified_Geo__c=true;
        PIvalTemp1 .Verified_BU__c=false;
        PIvalTemp1 .VerrifiedEnterpriseID__c=true;
        Insert PIvalTemp1 ;
        
        PIvalTemp1 .EnterpriseId__c='Test';
        
              
        update PIvalTemp1 ;
        
        
        
/************************Category='Category Area' & Cluster__c!=null , GeoScope__c='Country' & MarketUnit__c!=null**********************/
          
          
          
       SPE_PIDefinition__c pd2= new SPE_PIDefinition__c();
       
    //**********************Changes For Encryption******************//  
         //pd2.name= 'test pd2';
         pd2.PI_Title__c = 'test pd2';
   //**********************END******************//
       
       pd2.PIAbbreviation__c='pabb1';   
       pd2.ValuesType__c='Number';
       pd2.UoM__c='number';
       pd2.DataAcquisitionMethod__c='Survey Question';
       pd2.GeoScope__c='Country';
       pd2.CategoryScope__c='Category Area';
       pd2.BUScope__c='Business unit';
     
       insert pd2;
 
  //**********************Changes For Encryption******************//
     //system.assertequals(pd2.name,'test pd2');
     system.assertequals(pd2.PI_Title__c,'test pd2');
  //**********************END******************//
     
          
        SPE_PiValueTemp__c PIvalTemp2 = new SPE_PiValueTemp__c();    
        PIvalTemp2 .CurrencyIsoCode='EUR';
        PIvalTemp2 .PIDefination__c=Pd2.Id;
        PIvalTemp2 .EnterpriseId__c='test';
        //PIvalTemp2 .project__c='test';
        PIvalTemp2 .country__c='test';
        PIvalTemp2 .Cluster__c='test';
        //PIvalTemp2 .product__c='test';
        PIvalTemp2 .BusinessUnit__c='test';
        PIvalTemp2 .BusinessLine__c='Business Line';        
        PIvalTemp2 .ValidateCategory__c =true;
        //PIvalTemp2 .categorygroup__c='test';
        PIvalTemp2 .MarketUnit__c='Market Unit';
        PIvalTemp2 .ValidateCategory__c =false;
        PIvalTemp2 .Verified_Geo__c=false;
        PIvalTemp2 .Verified_BU__c=false;
        PIvalTemp2 .VerrifiedEnterpriseID__c=true;
        Insert PIvalTemp2 ;
      
        PIvalTemp2 .EnterpriseId__c='MO';
        
        update PIvalTemp2 ;
        

/********************************Category='Category Group' & categorygroup__c!=null**************************************************************/
        
      SPE_PIDefinition__c pd3= new SPE_PIDefinition__c();
      
   //**********************Changes For Encryption******************//  
         //pd3.name= 'test pd3';
         pd3.PI_Title__c = 'test pd3';
   //**********************END******************//
   
      pd3.PIAbbreviation__c='pabb3';   
      //pd3.ValuesType__c='Market';
      pd3.UoM__c='number';
      pd3.DataAcquisitionMethod__c='Survey Question';
      pd3.GeoScope__c='Market Unit';
      pd3.CategoryScope__c='Category Group';
      pd3.BUScope__c='Business Line';
     
      insert pd3;
  
  //**********************Changes For Encryption******************//
     //system.assertequals(pd3.name,'test pd3');
     system.assertequals(pd3.PI_Title__c,'test pd3');
  //**********************END******************//
   
        SPE_PiValueTemp__c PIvalTemp3 = new SPE_PiValueTemp__c();    
        PIvalTemp3 .CurrencyIsoCode='EUR';
        PIvalTemp3 .PIDefination__c=Pd3.Id;
        PIvalTemp3 .EnterpriseId__c='test';
        //PIvalTemp3 .project__c='test';
        //PIvalTemp3 .country__c='test';
        //PIvalTemp3 .Cluster__c='test';
        //PIvalTemp3 .product__c='test';
        PIvalTemp3 .BusinessUnit__c='Business Unit';
        PIvalTemp3 .BusinessLine__c='test';    
        PIvalTemp3 .MarketUnit__c='test';
        PIvalTemp3 .ValidateCategory__c =true;
        PIvalTemp3 .Verified_Geo__c=true;
        PIvalTemp3 .Verified_BU__c=true;
        PIvalTemp3 .Categorygroup__c='test';
         PIvalTemp3 .VerrifiedEnterpriseID__c=true;
       
        Insert PIvalTemp3 ;
        
        PIvalTemp3 .EnterpriseId__c='MO';   
        
        update PIvalTemp3 ;
       
/*******************************************GeoScope = Market******************************************************************************/
        
      SPE_PIDefinition__c pd4= new SPE_PIDefinition__c();
      
   //**********************Changes For Encryption******************//  
         //pd4.name= 'test pd4';
         pd4.PI_Title__c = 'test pd4';
   //**********************END******************// 
        
      pd4.PIAbbreviation__c='pabb4';   
     // pd4.ValuesType__c='Market';
      pd4.UoM__c='number';
      pd4.DataAcquisitionMethod__c='Survey Question';
      pd4.GeoScope__c='Market';
      pd4.CategoryScope__c='Category Group';
      pd3.BUScope__c='Product';
     
      insert pd4;
      
  //**********************Changes For Encryption******************//
     //system.assertequals(pd4.name,'test pd4');
     system.assertequals(pd4.PI_Title__c,'test pd4');
  //**********************END******************//  
      
     
        SPE_PiValueTemp__c PIvalTemp4 = new SPE_PiValueTemp__c();    
        PIvalTemp4 .CurrencyIsoCode='EUR';
        PIvalTemp4 .PIDefination__c=Pd3.Id;
        PIvalTemp4 .EnterpriseId__c='MO';
        //PIvalTemp4 .project__c='test';
        //PIvalTemp4 .country__c='test';
        //PIvalTemp4 .Cluster__c='test';
        PIvalTemp4 .product__c='test';
        PIvalTemp4 .BusinessUnit__c='Business Unit';
        PIvalTemp4 .BusinessLine__c='Business Line';    
        PIvalTemp4 .Market__c='test';
        PIvalTemp4 .MarketUnit__c='test';
        PIvalTemp4 .ValidateCategory__c =true;
        PIvalTemp4 .Verified_Geo__c=true;
        PIvalTemp4 .Categorygroup__c='test';
        PIvalTemp4 .VerrifiedEnterpriseID__c=true;
        
        
        Insert PIvalTemp4 ;
        
        PIvalTemp4 .EnterpriseId__c='Test';   
        
        update PIvalTemp4 ;




      SPE_PIDefinition__c pd5= new SPE_PIDefinition__c();
      
   //**********************Changes For Encryption******************//  
         //pd5.name= 'test pd5';
         pd5.PI_Title__c = 'test pd5';
   //**********************END******************//
   
      pd5.PIAbbreviation__c='pabb5';   
      pd5.ValuesType__c='Market';
      pd5.UoM__c='number';
      pd5.DataAcquisitionMethod__c='Survey Question';
      pd5.GeoScope__c='All Markets';
      pd5.CategoryScope__c='All Categories';
      pd3.BUScope__c='All Products';
     
      insert pd5;
  
  //**********************Changes For Encryption******************//
     //system.assertequals(pd5.name,'test pd5');
     system.assertequals(pd5.PI_Title__c,'test pd5');
  //**********************END******************//
     
        SPE_PiValueTemp__c PIvalTemp5 = new SPE_PiValueTemp__c();    
        PIvalTemp5 .CurrencyIsoCode='EUR';
        PIvalTemp5 .PIDefination__c=Pd3.Id;
        PIvalTemp5 .EnterpriseId__c='test';
        PIvalTemp5 .project__c='testing the class';
        PIvalTemp5 .country__c='testing the class';
        PIvalTemp5 .Cluster__c='testing the class';
        PIvalTemp5 .product__c='testing the class';
        PIvalTemp5 .BusinessUnit__c='testing the class';
        PIvalTemp5 .BusinessLine__c='testing the class';    
        PIvalTemp5 .Market__c='testing the class';
        PIvalTemp5 .MarketUnit__c='testing the class';
        //PIvalTemp5 .ValidateCategory__c =true;
        //PIvalTemp5 .Verified_Geo__c=true;
        //PIvalTemp5 .Verified_BU__c=true;
        PIvalTemp5 .Categorygroup__c='testing the class';
        
        
        Insert PIvalTemp5 ;
        
        PIvalTemp5 .EnterpriseId__c='MO';    
        
        update PIvalTemp5 ;
        
 }        
}