src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <picklist>
            <picklistValues>
                <fullName>Antennas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Workforce Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Hardware and Care Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Services (NO &amp; NPO)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Services (EMS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mechanics (MEC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI Installation &amp; Construction Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI Site Materials &amp; Power Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D and IT Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF Customized Components (RFC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF Products &amp; Castings (RFP&amp;C)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software and System Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard &amp; Interconnect Components (STC, INT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems and Embedded Power (SEP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel &amp; Fleet</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Procurement Category with highest spend with this supplier</inlineHelpText>
        <label>Category</label>
        <picklist>
            <controllingField>CategoryGroupSIM__c</controllingField>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building investment/CAPEX without Rents and Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Management services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental/Lease/Transactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure Services &amp; Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workplace Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associated Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coaching &amp; Other Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial, Tax &amp; Insurances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Intellectual Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Communications Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Peripheral Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Auxiliaries and Consumables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Incubation Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_CategoryInfo__c.object
<CustomObject>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Scope Tag</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Category Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_Respondent__c.object
<CustomObject>
    <fields>
        <fullName>SPEPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>Survey Respondents</relationshipLabel>
        <relationshipName>Survey_Respondents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Respondent</label>
    <nameField>
        <displayFormat>RDI-{00000}</displayFormat>
        <label>Respondents Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Respondents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPEPlan__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Area</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PRODUCT PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDIRECT PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICES PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNREPORTED SPEND</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>FACILITY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT PROCUREMENT &amp; TELECOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOGISTICS SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROFESSIONAL SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D SUBCONTRACTING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TESTING MANUFACTURING &amp; MEASUREMENT EQUIPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRAVEL &amp; FLEET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUSINESS INCUBATION &amp; E2E SOLUTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ELECTRONIC MANUFACTURING SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTERCONNECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MECHANICS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM/ODM/JDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPTICAL COMPONENTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEMICONDUCTOR AND RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STANDARD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CARE SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXTERNAL WORKFORCE SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI MATERIALS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBCONTRACTING MS NPO &amp; SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBCONTRACTING OTHER NI SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBCONTRACTING TELECOM IMPLEMENTATION SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEACTIVATED STRUCTURES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISCONTINUED BUSINESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPENDITURES REPORTED ERRONEOUSLY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NON-MANAGED EXPENDITURES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT ASSIGNED SPEND GROUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNREPORTED SPEND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D SOLUTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TESTING AND MANUFACTURING EQUIPMENT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SPE Plan</label>
    <nameField>
        <displayFormat>SPE - {00000}</displayFormat>
        <label>SPE Plan Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPEPlanSupplierMap__c.object
<CustomObject>
    <fields>
        <fullName>SPEPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>SPE Plan Supplier Maps</relationshipLabel>
        <relationshipName>SPE_Plan_Supplier_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SPE Plan Supplier Map</label>
    <nameField>
        <displayFormat>SPSMI-{00000}</displayFormat>
        <label>SPE Plan Supplier Map Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plan Supplier Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_SPEPlanRespondentExt.cls
public with sharing class SPE_SPEPlanRespondentExt 
{   
    public List<RespondentWrapper> respondentWrapperList {get;set;}
    
    private Id spePlanId;
    
    private SPE_SPEPlan__c spePlan;
    
    public String contactName {get;set;}
    
    private Set<Id> existContactIds = new Set<Id>();
     
    public SPE_SPEPlanRespondentExt (Apexpages.Standardcontroller st)
    {
        spePlanId = st.getId();
        
        spePlan = [SELECT Id, CategoryCluster__c, CategoryGroup__c, Category__c
                   FROM SPE_SPEPlan__c
                   WHERE Id =: spePlanId];
        
        addRespondent ();
    }   
    
    public void addRespondent ()
    {
        respondentWrapperList = new List<RespondentWrapper>();
        
        List<SPE_Respondent__c> respondents = [SELECT Id, Contact__c, Contact__r.Email, Contact__r.FirstName, Contact__r.LastName 
                                                   FROM SPE_Respondent__c
                                                   WHERE SPEPlan__c =: spePlanId];
        for (SPE_Respondent__c res: respondents)
        {
            existContactIds.add(res.Contact__c);
        }
        
        List<Contact> contactRespondentList = [SELECT Id, Email, FirstName, LastName, (SELECT Category__c, CategoryCluster__c, CategoryGroup__c FROM Categories_Info__r ) cat
                                               FROM Contact  
                                               WHERE Id In: existContactIds 
                                              ];
                                    
        Map<Id, List<SPE_CategoryInfo__c>> contactCategoriesMap = new Map<Id, List<SPE_CategoryInfo__c>>();
        
        for (Contact c: contactRespondentList)
        {
            contactCategoriesMap.put(c.Id, c.Categories_Info__r);
        }
        
        for (SPE_Respondent__c res: respondents)
        {
            RespondentWrapper rw = new RespondentWrapper(res, contactCategoriesMap.get(res.Contact__c));
            respondentWrapperList.add(rw);
        }
        
        Set<Id> contactsIds = new Set<Id>();
        
        for (SPE_CategoryInfo__c cat : [SELECT Category__c, CategoryCluster__c, CategoryGroup__c, Contact__c 
                                        FROM SPE_CategoryInfo__c
                                        WHERE ((CategoryCluster__c =: spePlan.CategoryCluster__c AND CategoryGroup__c = null AND Category__c = null) OR
                                                (CategoryCluster__c =: spePlan.CategoryCluster__c AND CategoryGroup__c =: spePlan.CategoryGroup__c AND Category__c = null) OR
                                                (CategoryCluster__c =: spePlan.CategoryCluster__c AND CategoryGroup__c =: spePlan.CategoryGroup__c AND Category__c =: spePlan.Category__c)
                                                ) AND
                                                Contact__c not In: existContactIds AND
                                                Contact__c != null])
        {
            contactsIds.add(cat.Contact__c);
        }
        
        
        List<SPE_SPEPlanSupplierMap__c> planSupplier = [SELECT Id, Supplier__c, Supplier__r.SupplierManager__c
                                                        FROM SPE_SPEPlanSupplierMap__c
                                                        WHERE SPEPlan__c =: spePlanId ];
        
        for (SPE_SPEPlanSupplierMap__c sup: planSupplier)
        {
            contactsIds.add(sup.Supplier__r.SupplierManager__c);
        }
        
        
        List<Contact> contactList = [SELECT Id, Email, FirstName, LastName, (SELECT Category__c, CategoryCluster__c, CategoryGroup__c FROM Categories_Info__r ) cat
                                     FROM Contact  
                                     Where Id In: contactsIds AND
                                           Id not In: existContactIds ];
        
        for (Contact c : contactList)
        {
            RespondentWrapper res = new RespondentWrapper(c, c.Categories_Info__r);
            
            respondentWrapperList.add(res);
            
            existContactIds.add(c.Id);
        }
        
    }
    
    public void searchRespondent ()
    {
        List<RespondentWrapper> selectedRespondent = new List<RespondentWrapper>();
        
        List<SPE_Respondent__c> toBeDeletedRespondent = new List<SPE_Respondent__c>();
        
        selectedRespondent.addAll(respondentWrapperList);
        
        respondentWrapperList.clear();
        
        
        for (RespondentWrapper r : selectedRespondent)
        {
            if (r.isChecked)
            {
                respondentWrapperList.add(r);
            }
            else
            {
                if (r.res.Id != null)
                {
                    toBeDeletedRespondent.add(r.res);
                }
                existContactIds.remove(r.res.Contact__c);
            }
        }
        
        delete toBeDeletedRespondent;
        
        String searchString = contactName;
        
        if  (searchString !=null && searchString.containsIgnoreCase('*'))
        {
            searchString = searchString.replaceAll('[*]', '%');
        }
        
        if (contactName != '' && contactName != '*')
        {
           List<Contact> contactList = [SELECT Id, Email, FirstName, LastName, (SELECT Category__c, CategoryCluster__c, CategoryGroup__c FROM Categories_Info__r ) cat
                                         FROM Contact  
                                         WHERE (FirstName LIKE: searchString OR LastName LIKE: searchString) AND
                                               Id not IN: existContactIds 
                                               LIMIT 100 ];
            for (Contact c : contactList)
            {
                RespondentWrapper res = new RespondentWrapper(c, c.Categories_Info__r);
                respondentWrapperList.add(res);
                existContactIds.add(c.Id);
            }   
        }
    }
    
    
    public Pagereference insertRespondent()
    {
        List<SPE_Respondent__c> toBeCreatedRespondent = createRespondent(respondentWrapperList);
        
        upsert toBeCreatedRespondent;
        
        Pagereference pr = new Pagereference('/'+spePlanId);
        
        return pr;
    }
    
    public Pagereference cancel()
    {
        Pagereference pr = new Pagereference('/'+spePlanId);
        
        return pr;
    }
    
    private List<SPE_Respondent__c> createRespondent (List<RespondentWrapper> respondentWrapperList)
    {
        
        List<SPE_Respondent__c> toBeCreatedRespondent = new List<SPE_Respondent__c>();
        
        List<SPE_Respondent__c> toBeDeletedRespondent = new List<SPE_Respondent__c>();
        
        for (RespondentWrapper rw : respondentWrapperList)
        {
            if (rw.isChecked)
            {
                rw.res.SPEPlan__c = spePlanId;
                toBeCreatedRespondent.add(rw.res);
            }
            else if (rw.isChecked == false && rw.res.Id != null)
            {
                toBeDeletedRespondent.add(rw.res);
            }
        }
        
        delete toBeDeletedRespondent;
        
        return toBeCreatedRespondent;
    }
    
    public class RespondentWrapper
    {
        public SPE_Respondent__c res {get;set;}
        public Boolean isChecked {get;set;}
        public List<SPE_CategoryInfo__c> categories {get;set;}
        
        public RespondentWrapper (SPE_Respondent__c res, List<SPE_CategoryInfo__c> cat)
        {
            this.res = res;
            isChecked = true;
            categories = cat;
        }
        
        public RespondentWrapper (Contact con, List<SPE_CategoryInfo__c> cat)
        {
            res = new SPE_Respondent__c();
            res.Contact__c = con.Id;
            res.Contact__r = con;
            
            categories = new List<SPE_CategoryInfo__c>();
            categories = cat;
            
            isChecked = false;
        }
    }

}