src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EnterpriseId__c</fullName>
        <encrypted>true</encrypted>
        <label>EncryptedEnterprise Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/KPI_IntermediateComputation__c.object
<CustomObject>
    <fields>
        <fullName>KPI_MappingScope__c</fullName>
        <label>KPI_MappingScope</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI_IntermediateComputations</relationshipLabel>
        <relationshipName>KPI_IntermediateComputations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>KPI_IntermediateComputation</label>
    <nameField>
        <displayFormat>KI-{0000}</displayFormat>
        <label>KPI_IntermediateComputation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI_IntermediateComputations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Master_KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI (Master KPI)</relationshipLabel>
        <relationshipName>KPI1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <description>Enter date when the KPI will be calculated (for data) or scheduled (for survey)</description>
        <inlineHelpText>This is an auto computed date looking at the underlying PI definitions (latest PI upload date + buffer days). This refreshes in batches and not instantaneously.</inlineHelpText>
        <label>Next Scheduled Date</label>
        <type>Date</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>PI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIUploadDuedate__c</fullName>
        <label>PI Upload Due date</label>
        <type>Date</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PIValues__c.object
<CustomObject>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <encrypted>true</encrypted>
        <label>Enterprise ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberValue__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PIDefination__c</fullName>
        <label>PI Defination</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>PI Values</relationshipLabel>
        <relationshipName>PI_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>PI Values</label>
    <nameField>
        <displayFormat>PVI-{00000}</displayFormat>
        <label>PI Values ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SPE2_DeleteKPIIntermediateTest.cls
@isTest(seeAllData = false)
private class SPE2_DeleteKPIIntermediateTest
{
   static testMethod void DeleteKPIIntermediateTest1() 
    {   
        Test.startTest();
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User u = new User(Alias = 'standt', Email='standarduser@abctestorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing User', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testabcorg.com');
       
        insert u;     
        System.RunAs(u){
        
         Account a = new Account();
        a.Name = 'COSCOM';
        a.enterpriseId__c='COSCOM';
        insert a;
        system.debug('account ::'+a);
                 
        
        SPE_PIDefinition__c pidef = SPE_TestObjectCreator.CreatePIDefinition();
         
         pidef.PIUploadDuedate__c = Date.newInstance(2016,6,24);       
         insert pidef;
        
         pidef.LifecycleStage__c = 'Pilot';
         update pidef;
         System.debug('pidef ::'+pidef);
        SPE_PIValues__c piVal = SPE_TestObjectCreator.CreatePIValues(pidef.id,a.id,a.enterpriseId__c);
        piVal.PIDefination__c =pidef.id;
        piVal.EnterpriseID__c = 'COSCOM';
        piVal.Period__c = Date.newInstance(2016,6,14);
        piVal.NumberValue__c =10;
        insert piVal;
        
        SPE_KPIDefinition__c masterkpi = new SPE_KPIDefinition__c();
        masterkpi = SPE_TestObjectCreator.CreateKPIDefinition(1);
        insert masterKpi;
        List<SPE_KPIDefinition__c> kpiList= new List<SPE_KPIDefinition__c >();
        for(integer i=0;i<1;i++){
            SPE_KPIDefinition__c kpiDefinition1 = new SPE_KPIDefinition__c();
            kpiDefinition1 = SPE_TestObjectCreator.CreateKPIDefinition(i);
            kpiDefinition1.Master_KPI__c = masterKpi.id;           
            kpiList.add(kpiDefinition1);
        }
        insert kpiList[0];
        for(SPE_KPIDefinition__c kp :kpiList){
            kp.LifecycleStage__c ='Pilot';            
            kp.ScheduledDate__c = kp.ScheduledDate__c.addDays(1);            
        }
        update kpilist;  
                
        List<KPI_IntermediateComputation__c> lstkpiInterComp = new List<KPI_IntermediateComputation__c>();
        KPI_IntermediateComputation__c kpiInterComp = new KPI_IntermediateComputation__c();
        kpiInterComp.KPI__c = kpilist[0].Id;
        //kpiInterComp.KPI_MappingScope__c = 
        insert kpiInterComp;
        lstkpiInterComp.add(kpiInterComp);
        
        SPE2_DeleteKPIIntermediate delKpiInter = new SPE2_DeleteKPIIntermediate(kpiList[0].Id+'');
        SchedulableContext scb ;
        Database.BatchableContext bcb;
        Database.executeBatch(delKpiInter , lstkpiInterComp.size());    
              
        }
        Test.stopTest();
    }
}