src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Procurement Category with highest spend with this supplier</inlineHelpText>
        <label>Category</label>
        <picklist>
            <controllingField>CategoryGroupSIM__c</controllingField>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building investment/CAPEX without Rents and Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Management services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental/Lease/Transactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure Services &amp; Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workplace Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associated Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coaching &amp; Other Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial, Tax &amp; Insurances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Intellectual Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Communications Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Peripheral Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Auxiliaries and Consumables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Incubation Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>PI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_Stop__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Stop_trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Stop  KPI Recursoin</label>
</CustomObject>

src/classes/SPE_KPISchedulePrebatch3AdhocTest.cls
@isTest(SeeAllData = False)
public class SPE_KPISchedulePrebatch3AdhocTest {

    public static testmethod void testSPE_KPISchedulePrebatch3AdhocMethod() {
       string enterprise='enterprise';
        //inserting pi 
        Date d=system.today();
        
        //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');      
        
        SPE_PIDefinition__c piDef = SPE_TestObjectCreator.CreatePIDefinition();      
       
        piDef.LifecycleStage__c = 'Draft';        
        piDef.GeoScope__c = 'Market';
        piDef.CategoryScope__c = 'Category Area';
        piDef.BUScope__c = 'Business Unit';       
        insert piDef;
        piDef.LifecycleStage__c = 'Published';
        update piDef;
        System.debug('inserting SPE_PIDefinition__c'+piDef.id);
        
        //entering supplier detail
        
        Account a=SPE_TestObjectCreator.CreateSupplier(enterprise);      
        insert a;
        System.debug('inserting supplier'+a.id);
        
       
         //SPE_KPIDefinition__c  details 
        SPE_KPIDefinition__c kpidef=SPE_TestObjectCreator.CreateKPIDefinition(1);      
        kpidef.Adhoc_Date__c=system.today().adddays(1); 
        kpidef.FrequencyinMonth__c='1';
        kpidef.ScheduledDate__c = System.today().adddays(2);
        kpidef.GeoScope__c = 'Market';
        kpidef.CategoryScope__c = 'Category Area';
        kpidef.BUScope__c = 'Business Unit';
        kpidef.Adhoc__c=true;        
        insert kpidef; 
        kpidef.ActualCalculation__c = 'A';
        kpidef.LifecycleStage__c='Pilot';
         update kpidef;    
         system.debug('inserting SPE_KPIDefinition__c done'+ kpidef.id);
         
         //inserting kpicalcualtion
          
         List<SPE_KPICalculation__c> listkpical=new List<SPE_KPICalculation__c>();        
        SPE_KPICalculation__c kpicalc=SPE_TestObjectCreator.createKPICalculation();    
        kpicalc.Aggregation__c='Min( Across Suppliers)';      
        kpicalc.KPIDefinition__c=kpidef.id;
        kpicalc.PIDefination__c=piDef.Id;
        kpicalc.TimeFrame__c=2;
        listkpical.add(kpicalc);
        
        SPE_KPICalculation__c kpicalc1=SPE_TestObjectCreator.createKPICalculation();      
        kpicalc1.Aggregation__c='Max( Across Suppliers)';       
        kpicalc1.KPIDefinition__c=kpidef.id;
        kpicalc1.PIDefination__c=piDef.Id;
        kpicalc1.TimeFrame__c=2;
        listkpical.add(kpicalc1);
        insert listkpical;
        
        //inserting supplier kpi calculation 
        
        Supplier_KPI_Callculation__c suppkpicalc=SPE_TestObjectCreator.createSupplierKPICal();
        suppkpicalc.EnterpriseID__c=a.EnterpriseId__c;        
        suppkpicalc.KPI__c=kpicalc.KPIDefinition__c;
        suppkpicalc.KPI_Calculation__c=kpicalc.id;
        insert suppkpicalc;
        system.debug('inserting Supplier_KPI_Callculation__c'+suppkpicalc.id);
        
       SPEKPIBatchSize__c size=new SPEKPIBatchSize__c();
        size.Size__c=2000;
        size.name='KPI Batch Size';
        insert size;
        system.debug('inserting SPEKPIBatchSize__c '+size.id);
        
        Supplier_KPI_Calculation_Adhoc__c batchObj1=new Supplier_KPI_Calculation_Adhoc__c();
        batchObj1.KPI__c=kpicalc.KPIDefinition__c;
        batchObj1.KPI_Calculation__c=kpicalc.id;
        insert batchObj1;
        
        System.debug('testing inserting Supplier_KPI_Calculation_Adhoc__c'+batchObj1.id );
        
    
        
        Test.startTest();
        System.AssertEquals(batchObj1.KPI__c,kpicalc.KPIDefinition__c);
        System.AssertEquals(size.name,'KPI Batch Size');
        SPE_KPISchedulePrebatch3Adhoc batchObj = new SPE_KPISchedulePrebatch3Adhoc(kpidef.id);
       
       
        Database.executeBatch(batchObj,200);
       
        
        Test.stopTest();
       
     
    
   
    
     
    
}
}