src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Actual_Spend__c</fullName>
        <defaultValue>00.00</defaultValue>
        <label>Actual Spend (YTD) (M€)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Business_Groups__c</fullName>
        <inlineHelpText>Business Groups which are buying from this supplier</inlineHelpText>
        <label>Business Groups</label>
        <picklist>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A&amp;A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Defined</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Business_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Classification__c</fullName>
        <inlineHelpText>Global Class of Supplier. Focus and Strategic suppliers are in scope of Supplier Relationship Management</inlineHelpText>
        <label>Classification</label>
        <picklist>
            <picklistValues>
                <fullName>Focus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier Base</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Supplier Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Supplier Manager</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nokia_as_a_Customer__c</fullName>
        <inlineHelpText>Supplier&apos;s view on Nokia as a customer (estimation)</inlineHelpText>
        <label>Supplier View</label>
        <picklist>
            <controllingField>Supplier_Segmentation__c</controllingField>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exploit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nuisance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not defined</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAM_Innovation_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Innovation Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Executive Sponsor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Governance_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Governance Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Segmentation__c</fullName>
        <inlineHelpText>Supplier Segmentation based on Kraljic Matrix</inlineHelpText>
        <label>Supplier Segmentation</label>
        <picklist>
            <picklistValues>
                <fullName>Strategic Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manage Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shop</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unique_Id__c</fullName>
        <externalId>true</externalId>
        <label>Unique Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/StakeHolder_Matrix_Supplier_contacts__c.object
<CustomObject>
    <fields>
        <fullName>Business_Group__c</fullName>
        <label>Business Role Supplier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encrypted>true</encrypted>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <encrypted>true</encrypted>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>SupplierName__c</fullName>
        <label>Supplier Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>StakeHolder Matrix - Supplier contacts</relationshipLabel>
        <relationshipName>StakeHolder_Matrix_Supplier_contacts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type_Of_Contact_Picklist__c</fullName>
        <label>Type Of Contact</label>
        <picklist>
            <picklistValues>
                <fullName>Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>StakeHolder Matrix - Supplier contact</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>StakeHolder Matrix - Supplier contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MySupplierDataController_Test.cls
@isTest
private class MySupplierDataController_Test{

@isTest
private static void MySupplierDataController_Test(){

Profile p = [Select Id from profile where Name = 'System Administrator'];
  User Usr23 = new User(FirstName = 'test', LastName = 'user', Email = 'test.user@gmail.com', Alias = 'test', ProfileID = p.id , EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='testUser@SPEorg.com');
    insert Usr23;

    Profile p1 = [Select Id from profile where Name = 'Supplier Manager'];
User supMgr = new User(FirstName = 'test', LastName = 'user', Email = 'test.user123@gmail.com', Alias = 'test123', ProfileID = p1.id , EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', LocaleSidKey='en_US',TimeZoneSidKey='America/Los_Angeles', UserName='testUser123@SPEorg.com');
    insert supMgr; 
    
    system.debug('***'+supMgr.id);
/*PageReference pageRef = Page.MySupplierCompleteView;
Test.setCurrentPage(pageRef);
ApexPages.currentPage().getParameters().put('Id',Usr23.id);
new MySupplierDataController().getContactDetails(Usr23.id);
MySupplierDataController mspdcontroller = new MySupplierDataController();*/
System.runas(Usr23){ 
        Account acc01 = new Account();
        acc01.Name = 'Test Account01';
        acc01.Model__c='Integrate';
        acc01.LSM__c = supMgr.id;
        acc01.SAM_Innovation_Manager__c= Usr23.id;
        acc01.Supplier_Governance_Manager__c = Usr23.id;
        acc01.Sponsor__c = Usr23.id;
        acc01.Supplier_Segmentation__c ='Leverage';
        acc01.Nokia_as_a_Customer__c = 'Develop';
        acc01.Business_Groups__c = 'sample';
        acc01.Business_Owner__c=Usr23.id;
      acc01.Actual_Spend__c = 19.5;
    acc01.Unique_Id__c = 'XYZ';    
    acc01.Classification__c = 'Focus';
        insert acc01;



       StakeHolder_Matrix_Supplier_contacts__c c02 = new StakeHolder_Matrix_Supplier_contacts__c();
        c02.FirstName__c='smpleTest';
        c02.Name='lastTest';
        c02.email__c='Test@test.com';
        c02.Business_Group__c = 'sample';
        c02.SupplierName__c= acc01.id;
        c02.phone__c='2345675623';
      //c02.Type_Of_Contact_Picklist__c = 'Supplier';
    insert c02;
    
            
//System.runas(Usr23){  
/*PageReference pageRef = Page.MySupplierCompleteView;
Test.setCurrentPage(pageRef);
ApexPages.currentPage().getParameters().put('Id',Usr23.id); */ 

    MySupplierDataController controller= new MySupplierDataController();
controller.getContactDetails(acc01.id);

ExecutiveSupplierDataController controllerE= new ExecutiveSupplierDataController();
controllerE.getContactDetails(acc01.id);

supplierSpendController SSC = new supplierSpendController();
    
  }  //}//
//System.runas(Usr23){
//Test.startTest();
//PageReference pageRef = Page.MySupplierCompleteView;
//Test.setCurrentPage(pageRef);
//ApexPages.currentPage().getParameters().put('Id',Usr23.id);
//new MySupplierDataController().getContactDetails(Usr23.id);
//Test.stopTest();   
//}


}
}