src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Procurement Category with highest spend with this supplier</inlineHelpText>
        <label>Category</label>
        <picklist>
            <controllingField>CategoryGroupSIM__c</controllingField>
            <picklistValues>
                <fullName>Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building investment/CAPEX without Rents and Leases</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility Management services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental/Lease/Transactions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure Services &amp; Cloud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Workplace Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associated Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Services Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coaching &amp; Other Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial, Tax &amp; Insurances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Intellectual Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Communications Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Functional Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT Peripheral Devices</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Auxiliaries and Consumables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Test Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fleet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Incubation Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EnterpriseId__c</fullName>
        <encrypted>true</encrypted>
        <label>EncryptedEnterprise Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DataAcquisitionMethod__c</fullName>
        <inlineHelpText>Identify how this data is acquired</inlineHelpText>
        <label>Data Acquisition Method</label>
        <picklist>
            <picklistValues>
                <fullName>Data Load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standalone Survey</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>PI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIAbbreviation__c</fullName>
        <inlineHelpText>10 Character Limit</inlineHelpText>
        <label>PI Abbreviation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIUploadDuedate__c</fullName>
        <label>PI Upload Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of PI 
(Standard Name field of PI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>PI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>i.e. Days, Units, %, Euros, etc.</inlineHelpText>
        <label>Unit of Measure</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValuesType__c</fullName>
        <description>To describe PI values data type</description>
        <inlineHelpText>Specify type of data values for this PI</inlineHelpText>
        <label>Values Type</label>
        <picklist>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PiValueTemp__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <encrypted>true</encrypted>
        <label>Enterprise ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDefination__c</fullName>
        <label>PI Defination</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>SPE_PiValueTemps</relationshipLabel>
        <relationshipName>SPE_PiValueTemps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE_PiValueTemp</label>
    <nameField>
        <displayFormat>PV-{0000}</displayFormat>
        <label>SPE_PiValueTemp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE_PiValueTemps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_Stop__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Stop_trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Stop  KPI Recursoin</label>
</CustomObject>

src/classes/spe_verifyBUExtTest.cls
@IsTest(SeeAllData=False)

public with sharing class spe_verifyBUExtTest

{

static testmethod void spe_verifyBUExtTest()

{
    test.starttest();  
    
  //*********************Code For Covering the Encryption*************************//  
    Account a = New Account();
    a.Name = 'Test Account';
    a.enterpriseId__c='MO';
    
    insert a;
  //*********************END*************************//  
    
    
    //---Custom Setting data ---
    LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
    PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
    picklistObj.Business_Line__c = 'All Business Lines';
    picklistObj.Business_Unit__c = 'All Business Units';
    picklistObj.Category_Area__c = 'All Category Areas';
    picklistObj.Category_Group__c = 'All Category Groups';
    picklistObj.Category__c = 'All Categories';
    picklistObj.Country__c = 'All Countries';
    picklistObj.Market_Unit__c = 'All Market Units';
    picklistObj.Market__c = 'All Markets';
    picklistObj.Name = 'Picklist Default Values';
    picklistObj.Product__c = 'All Products';
    picklistObj.Project__c = 'All Projects';
    
    lstpicklistObj.add(picklistObj);
    
    insert lstpicklistObj;
    
    insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    SPE_PIDefinition__c PIData = new SPE_PIDefinition__c();
    
    //******************Changes For Encryption*****************// 
        //PIData.Name='Test it 2015';
        PIData.PI_Title__c ='Test it 2015';
    //******************END*****************//     
    PIData.PIAbbreviation__c='123456';
    PIData.ValuesType__c='Number';
    PIData.UoM__c='3';
    PIData.DataAcquisitionMethod__c='Data Load';
    PIData.GeoScope__c='All Markets';
    PIData.CategoryScope__c='All Categories';
    PIData.BUScope__c='All Products';
    PIData.PIUploadDuedate__c=Date.newInstance(2016,10,10);
    
    insert PIData;
    
    PIData.LifecycleStage__c='Pilot';
    update PIData;
    
    SPE_PiValueTemp__c PIvalTemp = new SPE_PiValueTemp__c();
    
    PIvalTemp.CurrencyIsoCode='EUR';
    PIvalTemp.PIDefination__c=PIData.Id;
    PIvalTemp.enterpriseId__c='MO';
    
    Insert PIvalTemp;
    
    system.assertEquals('EUR',PIvalTemp.CurrencyIsoCode);
     
    spe_verifyBUExt BUExt = new spe_verifyBUExt();
    BUExt.updateBU(); 
    //BUExt.BatchUpload();
    BUExt.skipVal();   
    
    test.stoptest(); 
    
}
}