src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Actual_Spend__c</fullName>
        <defaultValue>00.00</defaultValue>
        <label>Actual Spend (YTD) (M€)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CategoryAreaSIM__c</fullName>
        <inlineHelpText>Category Area wiht highest spend with this supplier</inlineHelpText>
        <label>Category Area</label>
        <picklist>
            <picklistValues>
                <fullName>DELIVERY OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not defined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICES PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDIRECT PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRODUCT PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enterprise_Id__c</fullName>
        <encrypted>true</encrypted>
        <label>Enterprise  Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LE_Spend__c</fullName>
        <defaultValue>00.00</defaultValue>
        <label>LE Spend (YTD) (M€)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Supplier Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Supplier Manager</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nokia_as_a_Customer__c</fullName>
        <inlineHelpText>Supplier&apos;s view on Nokia as a customer (estimation)</inlineHelpText>
        <label>Supplier View</label>
        <picklist>
            <controllingField>Supplier_Segmentation__c</controllingField>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exploit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nuisance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not defined</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier_Segmentation__c</fullName>
        <inlineHelpText>Supplier Segmentation based on Kraljic Matrix</inlineHelpText>
        <label>Supplier Segmentation</label>
        <picklist>
            <picklistValues>
                <fullName>Strategic Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manage Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shop</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PI_Param__c.object
<CustomObject>
    <fields>
        <fullName>Commercial__c</fullName>
        <label>Commercial</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Delivery__c</fullName>
        <label>Delivery</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Innovation__c</fullName>
        <label>Innovation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Quality__c</fullName>
        <label>Quality</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <label>Supplier Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>PI Params</relationshipLabel>
        <relationshipName>PI_Params</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PI Param</label>
    <nameField>
        <displayFormat>PI Param - {0}</displayFormat>
        <label>PI Param ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Params</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_SupplirPrfrmnceChartController.cls
@isTest

public class Test_SupplirPrfrmnceChartController {

    public static testmethod void generatePIParamDatamethod(){
    
    Profile p = [Select Id from profile where Name = 'System Administrator'];
    
    User Usr = new User(FirstName = 'test', LastName = 'user', Email = 'test.user@gmail.com', Alias = 'test', ProfileID = p.id , EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', LocaleSidKey='en_US', 
             TimeZoneSidKey='America/Los_Angeles', UserName='testUser@SPEorg.com');
    insert Usr;
    
    System.runas(Usr){
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.Actual_Spend__c = 1000;
        acc.LE_Spend__c = 500;
        acc.Enterprise_Id__c = 'SupplierTest';
        acc.CategoryAreaSIM__c= 'Delivery Operations (DO)';
        acc.Supplier_Segmentation__c = 'Shop';
        acc.Nokia_as_a_Customer__c = 'Core';
        acc.LSM__c = Usr.id;
        
        insert acc;
        
        
        PI_Param__c Param = new PI_Param__c();
        Param.Supplier_Name__c = acc.id;
        Param.Commercial__c = 89;
        Param.Delivery__c = 56;
        Param.Innovation__c = 89;
        Param.Quality__c = 88;
        Param.Relationship__c = 89;
        insert Param;
        
        ApexPages.currentPage().getParameters().put('id',acc.id);
        ApexPages.standardController stdCon = new ApexPages.standardController(acc);
        SupplierPerformanceRadarChartController Controller = new SupplierPerformanceRadarChartController (stdCon);
        Controller.generatePIParamData();
        for(SupplierPerformanceRadarChartController.RadarData Wrcon : Controller.data){
            
        }
        }
    
    }

}