src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Actual_Spend__c</fullName>
        <defaultValue>00.00</defaultValue>
        <label>Actual Spend (YTD) (M€)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CategoryAreaSIM__c</fullName>
        <inlineHelpText>Category Area wiht highest spend with this supplier</inlineHelpText>
        <label>Category Area</label>
        <picklist>
            <picklistValues>
                <fullName>DELIVERY OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not defined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICES PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDIRECT PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRODUCT PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryArea__c</fullName>
        <label>Category Area</label>
        <picklist>
            <picklistValues>
                <fullName>Direct Services Procurement (DSP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indirect Procurement (INP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Networks Product Procurement (NPP)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Enterprise_Id__c</fullName>
        <encrypted>true</encrypted>
        <label>Enterprise  Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LE_Spend__c</fullName>
        <defaultValue>00.00</defaultValue>
        <label>LE Spend (YTD) (M€)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead Supplier Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Supplier Manager</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nokia_as_a_Customer__c</fullName>
        <inlineHelpText>Supplier&apos;s view on Nokia as a customer (estimation)</inlineHelpText>
        <label>Supplier View</label>
        <picklist>
            <controllingField>Supplier_Segmentation__c</controllingField>
            <picklistValues>
                <fullName>Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exploit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nuisance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not defined</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier_Segmentation__c</fullName>
        <inlineHelpText>Supplier Segmentation based on Kraljic Matrix</inlineHelpText>
        <label>Supplier Segmentation</label>
        <picklist>
            <picklistValues>
                <fullName>Strategic Alliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manage Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shop</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_Spend__c.object
<CustomObject>
    <fields>
        <fullName>CategoryArea__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Spend__c</fullName>
        <label>Spend</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Spend</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>SpendId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/leadSupplierManager_Test.cls
@isTest
public class leadSupplierManager_Test{
    static testMethod void leadSupplierManagerTest() {
      
        user us = new user();
        us.FirstName = 'test';
         us.LastName = 'user';
         us.Email = 'test.user@gmail.com';
         us.Alias = 'test';
        us.ProfileID = '00eU0000000UGZX';
        us.EmailEncodingKey='UTF-8';
        us.LanguageLocaleKey='en_US';
        us.LocaleSidKey='en_US';
        us.Username ='test.john1234@gmail.com';
        us.CommunityNickname = 'test';
        us.TimeZoneSidKey ='America/Denver';
        insert us;
        
         Account accTest = new Account();
        accTest.Name = 'Test Supplier';
        accTest.Actual_Spend__c = 1000;
        accTest.LE_Spend__c = 500;
        accTest.Enterprise_Id__c = 'SupplierTest123';
        accTest.CategoryAreaSIM__c= 'Delivery Operations (DO)';
        accTest.Supplier_Segmentation__c = 'Shop';
        accTest.Nokia_as_a_Customer__c = 'Core';
        accTest.LSM__c = us.id;
        insert accTest;
        
        SPE_Spend__c spe = new SPE_Spend__c();
        spe.CategoryArea__c ='Services Procurement Operations (SPO)';
        spe.Period__c = date.today();
        spe.Spend__c = 56 ;
        insert spe;
                        
        SPE_Spend__c spe1 = new SPE_Spend__c();
        spe1.CategoryArea__c ='Indirect Procurement Operations (INPO)';
        spe1.Period__c = date.today();
        spe1.Spend__c = 56 ;
        insert spe1;
        
        leadSupplierManager.barGraphData bargraph = new leadSupplierManager.barGraphData();
         Apexpages.StandardController stdController = new Apexpages.StandardController(accTest);
      leadSupplierManager leadsup = new leadSupplierManager(stdController);
        leadSupplierManager.getChartData();
        
        }
        }