src/objects/Claim_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Claims__c</fullName>
        <label>Claim</label>
        <referenceTo>MCAR_Claim_Management__c</referenceTo>
        <relationshipLabel>Claim Contacts</relationshipLabel>
        <relationshipName>Claim_Contacts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>(Category Mgr, Manufacturer, and SQS are required)  Please submit a Change Request to request any modification to this list</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>BPO Commercial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO Contract Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO Performance Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Factory SQE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance &amp; Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEX Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Analysis</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Claim Contact</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Claim Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MCAR_Claim_Management__c.object
<CustomObject>
    <description>Object for Claim management process</description>
    <fields>
        <fullName>Claim_Status__c</fullName>
        <inlineHelpText>Possible status: Draft &gt; Data Collection &gt; Negotiation &gt; Payments &gt; Closed or Cancelled</inlineHelpText>
        <label>Claim Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Data Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data_claim_Notification_Send__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Data claim Notification Send</description>
        <inlineHelpText>Data claim Notification Send</inlineHelpText>
        <label>Data claim Notification Send</label>
        <type>Checkbox</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>Claim-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Send_Email_Closed_Test.cls
@isTest
public class Send_Email_Closed_Test {
    static testmethod void test1 (){
        test.startTest();
        MCAR_Claim_Management__c mclaim = new MCAR_Claim_Management__c();
        mclaim.Data_claim_Notification_Send__c=true;
        mclaim.Claim_Status__c='Closed';
        insert mclaim;
        
        Claim_Contact__c cont= new Claim_Contact__c();
        cont.Email__c='priyaburghate@yahoo.in';
        cont.Claims__c=mclaim.id;
        cont.Contact_Type__c ='Manufacturer';  
        insert cont;
        
        cont.Contact_Type__c ='Category Manager';  
        update cont;
        
        cont.Contact_Type__c ='SQM';  
        update cont;
        
        test.stopTest();
        
    }

}