src/objects/Claim_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Claims__c</fullName>
        <label>Claim</label>
        <referenceTo>MCAR_Claim_Management__c</referenceTo>
        <relationshipLabel>Claim Contacts</relationshipLabel>
        <relationshipName>Claim_Contacts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>(Category Mgr, Manufacturer, and SQS are required)  Please submit a Change Request to request any modification to this list</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>BPO Commercial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO Contract Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO Performance Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Factory SQE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance &amp; Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEX Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Analysis</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Claim Contact</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Claim Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MCAR_Claim_Management__c.object
<CustomObject>
    <description>Object for Claim management process</description>
    <fields>
        <fullName>Category_Manager_Email__c</fullName>
        <description>Category Manager Email</description>
        <label>Category Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Previous_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>Claim-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SendEmailOnClaimOwnerChangeController.cls
public class SendEmailOnClaimOwnerChangeController 
{        
    list<string> emailList;
    
    public static void sendEmailToAll(String claimId)
    {   
        try{
        MCAR_Claim_Management__c query=[select Id,Name,Previous_Owner__r.Email,Previous_Owner__r.Name,Owner.Email,Category_Manager_Email__c from MCAR_Claim_Management__c where id =:claimId];
        List<Claim_Contact__c> ccContacts = [select Email__c from Claim_Contact__c where Claims__c =: query.Id and  Contact_Type__c IN('Category Manager','SQM')];
        system.debug('****'+query.Previous_Owner__r.Email);
        system.debug('----'+query.Owner.Email);
         system.debug('****'+query.Category_Manager_Email__c);
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
        String[] toAddresses = new String[] {query.Owner.Email}; 
        String[] ccAddresses = new String[] {query.Previous_Owner__r.Email}; 
        mail.setToAddresses(toAddresses); 
        for(Claim_Contact__c c : ccContacts)
        {
            ccAddresses.add(c.Email__c);
        }
        mail.setCCAddresses(ccAddresses);
        mail.subject ='New Owner Assigned for '+ query.Name;
        mail.plainTextBody = 'This message is to notify you that you are the new Owner for  #'+query.Name + ' Contact the previous Owner , '+ query.Previous_Owner__r.Name+', for any further questions.';

        Messaging.SingleEmailMessage[] messages = 
         new List<Messaging.SingleEmailMessage> {mail};
         Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        if (results[0].success) {
          System.debug('The email was sent successfully.');
        } 
        else {
                System.debug('The email failed to send: ' + results[0].errors[0].message);

         }
        }
        Catch(Exception e){
            system.debug('Email ID is missing');
        }

}
}