src/objects/Claim_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Claims__c</fullName>
        <label>Claim</label>
        <referenceTo>MCAR_Claim_Management__c</referenceTo>
        <relationshipLabel>Claim Contacts</relationshipLabel>
        <relationshipName>Claim_Contacts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>(Category Mgr, Manufacturer, and SQS are required)  Please submit a Change Request to request any modification to this list</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>BPO Commercial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO Contract Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO Performance Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Factory SQE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance &amp; Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEX Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Analysis</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Claim Contact</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Claim Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MCAR_Claim_Management__c.object
<CustomObject>
    <description>Object for Claim management process</description>
    <fields>
        <fullName>Category_Manager_Email__c</fullName>
        <description>Category Manager Email</description>
        <label>Category Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Previous_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>Claim-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SendEmailOnClaimOwnerChangeCont_Test.cls
@isTest
public class SendEmailOnClaimOwnerChangeCont_Test {
    static  testmethod void sendEmailToAll_test(){ 
    
    User user1 = [select id , name , Email from user where id =: userInfo.getUserId()];
        
        
    MCAR_Claim_Management__c claimRec1 = new MCAR_Claim_Management__c();
    claimRec1.Previous_Owner__c= user1.Id;
    //claimRec1.Previous_Owner__c ='priya burghate';
    //claimRec1.Owner = user1.Name; 
    claimRec1.Category_Manager_Email__c='saran.golagani@atos.net';
    insert claimRec1;
        
        
    MCAR_Claim_Management__c claimRec2 = new MCAR_Claim_Management__c();
    //claimRec2.Previous_Owner__c='priya.burghate@yahoo.com';
    claimRec2.Previous_Owner__c = claimRec1.Previous_Owner__c;
    //claimRec2.Owner = claimRec1.OwnerId; 
    claimRec2.Category_Manager_Email__c='saran.golagani@atos.net';
    insert claimRec2;
     
    
   // User u = claimRec.Owner;
    //u.email='test@sfdc.com';
    //u.Name='test user';
   // insert u;
      
    //claimRec.Previous_Owner__r.Email = u.Email;
    //claimRec.Previous_Owner__r.name = u.Name;
    //claimRec.Owner.Email= u.Email ;
    //update claimRec;
        
     Claim_Contact__c ccCont= new Claim_Contact__c();
     ccCont.Contact_Type__c = 'SQS';
     ccCont.Email__c ='priya.burghate@atos.net';
     ccCont.Claims__c=claimRec1.id;
     insert ccCont;
    
     test.startTest();
     SendEmailOnClaimOwnerChangeController.sendEmailToAll(claimRec2.id);
     test.stopTest();
        
        
        
        
    }

}