src/objects/Claim_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Claims__c</fullName>
        <label>Claim</label>
        <referenceTo>MCAR_Claim_Management__c</referenceTo>
        <relationshipLabel>Claim Contacts</relationshipLabel>
        <relationshipName>Claim_Contacts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>(Category Mgr, Manufacturer, and SQS are required)  Please submit a Change Request to request any modification to this list</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>BPO Commercial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO Contract Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO Performance Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Factory SQE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance &amp; Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEX Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Analysis</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Claim Contact</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Claim Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MCAR_Claim_Management__c.object
<CustomObject>
    <description>Object for Claim management process</description>
    <fields>
        <fullName>Sup_Confirmed_Re_ceipt_of_Reclamation__c</fullName>
        <label>Reclamation Confirmed Receipt</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Supplier_Confirmation_BY__c</fullName>
        <label>Supplier Confirmation BY</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Supplier_Confirmation_Mail_Detail__c</fullName>
        <description>Supplier confirmation details of reclamation Letter</description>
        <label>Supplier Confirmation Mail Detail</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>Claim-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClaimReclamationConfirm.cls
global class ClaimReclamationConfirm implements Messaging.InboundEmailHandler
{
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope)
    {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
        
        String MailSubject = email.subject;
        String MailFrom = email.fromAddress;        
        
		string ClaimName = checkClaimName(MailSubject);        
        
        //String ClaimName = MailSubject.substring(MailSubject.length() - 11);
        
        System.debug('Claim Name :'+ClaimName);
        System.debug('Mail From :'+MailFrom);
        System.debug('Mail Subject :'+MailSubject);
                
        
        if(ClaimName!=null)
        {
       	 	if([select id from MCAR_Claim_Management__c where name=:ClaimName limit 1].size()==1)
       		 {
           		 system.debug('control came inside.....');
            	MCAR_Claim_Management__c claim = [select id,Sup_Confirmed_Re_ceipt_of_Reclamation__c,Supplier_Confirmation_Mail_Detail__c,Supplier_Confirmation_BY__c from MCAR_Claim_Management__c where name=:ClaimName limit 1];             
                
                if([select id,Email__c from Claim_Contact__c where Claims__c =: claim.Id and Contact_Type__c ='Manufacturer' and Email__c =:MailFrom].size()>0)
           		 {            	
            		if(claim.Sup_Confirmed_Re_ceipt_of_Reclamation__c==null)
              	  	{
            			claim.Sup_Confirmed_Re_ceipt_of_Reclamation__c = system.now();                        
            			claim.Supplier_Confirmation_Mail_Detail__c = email.plainTextBody;
                        claim.Supplier_Confirmation_BY__c = MailFrom;
            			update Claim;     
                    
                    	boolean status  = sendMail(MailFrom,'Your Confirmation successfully updated for '+ClaimName,MailSubject);                        
               		}
                	else
                	{            		                  
            			String errInfo = 'Confirmation already sent for '+ClaimName+' at '+claim.Sup_Confirmed_Re_ceipt_of_Reclamation__c+' by '+claim.Supplier_Confirmation_BY__c;
                		system.debug(errInfo);
            			boolean status  = sendMail(MailFrom,errInfo,MailSubject);
            			return null;                     
                	}                
            	}
            	else
            	{
            		String errInfo = 'Your Contact Details (Email Id :'+ MailFrom +') not available for '+ ClaimName+ '. Please contact Claim Owner regarding same.';            	        
                	system.debug(errInfo);
            		boolean status  = sendMail(MailFrom,errInfo,MailSubject);
            		return null;           
           	 	}                
        	}        
        	else
        	{
           	 	String errInfo = 'Claim Name '+ClaimName+' Not Avaliable in Production. Do Not Edit subject line before sending your confirmation. Please contact Claim Owner regarding same.'; 
            	system.debug(errInfo);
            	boolean status  = sendMail(MailFrom,errInfo,MailSubject);
            	return null;
            }    
        }
        else
        {
            String errInfo = 'Claim Not Avaliable in Production. Do Not Edit subject line before sending your confirmation. Please contact Claim Owner regarding same.'; 
            system.debug(errInfo);
            boolean status  = sendMail(MailFrom,errInfo,MailSubject);
            return null;
		}
        result.success = true;
        return result;
    }    
    
    public boolean sendMail(String userMail,String errInfo,String sub)
    {   
        try
        {                        
            List<String> toMail =new List<String>();        
            toMail.add(userMail);              
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();              
        	Mail.setToAddresses(toMail);            
        	Mail.setSubject(sub);            
       	 	mail.setHtmlBody(errInfo);            
        	Messaging.sendEmail(new Messaging.SingleEmailMessage[] { Mail });                        
        	return true;    
        }
        catch(Exception e)
        {
            return false;
        }     
    }
    
    public string checkClaimName(String sub)
    {                
        Pattern p = Pattern.compile('Claim-{1}([0-9]+)');                           
        List<string> subVal = sub.split(' ');
        
        for(String s : subVal)
        {
            Matcher m = p.matcher(s);
           	if(m.matches() == true) 
				return s;
        }
        return null;
    }
}