src/objects/Claim_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Claims__c</fullName>
        <label>Claim</label>
        <referenceTo>MCAR_Claim_Management__c</referenceTo>
        <relationshipLabel>Claim Contacts</relationshipLabel>
        <relationshipName>Claim_Contacts1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>(Category Mgr, Manufacturer, and SQS are required)  Please submit a Change Request to request any modification to this list</inlineHelpText>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>BPO Commercial Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO Contract Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BPO Performance Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Factory SQE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance &amp; Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEX Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Analysis</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Claim Contact</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Claim Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claim Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Claim_NCC_Services_Worksheet__c.object
<CustomObject>
    <description>Claim NCC Services Worksheet for MCAR Claims</description>
    <fields>
        <fullName>Amount__c</fullName>
        <formula>Qty_Hours__c  *  Unit_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>MCAR_Claim_Management__c</referenceTo>
        <relationshipName>Claim_NCC_Services_Worksheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Qty_Hours__c</fullName>
        <label>Qty/Hours</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>16</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>NCC Services Worksheet</label>
    <nameField>
        <displayFormat>CNWS-{0000}</displayFormat>
        <label>NCC Services Worksheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCC Services Worksheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Materials_Field_Worksheet__c.object
<CustomObject>
    <description>Materials Field  Worksheet for MCAR Claims</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Total Amount</description>
        <formula>Qty_Hours__c * Unit_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total Amount -Auto column</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category</description>
        <inlineHelpText>Category</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Batch inspection at Supplier site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product testing &amp; acceptance at site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier Payment &amp; Performance guarantee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation from supplier site to Project site / NSN hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAT or other taxes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>MCAR_Claim_Management__c</referenceTo>
        <relationshipName>Materials_Field_Loss_Worksheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <inlineHelpText>Description</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Qty_Hours__c</fullName>
        <description>Qty/Hours</description>
        <inlineHelpText>Qty/Hours</inlineHelpText>
        <label>Qty/Hours</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Price</description>
        <inlineHelpText>Unit Price</inlineHelpText>
        <label>Unit Price</label>
        <precision>16</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>NCC Materials Field Worksheet</label>
    <nameField>
        <displayFormat>CMFLWS-{0000}</displayFormat>
        <label>Materials Field Loss Worksheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCC Materials Field Worksheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Materials_Hub_Worksheet__c.object
<CustomObject>
    <description>Materials Hub Worksheet for MCAR Claims</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount</description>
        <formula>Qty_Hours__c * Unit_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category</description>
        <inlineHelpText>Category</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Incoming Inspection/ Identity Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAT or other taxes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Claim</description>
        <inlineHelpText>Claim</inlineHelpText>
        <label>Claim</label>
        <referenceTo>MCAR_Claim_Management__c</referenceTo>
        <relationshipName>NCC_Materials_Hub_Worksheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Qty_Hours__c</fullName>
        <label>Qty/Hours</label>
        <precision>6</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Price</description>
        <inlineHelpText>Unit Price</inlineHelpText>
        <label>Unit Price</label>
        <precision>16</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>NCC Materials Hub Worksheet</label>
    <nameField>
        <displayFormat>CMHUWS-{0000}</displayFormat>
        <label>Materials Hub Worksheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCC Materials Hub Worksheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MCAR_Claim_Management__c.object
<CustomObject>
    <description>Object for Claim management process</description>
    <fields>
        <fullName>Amount__c</fullName>
        <inlineHelpText>Amount that is agreed between Claim Team and Supplier, that will be paid to NSN</inlineHelpText>
        <label>Negotiated Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Claim_Status__c</fullName>
        <inlineHelpText>Possible status: Draft &gt; Data Collection &gt; Negotiation &gt; Payments &gt; Closed or Cancelled</inlineHelpText>
        <label>Claim Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Data Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data_Collection_Notification_Send__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Data_Collection_Notification_Send</description>
        <label>Data Collection Notification Send</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Data_claim_Notification_Send__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Data claim Notification Send</description>
        <inlineHelpText>Data claim Notification Send</inlineHelpText>
        <label>Data claim Notification Send</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>I_Agree__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To approve the claim by claim owner</description>
        <label>I Agree</label>
        <type>Checkbox</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>Claim-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/NCC_Materials_Factory_Worksheet__c.object
<CustomObject>
    <description>Materials Factory Worksheet for MCAR Claims</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount</description>
        <formula>Qty_Hours__c * Unit_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Category</description>
        <inlineHelpText>Category</inlineHelpText>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Incoming Goods Inspection Cost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others cost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repair Cost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAT or other taxes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Claim</description>
        <inlineHelpText>Claim</inlineHelpText>
        <label>Claim</label>
        <referenceTo>MCAR_Claim_Management__c</referenceTo>
        <relationshipName>Materials_Factory_Worksheet</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <inlineHelpText>Description</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Qty_Hours__c</fullName>
        <description>Qty/Hours</description>
        <inlineHelpText>Qty/Hours</inlineHelpText>
        <label>Qty/Hours</label>
        <precision>11</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <description>Unit Price</description>
        <inlineHelpText>Unit Price</inlineHelpText>
        <label>Unit Price</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>NCC Materials Factory Worksheet</label>
    <nameField>
        <displayFormat>CMFAWS-{0000}</displayFormat>
        <label>NCC Materials Factory Worksheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCC Materials Factory Worksheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestClass_MCARClaims_Trigger.cls
@isTest
public with sharing class TestClass_MCARClaims_Trigger
{

           static TestMethod void Test_InsertWithValue_Trigger_Send_Email_Data_Collection()
        {
                MCAR_Claim_Management__c testObj = new MCAR_Claim_Management__c();
                testObj.Data_Collection_Notification_Send__c = True; 
                testObj.Claim_Status__c = 'Data Collection';
                testObj.CreatedDate= Datetime.now(); 
                insert testObj; 

                /*************Testing_Trigger_Send_Email_Data_Collection************/
                MCAR_Claim_Management__c inserted_testObj = [select Claim_Status__c,RecordTypeId from MCAR_Claim_Management__c where ID =: testObj.ID];
                RecordType Rec = [SELECT Id FROM RecordType WHERE Name = 'MCAR Claim Negotiation layout'limit 1];
                System.assertEquals('Negotiation',inserted_testObj.Claim_Status__c);
                System.assertEquals (Rec.Id,inserted_testObj.RecordTypeId);

        }


          static TestMethod void Test_InsertWithValue_Trigger_Send_Email_Closed()
        {
                MCAR_Claim_Management__c testObj = new MCAR_Claim_Management__c();
                testObj.Data_claim_Notification_Send__c  = True; 
                testObj.Claim_Status__c = 'Closed';
                testObj.CreatedDate= Datetime.now(); 
                insert testObj; 

                /*************Testing_Trigger_Send_Email_Data_Collection*****
                MCAR_Claim_Management__c inserted_testObj = [select Claim_Status__c,RecordTypeId from MCAR_Claim_Management__c where ID =: testObj.ID];
                RecordType Rec = [SELECT Id FROM RecordType WHERE Name = 'MCAR Claim close layout'limit 1];
                System.assertEquals (Rec.Id,inserted_testObj.RecordTypeId);*/
        }

         static TestMethod void Test_InsertWithValue_Trigger_Send_Email()
        {
                MCAR_Claim_Management__c testObj = new MCAR_Claim_Management__c();
                testObj.I_Agree__c  = True; 
                testObj.Claim_Status__c = 'Draft';
                testObj.CreatedDate= Datetime.now(); 
                insert testObj; 

                List<Claim_Contact__c> cc = new List<Claim_Contact__c>();
                Claim_Contact__c  Technical = new Claim_Contact__c ();
                Technical.Email__c ='test@nokia.com';
                Technical.Contact_Type__c='Technical';
                Technical.Claims__c =testObj.ID;
                cc.add(Technical);                
                insert cc;   
               
                Claim_Contact__c Technicalcon = [select Email__c,Contact_Type__c,Claims__c from Claim_Contact__c WHERE Claims__c =: testObj.ID AND Contact_Type__c != 'Manufacturer'];
                System.assertEquals('Technical',Technicalcon.Contact_Type__c);
                System.assertEquals(Technical.Email__c,Technicalcon.Email__c); 
          

                /*************Testing_Trigger_Send_Email_Data_Collection*****/
                MCAR_Claim_Management__c inserted_testObj = [select Claim_Status__c,RecordTypeId from MCAR_Claim_Management__c where ID =: testObj.ID];
                //System.assertEquals('Data Collection',inserted_testObj.Claim_Status__c);
            
        }
        
        static TestMethod void Test_Hub_Worksheet_Trigger()
        {
                MCAR_Claim_Management__c testObj = new MCAR_Claim_Management__c();
                testObj.I_Agree__c  = True; 
                testObj.Claim_Status__c = 'Draft';
                testObj.CreatedDate= Datetime.now(); 
                insert testObj; 

                Materials_Hub_Worksheet__c childtestObj = new Materials_Hub_Worksheet__c();
                childtestObj.Category__c='Test';
                childtestObj.Description__c='Test';
                childtestObj.Qty_Hours__c=5;
                childtestObj.Unit_Price__c=400;
                childtestObj.Claim__c=testObj.ID;
                insert childtestObj; 
            
                System.assertEquals(childtestObj.Amount__c,testObj.Materials_Hub_Loss__c);             
                delete childtestObj; 

                System.assertEquals(childtestObj.Amount__c,testObj.Materials_Hub_Loss__c);
               

            
        }



        static TestMethod void Test_Services_Worksheet_Trigger()
        {
                MCAR_Claim_Management__c testObj = new MCAR_Claim_Management__c();
                testObj.I_Agree__c  = True; 
                testObj.Claim_Status__c = 'Draft';
                testObj.CreatedDate= Datetime.now(); 
                insert testObj; 

                Claim_NCC_Services_Worksheet__c childtestObj = new Claim_NCC_Services_Worksheet__c();
                childtestObj.NCC_Category__c='Test';
                childtestObj.Description__c='Test';
                childtestObj.Qty_Hours__c=5;
                childtestObj.Unit_Price__c=400;
                childtestObj.Claim__c=testObj.ID;
                
                insert childtestObj; 
            
                System.assertEquals(childtestObj.Amount__c,testObj.Services_Loss__c);             
                
                delete childtestObj; 

                System.assertEquals(childtestObj.Amount__c,testObj.Services_Loss__c);
               

            
        }


        static TestMethod void Test_Field_Worksheet_Trigger()
        {
                MCAR_Claim_Management__c testObj = new MCAR_Claim_Management__c();
                testObj.I_Agree__c  = True; 
                testObj.Claim_Status__c = 'Draft';
                testObj.CreatedDate= Datetime.now(); 
                insert testObj; 

                Materials_Field_Worksheet__c childtestObj = new Materials_Field_Worksheet__c();
                childtestObj.Category__c='Test';
                childtestObj.Description__c='Test';
                childtestObj.Qty_Hours__c=5;
                childtestObj.Unit_Price__c=400;
                childtestObj.Claim__c=testObj.ID;
                insert childtestObj; 
            
                System.assertEquals(childtestObj.Amount__c,testObj.Materials_Field_Loss__c );             
                delete childtestObj; 

                System.assertEquals(childtestObj.Amount__c,testObj.Materials_Field_Loss__c );
               

            
        }


        static TestMethod void Test_Factory_Worksheet_Trigger()
        {
                MCAR_Claim_Management__c testObj = new MCAR_Claim_Management__c();
                testObj.I_Agree__c  = True; 
                testObj.Claim_Status__c = 'Draft';
                testObj.CreatedDate= Datetime.now(); 
                insert testObj; 

                NCC_Materials_Factory_Worksheet__c    childtestObj = new NCC_Materials_Factory_Worksheet__c  ();
                childtestObj.Category__c='Test';
                childtestObj.Description__c='Test';
                childtestObj.Qty_Hours__c=5;
                childtestObj.Unit_Price__c=400;
                childtestObj.Claim__c=testObj.ID;
                insert childtestObj; 
            
                System.assertEquals(childtestObj.Amount__c,testObj.Materials_Factory_Loss__c);             
                delete childtestObj; 

                System.assertEquals(childtestObj.Amount__c,testObj.Materials_Factory_Loss__c);
               

            
        }
        
        static TestMethod void Test_Claim_Type_Update_Trigger()
        {

                Date cDT = Date.today();
                MCAR_Claim_Management__c testObj = new MCAR_Claim_Management__c();
                testObj.I_Agree__c  = True; 
                testObj.Claim_Status__c = 'Draft';
                testObj.CreatedDate= Datetime.now(); 
                testObj.Technical_Details_Review_Approval__c = true;
                testObj.Legal_Team_Review_Approval__c =  true;
                testObj.Commodity_Manager_Review_Approval__c = true;
                testObj.Nonconformance_Costs_Review_Approval__c = true; 
                testObj.Claim_Type__c = 'Local';
                insert testObj; 
                
                NCC_Materials_Factory_Worksheet__c    childtestObj = new NCC_Materials_Factory_Worksheet__c  ();
                childtestObj.Category__c='Test';
                childtestObj.Description__c='Test';
                childtestObj.Qty_Hours__c=5;
                childtestObj.Unit_Price__c=400;
                childtestObj.Claim__c=testObj.ID;
                insert childtestObj; 
               
                MCAR_Claim_Management__c result = [Select Claim_Type__c,Root_Cause_Analysis_Approved_Date__c,Legal_Analysis_Approved_Date__c,Commodity_Manager_Approved_Date__c,Non_Conformance_Costs_Approved_Date__c from MCAR_Claim_Management__c where ID=:testObj.ID];
               
                System.assertEquals(cDT,result.Root_Cause_Analysis_Approved_Date__c);             
                System.assertEquals(cDT,result.Legal_Analysis_Approved_Date__c);             
                System.assertEquals(cDT,result.Commodity_Manager_Approved_Date__c);             
                System.assertEquals(cDT,result.Non_Conformance_Costs_Approved_Date__c);             
                //System.assertEquals('Local',result.Claim_Type__c);
                
                childtestObj.Qty_Hours__c=5000;
                update childtestObj;
                
                MCAR_Claim_Management__c update_result = [Select Claim_Type__c,Root_Cause_Analysis_Approved_Date__c,Legal_Analysis_Approved_Date__c,Commodity_Manager_Approved_Date__c,Non_Conformance_Costs_Approved_Date__c from MCAR_Claim_Management__c where ID=:testObj.ID];
                //System.assertEquals('Global',update_result.Claim_Type__c);

              
            
        }
         static TestMethod void Test_Claim_Contact_Trigger()
        {

                MCAR_Claim_Management__c testObj = new MCAR_Claim_Management__c();
                testObj.I_Agree__c  = True; 
                testObj.Claim_Status__c = 'Draft';
                testObj.CreatedDate= Datetime.now(); 
                testObj.Technical_Details_Review_Approval__c = true;
                testObj.Legal_Team_Review_Approval__c =  true;
                testObj.Commodity_Manager_Review_Approval__c = true;
                testObj.Nonconformance_Costs_Review_Approval__c = true; 
                testobj.Manufacturer_Email__c = 'test@gmail.com';
                testobj.Category_Manager_Email__c = 'test@gmail.com';
                insert testObj; 

            Claim_Contact__c childObj = new Claim_Contact__c();
            childObj.Contact_Type__c = 'Manufacturer';
            childObj.Email__c='test@gmail.com';
            childObj.Claims__c=testObj.ID;
            insert childObj;
            
           
            Claim_Contact__c childObj1 = new Claim_Contact__c();
            childObj1.Contact_Type__c = 'Category Manager';
            childObj1.Email__c='test@gmail.com';
           childObj1.Claims__c=testObj.ID;
            insert childObj1;
            
             MCAR_Claim_Management__c parent_obj = [select Manufacturer_Email__c,Category_Manager_Email__c from MCAR_Claim_Management__c WHERE id =:testObj.ID]; 
             System.assertEquals('test@gmail.com',parent_obj.Manufacturer_Email__c);             
             System.assertEquals('test@gmail.com',parent_obj.Category_Manager_Email__c); 
       
             

        }

}