src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>CM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplier</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isInternal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Internal Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_ConsequenceManagement__c.object
<CustomObject>
    <fields>
        <fullName>CategoryManager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category Manager</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>contains</operation>
                <value>SPE</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Consequence_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CorrectiveActionInstructions__c</fullName>
        <formula>KPIName__r.CorrectiveActionInstructions__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Corrective Action Instructions</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <formula>KPIName__r.Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPITitle__c</fullName>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MissingDatalogic__c</fullName>
        <label>Missing Data logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <formula>Contact__r.Password__c</formula>
        <label>Password</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Develop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Watchlist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Consequence Management</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Consequence Management ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consequence Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>AbbreviatedName__c</fullName>
        <inlineHelpText>10 character limit.  Applicable for all languages.</inlineHelpText>
        <label>KPI Abbreviation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActualCalculation__c</fullName>
        <label>Actual Calculation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Aggregation__c</fullName>
        <label>Aggregation</label>
        <picklist>
            <picklistValues>
                <fullName>AVG</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CorrectiveActionInstructions__c</fullName>
        <description>Corrective Action Instructions for Supplier</description>
        <inlineHelpText>Corrective Action Instructions for Supplier</inlineHelpText>
        <label>Corrective Action Instructions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>255 Character Limit</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FrequencyinMonth__c</fullName>
        <label>Frequency in Month</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group1__c</fullName>
        <inlineHelpText>See Guidelines</inlineHelpText>
        <label>Pillar</label>
        <picklist>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustainability</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group2__c</fullName>
        <inlineHelpText>See Guidelines</inlineHelpText>
        <label>Group 2</label>
        <picklist>
            <picklistValues>
                <fullName>Hard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsHighBetter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is High Better ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KPI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of KPI 
(Standard Name field of KPI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>See Guidelines; sets the number of buckets or scores.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MissingDatalogic__c</fullName>
        <inlineHelpText>Please Click on the Help Link on the top of this page</inlineHelpText>
        <label>Missing Data logic</label>
        <picklist>
            <picklistValues>
                <fullName>Past Data or Category Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPE Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OperationalType__c</fullName>
        <label>Operational Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lagging PI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leading PI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <description>Enter date when the KPI will be calculated (for data) or scheduled (for survey)</description>
        <inlineHelpText>This is an auto computed date looking at the underlying PI definitions (latest PI upload date + buffer days). This refreshes in batches and not instantaneously.</inlineHelpText>
        <label>Next Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Operational, Commercial, or Strategic</inlineHelpText>
        <label>KPI Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>i.e. Days, Units, %, Euros, etc.</inlineHelpText>
        <label>Unit of Measure</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VerNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <label>VerNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE2_ConsequenceMngtAddContactExt_Test.cls
@isTest(SeeAllData = false)
Public class SPE2_ConsequenceMngtAddContactExt_Test{
      
    public static testmethod void SPE2_ConsequenceMngtAddContactExtTest1(){
    test.startTest();
    
    SPE_KPIDefinition__c kpiDefinition2 = new SPE_KPIDefinition__c();
        kpiDefinition2.KPI_Title__c = 'Test KPI Definition 123';
        kpiDefinition2.AbbreviatedName__c = 'TKPIDe1';
        kpiDefinition2.Level__c = '1';
        kpiDefinition2.LifecycleStage__c = 'Pilot';
        kpiDefinition2.Description__c = 'Test';
        kpiDefinition2.MissingDatalogic__c = 'SPE Invalid';
        kpiDefinition2.OperationalType__c = 'Leading PI';
        kpiDefinition2.GeoScope__c = 'All Markets';
        kpiDefinition2.categoryscope__c = 'All Categories';
        kpiDefinition2.BUScope__c = 'All Products';
        kpiDefinition2.UoM__c = 'max';
        kpiDefinition2.Group1__c = 'Cost';
        kpiDefinition2.Group2__c = 'Hard';
        kpiDefinition2.Type__c = 'Operational';
        kpiDefinition2.ActualCalculation__c='A';
        kpiDefinition2.FrequencyinMonth__c = '2';
        kpiDefinition2.ScheduledDate__c = Date.newInstance(2016,10,15);
        kpiDefinition2.VerNumber__c = 0;
        kpiDefinition2.Aggregation__c = 'AVG'; 
        kpiDefinition2.IsHighBetter__c=true;
        kpiDefinition2.CorrectiveActionInstructions__c = 'ABCXYZ';
        insert kpiDefinition2;
        
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' OR Name='SPE']; 
        User u = new User(Alias ='standt', Email='abc@gmail.com.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testuser@testuser.com.spe2');
        insert u; 
        
        Account acc= new Account();
        acc.Name='Test Account' ;
        insert acc;

        Contact cont = new Contact();
        cont.FirstName='Test';
        cont.LastName='Test';
        cont.AccountID = acc.id;
        cont.Email= 'test@atos.net';
        cont.Password__c = '12345';
        cont.isInternal__c = true;
        insert cont;
        
        Contact CCcon1 = new Contact();
        CCcon1.LastName = 'Test Contact1';
        CCcon1.AccountId = acc.Id;
        CCcon1.Email = 'Test1@atos.net';
        insert CCcon1;
        
        Contact CCcon2 = new Contact();
        CCcon2.LastName = 'Test Contact2';
        CCcon2.AccountId = acc.Id;
        CCcon2.Email = 'test2@atos.net';
        insert CCcon2;
        
        Contact CCcon3 = new Contact();
        CCcon3.LastName = 'Test Contact3';
        CCcon3.AccountId = acc.Id;
        CCcon3.Email = 'test3@atos.net';
       
        
        system.debug('ConatctPassword:' +cont.Password__c);
        system.debug('ConatctId:' +cont.id);
        
        Account supplier = SPE_TestObjectCreator.CreateSupplier('Atos');
        insert supplier; 

        SPE_ConsequenceManagement__c SPEConMngmnt = new SPE_ConsequenceManagement__c();
        SPEConMngmnt.KPITitle__c = 'test SPEConseMangmnt 123';
        SPEConMngmnt.CategoryManager__c = u.id;
        SPEConMngmnt.Contact__c  = cont.id;
        SPEConMngmnt.CategoryCluster__c = 'All Category Areas';
        SPEConMngmnt.CategoryArea__c = 'All Category Areas';
        SPEConMngmnt.CategoryGroup__c = 'All Category Groups';
        SPEConMngmnt.Category__c = 'All Categories';
        SPEConMngmnt.Market__c = 'All Markets';
        SPEConMngmnt.MarketUnit__c ='All Market Units';
        SPEConMngmnt.Country__c = 'All Countries'; 
        SPEConMngmnt.Project__c = 'All Projects';
        SPEConMngmnt.BusinessUnit__c = 'All Business Units';
        SPEConMngmnt.BusinessLine__c = 'All Business Lines';
        SPEConMngmnt.Product__c =  'All Products';
        SPEConMngmnt.Supplier__c = supplier.id; 
        SPEConMngmnt.SupplierManagerContact__c = CCcon1.id;
        insert SPEConMngmnt;        
        
        List<Business_System_Role__c> BusinessroleList = new List<Business_System_Role__c>(); 
        Business_System_Role__c businessystrole = new Business_System_Role__c();
        businessystrole.name = 'Consequence Management';
        businessystrole.Object_Name__c = 'Consequence Management';
        businessystrole.Business_Role__c ='Supplier Quality Manager (SQM);Category Manager;Supplier Manager;Country Manager;Project Manager;Regional Category Manager;Nokia Global Account Manager;Supplier Account Manager;Supplier – Lead Quality Manager;Supplier – Quality Engineer';
        businessystrole.System_Role__c ='Developed Ticket Owner;Phase Out Manager;Auditor';
        BusinessroleList.add(businessystrole); 
        insert BusinessroleList;        
         
        list<SPE_CategoryInfo__c> lstCategory= new list<SPE_CategoryInfo__c>(); 
        for(integer i=0; i<20 ; i++){
            SPE_CategoryInfo__c catInfo = new SPE_CategoryInfo__c ();
            catInfo.Supplier__c = supplier.ID;
            catInfo.BusinessLine__c = 'All Business Lines';
            catInfo.Business_Role__c = 'Category Manager';
            catInfo.BusinessUnit__c ='All Business Units';
            catInfo.Category__c ='All Categories';
            catInfo.CategoryCluster__c ='All Category Areas';
            catInfo.CategoryGroup__c = 'All Category Groups';
            catInfo.Contact__c = CCcon1.ID;
            catInfo.Country__c = 'All Countries'; 
            catInfo.Region__c ='All Markets';
            catInfo.SubRegion__c = 'All Market Units';
            catInfo.Product__c = 'All Products';
            catInfo.Project__c = 'All Projects';
            catInfo.System_Role__c = 'Developed Ticket Owner';
            catInfo.CategoryScopeCombination__c = SPEConMngmnt.Market__c+';'+SPEConMngmnt.MarketUnit__c+';'+SPEConMngmnt.Country__c+';'+SPEConMngmnt.Project__c+';'+SPEConMngmnt.CategoryArea__c+';'+SPEConMngmnt.CategoryGroup__c+';'+SPEConMngmnt.Category__c+';'+SPEConMngmnt.BusinessUnit__c+';'+SPEConMngmnt.BusinessLine__c+';'+SPEConMngmnt.Product__c;

         //   insert catInfo;
            
           lstCategory.add(catInfo);
         }
         insert lstCategory;
         ApexPages.currentPage().getParameters().put('Id',SPEConMngmnt.id);
         ApexPages.StandardController sc = new ApexPages.StandardController(SPEConMngmnt);
        
        SPE2_ConsequenceMngtAddContactExt controller = new SPE2_ConsequenceMngtAddContactExt(sc);
        controller.getBusinessList();
        controller.getSystemList();
        controller.closePopup();
        controller.showPopup();
        controller.savecontact();
        controller.closePopup2();
        controller.showPopup2();
        controller.savecontact2();
        controller.con = CCcon3;
        controller.savecontact();
        controller.DEFAULT_PAGE_SIZE = 1;
        controller.showInternalContactOnly();
        controller.firstBtnClick();
        controller.DEFAULT_PAGE_SIZE = 1;
        controller.firstBtnClick();
        controller.nextBtnClick();
        controller.previousBtnClick();
        controller.lastBtnClick();
        ApexPages.currentPage().getParameters().put('crntPageNum','0');
        controller.goToPage();
        ApexPages.currentPage().getParameters().put('crntPageNum','1');
        controller.goToPage();
        ApexPages.currentPage().getParameters().put('crntPageNum','2');
        controller.goToPage(); 
        if(controller.maxPages != null){
          controller.pageNumber = controller.maxPages-1;
          controller.nextBtnClick();
        }
        controller.goToPage();
        controller.DEFAULT_PAGE_SIZE2 = 1;
        controller.contactName = '* Contact*';
        controller.doSearch();
        controller.contactName = 'Test Contact1';
        controller.doSearch();
        controller.contactName = 'Test*';
        controller.doSearch();
        controller.DEFAULT_PAGE_SIZE2 = 1;
        controller.firstBtnClick2();
        controller.nextBtnClick2();
        controller.previousBtnClick2();
        controller.lastBtnClick2();
        ApexPages.currentPage().getParameters().put('crntPageNum','0');
        controller.goToPage2();
        ApexPages.currentPage().getParameters().put('crntPageNum','1');
        controller.goToPage2();
        ApexPages.currentPage().getParameters().put('crntPageNum','2');
        controller.goToPage2(); 
        if(controller.maxPages2 != null){
          controller.pageNumber2 = controller.maxPages2-1;
          controller.nextBtnClick2();
        }
        controller.goToPage2();
        controller.addContact();
        ApexPages.currentPage().getParameters().put('contactId',CCcon2.id);
        controller.addContact();
        controller.cancel();
        controller.showInternalContactOnly2();
    test.stopTest();    
    
    }
}