src/objects/CPR__c.object
<CustomObject>
    <description>This is main home/Search page of the NQT application</description>
    <fields>
        <fullName>Customer_Hold__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to put CPR on Customer Hold</description>
        <inlineHelpText>Select this to put the CPR on Customer Hold</inlineHelpText>
        <label>Customer Hold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deliverable_Status_Backup__c</fullName>
        <label>Deliverable Status Backup</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NQT_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please select Account Manager</inlineHelpText>
        <label>Account Manager*</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>NQT</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Account</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Manager</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>CPRs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NQT_Area__c</fullName>
        <description>These are the Area  where Verizon provide its services</description>
        <inlineHelpText>Please select Area</inlineHelpText>
        <label>Area *</label>
        <picklist>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nationwide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North East</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NQT_CPR_Name__c</fullName>
        <inlineHelpText>Please enter CPR Name</inlineHelpText>
        <label>CPR Name *</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NQT_CPR_Start_Date__c</fullName>
        <description>This date represents the Customer Requested Quote Date.</description>
        <inlineHelpText>Please select CPR Start Date</inlineHelpText>
        <label>CPR Start Date *</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NQT_Class_Access_After__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Class Access After</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NQT_Class_Access_Before__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Class Access Before</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NQT_Customer_Contact_Phone__c</fullName>
        <inlineHelpText>Please enter Customer Contact Phone (e.g. 8479999999)</inlineHelpText>
        <label>Customer Contact Phone # *</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>NQT_Customer_Email_Address__c</fullName>
        <description>Email Address</description>
        <inlineHelpText>Please enter Customer Email Address</inlineHelpText>
        <label>Customer Email Address *</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>NQT_Customer_Requested_Ship_Date__c</fullName>
        <inlineHelpText>Please selcet Customer Requested Ship Date</inlineHelpText>
        <label>Customer Requested Ship Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NQT_Customer__c</fullName>
        <description>Picklist for selecting customer</description>
        <inlineHelpText>Please select Customer name</inlineHelpText>
        <label>Customer</label>
        <picklist>
            <picklistValues>
                <fullName>VERIZON</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NQT_Customer_contact_Name__c</fullName>
        <inlineHelpText>Please enter Customer Contact Name</inlineHelpText>
        <label>Customer Contact Name *</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NQT_Database_Work_Description__c</fullName>
        <inlineHelpText>Give the detail of Database Work Description</inlineHelpText>
        <label>Database Work Description:</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NQT_Deliverable_Status__c</fullName>
        <label>Deliverable Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Determine Deadline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering Deliverable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Requested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Deliverable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting For PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NQT_FE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please select FE</inlineHelpText>
        <label>FE</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3 AND 4)</booleanFilter>
            <filterItems>
                <field>User.FE__c</field>
                <operation>equals</operation>
                <value>TRUE</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>NQT</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Field</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Engineer</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>CPRs4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NQT_If_Other_MTSO__c</fullName>
        <inlineHelpText>Enter a value if &apos;Other&apos; is selected in MTSO.</inlineHelpText>
        <label>If Other</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NQT_Program_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please select  Program Manager</inlineHelpText>
        <label>Program Manager*</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3) OR 4</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>NQT</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Program</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Manager</value>
            </filterItems>
            <filterItems>
                <field>User.PM__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>CPRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NQT_Project_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please select Project Manager</inlineHelpText>
        <label>Project Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CPRs5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NQT_Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Request in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request In-Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NQT_SE_MSC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please select SE MSC</inlineHelpText>
        <label>SE MSC</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR (2 AND 3 AND 4 AND 5)</booleanFilter>
            <filterItems>
                <field>User.SEMSC__c</field>
                <operation>equals</operation>
                <value>TRUE</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>MSC</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Engineer</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>System</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>NQT</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>CPRs3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NQT_SE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please select SE</inlineHelpText>
        <label>SE</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(2 AND 4 AND 5 AND 3) OR 1</booleanFilter>
            <filterItems>
                <field>User.SE__c</field>
                <operation>equals</operation>
                <value>TRUE</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>System</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>notContain</operation>
                <value>MSC</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Engineer</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>NQT</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>CPRs2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NQT_Target_Service_Finish_Date__c</fullName>
        <inlineHelpText>please select Target Service Finish Date</inlineHelpText>
        <label>Target Service Finish Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NQT_Target_Service_Start_Date__c</fullName>
        <inlineHelpText>Please select Target Service Start Date</inlineHelpText>
        <label>Target Service Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Status_Backup__c</fullName>
        <label>Project Status Backup</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason_for_Customer_Hold__c</fullName>
        <label>Reason for Customer Hold</label>
        <type>TextArea</type>
    </fields>
    <label>NQT CPR</label>
    <nameField>
        <displayFormat>CPR-{000000}</displayFormat>
        <label>Project ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPRs</pluralLabel>
    <recordTypes>
        <fullName>CPR_Customer_Hold</fullName>
        <active>true</active>
        <label>CPR Customer Hold</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NQTCustomerHold.cls
public class NQTCustomerHold{

    public NQTCustomerHold(ApexPages.StandardController controller) {
        cpr = new CPR__c();
    }
    
    public CPR__c cpr { get; set; }
    
    public pagereference confirm(){
        if(cpr.Reason_for_Customer_Hold__c == NULL){
            cpr.Reason_for_Customer_Hold__c.addError('Please enter a value');
            return NULL;
            }
        List<String> check_CPR = ApexPages.currentPage().getURL().split('id=', 0);
        List<String> get_id = check_CPR[1].split('&', 0);
        Id CPRid = get_id[0];
        CPR__c CPR1 = [SELECT OwnerId, RecordTypeId, NQT_Class_Access_After__c, NQT_Class_Access_Before__c, NQT_Project_Status__c, NQT_Deliverable_Status__c, NQT_Program_Manager__c, NQT_Account_Manager__c, NQT_FE__c, NQT_SE__c, NQT_SE_MSC__c FROM CPR__c WHERE id =: CPRid];
        CPR1.NQT_Class_Access_After__c = TRUE;
        CPR1.NQT_Class_Access_Before__c = TRUE;
        CPR1.Project_Status_Backup__c = CPR1.NQT_Project_Status__c;
        CPR1.Deliverable_Status_Backup__c = CPR1.NQT_Deliverable_Status__c;
        CPR1.NQT_Project_Status__c = 'Customer Hold';
        CPR1.NQT_Deliverable_Status__c = 'Customer Hold';
        CPR1.Reason_for_Customer_Hold__c = cpr.Reason_for_Customer_Hold__c;   
        CPR1.RecordTypeId = [SELECT Id FROM RecordType WHERE developerName = 'CPR_Customer_Hold' LIMIT 1].Id;     
        //CPR1.Customer_Hold__c = TRUE;
        Update CPR1;
        
        User Customer = [SELECT ProfileId, Email FROM User WHERE Id =: CPR1.OwnerId LIMIT 1];
        String Profile = [SELECT Name FROM Profile WHERE Id =: Customer.ProfileId LIMIT 1].Name;
        
        EmailTemplate et = [SELECT id FROM EmailTemplate WHERE developerName = 'NQT_Customer_Hold_VF'];
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        list<String> EmailAddr = new list<String>();
        //[SELECT Email FROM User WHERE Id =: CPR1.NQT_Project_Manager__c LIMIT 1]
        //if(CPR1.NQT_Program_Manager__r.Email != null)
           EmailAddr.add([SELECT Email FROM User WHERE Id =: CPR1.NQT_Program_Manager__c LIMIT 1].Email); 
        //if(CPR1.NQT_Account_Manager__r.Email != null)
           EmailAddr.add([SELECT Email FROM User WHERE Id =: CPR1.NQT_Account_Manager__c LIMIT 1].Email);
        if(CPR1.NQT_FE__c != null)
            EmailAddr.add([SELECT Email FROM User WHERE Id =: CPR1.NQT_FE__c LIMIT 1].Email);
        if(CPR1.NQT_SE__c != null)
            EmailAddr.add([SELECT Email FROM User WHERE Id =: CPR1.NQT_SE__c LIMIT 1].Email);
        if(CPR1.NQT_SE_MSC__c != null)
            EmailAddr.add([SELECT Email FROM User WHERE Id =: CPR1.NQT_SE_MSC__c LIMIT 1].Email);
        if(Profile.contains('Customer'))
            EmailAddr.add(Customer.Email);
        
        email.setToAddresses(EmailAddr);    
        email.setTargetObjectId(CPR1.NQT_Program_Manager__c);
        email.setWhatId(CPR1.id);     
        email.setSaveAsActivity(false);            
        email.setTemplateId(et.id);            
        Messaging.sendEmail(New Messaging.SingleEmailMessage[]{email});
        
        PageReference pgref = new PageReference('/'+CPRid);
        return pgref;
        }
    static testMethod void NQTCustomerHold (){
        CPR__c c = new CPR__c();
        ApexPages.StandardController con = new ApexPages.StandardController(c);
        NQTCustomerHold ch = new NQTCustomerHold(con);
        PageReference pageRef = Page.NQT_Customer_Hold;
        Test.setCurrentPage(pageRef);
        CPR__c CPR = new CPR__c();
        
        User DummyUser = new User();
        DummyUser.LastName = 'adc';
        DummyUser.FirstName = 'adc';
        DummyUser.Alias = 'adc';
        DummyUser.Email = 'a@a.a';
        DummyUser.Username = 'a@a.a.adc';
        DummyUser.CommunityNickname = 'a';
        DummyUser.IsActive = TRUE;
        DummyUser.ProfileId = [SELECT Id FROM Profile WHERE Name LIKE '%System Administrator%' LIMIT 1].Id;
        DummyUser.TimeZoneSidKey = 'Asia/Kamchatka';
        DummyUser.LocaleSidKey = 'en_US';
        DummyUser.EmailEncodingKey = 'ISO-8859-1';
        DummyUser.LanguageLocaleKey = 'en_US';
        insert DummyUser;
        
        
        //CPR.NQT_If_Other_MTSO__c = NULL;
        //CPR.NQT_Database_Work_Description__c = NULL;
        CPR.NQT_Customer_Requested_Ship_Date__c = dateTime.now()+1;
        CPR.NQT_Target_Service_Start_Date__c = date.today()+1;
        CPR.NQT_Target_Service_Finish_Date__c = date.today()+1;
        CPR.NQT_Customer__c = 'VERIZON';
        CPR.NQT_CPR_Name__c = 'a';
        CPR.NQT_Customer_contact_Name__c = 'a';
        CPR.NQT_Customer_Contact_Phone__c = '3333';
        CPR.NQT_Customer_Email_Address__c = 'test@test.com';
        CPR.NQT_CPR_Start_Date__c = date.today();
        CPR.NQT_Account_manager__c = DummyUser.id;//'005Z0000000HsI1';
        CPR.NQT_Area__c = 'Mid West';
        CPR.NQT_Market__c = 'St. Clairesville';
        CPR.NQT_MTSO__c = 'St. Clairesville';
        CPR.NQT_Program_Manager__c = DummyUser.id;//'005Z0000000HsI2';
        CPR.NQT_Requested_Quote_Delivery_Date__c = dateTime.now()+1;
        CPR.NQT_Type_Of_Request__c = 'Services Only';
        CPR.NQT_MTX_Ericsson__c = TRUE;
        CPR.NQT_if_other__c = 'a';
        /*CPR.NQT_Product__c = 'BTS';
        CPR.NQT_SE__c = DummyUser.id;//'005Z0000000Hnsp';//[SELECT Id FROM USER WHERE Name LIKE: '%Test%' LIMIT 1].Id;
        CPR.NQT_FE__c = DummyUser.id;//'005Z0000000Hnsp';//[SELECT Id FROM USER WHERE Name LIKE: '%Test%' LIMIT 1].Id;
        CPR.NQT_SE_MSC__c = DummyUser.id;//'005Z0000000Hnsp';//[SELECT Id FROM USER WHERE Name LIKE: '%Test%' LIMIT 1].Id;
        CPR.NQT_Project_Manager__c = [SELECT Id FROM USER WHERE Name LIKE: '%Test%' LIMIT 1].Id;*/
        
        insert CPR;//}catch(exception e){}
        
        ApexPages.currentPage().getParameters().put('id', CPR.Id);
        ch.cpr.Reason_for_Customer_Hold__c = 'aa';
        ch.confirm();
        
    }        
}