src/objects/KPI_IntermediateComputation__c.object
<CustomObject>
    <fields>
        <fullName>KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI_IntermediateComputations</relationshipLabel>
        <relationshipName>KPI_IntermediateComputations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>KPI_IntermediateComputation</label>
    <nameField>
        <displayFormat>KI-{0000}</displayFormat>
        <label>KPI_IntermediateComputation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI_IntermediateComputations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE2_DeleteKPIIntermediate.cls
global class SPE2_DeleteKPIIntermediate implements Database.Batchable<sObject>{
    global String kpiDefinationID; 
    global String query;
     global SPE2_DeleteKPIIntermediate(String kpiDefinationID){
        this.kpiDefinationID = kpiDefinationID;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        query = 'Select Id FROM KPI_IntermediateComputation__c Where KPI__c =: kpiDefinationID';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC,List<KPI_IntermediateComputation__c> scope){ 
        delete scope;        
    }          
    global void finish(Database.BatchableContext BC){
        if(!Test.isRunningTest()){
            SPE2_DeletePITempValues dBatch = new SPE2_DeletePITempValues(kpiDefinationID);
            database.executebatch(dBatch,1000);
        }
    }      
}