src/objects/MCAR__c.object
<CustomObject>
    <description>Material Corrective Action Report.</description>
    <fields>
        <fullName>MCAR_Manufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer</label>
        <referenceTo>MCAR_Manufacturer__c</referenceTo>
        <relationshipLabel>MCARs</relationshipLabel>
        <relationshipName>MCARs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Site__c</fullName>
        <label>Manufacturer Site</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>MCARs</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>MCAR No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MCARs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MCAR_Manufacturer__c.object
<CustomObject>
    <label>Manufacturer</label>
    <nameField>
        <label>Manufacturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MCAR_Manufacturer_Site__c.object
<CustomObject>
    <fields>
        <fullName>MCAR_Manufacturer_Site_Address__c</fullName>
        <label>Manufacturer Site Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer Name</label>
        <referenceTo>MCAR_Manufacturer__c</referenceTo>
        <relationshipLabel>Manufacturer Sites</relationshipLabel>
        <relationshipName>MCAR_Manufacturer_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MCAR Manufacturer Site</label>
    <nameField>
        <label>Manufacturer Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCAR Manufacturer Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ManufacturerSiteOnMCAR.cls
public class ManufacturerSiteOnMCAR {
    
    public MCAR__c vmcar {get;set;}
    public MCAR_Manufacturer__c vmanfac {get;set;}
    public list<MCAR_Manufacturer_Site__c> vlstms {get;set;}
    public list<MCAR_Manufacturer_Site__c> Selectedms {get;set;}
    public list<MCAR_Manufacturer_Site__c> SelectedSites {get;set;}
    public list<wrappersites> vlstwst {get;set;}
    public list<wrappersites> vlstSelwst {get;set;}
    public list<MCAR__c> vlstmacr {get;set;}
    public ManufacturerSiteOnMCAR(ApexPages.StandardController stdcontroller)
    {
       string str = apexpages.currentPage().getParameters().get('id');
        vmcar = [select id,MCAR_Manufacturer__c ,Manufacturer_Site__c from MCAR__c where id =:str];
        vlstmacr  = new list<MCAR__c>();
         Selectedms = new list<MCAR_Manufacturer_Site__c>();
        SelectedSites = new list<MCAR_Manufacturer_Site__c>();
        system.debug('Current Record id----->' + vmcar);
        if(vlstwst == null)
        {
            vlstwst = new list<wrappersites>();
            vlstSelwst = new list<wrappersites>();
             
            vlstms = [select id,Name,Manufacturer_Name__c,MCAR_Manufacturer_Site_Address__c from MCAR_Manufacturer_Site__c where Manufacturer_Name__c =:vmcar.MCAR_Manufacturer__c];
            for(MCAR_Manufacturer_Site__c ms : vlstms)
            {
                if(ms.name!= vmcar.Manufacturer_Site__c)
                {                    
                    wrappersites us = new wrappersites(ms);             
                    vlstwst.add(us);
                }                
                else
                {
                    wrappersites us = new wrappersites(ms);
                    us.vbool = true;
                    vlstwst.add(us);
                }                 
           }            
        }
        
        for(wrappersites ws : vlstwst)
            {
             if(ws.vbool == true)
                {
                    Selectedms.add(ws.vms);
                    vlstSelwst.add(ws);
                }
            }
          SelectedSites = Selectedms;
		Selectedms.clear();
        system.debug('Current Record id----->' + vmcar);
        
        system.debug('SelectedSites--->'+ SelectedSites);
    }
    public pagereference DisplaySiteAccounts()
    {
        pagereference pr = new pagereference('/' + vmcar.id );
         pagereference pr2 = new pagereference('/apex/ManufactureSiteOnMCAR');
       
        for(wrappersites ws : vlstwst)
            {
             if(ws.vbool == true)
                {
                    system.debug('\n***'+ws.vbool+'***'+ws.vms);
                    Selectedms.add(ws.vms);
                    vlstSelwst.add(ws);
                }
            }                        
        
          SelectedSites = Selectedms;    
        SelectedSites.size();
        system.debug('Current Record id----->' + vmcar);
        
        system.debug('SelectedSites--->'+ SelectedSites);
    
        if(Selectedms.size() > 1)
        {
            
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Please Select only one Site'));
            SelectedSites.clear();
            return null;
            
        }
        else
        {
            String id=System.currentpagereference().getparameters().get('id');
            
           if(SelectedSites.size() > 0)
           {
           for(integer i=0;i<=SelectedSites.size();i++)
           {
             vmcar.Manufacturer_Site__c = SelectedSites[0].name;
             
           }
           // pr.setRedirect(true);
          }
             update vmcar;
             return pr;
        }                
    }
       
    public class wrappersites
    {
        public boolean vbool {get;set;}
        public MCAR_Manufacturer_Site__c vms {get;set;}
        public wrappersites(MCAR_Manufacturer_Site__c lstms)
        {
           vbool = false;
            vms = lstms;
        }
    }
}