src/objects/MCAR__c.object
<CustomObject>
    <description>Material Corrective Action Report.</description>
    <fields>
        <fullName>MCAR_CC_Email2__c</fullName>
        <label>CC Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MCAR_CC_Email3__c</fullName>
        <label>CC Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MCAR_CC_Email4__c</fullName>
        <label>CC Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MCAR_CC_Email5__c</fullName>
        <label>CC Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MCAR_CC_Email__c</fullName>
        <label>CC Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MCAR_Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Final assembly facility product was built in</description>
        <inlineHelpText>Final assembly facility product was built in</inlineHelpText>
        <label>Facility</label>
        <referenceTo>MCAR_Facility__c</referenceTo>
        <relationshipLabel>MCARs</relationshipLabel>
        <relationshipName>MCARs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MCAR_Factory_GM_Email__c</fullName>
        <description>A notification mail will be send to Factory GM Email id, if Severity Level is selected as High and Defect Location is Incoming or Production.</description>
        <inlineHelpText>A notification mail will be send to Factory GM Email id, if Severity Level is selected as High and Defect Location is Incoming or Production.</inlineHelpText>
        <label>Factory GM Email(s)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MCAR_Manufacturer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer</label>
        <referenceTo>MCAR_Manufacturer__c</referenceTo>
        <relationshipLabel>MCARs</relationshipLabel>
        <relationshipName>MCARs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MCAR_Mfg_Part_Number__c</fullName>
        <label>Mfg. Part Number</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Site__c</fullName>
        <label>Manufacturer Site</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>MCARs</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>MCAR No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MCARs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MCAR_Facility__c.object
<CustomObject>
    <fields>
        <fullName>MCAR_Facility_Company__c</fullName>
        <label>Company</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>MCAR Facility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MCAR_Facility_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Facility__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Facility</label>
        <referenceTo>MCAR_Facility__c</referenceTo>
        <relationshipLabel>Facility Contacts</relationshipLabel>
        <relationshipName>Facility_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MCAR_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MCAR User Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>MCAR</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Facility_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Facility Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MCAR_Manufacturer__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enterprise_ID__c</fullName>
        <label>Enterprise ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCAR_Supplier_Admin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer Admin</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Nokia MCAR External Supplier</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Manufacturers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Manufacturer</label>
    <nameField>
        <label>Manufacturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MCAR_Manufacturer_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MCAR_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MCAR User Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>Nokia MCAR External Supplier,Nokia MCAR EMS 2.0 User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Manufacturer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer Name</label>
        <referenceTo>MCAR_Manufacturer__c</referenceTo>
        <relationshipLabel>Manufacturer Contacts</relationshipLabel>
        <relationshipName>Manufacturer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>MCAR Manufacturer Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Manufacturer_Name__c</field>
                <operation>equals</operation>
                <valueField>MCAR_Manufacturer_Site__c.Manufacturer_Name__c</valueField>
            </filterItems>
            <infoMessage>Please Select A Manufacturer Site</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>MCAR_Manufacturer_Site__c</referenceTo>
        <relationshipLabel>Manufacturer Contacts</relationshipLabel>
        <relationshipName>Manufacturer_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Manufacturer Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturer Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MCAR_Manufacturer_Site__c.object
<CustomObject>
    <fields>
        <fullName>MCAR_Manufacturer_Site_Address__c</fullName>
        <label>Manufacturer Site Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer Name</label>
        <referenceTo>MCAR_Manufacturer__c</referenceTo>
        <relationshipLabel>Manufacturer Sites</relationshipLabel>
        <relationshipName>MCAR_Manufacturer_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>MCAR Manufacturer Site</label>
    <nameField>
        <label>Manufacturer Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MCAR Manufacturer Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MCAR_MEPS__c.object
<CustomObject>
    <fields>
        <fullName>MCAR_MEPS_Enterprise_ID__c</fullName>
        <label>Enterprise ID</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCAR_Mfg_Part_Number__c</fullName>
        <label>Mfg. Part Number</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MCAR_NSN_Part__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NSN Part</label>
        <referenceTo>NSN_Part__c</referenceTo>
        <relationshipName>MCAR_MEPS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer Name</label>
        <referenceTo>MCAR_Manufacturer__c</referenceTo>
        <relationshipName>MCAR_MEPS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MEPS</label>
    <nameField>
        <label>NSN Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MEPS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MCAR_NSN_Contacts__c.object
<CustomObject>
    <fields>
        <fullName>COM__c</fullName>
        <label>COM</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_External_Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Enterprise_ID__c</fullName>
        <label>Enterprise ID</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tec__c</fullName>
        <label>TEC</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <label>NSN Contact</label>
    <nameField>
        <label>NSN Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSN Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NSN_Part__c.object
<CustomObject>
    <fields>
        <fullName>COM__c</fullName>
        <label>COM</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Full description of the part</description>
        <inlineHelpText>Full description of the part</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSN_Part_Family__c</fullName>
        <label>Part Family</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSN_Part_Lifecycle__c</fullName>
        <description>Status of NSN Part Number</description>
        <inlineHelpText>Status of NSN Part Number</inlineHelpText>
        <label>Lifecycle</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NSN_Part_Recomendation__c</fullName>
        <label>Recomendation</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NSN_Part_Type__c</fullName>
        <description>Part commodity type</description>
        <inlineHelpText>Part commodity type</inlineHelpText>
        <label>Part Type</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TEC__c</fullName>
        <label>TEC</label>
        <length>127</length>
        <type>Text</type>
    </fields>
    <label>NSN Part</label>
    <nameField>
        <label>NSN Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NSN Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MCAR_Batch_PastDue_7DApproval_Test.cls
@isTest
private class MCAR_Batch_PastDue_7DApproval_Test{
static testmethod void MCAR_PastDue_7DApproval(){

User DummyUser = new User();
        DummyUser.LastName = 'adc';
        DummyUser.FirstName = 'adc';
        DummyUser.Alias = 'adc';
        DummyUser.Email = 'a@a.a';
        DummyUser.Username = 'a@a.a.adc';
        DummyUser.CommunityNickname = 'a';
        DummyUser.IsActive = TRUE;
        DummyUser.ProfileId = [SELECT Id FROM Profile WHERE Name LIKE '%System Administrator%' LIMIT 1].Id;
        DummyUser.TimeZoneSidKey = 'Asia/Kamchatka';
        DummyUser.LocaleSidKey = 'en_US';
        DummyUser.EmailEncodingKey = 'ISO-8859-1';
        DummyUser.LanguageLocaleKey = 'en_US';
        insert DummyUser;
        
        
        User DummyUserManufacturer = new User();
        DummyUserManufacturer .LastName = 'adcd';
        DummyUserManufacturer .FirstName = 'adcd';
        DummyUserManufacturer .Alias = 'adcd';
        DummyUserManufacturer .Email = 'ab@ab.ab';
        DummyUserManufacturer .Username = 'ab@ab.ab.adcb';
        DummyUserManufacturer .CommunityNickname = 'ab';
        DummyUserManufacturer .IsActive = TRUE;
        DummyUserManufacturer .ProfileId = [SELECT Id FROM Profile WHERE Name LIKE '%Nokia MCAR External Supplier%' LIMIT 1].Id;
        DummyUserManufacturer .TimeZoneSidKey = 'Asia/Kamchatka';
        DummyUserManufacturer .LocaleSidKey = 'en_US';
        DummyUserManufacturer .EmailEncodingKey = 'ISO-8859-1';
        DummyUserManufacturer .LanguageLocaleKey = 'en_US';
        insert DummyUserManufacturer ;
        
        User owner = DummyUser;
     User manufacturerUser  =DummyUserManufacturer;
     
     RecordType rtDraftMCAR = [select Id from RecordType where SObjectType='MCAR__c' and Name='Draft MCAR' limit 1];
     RecordType rtOpenMCAR = [select Id from RecordType where SObjectType='MCAR__c' and Name='Open MCAR' limit 1];
    MCAR_Manufacturer__c manufacturer = new MCAR_Manufacturer__c (Name='Test Systems Inc.',ownerId=owner.Id, MCAR_Supplier_Admin__c=manufacturerUser.id );
    insert manufacturer;
    // Manufacturer is wrong here  
    MCAR_Manufacturer_Site__c testSite = new MCAR_Manufacturer_Site__c(name='Test',Manufacturer_Name__c=manufacturer.id, MCAR_Manufacturer_Site_Address__c='Test',Zip__c = '12345'  );
    
    insert testSite;
    
    //MCAR_Manufacturer_Site__c=testSite.id,  
    MCAR_Manufacturer_Contact__c manufacturerContact = new MCAR_Manufacturer_Contact__c(Manufacturer_Site__c=testSite.id, Name='First', Email__c='last@company.com', Manufacturer_Name__c=manufacturer.Id, ownerId=owner.Id, MCAR_User__c=manufacturerUser.id  );
    insert manufacturerContact;
    
    
     
    NSN_Part__c testNSNPart = new NSN_Part__c(Name='1234567', Description__c='t', NSN_Part_Lifecycle__c='t', NSN_Part_Type__c='t', NSN_Part_Family__c='t', NSN_Part_Recomendation__c='Y', Tec__c='TEC1',Com__c='COM1' ); 
    insert testNSNPart; 
    
    MCAR_MEPS__c testMCARMeps =new MCAR_MEPS__c(Name='1234567',MCAR_NSN_Part__c=testNSNPart.id , MCAR_Mfg_Part_Number__c='1234', MCAR_MEPS_Enterprise_ID__c='TESTEID', Manufacturer_Name__c=manufacturer.Id);
    insert testMCARMeps;
    
    MCAR_NSN_Contacts__c nsnContactPart = new MCAR_NSN_Contacts__c (Domain__c='COM', Com__c='COM1', Name='123', Contact_External_Id__c=1122223, First_Name__c='First', Last_Name__c='Last', email__c='last@company.com' );
    insert nsnContactPart; 

    MCAR_NSN_Contacts__c nsnContactPart2 = new MCAR_NSN_Contacts__c ( Domain__c='TEC', Tec__c='TEC1', Name='123', Contact_External_Id__c=1122222, First_Name__c='First', Last_Name__c='Last', email__c='last@company.com');
    insert nsnContactPart2; 

    MCAR_NSN_Contacts__c nsnContactPart3 = new MCAR_NSN_Contacts__c ( Domain__c='Supplier', Enterprise_ID__c='TESTEID', Name='123', Contact_External_Id__c=1122221, First_Name__c='First', Last_Name__c='Last', email__c='last@company.com');
    insert nsnContactPart3; 

    //MCAR_NSN_Part_Contacts__c testNSNPartContact= new MCAR_NSN_Part_Contacts__c(    MCAR_NSN_Id__c= nsnContactPart.id, MCAR_NSN_Part__c=testNSNPart.id, MCAR_Role__c='test', MCAR_Topic__c='test' ); 
    //insert testNSNPartContact;
    
    MCAR_Facility__c testFacility = new MCAR_Facility__c(Name ='Chennai', MCAR_Facility_Company__c='NSN');
    insert testFacility;
    // facility removed 
    MCAR_Facility_Contact__c nsnContactFacility = new MCAR_Facility_Contact__c( Facility__c=testFacility.id,  Name='First', email__c='last@company.com' );
    insert nsnContactFacility;
     
   MCAR__c testMCAR = new MCAR__c(MCAR_Factory_GM_Email__c='test@test.com', MCAR_CC_Email__c='test@test.com', MCAR_CC_Email2__c='test@test.com',MCAR_CC_Email3__c='test@test.com',MCAR_CC_Email4__c='test@test.com',MCAR_CC_Email5__c='test@test.com', MCAR_Facility__c=testFacility.id,  MCAR_Status__c='Draft', MCAR_Failure_Type__c='Visual', MCAR_NSN_Code__c=testMCARMeps.id,MCAR_Severity_Level__c='Low',MCAR_Defect_Location__c='Production',MCAR_Defect_Quantity__c=4,MCAR_Product_Name__c='Test',MCAR_2D_Prob_Desc__c='Test',MCAR_2D_Analysis_Findings__c='Test',MCAR_3D_Days_Allowed__c='2',MCAR_4D_Days_Allowed__c='15',MCAR_5D_Days_Allowed__c='30',MCAR_6D_Days_Allowed__c='35',MCAR_7D_Days_Allowed__c='45',MCAR_Current_8D_Step__c='2D=Problem/Analysis', RecordTypeId=rtDraftMCAR.id,MCAR_7D_Due_Date__c=date.today()-5, MCAR_7D_Approval__c=false );
    insert testMCAR;
    MCAR_Batch_PastDue_7DApproval MBP = new MCAR_Batch_PastDue_7DApproval();
    Database.BatchableContext DBC;
    List<MCAR__C> obj = new List<MCAR__c>();
    obj.add(testMCAR);
    try{MBP.execute(DBC,obj);}catch(exception e){}
    MBP.start(DBC);
    MBP.finish(DBC);
}
}