src/objects/MCAR_Claim_Management__c.object
<CustomObject>
    <description>Object for Claim management process</description>
    <fields>
        <fullName>Claims_Business_Unit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>AA (Application Analytics)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AA-CT (AA Common Central Team)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FN-FANBI (ALU Fixed Networks NBI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FN-FNA (ALU-FNA - New Activities)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FN-FND (Fixed Networks)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FN-MVM (ALU - Multivendor Maintenance)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IONCD (ION Central Team)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IONIPR (ALU ION IP Routing)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IONNBI (ION OPTICS NBI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IONOP (ION - OPTICS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IONVID (ALU-ION-IP VIDEO )</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-3PI (3PI - 3rd Party Integration)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-AMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-COPR (ALU-MN Project related)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-HLN (ALU-MN HLN (backlog))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-MCT (MOBILE CENTRAL TEAM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-MOB (MN-MOBILE )</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-MSA (ALU-MN Service Assurance)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-MSI (MN - SDM - IMS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-MSPD (Managed Serv. andCyber Security)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-NBI (Network Build and Implementat. (backlog))</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-WNBI (Wireless Network Build and Implement.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN-WTD (MOBILE Wireless Transmission)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH-BLD (Bell Labs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH-BPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH-CS (Consulting Services)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH-IPCS (Intellectual Property Business Division)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH-OTHFUN (OTHER R and D FUNDING)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH-RFS (Radio Frequency Systems)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTH-SMD (Submarine)</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Claims_Product_Name__c</fullName>
        <label>Product Name</label>
        <picklist>
            <controllingField>Claims_Business_Line__c</controllingField>
            <picklistValues>
                <fullName>LTE 2.3GHZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.9 CLPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.9CLPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1.9G CDMA XMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1X MODEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1X MODEM PICO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1XMODEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2*2LTE PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1G DDRF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1G LPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1G SLIM XMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1G TRX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1G UBS XMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1G XMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2.1RFH/800RFH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800 CLPA/1,9 CLPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800 MHZ XMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800 RFH TANAPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800CLPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800M SLIM XMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800M UBS XMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800M CDMA XMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800M SLIM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800M XMI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800RFH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>A1800</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACTA 2.0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADM4000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ADPDU-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALARM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Manufacturer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Manufacturer for general info section</description>
        <inlineHelpText>Supplier that will be the recipient of this claim.</inlineHelpText>
        <label>Manufacturer</label>
        <referenceTo>MCAR_Manufacturer__c</referenceTo>
        <relationshipLabel>Claims</relationshipLabel>
        <relationshipName>Claims</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_Category__c</fullName>
        <label>Category Area</label>
        <picklist>
            <picklistValues>
                <fullName>Indirect Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Services Procurement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSCM AMS PO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Claim</label>
    <nameField>
        <displayFormat>Claim-{00000}</displayFormat>
        <label>Claim ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Claims</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MCAR_Manufacturer__c.object
<CustomObject>
    <fields>
        <fullName>Manufacturer_Name_Ext_Id__c</fullName>
        <externalId>true</externalId>
        <label>Manufacturer Name Ext Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Manufacturer</label>
    <nameField>
        <label>Manufacturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SendEmailOnClaimOwner_test.cls
@istest
public class SendEmailOnClaimOwner_test {
static testmethod void test(){
           MCAR_Manufacturer__c manufacturer = new MCAR_Manufacturer__c();
        manufacturer.Manufacturer_Name_Ext_Id__c = '1ST LABEL' ;
        insert manufacturer ;
        
       MCAR_Claim_Management__c Claim = new MCAR_Claim_Management__c();
         claim.Manufacturer__c = manufacturer.Id;
        claim.Part_Category__c = 'Indirect Procurement (IP)' ;
        claim.Claims_Business_Unit__c = 'Business Solutions';
        claim.Claims_Product_Name__c = 'LTE 2.3GHZ';
        insert claim;    
}
}