src/objects/MCAR_Category_Cross_Reference__c.object
<CustomObject>
    <description>MCAR- DEM0008846</description>
    <fields>
        <fullName>COM__c</fullName>
        <label>Legacy COM</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area_ID__c</fullName>
        <label>Category Area ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <description>MCAR- DEM0008846</description>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group_ID__c</fullName>
        <label>Category Group ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <description>MCAR- DEM0008846</description>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_ID__c</fullName>
        <label>Category ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ESN__c</fullName>
        <description>MCAR- DEM0008846</description>
        <label>COM (ESN, SubCatID)</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Category XR</label>
    <nameField>
        <label>Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Category XR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MCAR_Manufacturer__c.object
<CustomObject>
    <fields>
        <fullName>Enterprise_ID__c</fullName>
        <label>Enterprise ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Manufacturer</label>
    <nameField>
        <label>Manufacturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MCAR_MEPS__c.object
<CustomObject>
    <fields>
        <fullName>Manufacturer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manufacturer Name</label>
        <referenceTo>MCAR_Manufacturer__c</referenceTo>
        <relationshipName>MCAR_MEPS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_ID__c</fullName>
        <label>Supplier ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <label>Supplier Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MEPS</label>
    <nameField>
        <label>NSN Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MEPS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MCAR_Supplier_Data_Cross_Reference__c.object
<CustomObject>
    <description>MCAR- DEM0008846</description>
    <fields>
        <fullName>Enterprise_ID__c</fullName>
        <label>Enterprise ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Name__c</fullName>
        <description>MCAR- DEM0008846</description>
        <inlineHelpText>Should be one of the field values from the &quot;Manufacturer name&quot; fields in MEPS.</inlineHelpText>
        <label>Manufacturer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supplier_Name__c</fullName>
        <description>MCAR- DEM0008846</description>
        <label>Supplier Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Supplier XR</label>
    <nameField>
        <label>Supplier ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Supplier XR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MCARSupplierData_test.cls
@isTest
Public class MCARSupplierData_test
{
public static testmethod void UpdateNSNPartsDatatestmethod()
{

MCAR_Category_Cross_Reference__c   obj = new MCAR_Category_Cross_Reference__c();
obj.name= 'abc';
obj.Category_Area__c ='testarea';
obj.Category_Area_ID__c ='testareaid';
obj.Category_Group__c = 'testgroup';
obj.Category_Group_ID__c ='testgroupcid';
obj.Category_ID__c = 'catid';
obj.COM__c ='com';
obj.Sub_Category__c='sub';
obj.ESN__c='esn';
insert obj;

}

public static testmethod void UpdateMEPSDatatestmethod(){


MCAR_Manufacturer__c man = new MCAR_Manufacturer__c();
man.name = 'mtest';

insert man;

MCAR_Supplier_Data_Cross_Reference__c obj = new MCAR_Supplier_Data_Cross_Reference__c();
obj.name= 'abc';
obj.Enterprise_ID__c='testid';
obj.Manufacturer_Name__c = man.name;
obj.Supplier_Name__c='testname';


MCAR_MEPS__c mep = new MCAR_MEPS__c();
mep.Manufacturer_Name__c=man.id;
insert mep;
MCAR_MEPS__c mep1 = new MCAR_MEPS__c();
mep1 = [select id,name,Supplier_Name__c,Supplier_ID__c from MCAR_MEPS__c where id =:mep.id];
mep1.Supplier_ID__c = obj.name;
mep1.Supplier_Name__c = obj.Supplier_Name__c;
update mep1;
insert obj;


}

}