src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPETemplate__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>BUILDING INVESTMENT/CAPEX WITHOUT RENTS AND LEASES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FACILITY MANAGEMENT SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RENTAL/LEASE/TRANSACTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UTILITIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPLICATION DEVELOPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPLICATION MAINTENANCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT HW PERIPHERALS / SERVERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INFRASTRUCTURE SERVICES &amp; CLOUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOBILE VOICE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WORKPLACE DEVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSOCIATED SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANSPORT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WAREHOUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUSINESS SERVICES OTHERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COACHING &amp; OTHER CONSULTING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONSULTING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FINANCIAL TAX &amp; INSURANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LEGAL &amp; INTELLECTUAL PROPERTY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARKETING &amp; COMMUNICATIONS SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFFICE SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TEST SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRAINING SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FUNCTIONAL TEST EQUIPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT PERIPHERAL DEVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MANUFACTURING AUXILIARIES AND CONSUMABLES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MANUFACTURING EQUIPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PERFORMANCE TEST EQUIPMENT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>CHARGING GATEWAY CG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGING GATEWAY CG SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGING@VANTAGE SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIRCUIT SWITCHED DATA SERVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLASSROOM TRAINING OPEN SEAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMD SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS-8200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS-8200 DRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS-8200 DRA SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS-8200 HSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS-8200 HSS SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMX5000 SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-NTDB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-NTDB HW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-NTDB SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CODE SOLUTION PLANNING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMISSIONING OF X</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMON MANAGEMENT SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMON RACK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMUNICATION SUITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMUNICATIONS INTERFACE SERVER (CIS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMUNITY SERVICE DATA MANAGER (CSDM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMUNITY SERVICE DATA MANAGER (CSDM) HW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMUNITY SERVICE DATA MANAGER (CSDM) SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPACT DX MSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPETENCE DEVELOPMENT SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPETENCE TESTING SERVICE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPTEL INSTANTLINK (SAFIR) PROVISIONING TOOL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SPE Template</label>
    <nameField>
        <label>SPE Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_SPETemplateTriggerTest.cls
@isTest(SeeAllData = False)
public class SPE_SPETemplateTriggerTest 
{
    static TestMethod void updateTest()
    {     
         //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
        
        SPE_PIDefinition__c piDefinition = SPE_TestObjectCreator.CreatePIDefinition();
        piDefinition.LifecycleStage__c = 'Draft';
        piDefinition.ValuesType__c = 'Number';   
        piDefinition.DataAcquisitionMethod__c = 'Data Load';  
        piDefinition.PIUploadDuedate__c  = Date.newInstance(2020,10,10);     
        insert piDefinition;
        piDefinition.LifecycleStage__c = 'Published'; 
        update piDefinition;
        
        SPE_KPIDefinition__c kpiDefinition = SPE_TestObjectCreator.CreateKPIDefinition(1);
        
        kpiDefinition.PI_Data__c = piDefinition.Id;
        kpiDefinition.FrequencyinMonth__c = NULL;
        kpiDefinition.ScheduledDate__c = NULL;
        kpiDefinition.Buffer_Days__c = Null;
        
        insert kpiDefinition;
        
        SPE_SPETemplateTrigger speTemplateTrigger = new SPE_SPETemplateTrigger();
        List<SPE_SPETemplate__c> speTemplateList = new List<SPE_SPETemplate__c>();
        for(integer i=0;i<2;i++)
        {
        SPE_SPETemplate__c speTemplate = SPE_TestObjectCreator.CreateSPETemplate();
        speTemplate.Stage__c = 'Published';
        speTemplateList.add(speTemplate);
        }
        
        Insert speTemplateList;
        SPE_SPETemplateTrigger.DeleteValidation(speTemplateList);
        
     }     
}