src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DataAcquisitionMethod__c</fullName>
        <inlineHelpText>Identify how this data is acquired</inlineHelpText>
        <label>Data Acquisition Method</label>
        <picklist>
            <picklistValues>
                <fullName>Data Load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standalone Survey</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>PI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIAbbreviation__c</fullName>
        <inlineHelpText>10 Character Limit</inlineHelpText>
        <label>PI Abbreviation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of PI 
(Standard Name field of PI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>PI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>i.e. Days, Units, %, Euros, etc.</inlineHelpText>
        <label>Unit of Measure</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValuesType__c</fullName>
        <description>To describe PI values data type</description>
        <inlineHelpText>Specify type of data values for this PI</inlineHelpText>
        <label>Values Type</label>
        <picklist>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PiValueTemp__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <encrypted>true</encrypted>
        <label>Enterprise ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PIDefination__c</fullName>
        <label>PI Defination</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>SPE_PiValueTemps</relationshipLabel>
        <relationshipName>SPE_PiValueTemps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidateCategory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ValidateCategory</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE_PiValueTemp</label>
    <nameField>
        <displayFormat>PV-{0000}</displayFormat>
        <label>SPE_PiValueTemp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE_PiValueTemps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_Stop__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Stop_trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Stop  KPI Recursoin</label>
</CustomObject>

src/classes/spe_verifycategoryExtTest.cls
@IsTest(SeeAllData=false)

    public with sharing class spe_verifycategoryExtTest{
    static testmethod void spe_verifycategoryExtTest()
    {
    
     //---Custom Setting data ---
    LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
    PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
    picklistObj.Business_Line__c = 'All Business Lines';
    picklistObj.Business_Unit__c = 'All Business Units';
    picklistObj.Category_Area__c = 'All Category Areas';
    picklistObj.Category_Group__c = 'All Category Groups';
    picklistObj.Category__c = 'All Categories';
    picklistObj.Country__c = 'All Countries';
    picklistObj.Market_Unit__c = 'All Market Units';
    picklistObj.Market__c = 'All Markets';
    picklistObj.Name = 'Picklist Default Values';
    picklistObj.Product__c = 'All Products';
    picklistObj.Project__c = 'All Projects';
    
    lstpicklistObj.add(picklistObj);
    
    insert lstpicklistObj;
    
    insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
     
     
     SPE_PIDefinition__c pd1= new SPE_PIDefinition__c();
     
     //**************************Changes For Encryption*******************//
     //pd1.name= 'test pd1';
     pd1.PI_Title__c = 'test pd1';
     //**************************END*******************// 
     
     pd1.PIAbbreviation__c='pabb';   
     pd1.ValuesType__c='Number';
     pd1.UoM__c='number';
     pd1.DataAcquisitionMethod__c='Survey Question';
     pd1.GeoScope__c='Country';
     pd1.CategoryScope__c='Category Area';
     pd1.BUScope__c='Product';
     
     insert pd1;
     
     //**************************Changes For Encryption*******************//
     //system.assertequals(pd1.name,'test pd1');
     system.assertequals(pd1.PI_Title__c,'test pd1');
     //**************************END*******************//
       
     pd1.lifecyclestage__c='Published';
     
     update pd1;
     
     
     SPE_PiValueTemp__c PIvalTemp = new SPE_PiValueTemp__c();    
     PIvalTemp.CurrencyIsoCode='EUR';
     PIvalTemp.PIDefination__c=Pd1.Id;
     PIvalTemp.EnterpriseId__c='test';
     PIvalTemp.project__c='test';
     PIvalTemp.country__c='test';
     PIvalTemp.Cluster__c='test';
    
    
     PIvalTemp.product__c='test';
     PIvalTemp.BusinessUnit__c='test';
     PIvalTemp.BusinessLine__c='test';        
     PIvalTemp.ValidateCategory__c =false;
    
     Insert PIvalTemp;
        
        
     SPE_PIDefinition__c pd2= new SPE_PIDefinition__c();
     //**************************Changes For Encryption*******************//
     //pd2.name= 'test pd2';
     pd2.PI_Title__c = 'test pd2';
     //**************************END*******************// 
     
     pd2.PIAbbreviation__c='pabb1';   
     pd2.ValuesType__c='Number';
     pd2.UoM__c='number';
     pd2.DataAcquisitionMethod__c='Survey Question';
     pd2.GeoScope__c='Market Unit';
     pd2.CategoryScope__c='Category Group';
     pd2.BUScope__c='Product';
     
     insert pd2;
  
     //**************************Changes For Encryption*******************//
     //system.assertequals(pd2.name,'test pd2');
     system.assertequals(pd2.PI_Title__c,'test pd2');
     //**************************END*******************//
     
     pd2.lifecyclestage__c='Published';
     
     update pd2;
     
        SPE_PiValueTemp__c PIvalTemp1 = new SPE_PiValueTemp__c();    
        PIvalTemp1.CurrencyIsoCode='EUR';
        PIvalTemp1.PIDefination__c=Pd2.Id;
        PIvalTemp1.EnterpriseId__c='test';
        PIvalTemp1.project__c='test';
        PIvalTemp1.country__c='test';
        PIvalTemp1.Cluster__c='test';
        PIvalTemp1.product__c='test';
        PIvalTemp1.BusinessUnit__c='test';
        PIvalTemp1.BusinessLine__c='test';        
        PIvalTemp1.ValidateCategory__c =false;
        PIvalTemp1.Cluster__c='test';
       
        
        
        Insert PIvalTemp1;
      
      
      SPE_PIDefinition__c pd3= new SPE_PIDefinition__c();
     //**************************Changes For Encryption*******************//
     //pd3.name= 'test pd3';
     pd3.PI_Title__c = 'test pd3';
     //**************************END*******************//
     pd3.PIAbbreviation__c='pabb3';   
     pd3.ValuesType__c='Market';
     pd3.UoM__c='number';
     pd3.DataAcquisitionMethod__c='Survey Question';
     pd3.GeoScope__c='Project';
     pd3.CategoryScope__c='Category';
     pd3.BUScope__c='Product';
     
     insert pd3;
  
     //**************************Changes For Encryption*******************//
     //system.assertequals(pd3.name,'test pd2');
     system.assertequals(pd3.PI_Title__c,'test pd3');
     //**************************END*******************//
     
     pd3.lifecyclestage__c='Published';
     
     update pd3;
     
        SPE_PiValueTemp__c PIvalTemp2 = new SPE_PiValueTemp__c();    
        PIvalTemp2.CurrencyIsoCode='EUR';
        PIvalTemp2.PIDefination__c=Pd3.Id;
        PIvalTemp2.EnterpriseId__c='test';
        PIvalTemp2.project__c='test';
        PIvalTemp2.country__c='test';
        PIvalTemp2.Cluster__c='test';
        PIvalTemp2.product__c='test';
        PIvalTemp2.BusinessUnit__c='test';
        PIvalTemp2.BusinessLine__c='test';        
        PIvalTemp2.ValidateCategory__c =false;
        PIvalTemp2.Cluster__c='test';
        
        
        
        Insert PIvalTemp2;
        
        SPE_PIDefinition__c pd4= new SPE_PIDefinition__c();
     //**************************Changes For Encryption*******************//
     //pd4.name= 'test pd4';
     pd4.PI_Title__c = 'test pd4';
     //**************************END*******************//
     pd4.PIAbbreviation__c='pabb4';   
     pd4.ValuesType__c='Market';
     pd4.UoM__c='number';
     pd4.DataAcquisitionMethod__c='Survey Question';
     pd4.GeoScope__c='Market';
     pd4.CategoryScope__c='Category';
     pd4.BUScope__c='Product';
     
     insert pd4;
  
     //**************************Changes For Encryption*******************//
     //system.assertequals(pd4.name,'test pd4');
     system.assertequals(pd4.PI_Title__c,'test pd4');
     //**************************END*******************//
     
     pd4.lifecyclestage__c='Published';
     
     update pd4;
     
        SPE_PiValueTemp__c PIvalTemp3 = new SPE_PiValueTemp__c();    
        PIvalTemp3 .CurrencyIsoCode='EUR';
        PIvalTemp3 .PIDefination__c=Pd4.Id;
        PIvalTemp3 .EnterpriseId__c='test';
        PIvalTemp3 .project__c='test';
        PIvalTemp3 .country__c='test';
        PIvalTemp3 .Cluster__c='test';
        PIvalTemp3 .product__c='test';
        PIvalTemp3 .BusinessUnit__c='test';
        PIvalTemp3 .BusinessLine__c='test';        
        PIvalTemp3 .ValidateCategory__c=false;
        PIvalTemp3.Cluster__c='test';
       
        
        
        Insert PIvalTemp3 ;
        
        spe_verifycategoryExt vcx = new spe_verifycategoryExt();
        
        vcx.updateCat();
        vcx.validateGeography();
        vcx.BatchUpload();
        vcx.skiptoNxtVal();
}
}