src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_Stop__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Stop_trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Stop  KPI Recursoin</label>
</CustomObject>

src/objects/SPE_SurveyAnswer__c.object
<CustomObject>
    <description>For each Survey Question this object defines multiple Answers. The Answers have different types (Ex. Free text, Picklist, single answer etc.).</description>
    <fields>
        <fullName>Choices__c</fullName>
        <description>Choices for the particular question.</description>
        <inlineHelpText>User can have choices for a particular question.</inlineHelpText>
        <label>Choices</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <description>Automatically captures Questions while creating answers under Question Object.</description>
        <inlineHelpText>User can select questions for which they are creating answers.</inlineHelpText>
        <label>SurveyQuestion</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipName>SPE_SurveyAnswers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>Ans-{00000}</displayFormat>
        <label>Answers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_SurveyQuestion__c.object
<CustomObject>
    <customHelpPage>SPE_QuestionBank_Survey_Help_Page</customHelpPage>
    <description>SurveyQuestion object contains Question banks for the survey.</description>
    <fields>
        <fullName>AnswerType__c</fullName>
        <description>Answer type is required to base on Questions</description>
        <inlineHelpText>Select appropriate type of answer</inlineHelpText>
        <label>Answer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Free Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <description>Question which will appear on Survey page</description>
        <inlineHelpText>Enter your question</inlineHelpText>
        <label>Survey Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question Bank</label>
    <nameField>
        <label>Questions ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_AddQuestionAnswerExtTest.cls
@isTest(SeeAllData = False)
private class SPE_AddQuestionAnswerExtTest 
{
    
    static testMethod void createQuestionAnsPositive() 
    {
        Test.startTest();
        
        //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop'); 
        
        SPE_SurveyQuestion__c surQue = new SPE_SurveyQuestion__c();
                
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(surQue);
        
        SPE_AddQuestionAnswerExt addQueAns = new SPE_AddQuestionAnswerExt(stCon);
        
        addQueAns.speSurvey = SPE_TestObjectCreator.CreateSurveyQuestion();
        
        addQueAns.addAnswers();
        addQueAns.addAnswers();
                
        addQueAns.speAnswers[0] = SPE_TestObjectCreator.CreateSurveyAnswer();
        
        addQueAns.speAnswers[1] = SPE_TestObjectCreator.CreateSurveyAnswer();
        
        Apexpages.currentPage().getParameters().put('rowIndex', '1');
        
        addQueAns.deleteQuestionAnswer();
        
        addQueAns.save();
        
        Test.stopTest();
        
        System.assert(addQueAns.speSurvey.Id != null);
        
        List<SPE_SurveyAnswer__c> insertedSurveyAns = [SELECT Id, Choices__c 
                                                       FROM SPE_SurveyAnswer__c
                                                       WHERE SurveyQuestion__c =: addQueAns.speSurvey.Id];
        
        System.assertEquals(insertedSurveyAns.size(), 1);
    }
    
    
    static testMethod void createQuestionAnsNegative()
    {
       
         Test.startTest();
         
         //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop'); 
        
        SPE_SurveyQuestion__c surQue = new SPE_SurveyQuestion__c();
        
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(surQue);
        
        SPE_AddQuestionAnswerExt addQueAns = new SPE_AddQuestionAnswerExt(stCon);
        
        addQueAns.speSurvey = SPE_TestObjectCreator.CreateSurveyQuestion();
        
        addQueAns.save();
       
        System.assertEquals(addQueAns.speSurvey.Id, null); 
        
        Test.stopTest();
        
    }

        
    
    static testMethod void editQuestionAnsDuplicate()
    {
        SPE_SurveyQuestion__c surQue1 = new SPE_SurveyQuestion__c();
        surQue1 = SPE_TestObjectCreator.CreateSurveyQuestion();
        surQue1.AnswerType__c = 'Freetext';
        insert surQue1;
        
        Test.startTest();
        
        //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop'); 
              
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(surQue1);
        
        SPE_AddQuestionAnswerExt addQueAns = new SPE_AddQuestionAnswerExt(stCon);
        
        addQueAns.speSurvey = SPE_TestObjectCreator.CreateSurveyQuestion();
        
        addQueAns.addAnswers();
        addQueAns.addAnswers();
                
        addQueAns.speAnswers[0] = SPE_TestObjectCreator.CreateSurveyAnswer();
        
        addQueAns.speAnswers[1] = SPE_TestObjectCreator.CreateSurveyAnswer();
        
        addQueAns.save();
        
        Test.stopTest();
        
        System.assert(addQueAns.speSurvey.Id != null);
        
    }
    
    static testMethod void deleteQuestionAnsPostive()
    {
        
        
       Test.startTest();
       
       //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop'); 
      
        SPE_SurveyQuestion__c surQue = new SPE_SurveyQuestion__c();
        surQue.AnswerType__c = 'Picklist';
                
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(surQue);
        
        SPE_AddQuestionAnswerExt addQueAns = new SPE_AddQuestionAnswerExt(stCon);
        
        addQueAns.speSurvey = SPE_TestObjectCreator.CreateSurveyQuestion();
        
        addQueAns.addAnswers();
                
        addQueAns.speAnswers[0] = SPE_TestObjectCreator.CreateSurveyAnswer();
        
        surQue.AnswerType__c = 'Freetext';
        
        addQueAns.deleteAllAnswer();
        
        addQueAns.speSurvey.AnswerType__c = 'Freetext';
        
        addQueAns.save(); 
        
        Test.stopTest();
    }
    
    static testMethod void canceQuestionAns()
    {
        //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
        
        SPE_SurveyQuestion__c surQue1 = new SPE_SurveyQuestion__c();
        surQue1 = SPE_TestObjectCreator.CreateSurveyQuestion();
        surQue1.AnswerType__c = 'Freetext';
        insert surQue1;
        
        Test.startTest();
              
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(surQue1);
        
        SPE_AddQuestionAnswerExt addQueAns = new SPE_AddQuestionAnswerExt(stCon);
        
        addQueAns.speSurvey = SPE_TestObjectCreator.CreateSurveyQuestion();
        
        addQueAns.addAnswers();
        addQueAns.addAnswers();
                
        addQueAns.speAnswers[0] = SPE_TestObjectCreator.CreateSurveyAnswer();
        
        addQueAns.speAnswers[1] = SPE_TestObjectCreator.CreateSurveyAnswer();
        
        addQueAns.cancelQuestion();
        
        Test.stopTest();
    }
    
    static testMethod void cloneQuestionAns()
    {
        //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
        
        SPE_SurveyQuestion__c surQue1 = new SPE_SurveyQuestion__c();
        surQue1 = SPE_TestObjectCreator.CreateSurveyQuestion();
        surQue1.AnswerType__c = 'Freetext';
        insert surQue1;
        
        Test.startTest(); 
        
        Apexpages.currentPage().getParameters().put('isClone', 'true');     
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(surQue1);
        
       
        SPE_AddQuestionAnswerExt addQueAns = new SPE_AddQuestionAnswerExt(stCon);
        
        Test.stopTest();
    }
  
}