src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_KPICalculation__c.object
<CustomObject>
    <fields>
        <fullName>Aggregation__c</fullName>
        <label>Aggregation</label>
        <picklist>
            <picklistValues>
                <fullName>Min</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Min( Across Suppliers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max( Across Suppliers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg( Across Suppliers)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDefination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Defination</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please Select a Published PI</errorMessage>
            <filterItems>
                <field>SPE_PIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrevKPIDefination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prev KPI Defination</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SPE_KPIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations (Prev KPI Defination)</relationshipLabel>
        <relationshipName>KPI_Calculations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>KPI Calculation</label>
    <nameField>
        <displayFormat>KCal-{00000}</displayFormat>
        <label>KPI Calculation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Aggregation__c</fullName>
        <label>Aggregation</label>
        <picklist>
            <picklistValues>
                <fullName>AVG</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FrequencyinMonth__c</fullName>
        <label>Frequency in Month</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <description>Enter date when the KPI will be calculated (for data) or scheduled (for survey)</description>
        <inlineHelpText>This is an auto computed date looking at the underlying PI definitions (latest PI upload date + buffer days). This refreshes in batches and not instantaneously.</inlineHelpText>
        <label>Next Scheduled Date</label>
        <type>Date</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_Stop__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Stop_trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Stop  KPI Recursoin</label>
</CustomObject>

src/classes/SPE_CalculationCanvasEXTTest.cls
@isTest(SeeAllData = False)

public class SPE_CalculationCanvasEXTTest{
    
  
    //-----CalList[k].PIDefination__c!= Null || CalList[k].PrevKPIDefination__c!=Null ) && calList[k].Aggregation__c == 'Constant'---
    
    static testmethod void testSPE_CalculationCanvasEXT1(){
    
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
  //----update KPI----
   KPI.ActualCalculation__c = 'A';  


   KPI.LifecycleStage__c = 'Pilot';
       
    update KPI;
    
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    //KPIcalc.PrevKPIDefination__c = KPI.Id;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Constant'; // method 1
    KPIcalc.Index__c = 'A';
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c= :KPI.Id];
                
    system.assert(testResult!=null);
    
    }

    //------f(CalList[k].Aggregation__c=='--None--' || CalList[k].Aggregation__c==' ' || CalList[k].Aggregation__c==Null){-------
    
     static testmethod void testSPE_CalculationCanvasEXT2(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
  //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
   KPI.LifecycleStage__c = 'Pilot';
       
    update KPI;
    
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = ''; //method 2
    KPIcalc.Index__c = 'A';
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c= :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    
    
    }
    
    //--------CalList[k].PrevKPIDefination__c!=Null && (calList[k].Aggregation__c == 'Min( Across Suppliers)' || calList[k].Aggregation__c == 'Max( Across Suppliers)' || calList[k].Aggregation__c == 'Avg( Across Suppliers)'))----------
    
     static testmethod void testSPE_CalculationCanvasEXT3(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
  //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
   KPI.LifecycleStage__c = 'Pilot';
       
    update KPI;
    
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = null;
    //KPIcalc.PrevKPIDefination__c = KPI.Id;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Min( Across Suppliers)'; //method 3 
    KPIcalc.Index__c = 'A';
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c=:KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    //----if(CalList[k].PIDefination__c == null && CalList[k].PrevKPIDefination__c == null && calList[k].Aggregation__c != 'Constant' )
    
     static testmethod void testSPE_CalculationCanvasEXT4(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
  //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
   KPI.LifecycleStage__c = 'Pilot';
       
    update KPI;
    
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = null;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; //method 4 
    KPIcalc.Index__c = 'A';
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();
    
    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c=:KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
     static testmethod void testSPE_CalculationCanvasEXT5(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
  //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
   KPI.LifecycleStage__c = 'Pilot';
       
    update KPI;
    
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = null;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; //method 5
    KPIcalc.Index__c = 'A';
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c= :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    static testmethod void testSPE_CalculationCanvasEXT6(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
  //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
   KPI.LifecycleStage__c = 'Pilot';
       
    update KPI;
    
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = null;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; //method 6
    KPIcalc.Index__c = 'A';
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c = :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    static testmethod void testSPE_CalculationCanvasEXT7(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; //method 7 - indexname=null;
    KPIcalc.Index__c = 'A';
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c= :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }

    
    static testmethod void testSPE_CalculationCanvasEXT8(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
    //----update KPI----
      KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    PIDefObj.ValuesType__c = 'Date';  //---------ValueType=='Date' and PIDefinition!= NULL---
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; //method 8 - PIDefination__c!=Null
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'Test'; //IndexName!=Null
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c= :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    //------------test BUSCOPE,GEOSCOPE And Category Scope and PIDEFINITION!=NULL--------
    
    static testmethod void testSPE_CalculationCanvasEXT9(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Market Unit';
    KPI.BUScope__c = 'Business Unit';
    KPI.categoryscope__c = 'Category Area';
    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    PIDefObj.ValuesType__c = 'Number'; 
    PIDefObj.GeoScope__c = 'All Markets';   
    PIDefObj.CategoryScope__c = 'All Categories';
    
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; 
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'Test'; 
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c= :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    
    
    static testmethod void testSPE_CalculationCanvasEXT10(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    PIDefObj.ValuesType__c = 'Number'; 
    PIDefObj.GeoScope__c = 'All Markets';   
    PIDefObj.CategoryScope__c = 'All Categories';
    
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = null;
    //KPIcalc.PrevKPIDefination__c = KPI.Id;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; 
    KPIcalc.Index__c = 'A';
    //KPIcalc.IndexName__c = 'Test'; 
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c= :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    //------------test UpdateKPI-----------
    
    static testmethod void testSPE_CalculationCanvasEXT11(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    KPI.CalculationFormula__c = 'sum';
    KPI.RPNExpression__c = 'A';

    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    PIDefObj.ValuesType__c = 'Number'; 
    PIDefObj.GeoScope__c = 'All Markets';   
    PIDefObj.CategoryScope__c = 'All Categories';
    
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    //KPIcalc.PrevKPIDefination__c = KPI.Id;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; 
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'A'; 
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('RPN','A');
    ApexPages.currentPage().getParameters().put('ActualCalculation','sum');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.SaveRecords();
    calcObj.updateKPI();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c= :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    static testmethod void testSPE_CalculationCanvasEXT12(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    KPI.CalculationFormula__c = 'sum';
    KPI.RPNExpression__c = 'A,B,+';

    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    PIDefObj.ValuesType__c = 'Number'; 
    PIDefObj.GeoScope__c = 'All Markets';   
    PIDefObj.CategoryScope__c = 'All Categories';
    
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    //KPIcalc.PrevKPIDefination__c = KPI.Id;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; 
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'A'; 
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('RPN','A');
    ApexPages.currentPage().getParameters().put('ActualCalculation','sum');
    
    
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.SaveRecords();
    calcObj.updateKPI();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c = :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    static testmethod void testSPE_CalculationCanvasEXT13(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    
    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    //PIDefObj.Max_Question_Score__c = 3.0;
    
    
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    //KPIcalc.PrevKPIDefination__c = KPI.Id;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; 
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'A'; 
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
        
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    PageReference p = calcObj.backToKPI();
    Integer I=2;
    Boolean bool = SPE_CalculationCanvasEXT.getPIDefinition(lstPIDefObj[0].Id,I);
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c = :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    //----- test valuetype=String ----
    
    static testmethod void testSPE_CalculationCanvasEXT14(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    PIDefObj.ValuesType__c = 'String';  
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; //method 8 - PIDefination__c!=Null
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'Test'; //IndexName!=Null
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    //calcObj.addRecords();
   // calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c = :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    static testmethod void testSPE_CalculationCanvasEXT15(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    PIDefObj.ValuesType__c = 'String';  
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; //method 8 - PIDefination__c!=Null
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'Test'; //IndexName!=Null
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    //calcObj.addRecords();
   // calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c= :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    //  ----kpi.categoryscope__c =='Category Area' && (PI.CategoryScope__c == 'All Categories'---
    
    static testmethod void testSPE_CalculationCanvasEXT16(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Market Unit';
    KPI.BUScope__c = 'Business Unit';
    KPI.categoryscope__c = 'Category Area';
    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    PIDefObj.ValuesType__c = 'Number'; 
    PIDefObj.GeoScope__c = 'All Markets';   
    PIDefObj.BUScope__c = 'Product';
    PIDefObj.CategoryScope__c = 'All Categories';
    
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; 
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'Test'; 
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
   
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c= :KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    static testmethod void testSPE_CalculationCanvasEXT17(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Market';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    PIDefObj.ValuesType__c = 'Number'; 
    PIDefObj.GeoScope__c = 'All Markets';   
    PIDefObj.BUScope__c = 'Product';
    PIDefObj.CategoryScope__c = 'Category';
    
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; 
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'Test'; 
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
   
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c=:KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    static testmethod void testSPE_CalculationCanvasEXT18(){
        
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
  //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
   KPI.LifecycleStage__c = 'Pilot';
       
    update KPI;
    
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = null;
    //KPIcalc.PrevKPIDefination__c = KPI.Id;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Constant'; 
    KPIcalc.Index__c = 'A';
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
   
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c=:KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    
    static testmethod void testSPE_CalculationCanvasEXT19(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');    
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
  //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
   KPI.LifecycleStage__c = 'Pilot';
       
    update KPI;
    
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************/
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = null;
    KPIcalc.PrevKPIDefination__c = null;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Constant'; 
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'A';
    KPIcalc.constantvalue__c = null;
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
   
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c=:KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
    
    static testmethod void testSPE_CalculationCanvasEXT20(){
    
    //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
    //--- KPI data------
    SPE_KPIDefinition__c KPI = new SPE_KPIDefinition__c();
    KPI = SPE_TestObjectCreator.CreateKPIDefinition(1);
    KPI.ScheduledDate__c = Date.newInstance(2099, 07, 03); 
    KPI.FrequencyinMonth__c = '1';
    KPI.GeoScope__c = 'Country';
    KPI.BUScope__c = 'Product';
    KPI.categoryscope__c = 'Category';
    insert KPI;
    
    //----update KPI----
  KPI.ActualCalculation__c = 'A'; 
    KPI.LifecycleStage__c = 'Pilot';
           
    update KPI;
        
    //-----KPI data ends----
    
     List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
    for(Integer i=0;i<2;i++){
    SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
    
    //*************Changes for Encryption*************//
    //PIDefObj.Name = 'Test PI Definition'+i;
    PIDefObj.PI_Title__c = 'Test PI Definition'+i;
    //************Changes End****************//
    
    PIDefObj.LifecycleStage__c = 'Draft';
    PIDefObj.ValuesType__c = 'Date';  //---------ValueType=='Date' and PIDefinition!= NULL---
    lstPIDefObj.add(PIDefObj);
    }
    insert lstPIDefObj;
    
    //update lifecycle stage
    
    for(Integer i=0;i<2;i++){
    lstPIDefObj[i].LifecycleStage__c= 'Published';
    }
    
    update lstPIDefObj;
    
    //-----pi definition data ends----
    
    //--- KPI calculation data preparation starts ---
    
    List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();
    for(Integer i=0;i<2;i++){
    SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
    KPIcalc.PIDefination__c = null;
    //KPIcalc.PrevKPIDefination__c = KPI.Id;
    KPIcalc.TimeFrame__c = 2.0;
    KPIcalc.KPIDefinition__c = KPI.Id;
    KPIcalc.Aggregation__c = 'Sum'; 
    KPIcalc.Index__c = 'A';
    KPIcalc.IndexName__c = 'Test'; //IndexName!=Null
    KPIcalc.Filter1__c = '1';
    KPIcalc.Filter2__c = '1';
    KPIcalc.Filter3__c = '1';
    KPIcalc.Filter4__c = '1';
    KPIcalc.Filter5__c = '1';
    KPIcalc.Filter6__c = '1';
    KPIcalc.Filter7__c = '1';
    KPIcalc.Filter8__c = '1';
   // KPIcalc.Filter9__c = '1';
    KPIcalc.Filter10__c = '1';
    lstKPIcalc.add(KPIcalc);
    }
    
    insert lstKPIcalc;
    
    //-----KPI calc data ends----
    
    
    PageReference pageRef = Page.SPE_CalculationCanvas;
    Test.setCurrentPage(pageRef);
    
    ApexPages.currentPage().getParameters().put('id',KPI.Id );
    ApexPages.currentPage().getParameters().put('rowIndex','3');
    
    //----row index data------
    
    test.startTest();

    SPE_CalculationCanvasEXT calcObj = new SPE_CalculationCanvasEXT();
    calcObj.addRecords();
    calcObj.RemoveRecords();
    calcObj.SaveRecords();
    
    test.stopTest();
    
    List<SPE_KPICalculation__c> testResult = [SELECT id,IndexName__c,Filter1__c,Filter2__c,Filter3__c,Filter4__c,Filter5__c,Filter6__c,Filter7__c,Filter8__c,Filter9__c,Filter10__c,
                    Index__c,ConstantValue__c,Aggregation__c, KPIDefinition__c, PIDefination__c,PrevKPIDefination__c,SurveyQuestion__c,TimeFrame__c 
                    FROM SPE_KPICalculation__c
                    WHERE KPIDefinition__c=:KPI.Id];
                
    system.assert(testResult!=null);
    
    
    }
  


}