src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_KPICalculation__c.object
<CustomObject>
    <fields>
        <fullName>Aggregation__c</fullName>
        <label>Aggregation</label>
        <picklist>
            <picklistValues>
                <fullName>Min</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Min( Across Suppliers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max( Across Suppliers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg( Across Suppliers)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ConstantValue__c</fullName>
        <label>Constant Value</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Filter1__c</fullName>
        <label>Filter1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter2__c</fullName>
        <label>Filter2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter3__c</fullName>
        <label>Filter3</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter4__c</fullName>
        <label>Filter4</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter5__c</fullName>
        <label>Filter5</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter6__c</fullName>
        <label>Filter6</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter7__c</fullName>
        <label>Filter7</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Filter8__c</fullName>
        <label>Filter8</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IndexName__c</fullName>
        <label>Index Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDefination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Defination</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please Select a Published PI</errorMessage>
            <filterItems>
                <field>SPE_PIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PrevKPIDefination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prev KPI Defination</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SPE_KPIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations (Prev KPI Defination)</relationshipLabel>
        <relationshipName>KPI_Calculations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionName__c</fullName>
        <formula>SurveyQuestion__r.SurveyQuestion__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Survey Question to calculate survey based PI (Soft PI)</description>
        <label>Survey Question</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SPE_SurveyQuestion__c.PIDefinition__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <infoMessage>Question linked to PI are shown here</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>filter10__c</fullName>
        <label>filter10</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>filter9__c</fullName>
        <label>filter9</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>flag</label>
        <type>Checkbox</type>
    </fields>
    <label>KPI Calculation</label>
    <nameField>
        <displayFormat>KCal-{00000}</displayFormat>
        <label>KPI Calculation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Aggregation__c</fullName>
        <label>Aggregation</label>
        <picklist>
            <picklistValues>
                <fullName>AVG</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DataAcquisitionMethod__c</fullName>
        <label>Data Acquisition Method</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>DataAcquisitionMethod__c</fullName>
        <inlineHelpText>Identify how this data is acquired</inlineHelpText>
        <label>Data Acquisition Method</label>
        <picklist>
            <picklistValues>
                <fullName>Data Load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standalone Survey</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>PI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIUploadDuedate__c</fullName>
        <label>PI Upload Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of PI 
(Standard Name field of PI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>PI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_Stop__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Stop_trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Stop  KPI Recursoin</label>
</CustomObject>

src/classes/SPE_KPIClone_Test.cls
@isTest(seeAllData=False)
public class SPE_KPIClone_Test{
    
    public static testmethod void SPE_KPICloneTest(){
    
        //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');

        List<SPE_KPIDefinition__c>  kpi = new List<SPE_KPIDefinition__c>();
        List<SPE_KPICalculation__c> lstKPICalc= new List<SPE_KPICalculation__c>();
        List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
            for(Integer i=0;i<1;i++){
                SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
                PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
                
             //**********************Changes For Encryption******************//
                //PIDefObj.Name = 'Test PI Definition'+i;
                PIDefObj.PI_Title__c = 'Test PI Definition'+i;
             //**********************END******************//   
                
                PIDefObj.LifecycleStage__c = 'Draft';
                PIDefObj.DataAcquisitionMethod__c = 'Data Load';
                PIDefObj.PIUploadDuedate__c = Date.newInstance(2099,2,3);
                lstPIDefObj.add(PIDefObj);
            }
        insert lstPIDefObj;
                   
            SPE_KPIDefinition__c kpidef = SPE_TestObjectCreator.CreateKPIDefinition(1);
                insert kpidef;
                
          lstKPICalc=[select id,Aggregation__c,ConstantValue__c,Filter1__c,filter10__c,Filter2__c,Filter3__c,Filter4__c,
                                    Filter5__c,Filter6__c,Filter7__c,Filter8__c,filter9__c,flag__c,Index__c,IndexName__c,KPIDefinition__c,
                                    PIDefination__c,PrevKPIDefination__c,QuestionName__c,SurveyQuestion__c,TimeFrame__c
                             From SPE_KPICalculation__c where KPIDefinition__c =: kpidef.id ];
                             
        System.assertNotEquals( kpidef.id,null);      
        
        ApexPages.StandardController sc = new ApexPages.StandardController(kpidef);
        SPE_KPIClone p =new SPE_KPIClone(sc);
        p.SaveKPI();
    }
    
    // For Else Part ..
    
    public static testmethod void SPE_CreateKPIVersionTest2(){
    test.startTest();
    
        //---Custom Setting data ---
        LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);
        
        insert lstpicklistObj;
        
        insert new SPE_Stop__c(Stop_trigger__c = true,Name ='Stop');
    
        //List<SPE_KPIDefinition__c>  kpi = new List<SPE_KPIDefinition__c>();
        //List<SPE_KPICalculation__c> lstKPICalc= new List<SPE_KPICalculation__c>();
        
        SPE_KPIDefinition__c kpiDefinition1 = new SPE_KPIDefinition__c();
        
        //**********************Changes For Encryption******************//
            //kpiDefinition1.Name = 'Test KPI Definition 1236';
            kpiDefinition1.KPI_Title__c = 'Test KPI Definition 1236';
        //**********************************END****************************//       
            
            kpiDefinition1.AbbreviatedName__c = 'TKPIDe5';
            kpiDefinition1.Level__c = '1';
            kpiDefinition1.LifecycleStage__c = 'Draft';
            kpiDefinition1.Description__c = 'Test';
            kpiDefinition1.MissingDatalogic__c = 'Logic1';
            kpiDefinition1.OperationalType__c = 'Leading PI';
            kpiDefinition1.GeoScope__c = 'All Markets';
            kpiDefinition1.categoryscope__c = 'All Categories';
            kpiDefinition1.BUScope__c = 'All Products';
            kpiDefinition1.UoM__c = 'max';
            kpiDefinition1.Group1__c = 'Cost';
            kpiDefinition1.Group2__c = 'Hard';
            kpiDefinition1.Type__c = 'Operational';
            kpiDefinition1.FrequencyinMonth__c = '2';
            kpiDefinition1.ScheduledDate__c = system.today().addDays(20);
            kpiDefinition1.VerNumber__c = 1;
        insert kpiDefinition1;
        
        List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
            for(Integer i=0;i<1;i++){
                SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
                PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
                
             //**********************Changes For Encryption******************//
                //PIDefObj.Name = 'Test PI Definition'+i;
                PIDefObj.PI_Title__c = 'Test PI Definition'+i;
             //**********************END******************//
             
                PIDefObj.LifecycleStage__c = 'Draft';
                PIDefObj.DataAcquisitionMethod__c = 'Data Load';
                PIDefObj.PIUploadDuedate__c = Date.newInstance(2099,2,3);
                lstPIDefObj.add(PIDefObj);
            }
        insert lstPIDefObj;
        
        //update lifecycle stage
    
        for(Integer i=0;i<1;i++){
        lstPIDefObj[i].LifecycleStage__c= 'Published';
        }
        
        update lstPIDefObj;
        
        SPE_KPIDefinition__c kpidef = SPE_TestObjectCreator.CreateKPIDefinition(1);
            kpidef.Master_KPI__c= kpiDefinition1.Id;
        insert kpidef;
        
        List<SPE_KPICalculation__c> lstKPIcalc = new List<SPE_KPICalculation__c>();

        for(Integer i=0;i<1;i++){
            SPE_KPICalculation__c KPIcalc = new SPE_KPICalculation__c();
            KPIcalc.PIDefination__c = lstPIDefObj[i].Id;
            KPIcalc.TimeFrame__c = 2.0;
            KPIcalc.KPIDefinition__c = kpidef.Id;
            KPIcalc.Aggregation__c = 'Sum';
            KPIcalc.Index__c = 'A';
            KPIcalc.Filter1__c = '1';
            KPIcalc.Filter2__c = '1';
            KPIcalc.Filter3__c = '1';
            KPIcalc.Filter4__c = '1';
            KPIcalc.Filter5__c = '1';
            KPIcalc.Filter6__c = '1';
            KPIcalc.Filter7__c = '1';
            KPIcalc.Filter8__c = '1';
            KPIcalc.Filter10__c = '1';
            lstKPIcalc.add(KPIcalc);
        } 
        
        insert lstKPIcalc;
                
        lstKPICalc=[select id,Aggregation__c,ConstantValue__c,Filter1__c,filter10__c,Filter2__c,Filter3__c,Filter4__c,
                                    Filter5__c,Filter6__c,Filter7__c,Filter8__c,filter9__c,flag__c,Index__c,IndexName__c,KPIDefinition__c,
                                    PIDefination__c,PrevKPIDefination__c,QuestionName__c,SurveyQuestion__c,TimeFrame__c
                             From SPE_KPICalculation__c where KPIDefinition__c =: kpidef.id ];
                             
        System.assertNotEquals( kpidef.id,null);      
        
        ApexPages.StandardController sc = new ApexPages.StandardController(kpidef);
        SPE_KPIClone p =new SPE_KPIClone(sc);
        p.SaveKPI();
        test.stopTest();
    }
}