src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE2Survey__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Days__c</fullName>
        <label>Additional Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Additional_Days_for_week__c</fullName>
        <label>Additional Days for week</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryArea__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Day_name_of_upload_week__c</fullName>
        <label>Day name of upload week</label>
        <picklist>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FrequencyInMonths__c</fullName>
        <inlineHelpText>Survey frequency as in “once every xx months</inlineHelpText>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_One_Time_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is One Time Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MarketUnit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Month_Upload_Day__c</fullName>
        <label>Month Upload Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_Value__c</fullName>
        <label>Month Value</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurrence_Pattern__c</fullName>
        <label>Recurrence Pattern</label>
        <picklist>
            <picklistValues>
                <fullName>DayPerMonth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeekPerMonth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DayPerYear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeekPerYear</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurrence_frequency_type__c</fullName>
        <label>Recurrence frequency type</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <inlineHelpText>Desired launch date of the survey from calendar.  Default is tomorrow’s date.  If today’s date or earlier is selected, then the survey launches on Publish.</inlineHelpText>
        <label>Survey Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SurveyExecutionBeforeIndays__c</fullName>
        <label>Survey Due Date (In Days)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SurveyReminderBeforeExecutionDate__c</fullName>
        <inlineHelpText>Survey Closing Reminder xx  Days Before Survey Closing Date</inlineHelpText>
        <label>Survey Closing Reminder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Shut_Down__c</fullName>
        <inlineHelpText>Survey Close in xx  Days after Launch</inlineHelpText>
        <label>Survey Shut Down</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upload_Day__c</fullName>
        <label>Upload Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_Count__c</fullName>
        <label>Week Count</label>
        <picklist>
            <picklistValues>
                <fullName>First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fourth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Yearly_Day_Name_of_Upload_Week__c</fullName>
        <label>Yearly Day Name of Upload Week</label>
        <picklist>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Yearly_Week_Count__c</fullName>
        <label>Yearly Week Count</label>
        <picklist>
            <picklistValues>
                <fullName>First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fourth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>Survey-{0000}</displayFormat>
        <label>Survey Sequential Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standalone Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE2_SurveyCreateExtTest.cls
@IsTest(SeeAllData=False)

public class SPE2_SurveyCreateExtTest

{

    static testmethod void TestSPE2_SurveyCreateExt1()
    {
        
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';       
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';        
        picklistObj.Project__c = 'All Projects';        
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';                       
        picklistObj.Market__c = 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';       
        picklistObj.Product__c = 'All Products';
                
        lstpicklistObj.add(picklistObj);    
        
        insert lstpicklistObj;
        
        SPE2Survey__c SurDefObj = new SPE2Survey__c();
        SurDefObj.Additional_Days__c = 2;
        SurDefObj.Additional_Days_for_week__c = 2;
        SurDefObj.BusinessLine__c = 'All Business Lines';
        SurDefObj.BusinessUnit__c = 'All Business Units';
        SurDefObj.Category__c = 'All Categories';
        SurDefObj.CategoryArea__c = 'All Category Areas';
        SurDefObj.CategoryGroup__c = 'All Category Groups';
        SurDefObj.Country__c = 'All Countries';
        SurDefObj.Day_name_of_upload_week__c = 'Sunday';
        SurDefObj.EndDate__c = Date.newInstance(2017, 8, 17);
        SurDefObj.FrequencyInMonths__c = '1';
        SurDefObj.Is_One_Time_Survey__c = True; 
        SurDefObj.Market__c = 'All Markets';
        SurDefObj.MarketUnit__c = 'All Market Units';
        SurDefObj.Month_Upload_Day__c = null;
        SurDefObj.Product__c = 'All Products';
        SurDefObj.Project__c = 'All Projects';
        SurDefObj.Recurrence_frequency_type__c = 'Monthly';
        SurDefObj.Recurrence_Pattern__c = 'DayPerMonth';
        SurDefObj.Stage__c = 'Draft';
        SurDefObj.SurveyReminderBeforeExecutionDate__c = 1;
        SurDefObj.SurveyExecutionBeforeIndays__c = 1;
        SurDefObj.StartDate__c = Date.newInstance(2017, 8, 15);
        SurDefObj.Survey_Shut_Down__c = 1;
        SurDefObj.Upload_Day__c = 2;
        SurDefObj.Week_Count__c = 'First';
        SurDefObj.Yearly_Day_Name_of_Upload_Week__c = 'Sunday';
        SurDefObj.Yearly_Week_Count__c = 'Second';
        
        insert SurDefObj;
        
        PageReference pageRef = Page.SPE2_SurveyCreate;
        Test.setCurrentPage(pageRef);  
        Test.StartTest();
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(SurDefObj);
        SPE2_SurveyCreateExt surRec = new SPE2_SurveyCreateExt(stcon);
        surRec.getFrequencyTypes();
        surRec.getWeekCountList();
        surRec.getweekDays();
        surRec.getMonthList();
        surRec.displayRecurrence();
        surRec.closePopup();
        surRec.SaveCustom();
        surRec.getMarketValues();
        surRec.getMarketUnitValues();
        surRec.fillMarketUnit();
        surRec.getCountryValues();
        surRec.fillCountry();
        surRec.getProjectValues();
        surRec.fillProject();
        surRec.getBusinessUnitValues();
        surRec.getBusinesLineValues();
        surRec.fillBusinessLine();
        surRec.getProductValues();
        surRec.showProdVals();
        surRec.fillProduct();
        surRec.getCategoryAreaValues();
        surRec.getCategoryGroupValues();
        surRec.fillCategoryGroup();
        surRec.getCategoryValues();
        surRec.fillCategory();
        surRec.blankMethod();
        surRec.save();
        //surRec.createSPETracker(SurDefObj, True);
        surRec.generateTracker();
        
    }
      static testmethod void TestSPE2_SurveyCreateExt2()
    {
        
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';       
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';        
        picklistObj.Project__c = 'All Projects';        
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';                       
        picklistObj.Market__c = 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';       
        picklistObj.Product__c = 'All Products';
                
        lstpicklistObj.add(picklistObj);    
        
        insert lstpicklistObj;
        
        SPE2Survey__c SurDefObj = new SPE2Survey__c();
        SurDefObj.Additional_Days__c = 2;
        SurDefObj.Additional_Days_for_week__c = 2;
        SurDefObj.BusinessLine__c = 'All Business Lines';
        SurDefObj.BusinessUnit__c = 'All Business Units';
        SurDefObj.Category__c = 'All Categories';
        SurDefObj.CategoryArea__c = 'All Category Areas';
        SurDefObj.CategoryGroup__c = 'All Category Groups';
        SurDefObj.Country__c = 'All Countries';
        SurDefObj.Day_name_of_upload_week__c = 'Sunday';
        SurDefObj.EndDate__c = Date.newInstance(2017, 8, 17);
        SurDefObj.FrequencyInMonths__c = '';
        SurDefObj.Is_One_Time_Survey__c = False; 
        SurDefObj.Market__c = 'All Markets';
        SurDefObj.MarketUnit__c = 'All Market Units';
        SurDefObj.Month_Upload_Day__c = 7;
        SurDefObj.Product__c = 'All Products';
        SurDefObj.Project__c = 'All Projects';
        SurDefObj.Recurrence_frequency_type__c = 'Monthly';
        SurDefObj.Recurrence_Pattern__c = 'WeekPerMonth';
        SurDefObj.Stage__c = 'Draft';
        SurDefObj.SurveyReminderBeforeExecutionDate__c = 1;
        SurDefObj.SurveyExecutionBeforeIndays__c = 1;
        SurDefObj.StartDate__c = Date.newInstance(2017, 8, 15);
        SurDefObj.Survey_Shut_Down__c = 1;
        SurDefObj.Upload_Day__c = 2;
        SurDefObj.Week_Count__c = 'First';
        SurDefObj.Yearly_Day_Name_of_Upload_Week__c = 'Sunday';
        SurDefObj.Yearly_Week_Count__c = 'Second';
        
        insert SurDefObj;
        
        PageReference pageRef = Page.SPE2_SurveyCreate;
        Test.setCurrentPage(pageRef);  
        Test.StartTest();
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(SurDefObj);
        SPE2_SurveyCreateExt surRec = new SPE2_SurveyCreateExt(stcon);
        surRec.getFrequencyTypes();
        surRec.getWeekCountList();
        surRec.getweekDays();
        surRec.getMonthList();
        surRec.displayRecurrence();
        surRec.closePopup();
        surRec.SaveCustom();
        surRec.getMarketValues();
        surRec.getMarketUnitValues();
        surRec.fillMarketUnit();
        surRec.getCountryValues();
        surRec.fillCountry();
        surRec.getProjectValues();
        surRec.fillProject();
        surRec.getBusinessUnitValues();
        surRec.getBusinesLineValues();
        surRec.fillBusinessLine();
        surRec.getProductValues();
        surRec.showProdVals();
        surRec.fillProduct();
        surRec.getCategoryAreaValues();
        surRec.getCategoryGroupValues();
        surRec.fillCategoryGroup();
        surRec.getCategoryValues();
        surRec.fillCategory();
        surRec.blankMethod();
        //surRec.save();
        //surRec.createSPETracker(SurDefObj, True);
        //surRec.generateTracker();
        
    }  
        
        static testmethod void TestSPE2_SurveyCreateExt3()
    {
        
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';       
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';        
        picklistObj.Project__c = 'All Projects';        
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';                       
        picklistObj.Market__c = 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';       
        picklistObj.Product__c = 'All Products';
                
        lstpicklistObj.add(picklistObj);    
        
        insert lstpicklistObj;
        
        SPE2Survey__c SurDefObj = new SPE2Survey__c();
        SurDefObj.Additional_Days__c = 2;
        SurDefObj.Additional_Days_for_week__c = 2;
        SurDefObj.BusinessLine__c = 'All Business Lines';
        SurDefObj.BusinessUnit__c = 'All Business Units';
        SurDefObj.Category__c = 'All Categories';
        SurDefObj.CategoryArea__c = 'All Category Areas';
        SurDefObj.CategoryGroup__c = 'All Category Groups';
        SurDefObj.Country__c = 'All Countries';
        SurDefObj.Day_name_of_upload_week__c = 'Sunday';
        SurDefObj.EndDate__c = Date.newInstance(2017, 8, 17);
        SurDefObj.FrequencyInMonths__c = '1';
        SurDefObj.Is_One_Time_Survey__c = True; 
        SurDefObj.Market__c = 'All Markets';
        SurDefObj.MarketUnit__c = 'All Market Units';
        SurDefObj.Month_Upload_Day__c = 7;
        SurDefObj.Product__c = 'All Products';
        SurDefObj.Project__c = 'All Projects';
        SurDefObj.Recurrence_frequency_type__c = 'Monthly';
        SurDefObj.Recurrence_Pattern__c = 'DayPerYear';
        SurDefObj.Stage__c = 'Draft';
        SurDefObj.SurveyReminderBeforeExecutionDate__c = 1;
        SurDefObj.SurveyExecutionBeforeIndays__c = 1;
        SurDefObj.StartDate__c = Date.newInstance(2017, 8, 15);
        SurDefObj.Survey_Shut_Down__c = 1;
        SurDefObj.Upload_Day__c = 2;
        SurDefObj.Week_Count__c = 'First';
        SurDefObj.Yearly_Day_Name_of_Upload_Week__c = 'Sunday';
        SurDefObj.Yearly_Week_Count__c = 'Second';
        
        insert SurDefObj;
        
        PageReference pageRef = Page.SPE2_SurveyCreate;
        Test.setCurrentPage(pageRef);  
        Test.StartTest();
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(SurDefObj);
        SPE2_SurveyCreateExt surRec = new SPE2_SurveyCreateExt(stcon);
        surRec.getFrequencyTypes();
        surRec.getWeekCountList();
        surRec.getweekDays();
        surRec.getMonthList();
        surRec.displayRecurrence();
        surRec.closePopup();
        surRec.SaveCustom();
        surRec.getMarketValues();
        surRec.getMarketUnitValues();
        surRec.fillMarketUnit();
        surRec.getCountryValues();
        surRec.fillCountry();
        surRec.getProjectValues();
        surRec.fillProject();
        surRec.getBusinessUnitValues();
        surRec.getBusinesLineValues();
        surRec.fillBusinessLine();
        surRec.getProductValues();
        surRec.showProdVals();
        surRec.fillProduct();
        surRec.getCategoryAreaValues();
        surRec.getCategoryGroupValues();
        surRec.fillCategoryGroup();
        surRec.getCategoryValues();
        surRec.fillCategory();
        surRec.blankMethod();
        surRec.save();
        //surRec.createSPETracker(SurDefObj, True);
        surRec.generateTracker();
        
    }  
        static testmethod void TestSPE2_SurveyCreateExt4()
    {
        
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';       
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';        
        picklistObj.Project__c = 'All Projects';        
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';                       
        picklistObj.Market__c = 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';       
        picklistObj.Product__c = 'All Products';
                
        lstpicklistObj.add(picklistObj);    
        
        insert lstpicklistObj;
        
        SPE2Survey__c SurDefObj = new SPE2Survey__c();
        SurDefObj.Additional_Days__c = 2;
        SurDefObj.Additional_Days_for_week__c = 2;
        SurDefObj.BusinessLine__c = 'All Business Lines';
        SurDefObj.BusinessUnit__c = 'All Business Units';
        SurDefObj.Category__c = 'All Categories';
        SurDefObj.CategoryArea__c = 'All Category Areas';
        SurDefObj.CategoryGroup__c = 'All Category Groups';
        SurDefObj.Country__c = 'All Countries';
        SurDefObj.Day_name_of_upload_week__c = 'Sunday';
        SurDefObj.EndDate__c = Date.newInstance(2017, 8, 17);
        SurDefObj.FrequencyInMonths__c = '1';
        SurDefObj.Is_One_Time_Survey__c = false; 
        SurDefObj.Market__c = 'All Markets';
        SurDefObj.MarketUnit__c = 'All Market Units';
        SurDefObj.Month_Upload_Day__c = 7;
        SurDefObj.Product__c = 'All Products';
        SurDefObj.Project__c = 'All Projects';
        SurDefObj.Recurrence_frequency_type__c = 'Monthly';
        SurDefObj.Recurrence_Pattern__c = 'WeekPerYear';
        SurDefObj.Stage__c = 'Published';
        SurDefObj.SurveyReminderBeforeExecutionDate__c = 1;
        SurDefObj.SurveyExecutionBeforeIndays__c = 1;
        SurDefObj.StartDate__c = Date.newInstance(2017, 8, 15);
        SurDefObj.Survey_Shut_Down__c = 1;
        SurDefObj.Upload_Day__c = 2;
        SurDefObj.Week_Count__c = 'First';
        SurDefObj.Yearly_Day_Name_of_Upload_Week__c = 'Sunday';
        SurDefObj.Yearly_Week_Count__c = 'Second';
        
        insert SurDefObj;
        
        ApexPages.currentPage().getParameters().put('countryVal','countryVal');
        ApexPages.currentPage().getParameters().put('isClone','abcd');
        //ApexPages.currentPage().getParameters().put('Clone',true);
        //Apexpages.currentPage().getParameters().get('countryVal');
        PageReference pageRef = Page.SPE2_SurveyCreate;
        Test.setCurrentPage(pageRef);  
        Test.StartTest();
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(SurDefObj);
        SPE2_SurveyCreateExt surRec = new SPE2_SurveyCreateExt(stcon);
        surRec.getFrequencyTypes();
        surRec.getWeekCountList();
        surRec.getweekDays();
        surRec.getMonthList();
        surRec.displayRecurrence();
        surRec.closePopup();
        surRec.SaveCustom();
        surRec.getMarketValues();
        surRec.getMarketUnitValues();
        surRec.fillMarketUnit();
        surRec.getCountryValues();
        surRec.fillCountry();
        surRec.getProjectValues();
        surRec.fillProject();
        surRec.getBusinessUnitValues();
        surRec.getBusinesLineValues();
        surRec.fillBusinessLine();
        surRec.getProductValues();
        surRec.showProdVals();
        surRec.fillProduct();
        surRec.getCategoryAreaValues();
        surRec.getCategoryGroupValues();
        surRec.fillCategoryGroup();
        surRec.getCategoryValues();
        surRec.fillCategory();
        surRec.blankMethod();
        surRec.save();
        //surRec.createSPETracker(SurDefObj, True);
        surRec.generateTracker();
        surRec.DatePattern();
        surRec.DisplaySaveCancelButton();
        
    }
        
        static testmethod void TestSPE2_SurveyCreateExt5()
    {
        
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';       
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';        
        picklistObj.Project__c = 'All Projects';        
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';                       
        picklistObj.Market__c = 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';       
        picklistObj.Product__c = 'All Products';
                
        lstpicklistObj.add(picklistObj);    
        
        insert lstpicklistObj;
        
        SPE2Survey__c SurDefObj = new SPE2Survey__c();
        SurDefObj.Additional_Days__c = 2;
        SurDefObj.Additional_Days_for_week__c = 2;
        SurDefObj.BusinessLine__c = 'All Business Lines';
        SurDefObj.BusinessUnit__c = 'All Business Units';
        SurDefObj.Category__c = 'All Categories';
        SurDefObj.CategoryArea__c = 'All Category Areas';
        SurDefObj.CategoryGroup__c = 'All Category Groups';
        SurDefObj.Country__c = 'All Countries';
        SurDefObj.Day_name_of_upload_week__c = 'Sunday';
        SurDefObj.EndDate__c = Date.newInstance(2017, 8, 17);
        SurDefObj.FrequencyInMonths__c = '1';
        SurDefObj.Is_One_Time_Survey__c = True; 
        SurDefObj.Market__c = 'All Markets';
        SurDefObj.MarketUnit__c = 'All Market Units';
        SurDefObj.Month_Upload_Day__c = 7;
        SurDefObj.Product__c = 'All Products';
        SurDefObj.Project__c = 'All Projects';
        SurDefObj.Recurrence_frequency_type__c = 'Monthly';
        SurDefObj.Recurrence_Pattern__c = 'DayPerMonth';
        SurDefObj.Stage__c = 'Draft';
        SurDefObj.SurveyReminderBeforeExecutionDate__c = 1;
        SurDefObj.SurveyExecutionBeforeIndays__c = 1;
        SurDefObj.StartDate__c = Date.newInstance(2017, 8, 15);
        SurDefObj.Survey_Shut_Down__c = 1;
        SurDefObj.Upload_Day__c = 2;
        SurDefObj.Week_Count__c = 'First';
        SurDefObj.Yearly_Day_Name_of_Upload_Week__c = 'Sunday';
        SurDefObj.Yearly_Week_Count__c = 'Second';
        
        insert SurDefObj;
        
        PageReference pageRef = Page.SPE2_SurveyCreate;
        Test.setCurrentPage(pageRef);  
        Test.StartTest();
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(new SPE2Survey__c());
        SPE2_SurveyCreateExt surRec = new SPE2_SurveyCreateExt(stcon);
        surRec.getFrequencyTypes();
        surRec.getWeekCountList();
        surRec.getweekDays();
        surRec.getMonthList();
        surRec.displayRecurrence();
        surRec.closePopup();
        surRec.SaveCustom();
        surRec.getMarketValues();
        surRec.getMarketUnitValues();
        surRec.fillMarketUnit();
        surRec.getCountryValues();
        surRec.fillCountry();
        surRec.getProjectValues();
        surRec.fillProject();
        surRec.getBusinessUnitValues();
        surRec.getBusinesLineValues();
        surRec.fillBusinessLine();
        surRec.getProductValues();
        surRec.showProdVals();
        surRec.fillProduct();
        surRec.getCategoryAreaValues();
        surRec.getCategoryGroupValues();
        surRec.fillCategoryGroup();
        surRec.getCategoryValues();
        surRec.fillCategory();
        surRec.blankMethod();
        surRec.save();
        //surRec.createSPETracker(SurDefObj, True);
        //surRec.generateTracker();
        
    }
        static testmethod void TestSPE2_SurveyCreateExt6()
    {
        
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';       
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';        
        picklistObj.Project__c = 'All Projects';        
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';                       
        picklistObj.Market__c = 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';       
        picklistObj.Product__c = 'All Products';
                
        lstpicklistObj.add(picklistObj);    
        
        insert lstpicklistObj;
        
        SPE2Survey__c SurDefObj = new SPE2Survey__c();
        SurDefObj.Additional_Days__c = 2;
        SurDefObj.Additional_Days_for_week__c = 2;
        SurDefObj.BusinessLine__c = 'All Business Lines';
        SurDefObj.BusinessUnit__c = 'All Business Units';
        SurDefObj.Category__c = 'All Categories';
        SurDefObj.CategoryArea__c = 'All Category Areas';
        SurDefObj.CategoryGroup__c = 'All Category Groups';
        SurDefObj.Country__c = 'All Countries';
        SurDefObj.Day_name_of_upload_week__c = 'Sunday';
        SurDefObj.EndDate__c = Date.newInstance(2017, 9, 17);
        SurDefObj.FrequencyInMonths__c = '1' ;
        SurDefObj.Is_One_Time_Survey__c = False; 
        SurDefObj.Market__c = 'All Markets';
        SurDefObj.MarketUnit__c = 'All Market Units';
        SurDefObj.Month_Upload_Day__c = 7;
        SurDefObj.Product__c = 'All Products';
        SurDefObj.Project__c = 'All Projects';
        SurDefObj.Recurrence_frequency_type__c = 'Monthly';
        SurDefObj.Recurrence_Pattern__c = 'DayPerMonth';
        SurDefObj.Stage__c = 'Draft';
        SurDefObj.SurveyReminderBeforeExecutionDate__c = 1;
        SurDefObj.SurveyExecutionBeforeIndays__c = 1;
        SurDefObj.StartDate__c = Date.newInstance(2017, 8, 15);
        SurDefObj.Survey_Shut_Down__c = 1;
        SurDefObj.Upload_Day__c = 2;
        SurDefObj.Week_Count__c = 'First';
        SurDefObj.Yearly_Day_Name_of_Upload_Week__c = 'Sunday';
        SurDefObj.Yearly_Week_Count__c = 'Second';
        
        insert SurDefObj;
        
        PageReference pageRef = Page.SPE2_SurveyCreate;
        Test.setCurrentPage(pageRef);  
        Test.StartTest();
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(SurDefObj);
        SPE2_SurveyCreateExt surRec = new SPE2_SurveyCreateExt(stcon);
        surRec.getFrequencyTypes();
        surRec.getWeekCountList();
        surRec.getweekDays();
        surRec.getMonthList();
        surRec.displayRecurrence();
        surRec.closePopup();
        surRec.SaveCustom();
        surRec.getMarketValues();
        surRec.getMarketUnitValues();
        surRec.fillMarketUnit();
        surRec.getCountryValues();
        surRec.fillCountry();
        surRec.getProjectValues();
        surRec.fillProject();
        surRec.getBusinessUnitValues();
        surRec.getBusinesLineValues();
        surRec.fillBusinessLine();
        surRec.getProductValues();
        surRec.showProdVals();
        surRec.fillProduct();
        surRec.getCategoryAreaValues();
        surRec.getCategoryGroupValues();
        surRec.fillCategoryGroup();
        surRec.getCategoryValues();
        surRec.fillCategory();
        surRec.blankMethod();
        //surRec.save();
        //surRec.createSPETracker(SurDefObj, True);
        //surRec.generateTracker();
        
    }  
    static testmethod void TestSPE2_SurveyCreateExt7()
    {
        
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';       
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';        
        picklistObj.Project__c = 'All Projects';        
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';                       
        picklistObj.Market__c = 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';       
        picklistObj.Product__c = 'All Products';
                
        lstpicklistObj.add(picklistObj);    
        
        insert lstpicklistObj;
        
        SPE2Survey__c SurDefObj = new SPE2Survey__c();
        SurDefObj.Additional_Days__c = 2;
        SurDefObj.Additional_Days_for_week__c = 2;
        SurDefObj.BusinessLine__c = 'All Business Lines';
        SurDefObj.BusinessUnit__c = 'All Business Units';
        SurDefObj.Category__c = 'All Categories';
        SurDefObj.CategoryArea__c = 'All Category Areas';
        SurDefObj.CategoryGroup__c = 'All Category Groups';
        SurDefObj.Country__c = 'All Countries';
        SurDefObj.Day_name_of_upload_week__c = 'Sunday';
        SurDefObj.EndDate__c = Date.newInstance(2017, 8, 17);
        SurDefObj.FrequencyInMonths__c = '1' ;
        SurDefObj.Is_One_Time_Survey__c = False; 
        SurDefObj.Market__c = 'All Markets';
        SurDefObj.MarketUnit__c = 'All Market Units';
        SurDefObj.Month_Upload_Day__c = 7;
        SurDefObj.Product__c = 'All Products';
        SurDefObj.Project__c = 'All Projects';
        SurDefObj.Recurrence_frequency_type__c = 'Yearly';
        SurDefObj.Recurrence_Pattern__c = 'DayPerYear';
        SurDefObj.Stage__c = 'Draft';
        SurDefObj.SurveyReminderBeforeExecutionDate__c = 1;
        SurDefObj.SurveyExecutionBeforeIndays__c = 1;
        SurDefObj.StartDate__c = Date.newInstance(2017, 8, 15);
        SurDefObj.Survey_Shut_Down__c = 1;
        SurDefObj.Upload_Day__c = 2;
        SurDefObj.Week_Count__c = 'First';
        SurDefObj.Yearly_Day_Name_of_Upload_Week__c = 'Sunday';
        SurDefObj.Yearly_Week_Count__c = 'Second';
        
        insert SurDefObj;
        
        PageReference pageRef = Page.SPE2_SurveyCreate;
        Test.setCurrentPage(pageRef);  
        Test.StartTest();
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(SurDefObj);
        SPE2_SurveyCreateExt surRec = new SPE2_SurveyCreateExt(stcon);
        surRec.getFrequencyTypes();
        surRec.getWeekCountList();
        surRec.getweekDays();
        surRec.getMonthList();
        surRec.displayRecurrence();
        surRec.closePopup();
        //surRec.SaveCustom();
        surRec.getMarketValues();
        surRec.getMarketUnitValues();
        surRec.fillMarketUnit();
        surRec.getCountryValues();
        surRec.fillCountry();
        surRec.getProjectValues();
        surRec.fillProject();
        surRec.getBusinessUnitValues();
        surRec.getBusinesLineValues();
        surRec.fillBusinessLine();
        surRec.getProductValues();
        surRec.showProdVals();
        surRec.fillProduct();
        surRec.getCategoryAreaValues();
        surRec.getCategoryGroupValues();
        surRec.fillCategoryGroup();
        surRec.getCategoryValues();
        surRec.fillCategory();
        surRec.blankMethod();
        //surRec.save();
        //surRec.createSPETracker(SurDefObj, True);
        surRec.generateTracker();
        
    }  
    static testmethod void TestSPE2_SurveyCreateExt8()
    {
        
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';       
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';        
        picklistObj.Project__c = 'All Projects';        
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';                       
        picklistObj.Market__c = 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';       
        picklistObj.Product__c = 'All Products';
                
        lstpicklistObj.add(picklistObj);    
        
        insert lstpicklistObj;
        
        SPE2Survey__c SurDefObj = new SPE2Survey__c();
        SurDefObj.Additional_Days__c = 2;
        SurDefObj.Additional_Days_for_week__c = 2;
        SurDefObj.BusinessLine__c = 'All Business Lines';
        SurDefObj.BusinessUnit__c = 'All Business Units';
        SurDefObj.Category__c = 'All Categories';
        SurDefObj.CategoryArea__c = 'All Category Areas';
        SurDefObj.CategoryGroup__c = 'All Category Groups';
        SurDefObj.Country__c = 'All Countries';
        //SurDefObj.Day_name_of_upload_week__c = 'Sunday';
        SurDefObj.EndDate__c = Date.newInstance(2017, 8, 17);
        SurDefObj.FrequencyInMonths__c = '1' ;
        SurDefObj.Is_One_Time_Survey__c = False; 
        SurDefObj.Market__c = 'All Markets';
        SurDefObj.MarketUnit__c = 'All Market Units';
        SurDefObj.Month_Upload_Day__c = 7;
        SurDefObj.Product__c = 'All Products';
        SurDefObj.Project__c = 'All Projects';
        SurDefObj.Recurrence_frequency_type__c = 'Yearly';
        SurDefObj.Recurrence_Pattern__c = 'DayPerYear';
        SurDefObj.Stage__c = 'Draft';
        SurDefObj.SurveyReminderBeforeExecutionDate__c = 1;
        SurDefObj.SurveyExecutionBeforeIndays__c = 1;

        SurDefObj.Survey_Shut_Down__c = 1;
        SurDefObj.Upload_Day__c = 2;
        //SurDefObj.Week_Count__c = 'First';
        SurDefObj.Yearly_Day_Name_of_Upload_Week__c = 'Sunday';
        SurDefObj.Yearly_Week_Count__c = 'Second';
        SurDefObj.Month_Value__c = 'January';
        
        insert SurDefObj;
        
        PageReference pageRef = Page.SPE2_SurveyCreate;
        Test.setCurrentPage(pageRef);  
        Test.StartTest();
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(SurDefObj);
        SPE2_SurveyCreateExt surRec = new SPE2_SurveyCreateExt(stcon);
        surRec.getFrequencyTypes();
        surRec.getWeekCountList();
        surRec.getweekDays();
        surRec.getMonthList();
        surRec.displayRecurrence();
        surRec.closePopup();
        surRec.SaveCustom();
        surRec.getMarketValues();
        surRec.getMarketUnitValues();
        surRec.fillMarketUnit();
        surRec.getCountryValues();
        surRec.fillCountry();
        surRec.getProjectValues();
        surRec.fillProject();
        surRec.getBusinessUnitValues();
        surRec.getBusinesLineValues();
        surRec.fillBusinessLine();
        surRec.getProductValues();
        surRec.showProdVals();
        surRec.fillProduct();
        surRec.getCategoryAreaValues();
        surRec.getCategoryGroupValues();
        surRec.fillCategoryGroup();
        surRec.getCategoryValues();
        surRec.fillCategory();
        surRec.blankMethod();
        //surRec.save();
        //surRec.createSPETracker(SurDefObj, True);
        surRec.generateTracker();
        
    }  
    static testmethod void TestSPE2_SurveyCreateExt9()
    {
        
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';       
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';        
        picklistObj.Project__c = 'All Projects';        
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';                       
        picklistObj.Market__c = 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';       
        picklistObj.Product__c = 'All Products';
                
        lstpicklistObj.add(picklistObj);    
        
        insert lstpicklistObj;
        
        SPE2Survey__c SurDefObj = new SPE2Survey__c();
        SurDefObj.Additional_Days__c = 2;
        SurDefObj.Additional_Days_for_week__c = 2;
        SurDefObj.BusinessLine__c = 'All Business Lines';
        SurDefObj.BusinessUnit__c = 'All Business Units';
        SurDefObj.Category__c = 'All Categories';
        SurDefObj.CategoryArea__c = 'All Category Areas';
        SurDefObj.CategoryGroup__c = 'All Category Groups';
        SurDefObj.Country__c = 'All Countries';
        //SurDefObj.Day_name_of_upload_week__c = 'Sunday';
        SurDefObj.EndDate__c = Date.newInstance(2017, 8, 17);
        SurDefObj.FrequencyInMonths__c = '1' ;
        SurDefObj.Is_One_Time_Survey__c = False; 
        SurDefObj.Market__c = 'All Markets';
        SurDefObj.MarketUnit__c = 'All Market Units';
        SurDefObj.Month_Upload_Day__c = 7;
        SurDefObj.Product__c = 'All Products';
        SurDefObj.Project__c = 'All Projects';
        SurDefObj.Recurrence_frequency_type__c = 'Yearly';
        SurDefObj.Recurrence_Pattern__c = 'WeekPerYear';
        SurDefObj.Stage__c = 'Draft';
        SurDefObj.SurveyReminderBeforeExecutionDate__c = 1;
        SurDefObj.SurveyExecutionBeforeIndays__c = 1;
        SurDefObj.StartDate__c = Date.newInstance(2017, 8, 15);
        SurDefObj.Survey_Shut_Down__c = 1;
        SurDefObj.Upload_Day__c = 2;
        //SurDefObj.Week_Count__c = 'First';
        SurDefObj.Yearly_Day_Name_of_Upload_Week__c = 'Sunday';
        SurDefObj.Yearly_Week_Count__c = 'First';
        SurDefObj.Month_Value__c = 'January';
        
        insert SurDefObj;
        
        PageReference pageRef = Page.SPE2_SurveyCreate;
        Test.setCurrentPage(pageRef);  
        Test.StartTest();
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(SurDefObj);
        SPE2_SurveyCreateExt surRec = new SPE2_SurveyCreateExt(stcon);
        surRec.getFrequencyTypes();
        surRec.getWeekCountList();
        surRec.getweekDays();
        surRec.getMonthList();
        surRec.displayRecurrence();
        surRec.closePopup();
        surRec.SaveCustom();
        surRec.getMarketValues();
        surRec.getMarketUnitValues();
        surRec.fillMarketUnit();
        surRec.getCountryValues();
        surRec.fillCountry();
        surRec.getProjectValues();
        surRec.fillProject();
        surRec.getBusinessUnitValues();
        surRec.getBusinesLineValues();
        surRec.fillBusinessLine();
        surRec.getProductValues();
        surRec.showProdVals();
        surRec.fillProduct();
        surRec.getCategoryAreaValues();
        surRec.getCategoryGroupValues();
        surRec.fillCategoryGroup();
        surRec.getCategoryValues();
        surRec.fillCategory();
        surRec.blankMethod();
        //surRec.save();
        //surRec.createSPETracker(SurDefObj, True);
        surRec.generateTracker();
        
    }  
    static testmethod void TestSPE2_SurveyCreateExt10()
    {
        
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Name = 'Picklist Default Values';       
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Business_Line__c = 'All Business Lines';        
        picklistObj.Project__c = 'All Projects';        
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';                       
        picklistObj.Market__c = 'All Markets';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Country__c = 'All Countries';       
        picklistObj.Product__c = 'All Products';
                
        lstpicklistObj.add(picklistObj);    
        
        insert lstpicklistObj;
        
        SPE2Survey__c SurDefObj = new SPE2Survey__c();
        SurDefObj.Additional_Days__c = 2;
        SurDefObj.Additional_Days_for_week__c = 2;
        SurDefObj.BusinessLine__c = 'All Business Lines';
        SurDefObj.BusinessUnit__c = 'All Business Units';
        SurDefObj.Category__c = 'All Categories';
        SurDefObj.CategoryArea__c = 'All Category Areas';
        SurDefObj.CategoryGroup__c = 'All Category Groups';
        SurDefObj.Country__c = 'All Countries';
        //SurDefObj.Day_name_of_upload_week__c = 'Sunday';
        SurDefObj.EndDate__c = Date.newInstance(2017, 8, 17);
        SurDefObj.FrequencyInMonths__c = '1' ;
        SurDefObj.Is_One_Time_Survey__c = False; 
        SurDefObj.Market__c = 'All Markets';
        SurDefObj.MarketUnit__c = 'All Market Units';
        SurDefObj.Month_Upload_Day__c = 7;
        SurDefObj.Product__c = 'All Products';
        SurDefObj.Project__c = 'All Projects';
        SurDefObj.Recurrence_frequency_type__c = 'Yearly';
        SurDefObj.Recurrence_Pattern__c = '';
        SurDefObj.Stage__c = 'Draft';
        SurDefObj.SurveyReminderBeforeExecutionDate__c = 1;
        SurDefObj.SurveyExecutionBeforeIndays__c = 1;
        SurDefObj.StartDate__c = Date.newInstance(2017, 8, 15);
        SurDefObj.Survey_Shut_Down__c = 1;
        SurDefObj.Upload_Day__c = 2;
        //SurDefObj.Week_Count__c = 'First';
        SurDefObj.Yearly_Day_Name_of_Upload_Week__c = 'Sunday';
        SurDefObj.Yearly_Week_Count__c = 'First';
        SurDefObj.Month_Value__c = 'January';
        
        insert SurDefObj;
        
        PageReference pageRef = Page.SPE2_SurveyCreate;
        Test.setCurrentPage(pageRef);  
        Test.StartTest();
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(SurDefObj);
        SPE2_SurveyCreateExt surRec = new SPE2_SurveyCreateExt(stcon);
        surRec.getFrequencyTypes();
        surRec.getWeekCountList();
        surRec.getweekDays();
        surRec.getMonthList();
        surRec.displayRecurrence();
        surRec.closePopup();
        surRec.SaveCustom();
        surRec.getMarketValues();
        surRec.getMarketUnitValues();
        surRec.fillMarketUnit();
        surRec.getCountryValues();
        surRec.fillCountry();
        surRec.getProjectValues();
        surRec.fillProject();
        surRec.getBusinessUnitValues();
        surRec.getBusinesLineValues();
        surRec.fillBusinessLine();
        surRec.getProductValues();
        surRec.showProdVals();
        surRec.fillProduct();
        surRec.getCategoryAreaValues();
        surRec.getCategoryGroupValues();
        surRec.fillCategoryGroup();
        surRec.getCategoryValues();
        surRec.fillCategory();
        surRec.blankMethod();
        //surRec.save();
        //surRec.createSPETracker(SurDefObj, True);
        surRec.generateTracker();
        
    } 
}