src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE2_KPI_Threshold__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUILDING INVESTMENT/CAPEX WITHOUT RENTS AND LEASES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FACILITY MANAGEMENT SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RENTAL/LEASE/TRANSACTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UTILITIES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APPLICATION MAINTENANCE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WORKPLACE DEVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASSOCIATED SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRANSPORT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WAREHOUSE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUSINESS SERVICES OTHERS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COACHING &amp; OTHER CONSULTING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CONSULTING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FINANCIAL TAX &amp; INSURANCES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HR SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LEGAL &amp; INTELLECTUAL PROPERTY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARKETING &amp; COMMUNICATIONS SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OFFICE SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TEST SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRAINING SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FUNCTIONAL TEST EQUIPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT PERIPHERAL DEVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MANUFACTURING AUXILIARIES AND CONSUMABLES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MANUFACTURING EQUIPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PERFORMANCE TEST EQUIPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FLEET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRAVEL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUSINESS INCUBATION OTHER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IOT SOLUTIONS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KPI_Title__c</fullName>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>KPI Threshold</label>
    <nameField>
        <displayFormat>Thr-{000000}</displayFormat>
        <label>Threshold Sequential Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Thresholds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>AbbreviatedName__c</fullName>
        <inlineHelpText>10 character limit.  Applicable for all languages.</inlineHelpText>
        <label>KPI Abbreviation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActualCalculation__c</fullName>
        <label>Actual Calculation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>255 Character Limit</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsHighBetter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is High Better ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KPI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of KPI 
(Standard Name field of KPI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>See Guidelines; sets the number of buckets or scores.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MissingDatalogic__c</fullName>
        <inlineHelpText>Please Click on the Help Link on the top of this page</inlineHelpText>
        <label>Missing Data logic</label>
        <picklist>
            <picklistValues>
                <fullName>Past Data or Category Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPE Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_ScoringCalculation__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Scoring Calculations</relationshipLabel>
        <relationshipName>Scoring_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scoring Calculation</label>
    <nameField>
        <displayFormat>SCI-{00000}</displayFormat>
        <label>Scoring Calculation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE2_NewKPIThresholdExtTest.cls
@isTest (seeAllData=false)
private class SPE2_NewKPIThresholdExtTest{
     static testMethod void createKPIThresholdPositive(){
         
        //---Custom Setting data ---
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);        
        insert lstpicklistObj; 
        
       // PicklistDefaultValues__c defaultPicklist = SPE_TestObjectCreator.CreateDefaultPicklist();
        
        //SPE_KPIDefinition__c kpiDefinition1 = SPE_TestObjectCreator.CreateKPIDefinition(1);       
        SPE_KPIDefinition__c kpiDefinition1 = new SPE_KPIDefinition__c();
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.Level__c = '1;2';
        kpiDefinition1.GeoScope__c ='All Markets';
        kpiDefinition1.CategoryScope__c ='All Categories';
        kpiDefinition1.BUScope__c ='All Products';
        kpiDefinition1.IsHighBetter__c = Boolean.ValueOf('True');        
        kpiDefinition1.KPI_Title__c = 'Atos_KPI_Test1';
        kpiDefinition1.AbbreviatedName__c = 'TKPIDe1';
        kpiDefinition1.Level__c = '1';
        kpiDefinition1.LifecycleStage__c = 'Draft';
        kpiDefinition1.Description__c = 'Test';
        kpiDefinition1.MissingDatalogic__c = 'Logic1';
        kpiDefinition1.OperationalType__c = 'Leading PI';
        kpiDefinition1.GeoScope__c = 'All Markets';
        kpiDefinition1.categoryscope__c = 'All Categories';
        kpiDefinition1.BUScope__c = 'All Products';
        kpiDefinition1.UoM__c = 'max';
        kpiDefinition1.Group1__c = 'Cost';
        kpiDefinition1.Group2__c = 'Hard';
        kpiDefinition1.Type__c = 'Operational';
        kpiDefinition1.FrequencyinMonth__c = '2';
        kpiDefinition1.ScheduledDate__c = system.today().addDays(20);
        kpiDefinition1.VerNumber__c = 0;
        insert kpiDefinition1;
        
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.LifecycleStage__c = 'Pilot';
        update kpiDefinition1;
        
        kpiDefinition1.lifecyclestage__c='Published';
       // update kpiDefinition1; 
      
        SPE2_KPI_Threshold__c kpiThreshold =new SPE2_KPI_Threshold__c();
        kpiThreshold.KPI_ID__c =kpiDefinition1.Id;
        kpiThreshold.Threshold_Title__c ='ABC Threshold';
        kpiThreshold.OwnerId =Userinfo.getUserId();
        kpiThreshold.High_Better__c =kpiDefinition1.IsHighBetter__c;
        insert kpiThreshold;

        SPE_ScoringCalculation__c sc = new SPE_ScoringCalculation__c();
        sc.KPIDefinition__c = kpiThreshold.KPI_ID__c;
        sc.Score__c = 1;
        sc.Lower__c = 0;
        sc.LowerTo__c = '>';
        sc.Upper__c = 50;
        sc.UpperTo__c = '<';
        sc.KPI_Threshold__c = kpiThreshold.Id;
        insert sc;                
        system.debug('sc ::'+sc);
        
        Test.StartTest();        
        ApexPages.StandardController st = new ApexPages.StandardController(kpiThreshold);             
        
        SPE2_NewKPIThresholdExt newkpiThreshold = new SPE2_NewKPIThresholdExt(st);
        SPE2_NewKPIThresholdExt.KPIRangeWrapper Wrapvar = new SPE2_NewKPIThresholdExt.KPIRangeWrapper(sc);
        PageReference pageRef = Page.SPE2_NewKPIThreshold;
        Test.setCurrentPage(pageRef);
        newkpiThreshold.enableattributesMap.put('Market',true);
        newkpiThreshold.enableattributesMap.put('Market Unit',true);
        newkpiThreshold.enableattributesMap.put('Country',true);
        newkpiThreshold.enableattributesMap.put('Project',true);
        newkpiThreshold.enableattributesMap.put('Category Area',true);
        newkpiThreshold.enableattributesMap.put('Category Group',true);
        newkpiThreshold.enableattributesMap.put('Category',true);
        newkpiThreshold.enableattributesMap.put('Business Unit',true);
        newkpiThreshold.enableattributesMap.put('Business Line',true);
        newkpiThreshold.enableattributesMap.put('Product',true);
        newkpiThreshold.save();
        pageRef.getParameters().put('isClone', '');       
        newkpiThreshold.getMarketValues();
        newkpiThreshold.getMarketUnitValues();
        newkpiThreshold.getCountryValues();
        newkpiThreshold.getProjectValues();
        newkpiThreshold.getBusinessUnitValues();
        newkpiThreshold.getBusinesLineValues();
        newkpiThreshold.getProductValues();
        newkpiThreshold.getCategoryAreaValues();
        newkpiThreshold.getCategoryGroupValues();
        newkpiThreshold.getCategoryValues();
        newkpiThreshold.StagePilot();
        newkpiThreshold.StagePublished();
        newkpiThreshold.StageObsolete();
        newkpiThreshold.populateAllValues();
       // newkpiThreshold.calculation();
        newkpiThreshold.validate();              
        newkpiThreshold.cloneFn();
        
        newkpiThreshold.cancel();
        newkpiThreshold.edi(); 
                        
        Test.StopTest();
     }
     static testMethod void createKPIThresholdPositive6(){
         
        //---Custom Setting data ---
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);        
        insert lstpicklistObj; 
        
       // PicklistDefaultValues__c defaultPicklist = SPE_TestObjectCreator.CreateDefaultPicklist();
        
        //SPE_KPIDefinition__c kpiDefinition1 = SPE_TestObjectCreator.CreateKPIDefinition(1);       
        SPE_KPIDefinition__c kpiDefinition1 = new SPE_KPIDefinition__c();
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.Level__c = '1;2';
        kpiDefinition1.GeoScope__c ='All Markets';
        kpiDefinition1.CategoryScope__c ='All Categories';
        kpiDefinition1.BUScope__c ='All Products';
        kpiDefinition1.IsHighBetter__c = Boolean.ValueOf('True');        
        kpiDefinition1.KPI_Title__c = 'Atos_KPI_Test1';
        kpiDefinition1.AbbreviatedName__c = 'TKPIDe1';
        kpiDefinition1.Level__c = '1';
        kpiDefinition1.LifecycleStage__c = 'Draft';
        kpiDefinition1.Description__c = 'Test';
        kpiDefinition1.MissingDatalogic__c = 'Logic1';
        kpiDefinition1.OperationalType__c = 'Leading PI';
        kpiDefinition1.GeoScope__c = 'All Markets';
        kpiDefinition1.categoryscope__c = 'All Categories';
        kpiDefinition1.BUScope__c = 'All Products';
        kpiDefinition1.UoM__c = 'max';
        kpiDefinition1.Group1__c = 'Cost';
        kpiDefinition1.Group2__c = 'Hard';
        kpiDefinition1.Type__c = 'Operational';
        kpiDefinition1.FrequencyinMonth__c = '2';
        kpiDefinition1.ScheduledDate__c = system.today().addDays(20);
        kpiDefinition1.VerNumber__c = 0;
        insert kpiDefinition1;
        
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.LifecycleStage__c = 'Pilot';
        update kpiDefinition1;
        
        kpiDefinition1.lifecyclestage__c='Published';
       // update kpiDefinition1; 
      
        SPE2_KPI_Threshold__c kpiThreshold =new SPE2_KPI_Threshold__c();
        kpiThreshold.KPI_ID__c =kpiDefinition1.Id;
        kpiThreshold.Threshold_Title__c ='ABC Threshold';
        kpiThreshold.OwnerId =Userinfo.getUserId();
        kpiThreshold.High_Better__c =kpiDefinition1.IsHighBetter__c;
        insert kpiThreshold;

        SPE_ScoringCalculation__c sc = new SPE_ScoringCalculation__c();
        sc.KPIDefinition__c = kpiThreshold.KPI_ID__c;
        sc.Score__c = 1;
        sc.Lower__c = 0;
        sc.LowerTo__c = '>';
        sc.Upper__c = 50;
        sc.UpperTo__c = '<';
        sc.KPI_Threshold__c = kpiThreshold.Id;
        insert sc;                
        system.debug('sc ::'+sc);
        
        Test.StartTest();        
        ApexPages.StandardController st = new ApexPages.StandardController(kpiThreshold);             
        
        SPE2_NewKPIThresholdExt newkpiThreshold = new SPE2_NewKPIThresholdExt(st);
        SPE2_NewKPIThresholdExt.KPIRangeWrapper Wrapvar = new SPE2_NewKPIThresholdExt.KPIRangeWrapper(sc);
        PageReference pageRef = Page.SPE2_NewKPIThreshold;
        Test.setCurrentPage(pageRef);
        newkpiThreshold.enableattributesMap.put('Market Unit',true);
        newkpiThreshold.enableattributesMap.put('Country',true);
        newkpiThreshold.enableattributesMap.put('Project',true);
        newkpiThreshold.enableattributesMap.put('Category Area',true);
        newkpiThreshold.enableattributesMap.put('Category Group',true);
        newkpiThreshold.enableattributesMap.put('Category',true);
        newkpiThreshold.enableattributesMap.put('Business Unit',true);
        newkpiThreshold.enableattributesMap.put('Business Line',true);
        newkpiThreshold.enableattributesMap.put('Product',true);
        newkpiThreshold.save();
        pageRef.getParameters().put('isClone', '');       
        newkpiThreshold.getMarketValues();
        newkpiThreshold.getMarketUnitValues();
        newkpiThreshold.getCountryValues();
        newkpiThreshold.getProjectValues();
        newkpiThreshold.getBusinessUnitValues();
        newkpiThreshold.getBusinesLineValues();
        newkpiThreshold.getProductValues();
        newkpiThreshold.getCategoryAreaValues();
        newkpiThreshold.getCategoryGroupValues();
        newkpiThreshold.getCategoryValues();
        newkpiThreshold.StagePilot();
        newkpiThreshold.StagePublished();
        newkpiThreshold.StageObsolete();
        newkpiThreshold.populateAllValues();
       // newkpiThreshold.calculation();
        newkpiThreshold.validate();              
        newkpiThreshold.cloneFn();
        
        newkpiThreshold.cancel();
        newkpiThreshold.edi(); 
                        
        Test.StopTest();
     }
    static testMethod void createKPIThresholdPositive2(){
         
        //---Custom Setting data ---
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);        
        insert lstpicklistObj; 
        
       // PicklistDefaultValues__c defaultPicklist = SPE_TestObjectCreator.CreateDefaultPicklist();
        
        //SPE_KPIDefinition__c kpiDefinition1 = SPE_TestObjectCreator.CreateKPIDefinition(1);       
        SPE_KPIDefinition__c kpiDefinition1 = new SPE_KPIDefinition__c();
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.Level__c = '1;2';
        kpiDefinition1.GeoScope__c ='All Markets';
        kpiDefinition1.CategoryScope__c ='All Categories';
        kpiDefinition1.BUScope__c ='All Products';
        kpiDefinition1.IsHighBetter__c = Boolean.ValueOf('True');        
        kpiDefinition1.KPI_Title__c = 'Atos_KPI_Test1';
        kpiDefinition1.AbbreviatedName__c = 'TKPIDe1';
        kpiDefinition1.Level__c = '1';
        kpiDefinition1.LifecycleStage__c = 'Draft';
        kpiDefinition1.Description__c = 'Test';
        kpiDefinition1.MissingDatalogic__c = 'Logic1';
        kpiDefinition1.OperationalType__c = 'Leading PI';
        kpiDefinition1.GeoScope__c = 'All Markets';
        kpiDefinition1.categoryscope__c = 'All Categories';
        kpiDefinition1.BUScope__c = 'All Products';
        kpiDefinition1.UoM__c = 'max';
        kpiDefinition1.Group1__c = 'Cost';
        kpiDefinition1.Group2__c = 'Hard';
        kpiDefinition1.Type__c = 'Operational';
        kpiDefinition1.FrequencyinMonth__c = '2';
        kpiDefinition1.ScheduledDate__c = system.today().addDays(20);
        kpiDefinition1.VerNumber__c = 0;
        insert kpiDefinition1;
        
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.LifecycleStage__c = 'Pilot';
        update kpiDefinition1;
        
        kpiDefinition1.lifecyclestage__c='Published';
        //update kpiDefinition1; 
      
        /*SPE2_KPI_Threshold__c kpiThreshold =new SPE2_KPI_Threshold__c();
        kpiThreshold.KPI_ID__c = ApexPages.currentPage().getParameters().get('kpiDefinition1'); 
        kpiThreshold.Threshold_Title__c ='ABC Threshold';
        kpiThreshold.OwnerId =Userinfo.getUserId();
        kpiThreshold.High_Better__c =kpiDefinition1.IsHighBetter__c;
        insert kpiThreshold;*/
      
        Test.StartTest();
        PageReference pageRef = Page.SPE2_NewKPIThreshold;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('kpiId', kpiDefinition1.Id);
        pageRef.getParameters().put('isNew','TRUE');  
        pageRef.getParameters().put('isEdit','FALSE');      
        ApexPages.StandardController st = new ApexPages.StandardController(new SPE2_KPI_Threshold__c());   
       // ApexPages.currentPage().getParameters().put('kpiDefinition1');          
        
        SPE2_NewKPIThresholdExt newkpiThreshold = new SPE2_NewKPIThresholdExt(st);
        //SPE2_NewKPIThresholdExt.KPIRangeWrapper Wrapvar = new SPE2_NewKPIThresholdExt.KPIRangeWrapper(sc);
        newkpiThreshold.checkValidation();
        newkpiThreshold.Validate();
        pageRef.getParameters().put('isNew','TRUE');  
        pageRef.getParameters().put('isEdit','FALSE');
       // newkpiThreshold.calculation();
        newkpiThreshold.save();
       // pageRef.getParameters().put('isNew','TRUE');  
       // pageRef.getParameters().put('isEdit','FALSE'); 
        newkpiThreshold.cancel();
      //  newkpiThreshold.edi(); 
                        
        Test.StopTest();
        
    }
    
    static testMethod void createKPIThresholdCloned(){
         
        //---Custom Setting data ---
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);        
        insert lstpicklistObj; 
        
       // PicklistDefaultValues__c defaultPicklist = SPE_TestObjectCreator.CreateDefaultPicklist();
        
        //SPE_KPIDefinition__c kpiDefinition1 = SPE_TestObjectCreator.CreateKPIDefinition(1);       
        SPE_KPIDefinition__c kpiDefinition1 = new SPE_KPIDefinition__c();
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.Level__c = '1;2';
        kpiDefinition1.GeoScope__c ='All Markets';
        kpiDefinition1.CategoryScope__c ='All Categories';
        kpiDefinition1.BUScope__c ='All Products';
        kpiDefinition1.IsHighBetter__c = Boolean.ValueOf('True');        
        kpiDefinition1.KPI_Title__c = 'Atos_KPI_Test1';
        kpiDefinition1.AbbreviatedName__c = 'TKPIDe1';
        kpiDefinition1.Level__c = '1';
        kpiDefinition1.LifecycleStage__c = 'Draft';
        kpiDefinition1.Description__c = 'Test';
        kpiDefinition1.MissingDatalogic__c = 'Logic1';
        kpiDefinition1.OperationalType__c = 'Leading PI';
        kpiDefinition1.GeoScope__c = 'All Markets';
        kpiDefinition1.categoryscope__c = 'All Categories';
        kpiDefinition1.BUScope__c = 'All Products';
        kpiDefinition1.UoM__c = 'max';
        kpiDefinition1.Group1__c = 'Cost';
        kpiDefinition1.Group2__c = 'Hard';
        kpiDefinition1.Type__c = 'Operational';
        kpiDefinition1.FrequencyinMonth__c = '2';
        kpiDefinition1.ScheduledDate__c = system.today().addDays(20);
        kpiDefinition1.VerNumber__c = 0;
        insert kpiDefinition1;
        
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.LifecycleStage__c = 'Pilot';
        update kpiDefinition1;
        
        kpiDefinition1.lifecyclestage__c='Published';
       // update kpiDefinition1; 
      
        SPE2_KPI_Threshold__c kpiThreshold =new SPE2_KPI_Threshold__c();
        kpiThreshold.KPI_ID__c =kpiDefinition1.Id;
        kpiThreshold.Threshold_Title__c ='ABC Threshold';
        kpiThreshold.OwnerId =Userinfo.getUserId();
        kpiThreshold.High_Better__c =kpiDefinition1.IsHighBetter__c;
        insert kpiThreshold;
               
        SPE2_KPI_Threshold__c kpiThresholdCloned =new SPE2_KPI_Threshold__c();
        kpiThresholdCloned.KPI_ID__c =kpiDefinition1.Id;
        kpiThresholdCloned.Threshold_Title__c ='ABC Threshold';
        kpiThresholdCloned.OwnerId =Userinfo.getUserId();
        kpiThresholdCloned.High_Better__c =kpiDefinition1.IsHighBetter__c;
        insert kpiThresholdCloned ;

        SPE_ScoringCalculation__c sc = new SPE_ScoringCalculation__c();
        sc.KPIDefinition__c = kpiThresholdCloned.KPI_ID__c;
        sc.Score__c = 1;
        sc.Lower__c = 0;
        sc.LowerTo__c = '>';
        sc.Upper__c = 50;
        sc.UpperTo__c = '<';
        sc.KPI_Threshold__c = kpiThresholdCloned.Id;
        insert sc;                
        system.debug('sc ::'+sc);
        
        Test.StartTest(); 
        PageReference pageRef = Page.SPE2_NewKPIThreshold;
        Test.setCurrentPage(pageRef);  
        pageRef.getParameters().put('isClone', 'True');      
        ApexPages.StandardController st = new ApexPages.StandardController(kpiThresholdCloned);                     
        SPE2_NewKPIThresholdExt newkpiThreshold = new SPE2_NewKPIThresholdExt(st);
        
    //    ApexPages.currentPage().getParameters().put('isClone','TRUE');        
                       
        newkpiThreshold.save();
                            
        newkpiThreshold.getMarketValues();
        newkpiThreshold.getMarketUnitValues();
        newkpiThreshold.getCountryValues();
        newkpiThreshold.getProjectValues();
        newkpiThreshold.getBusinessUnitValues();
        newkpiThreshold.getBusinesLineValues();
        newkpiThreshold.getProductValues();
        newkpiThreshold.getCategoryAreaValues();
        newkpiThreshold.getCategoryGroupValues();
        newkpiThreshold.getCategoryValues();
        newkpiThreshold.StagePilot();
        newkpiThreshold.StagePublished();
        newkpiThreshold.StageObsolete();
        newkpiThreshold.populateAllValues();
       // newkpiThreshold.calculation();                    
        newkpiThreshold.cloneFn(); 
        newkpiThreshold.validate();
        newkpiThreshold.checkValidation();      
        newkpiThreshold.cancel();
        newkpiThreshold.edi(); 
                        
        Test.StopTest();
     }
      static testMethod void createKPIThreshold3(){
         
        //---Custom Setting data ---
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);        
        insert lstpicklistObj; 
        
       // PicklistDefaultValues__c defaultPicklist = SPE_TestObjectCreator.CreateDefaultPicklist();
        
        //SPE_KPIDefinition__c kpiDefinition1 = SPE_TestObjectCreator.CreateKPIDefinition(1);       
        SPE_KPIDefinition__c kpiDefinition1 = new SPE_KPIDefinition__c();
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.Level__c = '1;2';
        kpiDefinition1.GeoScope__c ='All Markets';
        kpiDefinition1.CategoryScope__c ='All Categories';
        kpiDefinition1.BUScope__c ='All Products';
        kpiDefinition1.IsHighBetter__c = Boolean.ValueOf('True');        
        kpiDefinition1.KPI_Title__c = 'Atos_KPI_Test1';
        kpiDefinition1.AbbreviatedName__c = 'TKPIDe1';
        kpiDefinition1.Level__c = '1';
        kpiDefinition1.LifecycleStage__c = 'Draft';
        kpiDefinition1.Description__c = 'Test';
        kpiDefinition1.MissingDatalogic__c = 'Logic1';
        kpiDefinition1.OperationalType__c = 'Leading PI';
        kpiDefinition1.GeoScope__c = 'All Markets';
        kpiDefinition1.categoryscope__c = 'All Categories';
        kpiDefinition1.BUScope__c = 'All Products';
        kpiDefinition1.UoM__c = 'max';
        kpiDefinition1.Group1__c = 'Cost';
        kpiDefinition1.Group2__c = 'Hard';
        kpiDefinition1.Type__c = 'Operational';
        kpiDefinition1.FrequencyinMonth__c = '2';
        kpiDefinition1.ScheduledDate__c = system.today().addDays(20);
        kpiDefinition1.VerNumber__c = 0;
        insert kpiDefinition1;
        
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.LifecycleStage__c = 'Pilot';
        update kpiDefinition1;
        
        kpiDefinition1.lifecyclestage__c='Published';
        //update kpiDefinition1; 
      
        SPE2_KPI_Threshold__c kpiThreshold =new SPE2_KPI_Threshold__c();
     /* kpiThreshold.KPI_ID__c =kpiDefinition1.Id;
        kpiThreshold.Threshold_Title__c ='ABC Threshold';
        kpiThreshold.OwnerId =Userinfo.getUserId();
        kpiThreshold.High_Better__c =kpiDefinition1.IsHighBetter__c;
        insert kpiThreshold;*/
        ApexPages.currentPage().getParameters().put('isNew','TRUE');
        ApexPages.currentPage().getParameters().put('isEdit','FALSE');
        
               
        SPE_ScoringCalculation__c sc = new SPE_ScoringCalculation__c();
        sc.KPIDefinition__c = kpiThreshold.KPI_ID__c;
        sc.Score__c = 1;
        sc.Lower__c = 0;
        sc.LowerTo__c = '>';
        sc.Upper__c = 50;
        sc.UpperTo__c = '<';
        sc.KPI_Threshold__c = kpiThreshold.Id;
        insert sc;                
        system.debug('sc ::'+sc);
        
        Test.StartTest(); 
        PageReference pageRef = Page.SPE2_NewKPIThreshold;
        Test.setCurrentPage(pageRef);
        pageRef.getParameters().put('kpiId', kpiDefinition1.Id);
        pageRef.getParameters().put('isNew','TRUE');
        pageRef.getParameters().put('isEdit','FALSE');     
        ApexPages.StandardController st = new ApexPages.StandardController(kpiThreshold);                     
        SPE2_NewKPIThresholdExt newkpiThreshold = new SPE2_NewKPIThresholdExt(st);
        newkpiThreshold.save();
        newkpiThreshold.validate();
        newkpiThreshold.checkValidation();                           
                                    
        newkpiThreshold.getMarketValues();
        newkpiThreshold.getMarketUnitValues();
        newkpiThreshold.getCountryValues();
        newkpiThreshold.getProjectValues();
        newkpiThreshold.getBusinessUnitValues();
        newkpiThreshold.getBusinesLineValues();
        newkpiThreshold.getProductValues();
        newkpiThreshold.getCategoryAreaValues();
        newkpiThreshold.getCategoryGroupValues();
        newkpiThreshold.getCategoryValues();
        newkpiThreshold.StagePilot();
        newkpiThreshold.StagePublished();
        newkpiThreshold.StageObsolete();
        newkpiThreshold.populateAllValues();
       // newkpiThreshold.calculation();                    
      //  newkpiThreshold.cloneFn(); 
             
       // newkpiThreshold.cancel();
      //  newkpiThreshold.edi(); 
                        
        Test.StopTest();
     }
     static testMethod void createKPIThreshold4(){
         
        //---Custom Setting data ---
        List<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
        PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
        picklistObj.Business_Line__c = 'All Business Lines';
        picklistObj.Business_Unit__c = 'All Business Units';
        picklistObj.Category_Area__c = 'All Category Areas';
        picklistObj.Category_Group__c = 'All Category Groups';
        picklistObj.Category__c = 'All Categories';
        picklistObj.Country__c = 'All Countries';
        picklistObj.Market_Unit__c = 'All Market Units';
        picklistObj.Market__c = 'All Markets';
        picklistObj.Name = 'Picklist Default Values';
        picklistObj.Product__c = 'All Products';
        picklistObj.Project__c = 'All Projects';
        
        lstpicklistObj.add(picklistObj);        
        insert lstpicklistObj; 
        
       // PicklistDefaultValues__c defaultPicklist = SPE_TestObjectCreator.CreateDefaultPicklist();
        
        //SPE_KPIDefinition__c kpiDefinition1 = SPE_TestObjectCreator.CreateKPIDefinition(1);       
        SPE_KPIDefinition__c kpiDefinition1 = new SPE_KPIDefinition__c();
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.Level__c = '1';
        kpiDefinition1.GeoScope__c ='All Markets';
        kpiDefinition1.CategoryScope__c ='All Categories';
        kpiDefinition1.BUScope__c ='All Products';
        kpiDefinition1.IsHighBetter__c = Boolean.ValueOf('True');        
        kpiDefinition1.KPI_Title__c = 'Atos_KPI_Test1';
        kpiDefinition1.AbbreviatedName__c = 'TKPIDe1';
        
        kpiDefinition1.LifecycleStage__c = 'Draft';
        kpiDefinition1.Description__c = 'Test';
        kpiDefinition1.MissingDatalogic__c = 'Logic1';
        kpiDefinition1.OperationalType__c = 'Leading PI';
        kpiDefinition1.GeoScope__c = 'Project';
        kpiDefinition1.categoryscope__c = 'Category';
        kpiDefinition1.BUScope__c = 'Product';
        kpiDefinition1.UoM__c = 'max';
        kpiDefinition1.Group1__c = 'Cost';
        kpiDefinition1.Group2__c = 'Hard';
        kpiDefinition1.Type__c = 'Operational';
        kpiDefinition1.FrequencyinMonth__c = '2';
        kpiDefinition1.ScheduledDate__c = system.today().addDays(20);
        kpiDefinition1.VerNumber__c = 0;
        insert kpiDefinition1;
        
        kpiDefinition1.ActualCalculation__c = 'A+B+C';
        kpiDefinition1.LifecycleStage__c = 'Pilot';
        update kpiDefinition1;
              
        SPE2_KPI_Threshold__c kpiThreshold =new SPE2_KPI_Threshold__c();
        kpiThreshold.KPI_ID__c =kpiDefinition1.Id;
        kpiThreshold.Threshold_Title__c ='ABC Threshold';
        kpiThreshold.OwnerId =Userinfo.getUserId();
        kpiThreshold.High_Better__c =kpiDefinition1.IsHighBetter__c;
        kpiThreshold.Region__c= 'NAM'; 
        kpiThreshold.SubRegion__c= 'NAM US'; 
        kpiThreshold.Country__c = 'United States of America'; 
        kpiThreshold.Project__c = 'US Cellular'; 
        kpiThreshold.CategoryCluster__c= 'Product Procurement'; 
        kpiThreshold.CategoryGroup__c ='Mechanics'; 
        kpiThreshold.Category__c = 'Sheet Metal Parts'; 
        kpiThreshold.BusinessUnit__c = 'Global Services'; 
        kpiThreshold.BusinessLine__c = 'Care'; 
        kpiThreshold.Product__c = 'PTF';          

        insert kpiThreshold;
               
        SPE_ScoringCalculation__c sc = new SPE_ScoringCalculation__c();
        sc.KPIDefinition__c = kpiThreshold.KPI_ID__c;
        sc.Score__c = 1;
        sc.Lower__c = 0;
        sc.LowerTo__c = '>';
        sc.Upper__c = 50;
        sc.UpperTo__c = '<';
        sc.KPI_Threshold__c = kpiThreshold.Id;
        insert sc;                
        system.debug('sc ::'+sc);
        
        ApexPages.currentPage().getParameters().put('isNew','TRUE');
        ApexPages.currentPage().getParameters().put('isEdit','FALSE');  
        
        Test.StartTest(); 
        PageReference pageRef = Page.SPE2_NewKPIThreshold;
        Test.setCurrentPage(pageRef);  
        pageRef.getParameters().put('kpiId', kpiDefinition1.Id);
        pageRef.getParameters().put('isNew','TRUE');
        pageRef.getParameters().put('isEdit','FALSE');    
        ApexPages.StandardController st = new ApexPages.StandardController(kpiThreshold);                     
        SPE2_NewKPIThresholdExt newkpiThreshold = new SPE2_NewKPIThresholdExt(st);
       // SPE2_NewKPIThresholdExt.ScoringCalcWrapper scw = new SPE2_NewKPIThresholdExt.ScoringCalcWrapper(sc);
        newkpiThreshold.populateAllValues(); 
        newkpiThreshold.validate();
        newkpiThreshold.checkValidation();                           
        newkpiThreshold.save();
        List<PicklistDefaultValues__c> picklist =newkpiThreshold.defalultPickl;
        newkpiThreshold.isNew =true;
        newkpiThreshold.isEdit =false;
        
      //  ApexPages.currentPage().getParameters().put('isNew','TRUE');
      //  ApexPages.currentPage().getParameters().put('isEdit','FALSE');                           
                             
        newkpiThreshold.getMarketValues();
        newkpiThreshold.getCountryValues();
        newkpiThreshold.getProjectValues();
        newkpiThreshold.getBusinessUnitValues();
       newkpiThreshold.getProductValues();
        newkpiThreshold.getCategoryAreaValues();
        newkpiThreshold.getCategoryValues();                  
                        
        Test.StopTest();
     }
}