src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/classes/SPE_MathsUtil.cls
public with sharing class SPE_MathsUtil 
{
    
    public static string market1 = PicklistDefaultValues__c.getall().values()[0].Market__c;
    public static string marketUnit1 = PicklistDefaultValues__c.getall().values()[0].Market_Unit__c;
    public static string country1 = PicklistDefaultValues__c.getall().values()[0].Country__c;
    public static string project1 = PicklistDefaultValues__c.getall().values()[0].Project__c;
    public static string bu1 = PicklistDefaultValues__c.getall().values()[0].Business_Unit__c;
    public static string bl1 = PicklistDefaultValues__c.getall().values()[0].Business_Line__c;
    public static string prd1 = PicklistDefaultValues__c.getall().values()[0].Product__c;
    public static string ca1 = PicklistDefaultValues__c.getall().values()[0].Category_Area__c;
    public static string cg1 = PicklistDefaultValues__c.getall().values()[0].Category_Group__c;
    public static string ct1 = PicklistDefaultValues__c.getall().values()[0].Category__c;
    
    public static Boolean isEdit = false;
    
    static Map<String, EnumOperation> arithmeticOperationMap = new Map<String, EnumOperation>();
    
    static 
    {
        arithmeticOperationMap.put('>', EnumOperation.Greater);
        arithmeticOperationMap.put('>=', EnumOperation.GreaterAndEqual);
        arithmeticOperationMap.put('==', EnumOperation.Equal);
        arithmeticOperationMap.put('<', EnumOperation.Lesser);
        arithmeticOperationMap.put('<=', EnumOperation.LesserAndEqual);
    }
    
    public static Decimal textToArithmeticOperator(Decimal lower, String lowerOpp, Decimal upper, String upperOpp, Decimal score, Decimal actualScore)
    {
        
        if (operationCompare((EnumOperation)arithmeticOperationMap.get(lowerOpp), actualScore, lower) &&
            operationCompare((EnumOperation)arithmeticOperationMap.get(upperOpp), actualScore, upper) )
        {
            return score;
        }
        
        return null;
    }
    
    
    public enum EnumOperation 
    {
        Greater, GreaterAndEqual, Equal, Lesser, LesserAndEqual
    }
    
    public static Boolean operationCompare(EnumOperation opp, Decimal val1, Decimal val2)
    {
        
        if (EnumOperation.Greater == opp)
        {
            return val1 > val2;
        }
        else if (EnumOperation.GreaterAndEqual == opp)
        {
            return val1 >= val2;
        }
        else if (EnumOperation.Equal == opp)
        {
            return val1 == val2;
        }
        else if (EnumOperation.Lesser == opp)
        {
            return val1 < val2;
        }
        else if (EnumOperation.LesserAndEqual == opp)
        {
            return val1 <= val2;
        }
        else
        {
            return false;
        }   
    }
    
}