src/objects/PicklistDefaultValues__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the default values for custom picklists</description>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Picklist Default Values</label>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>AbbreviatedName__c</fullName>
        <inlineHelpText>10 character limit.  Applicable for all languages.</inlineHelpText>
        <label>KPI Abbreviation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActualCalculation__c</fullName>
        <label>Actual Calculation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>255 Character Limit</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FrequencyinMonth__c</fullName>
        <label>Frequency in Month</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group1__c</fullName>
        <inlineHelpText>See Guidelines</inlineHelpText>
        <label>Pillar</label>
        <picklist>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustainability</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group2__c</fullName>
        <inlineHelpText>See Guidelines</inlineHelpText>
        <label>Group 2</label>
        <picklist>
            <picklistValues>
                <fullName>Hard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KPI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of KPI 
(Standard Name field of KPI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>See Guidelines; sets the number of buckets or scores.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MissingDatalogic__c</fullName>
        <inlineHelpText>Please Click on the Help Link on the top of this page</inlineHelpText>
        <label>Missing Data logic</label>
        <picklist>
            <picklistValues>
                <fullName>Past Data or Category Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPE Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OperationalType__c</fullName>
        <label>Operational Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lagging PI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leading PI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <description>Enter date when the KPI will be calculated (for data) or scheduled (for survey)</description>
        <inlineHelpText>This is an auto computed date looking at the underlying PI definitions (latest PI upload date + buffer days). This refreshes in batches and not instantaneously.</inlineHelpText>
        <label>Next Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Operational, Commercial, or Strategic</inlineHelpText>
        <label>KPI Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>i.e. Days, Units, %, Euros, etc.</inlineHelpText>
        <label>Unit of Measure</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VerNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <label>VerNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/thresholdscopeAttributeMapTest.cls
@isTest (seeAllData=false)
private class thresholdscopeAttributeMapTest{
      static testMethod void populateAttributes1(){
           
           LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
            PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
            picklistObj.Business_Line__c = 'All Business Lines';
            picklistObj.Business_Unit__c = 'All Business Units';
            picklistObj.Category_Area__c = 'All Category Areas';
            picklistObj.Category_Group__c = 'All Category Groups';
            picklistObj.Category__c = 'All Categories';
            picklistObj.Country__c = 'All Countries';
            picklistObj.Market_Unit__c = 'All Market Units';
            picklistObj.Market__c = 'All Markets';
            picklistObj.Name = 'Picklist Default Values';
            picklistObj.Product__c = 'All Products';
            picklistObj.Project__c = 'All Projects';
            
            lstpicklistObj.add(picklistObj);
            
            insert lstpicklistObj; 
             
           SPE_KPIDefinition__c kpiDef = new SPE_KPIDefinition__c();
            kpiDef.KPI_Title__c = 'Test KPI Definition 123';
            kpiDef.AbbreviatedName__c = 'TKPIDe1';
            kpiDef.Level__c = '1';
            kpiDef.LifecycleStage__c = 'Draft';
            kpiDef.Description__c = 'Test';
            kpiDef.MissingDatalogic__c = 'Logic1';
            kpiDef.OperationalType__c = 'Leading PI';
            kpiDef.GeoScope__c = 'All Markets';
            kpiDef.categoryscope__c = 'All Categories';
            kpiDef.BUScope__c = 'All Products';
            kpiDef.UoM__c = 'max';
            kpiDef.Group1__c = 'Cost';
            kpiDef.Group2__c = 'Hard';
            kpiDef.Type__c = 'Operational';
            kpiDef.FrequencyinMonth__c = '2';
            kpiDef.ScheduledDate__c = system.today().addDays(20);
            kpiDef.VerNumber__c = 0;
            insert kpiDef;
            
           /* kpiDef.ActualCalculation__c = 'A+B+C';
            kpiDef.lifecyclestage__c='Published';
            update kpiDef;
             */      
           Test.StartTest(); 
           thresholdscopeAttributeMap saMap = new thresholdscopeAttributeMap();
           saMap.initializeMapValue();
           saMap.qualifyScopeAttributes(kpiDef);
           
           Test.StopTest();
      }
       static testMethod void populateAttributes2(){
           LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
            PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
            picklistObj.Business_Line__c = 'All Business Lines';
            picklistObj.Business_Unit__c = 'All Business Units';
            picklistObj.Category_Area__c = 'All Category Areas';
            picklistObj.Category_Group__c = 'All Category Groups';
            picklistObj.Category__c = 'All Categories';
            picklistObj.Country__c = 'All Countries';
            picklistObj.Market_Unit__c = 'All Market Units';
            picklistObj.Market__c = 'All Markets';
            picklistObj.Name = 'Picklist Default Values';
            picklistObj.Product__c = 'All Products';
            picklistObj.Project__c = 'All Projects';
            
            lstpicklistObj.add(picklistObj);
            
            insert lstpicklistObj; 
             
           SPE_KPIDefinition__c kpiDef = new SPE_KPIDefinition__c();
            kpiDef.KPI_Title__c = 'Test KPI Definition 123';
            kpiDef.AbbreviatedName__c = 'TKPIDe1';
            kpiDef.Level__c = '1';
            kpiDef.LifecycleStage__c = 'Draft';
            kpiDef.Description__c = 'Test';
            kpiDef.MissingDatalogic__c = 'Logic1';
            kpiDef.OperationalType__c = 'Leading PI';
            kpiDef.GeoScope__c = 'Market';
            kpiDef.categoryscope__c = 'Category Area';
            kpiDef.BUScope__c = 'Business Unit';
            kpiDef.UoM__c = 'max';
            kpiDef.Group1__c = 'Cost';
            kpiDef.Group2__c = 'Hard';
            kpiDef.Type__c = 'Operational';
            kpiDef.FrequencyinMonth__c = '2';
            kpiDef.ScheduledDate__c = system.today().addDays(20);
            kpiDef.VerNumber__c = 0;
            insert kpiDef;
            
           /* kpiDef.ActualCalculation__c = 'A+B+C';
            kpiDef.lifecyclestage__c='Published';
            update kpiDef;
             */        
           Test.StartTest(); 
           thresholdscopeAttributeMap saMap = new thresholdscopeAttributeMap();
           saMap.initializeMapValue();
           saMap.qualifyScopeAttributes(kpiDef);
           
           Test.StopTest();
       }
       static testMethod void populateAttributes3(){
           LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
            PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
            picklistObj.Business_Line__c = 'All Business Lines';
            picklistObj.Business_Unit__c = 'All Business Units';
            picklistObj.Category_Area__c = 'All Category Areas';
            picklistObj.Category_Group__c = 'All Category Groups';
            picklistObj.Category__c = 'All Categories';
            picklistObj.Country__c = 'All Countries';
            picklistObj.Market_Unit__c = 'All Market Units';
            picklistObj.Market__c = 'All Markets';
            picklistObj.Name = 'Picklist Default Values';
            picklistObj.Product__c = 'All Products';
            picklistObj.Project__c = 'All Projects';
            
            lstpicklistObj.add(picklistObj);
            
            insert lstpicklistObj; 
             
           SPE_KPIDefinition__c kpiDef = new SPE_KPIDefinition__c();
            kpiDef.KPI_Title__c = 'Test KPI Definition 123';
            kpiDef.AbbreviatedName__c = 'TKPIDe1';
            kpiDef.Level__c = '1';
            kpiDef.LifecycleStage__c = 'Draft';
            kpiDef.Description__c = 'Test';
            kpiDef.MissingDatalogic__c = 'Logic1';
            kpiDef.OperationalType__c = 'Leading PI';
            kpiDef.GeoScope__c = 'Market Unit';
            kpiDef.categoryscope__c = 'Category Group';
            kpiDef.BUScope__c = 'Business Line';
            kpiDef.UoM__c = 'max';
            kpiDef.Group1__c = 'Cost';
            kpiDef.Group2__c = 'Hard';
            kpiDef.Type__c = 'Operational';
            kpiDef.FrequencyinMonth__c = '2';
            kpiDef.ScheduledDate__c = system.today().addDays(20);
            kpiDef.VerNumber__c = 0;
            insert kpiDef;
            
           /* kpiDef.ActualCalculation__c = 'A+B+C';
            kpiDef.lifecyclestage__c='Published';
            update kpiDef;
             */      
           Test.StartTest(); 
           thresholdscopeAttributeMap saMap = new thresholdscopeAttributeMap();
           saMap.initializeMapValue();
           saMap.qualifyScopeAttributes(kpiDef);
           
           Test.StopTest();
       }
       static testMethod void populateAttributes4(){
           LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
            PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
            picklistObj.Business_Line__c = 'All Business Lines';
            picklistObj.Business_Unit__c = 'All Business Units';
            picklistObj.Category_Area__c = 'All Category Areas';
            picklistObj.Category_Group__c = 'All Category Groups';
            picklistObj.Category__c = 'All Categories';
            picklistObj.Country__c = 'All Countries';
            picklistObj.Market_Unit__c = 'All Market Units';
            picklistObj.Market__c = 'All Markets';
            picklistObj.Name = 'Picklist Default Values';
            picklistObj.Product__c = 'All Products';
            picklistObj.Project__c = 'All Projects';
            
            lstpicklistObj.add(picklistObj);
            
            insert lstpicklistObj; 
             
           SPE_KPIDefinition__c kpiDef = new SPE_KPIDefinition__c();
            kpiDef.KPI_Title__c = 'Test KPI Definition 123';
            kpiDef.AbbreviatedName__c = 'TKPIDe1';
            kpiDef.Level__c = '1';
            kpiDef.LifecycleStage__c = 'Draft';
            kpiDef.Description__c = 'Test';
            kpiDef.MissingDatalogic__c = 'Logic1';
            kpiDef.OperationalType__c = 'Leading PI';
            kpiDef.GeoScope__c = 'Country';
            kpiDef.categoryscope__c = 'Category';
            kpiDef.BUScope__c = 'Product';
            kpiDef.UoM__c = 'max';
            kpiDef.Group1__c = 'Cost';
            kpiDef.Group2__c = 'Hard';
            kpiDef.Type__c = 'Operational';
            kpiDef.FrequencyinMonth__c = '2';
            kpiDef.ScheduledDate__c = system.today().addDays(20);
            kpiDef.VerNumber__c = 0;
            insert kpiDef;
            
          /*  kpiDef.ActualCalculation__c = 'A+B+C';
            kpiDef.lifecyclestage__c='Published';
            update kpiDef;
            */        
           Test.StartTest(); 
           thresholdscopeAttributeMap saMap = new thresholdscopeAttributeMap();
           saMap.initializeMapValue();
           saMap.qualifyScopeAttributes(kpiDef);
           
           Test.StopTest();
       }
      static testMethod void populateAttributes5(){
           LIst<PicklistDefaultValues__c> lstpicklistObj = new List<PicklistDefaultValues__c>();
            PicklistDefaultValues__c picklistObj = new PicklistDefaultValues__c();
            picklistObj.Business_Line__c = 'All Business Lines';
            picklistObj.Business_Unit__c = 'All Business Units';
            picklistObj.Category_Area__c = 'All Category Areas';
            picklistObj.Category_Group__c = 'All Category Groups';
            picklistObj.Category__c = 'All Categories';
            picklistObj.Country__c = 'All Countries';
            picklistObj.Market_Unit__c = 'All Market Units';
            picklistObj.Market__c = 'All Markets';
            picklistObj.Name = 'Picklist Default Values';
            picklistObj.Product__c = 'All Products';
            picklistObj.Project__c = 'All Projects';
            
            lstpicklistObj.add(picklistObj);
            
            insert lstpicklistObj; 
             
           SPE_KPIDefinition__c kpiDef = new SPE_KPIDefinition__c();
            kpiDef.KPI_Title__c = 'Test KPI Definition 123';
            kpiDef.AbbreviatedName__c = 'TKPIDe1';
            kpiDef.Level__c = '1';
            kpiDef.LifecycleStage__c = 'Draft';
            kpiDef.Description__c = 'Test';
            kpiDef.MissingDatalogic__c = 'Logic1';
            kpiDef.OperationalType__c = 'Leading PI';
            kpiDef.GeoScope__c = 'Project';
            kpiDef.categoryscope__c = 'All Categories';
            kpiDef.BUScope__c = 'Product';
            kpiDef.UoM__c = 'max';
            kpiDef.Group1__c = 'Cost';
            kpiDef.Group2__c = 'Hard';
            kpiDef.Type__c = 'Operational';
            kpiDef.FrequencyinMonth__c = '2';
            kpiDef.ScheduledDate__c = system.today().addDays(20);
            kpiDef.VerNumber__c = 0;
            insert kpiDef;
            
            /*kpiDef.ActualCalculation__c = 'A+B+C';
            kpiDef.lifecyclestage__c='Published';
            update kpiDef;
              */      
           Test.StartTest(); 
           thresholdscopeAttributeMap saMap = new thresholdscopeAttributeMap();
           saMap.initializeMapValue();
           saMap.qualifyScopeAttributes(kpiDef);
           
           Test.StopTest();
       }
}