src/objects/Portfolios_Owner__c.object
<CustomObject>
    <fields>
        <fullName>DMAIC_DMADV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DMAIC / DMADV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>QIPP_Contact__c</fullName>
        <label>QIPP Contact</label>
        <referenceTo>QIPP_Contacts__c</referenceTo>
        <relationshipLabel>Portfolios Owners</relationshipLabel>
        <relationshipName>Portfolios_Owners</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QIPP_Portfolio__c</fullName>
        <label>QIPP Portfolio</label>
        <referenceTo>QIPP_Portfolio__c</referenceTo>
        <relationshipLabel>Portfolios Owners</relationshipLabel>
        <relationshipName>Portfolios_Owners</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Portfolios Owner</label>
    <nameField>
        <label>Portfolios Owner</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QIPP_Contacts__c.object
<CustomObject>
    <description>Contact database for QIPP Application</description>
    <fields>
        <fullName>Belt_Certification__c</fullName>
        <label>Belt Certification</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Specified</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Nokia-Green Belt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nokia-Black Belt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nokia-Master Black Belt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External-Green Belt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External-Black Belt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External-Master Black Belt</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CoPQ_Role_1__c</fullName>
        <label>Role 1</label>
        <picklist>
            <picklistValues>
                <fullName>Business Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Owner Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Approver Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q PMO Team Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Measure Creator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL Transformation Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit Master Black Belt</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_BL__c</fullName>
        <label>L3 Org (BL)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_BU__c</fullName>
        <label>L2 Org (BU)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_L4_Org__c</fullName>
        <label>L4 Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_State__c</fullName>
        <label>Contact State</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User_License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select a user account, if it is already setup</inlineHelpText>
        <label>User License</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>QIPP Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/QIPP_Portfolio__c.object
<CustomObject>
    <description>Custom Object &quot;Portfolio&quot; for the QIPP Application</description>
    <fields>
        <fullName>DMAIC_DMADV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DMAIC/DMADV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portfolio_Business_Unit__c</fullName>
        <inlineHelpText>The benefitting Business group/Functional Group for the Portfolio. The project details will NOT automatically be changed to the newly updated portfolio values.</inlineHelpText>
        <label>Portfolio Business Grp/Functional Grp</label>
        <picklist>
            <picklistValues>
                <fullName>Applications &amp; Analytics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Financial Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief innovation and Operating office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Strategy &amp; Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Networks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP/Optical Networks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal &amp; Compliance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing &amp; Corporate Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Networks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Portfolio_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio Owner</label>
        <referenceTo>QIPP_Contacts__c</referenceTo>
        <relationshipLabel>Portfolios (Portfolio Owner)</relationshipLabel>
        <relationshipName>Portfolios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio_Status__c</fullName>
        <label>Portfolio Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QIPP Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/QIPP_Portfolio_Owner_Count_TestClass.cls
@isTest
private class QIPP_Portfolio_Owner_Count_TestClass {
    public testMethod static void POwnerCountTest(){
	List<QIPP_Project__c> proj;
    QIPP_Contacts__c qCont;    
    User u;
    string msg;
        Portfolios_Owner__c qport;
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
          System.runAs ( thisUser ) {
          Profile p = [SELECT Id,UserLicense.Name FROM Profile WHERE Name='System Administrator' and UserLicense.Name != '']; 
          UserRole r = [SELECT Id FROM UserRole WHERE Name='QIPP Portfolio Owner'];  
          u = new User();
          u.Alias = 'standt';
          u.Email='manish@manish.com';
          u.EmailEncodingKey='UTF-8';
          u.LastName='Testing';
          u.LanguageLocaleKey='en_US';
          u.LocaleSidKey='en_US';
          u.ProfileId = p.Id;
          u.UserRoleId = r.Id;
          u.TimeZoneSidKey='America/Los_Angeles'; 
          u.UserName='standarduser_manish@testorg.com';
          u.IsActive=true;    
          insert u; 
              
          	qCont = new QIPP_Contacts__c();
            qCont.Name = 'testManish';
            qCont.Email__c = 'manish@manish.com';
            qCont.Contact_State__c = 'Active';
            qCont.Contact_BU__c = 'CFO Functions';
            qCont.Contact_BL__c = 'test7894656';
            qCont.Contact_L4_Org__c = 'testmanish1234';
            qCont.Belt_Certification__c = 'Nokia-Black Belt';
            qCont.User_License__c = u.Id;
            qCont.CoPQ_Role_1__c = 'Business Unit Master Black Belt'; 
          }       
	Portfolios_Owner__c qPortowner = new Portfolios_Owner__c();
	  system.runas(u){
      insert qCont;
      //insert qCont2;   
      system.debug('qCont  :'+qCont);    
        QIPP_Portfolio__c qPortfolio = new QIPP_Portfolio__c();
        qPortfolio.Name = 'testManish';
        //qPortfolio.Portfolio_Owner__c = qCont.Id;
        qPortfolio.Portfolio_Business_Unit__c = 'Human Resources';
        qPortfolio.Portfolio_Status__c = 'Active';
        qPortfolio.DMAIC_DMADV__c = true;
        insert qPortfolio;  
        system.debug('qPortfolio  :'+qPortfolio);      
          
        Portfolios_Owner__c POwnerIns = new Portfolios_Owner__c();
        POwnerIns.Name = 'testManish';
        POwnerIns.Email__c = 'manish@manish.com';
        POwnerIns.QIPP_Contact__c = qCont.id;
        POwnerIns.QIPP_Portfolio__c = qPortfolio.id;
        POwnerIns.DMAIC_DMADV__c = true;
        insert POwnerIns;
          
        ApexPages.StandardController sc = new ApexPages.StandardController(qPortfolio);
        System.currentPageReference().getParameters().put('rec', qPortfolio.id);
        QIPP_Portfolio_Owner_Count ownercount = new QIPP_Portfolio_Owner_Count(sc);  
		}
    }
}