src/objects/QIPP_Contacts__c.object
<CustomObject>
    <description>Contact database for QIPP Application</description>
    <fields>
        <fullName>Contact_State__c</fullName>
        <label>Contact State</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NSN_ID_Text__c</fullName>
        <externalId>true</externalId>
        <label>NSN ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>QIPP Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/QIPPUpdateLineManagerEmail_Test.cls
@isTest
private class QIPPUpdateLineManagerEmail_Test
{
    
    static testmethod void test()
    {
        QIPP_Contacts__c con = new QIPP_Contacts__c();
        con.Name = 'Venkat Maddipati';
        con.Email__c = 'venkat.maddipati@igate.com';
        con.Contact_State__c = 'Active';
        con.NSN_ID_Text__c = '12345';
        insert con;
        
        QIPP_Contacts__c con1 = new QIPP_Contacts__c();
        con1.Name = 'Venkat2 Maddipati';
        con1.Email__c = 'venkat2.maddipati@igate.com';
        con1.Contact_State__c = 'Active';
        con1.NSN_ID_Text__c = '123456';
        insert con1;
        
          
               
    }
}