src/objects/QIPP_Benefit_Conversion_Table__c.object
<CustomObject>
    <description>Custom Object &quot;Benefit Convesion Table&quot; for QIPP Application</description>
    <fields>
        <fullName>Benefit_Type__c</fullName>
        <label>Benefit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Financial Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational Savings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <picklist>
            <picklistValues>
                <fullName>SCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PaCo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCDMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLATFORMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CoPQ_Reduction_Conversion_Rate__c</fullName>
        <inlineHelpText>Output in k€</inlineHelpText>
        <label>CoPQ Reduction Conversion Rate</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CoPQ_Type__c</fullName>
        <label>Financial Type</label>
        <picklist>
            <picklistValues>
                <fullName>Direct Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indirect Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Financial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Directional_Indicator__c</fullName>
        <label>Directional Indicator</label>
        <picklist>
            <picklistValues>
                <fullName>Lower is Favorable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Higher is Favorable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Financial_Impact_Calculation_Driver__c</fullName>
        <label>Financial Impact Calculation Driver</label>
        <picklist>
            <picklistValues>
                <fullName>NCDR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Failures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Overrun due to Quality Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warranties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retrofit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E&amp;O</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Penalties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional HW and/or SW</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <label>Fiscal Quarter</label>
        <picklist>
            <picklistValues>
                <fullName>Q1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Impacted_P_L_Line__c</fullName>
        <label>Impacted P/L Line</label>
        <picklist>
            <controllingField>CoPQ_Type__c</controllingField>
            <picklistValues>
                <fullName>R&amp;D Budget</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cost of Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <picklist>
            <picklistValues>
                <fullName>Each</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K Euro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts per Million</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Improvement Measure</label>
    <nameField>
        <label>Improvement Measure (KPI)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Improvement Measures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/QIPPBCTDuplicateRecordValidation_Test.cls
@isTest
private class QIPPBCTDuplicateRecordValidation_Test
{
  
    static testmethod void test()
    {
        QIPP_Benefit_Conversion_Table__c bct = new QIPP_Benefit_Conversion_Table__c();
        bct.Financial_Impact_Calculation_Driver__c = 'NCDR';
        bct.Business_Line__c = 'VIPT';
        bct.Unit_of_Measure__c = 'Each';
        bct.Benefit_Type__c = 'CoPQ Reduction';
        bct.CoPQ_Type__c = 'Indirect Financial';
        bct.Impacted_P_L_Line__c = 'R&D Budget';
        bct.Directional_Indicator__c = 'Lower is Favorable';
        bct.Fiscal_Year__c = '2013';
        bct.Fiscal_Quarter__c = 'Q3';
        bct.CoPQ_Reduction_Conversion_Rate__c = 100;
        insert bct;
        
      
               
    }
}