src/objects/QIPP_Benefit__c.object
<CustomObject>
    <description>Benefit Monetization for Projects</description>
    <fields>
        <fullName>Achieved_Benefit_Period_Weeks__c</fullName>
        <label>Achieved Benefit Period (Weeks)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Achieved_Quantity__c</fullName>
        <label>Performance Quantity (Achieved To-Date)</label>
        <precision>10</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Achieved_Start_Date__c</fullName>
        <label>Achieved Benefit Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Baseline_Period_weeks__c</fullName>
        <label>Baseline Period (weeks)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Baseline_Quantity__c</fullName>
        <label>Baseline Quantity</label>
        <precision>10</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Baseline_Rate_N__c</fullName>
        <label>Baseline Rate</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Benefit_Type__c</fullName>
        <inlineHelpText>The default Benefit Type will auto-populate this field. To change the Benefit Type select the appropriate type.</inlineHelpText>
        <label>Benefit Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <picklist>
            <controllingField>Improvement_Measure__c</controllingField>
            <picklistValues>
                <fullName>GSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCDMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PaCo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLATFORMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Directional_Indicator__c</fullName>
        <label>Directional Indicator</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financial_Type__c</fullName>
        <label>Financial Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Improvement_Measure_KPI__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Improvement Measure (KPI)</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>QIPP_Benefit_Conversion_Table__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>QIPP_Benefit_Conversion_Table__c</referenceTo>
        <relationshipLabel>Benefits (Improvement Measure (KPI))</relationshipLabel>
        <relationshipName>Improvement_Measure_KPI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planned_Benefit_Period_Weeks__c</fullName>
        <label>Planned Benefit Period (Weeks)</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_End_Date__c</fullName>
        <label>Planned Benefit End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Planned_Operational_Manual_Amount__c</fullName>
        <label>Planned</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_Quanity__c</fullName>
        <label>Performance Quantity (Planned)</label>
        <precision>10</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planned_Start_Date__c</fullName>
        <label>Planned Benefit Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Portfolio_Name__c</fullName>
        <label>Portfolio Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <label>Project Lead</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Measure__c</fullName>
        <label>Type of Measure (Time Period)</label>
        <picklist>
            <picklistValues>
                <fullName>Distributed Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly Rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly Rate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <inlineHelpText>The default Unit of Measure will auto-populate this field.  To change the Unit of Measure click on the cell and select from the drop-down list.  You may also add a new Improvement Measure by entering the new value in this field.</inlineHelpText>
        <label>Unit of Measure</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>QIPP Benefit</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Benefit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QIPP_Benefit_Conversion_Table__c.object
<CustomObject>
    <description>Custom Object &quot;Benefit Convesion Table&quot; for QIPP Application</description>
    <fields>
        <fullName>Benefit_Type__c</fullName>
        <label>Benefit Type</label>
        <picklist>
            <picklistValues>
                <fullName>Financial Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operational Savings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <picklist>
            <picklistValues>
                <fullName>SCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PaCo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WCDMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VCM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PLATFORMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Directional_Indicator__c</fullName>
        <label>Directional Indicator</label>
        <picklist>
            <picklistValues>
                <fullName>Lower is Favorable</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Higher is Favorable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Monetization_Calculation_Method__c</fullName>
        <label>Monetization Calculation Method</label>
        <picklist>
            <controllingField>Benefit_Type__c</controllingField>
            <picklistValues>
                <fullName>Automated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <picklist>
            <picklistValues>
                <fullName>Each</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K Euro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Integer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hours</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts per Million</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Improvement Measure</label>
    <nameField>
        <label>Improvement Measure (KPI)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Improvement Measures</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/QIPP_BU_Reporting__c.object
<CustomObject>
    <fields>
        <fullName>Benefit_Type__c</fullName>
        <label>Benefit Type</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portfolio_Name__c</fullName>
        <label>Portfolio Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>QIPP – Benefit Report</label>
    <nameField>
        <label>QIPP - BU Reporting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QIPP – Benefit Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/QIPP_Contacts__c.object
<CustomObject>
    <description>Contact database for QIPP Application</description>
    <fields>
        <fullName>Contact_State__c</fullName>
        <label>Contact State</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NSN_ID_Text__c</fullName>
        <externalId>true</externalId>
        <label>NSN ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>QIPP Contact</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/QIPP_Portfolio__c.object
<CustomObject>
    <description>Custom Object &quot;Portfolio&quot; for the QIPP Application</description>
    <fields>
        <fullName>CDT_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use directory search or see Portfolio Mgr (Mike Patel) to add new CDT lead</inlineHelpText>
        <label>CDT Lead</label>
        <referenceTo>QIPP_Contacts__c</referenceTo>
        <relationshipName>Portfolio1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CPV_Trend__c</fullName>
        <label>CPV Trend</label>
        <picklist>
            <picklistValues>
                <fullName>Down</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neutral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CPVi_Composite__c</fullName>
        <label>CPVi-Composite</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CPVi_Future__c</fullName>
        <label>CPVi-Expectation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>CPVi_Past__c</fullName>
        <label>CPVi-Experience</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>DMAIC_DMADV__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DMAIC/DMADV</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lean_including_Kaizen__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Lean (including Kaizen)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portfolio_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Portfolio Owner</label>
        <referenceTo>QIPP_Contacts__c</referenceTo>
        <relationshipLabel>Portfolios (Portfolio Owner)</relationshipLabel>
        <relationshipName>Portfolios</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portfolio_Status__c</fullName>
        <label>Portfolio Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QIPP Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/QIPP_Benefit_History_Component_Test.cls
@istest(seealldata =true)
public class QIPP_Benefit_History_Component_Test {
   // static id RTID_DMAIC = [select Id from RecordType where Name = 'Methodology: DMAIC / DMADV' and SobjectType = 'QIPP_Project__c'].Id;
    
   /* static testmethod void GenericHistoryComponentController_1(){  
        User DummyUser = new User();
        DummyUser.LastName = 'adc';      
        DummyUser.FirstName = 'adc';
        DummyUser.Alias = 'adc';
        DummyUser.Email = 'a@a.a';
        DummyUser.Username = 'a@a.a.adc';
        DummyUser.CommunityNickname = 'a';
        DummyUser.IsActive = TRUE;
        DummyUser.ProfileId = [SELECT Id FROM Profile WHERE Name LIKE '%System Administrator%' LIMIT 1].Id;
        DummyUser.TimeZoneSidKey = 'Asia/Kamchatka';
        DummyUser.LocaleSidKey = 'en_US';
        DummyUser.EmailEncodingKey = 'ISO-8859-1';
        DummyUser.LanguageLocaleKey = 'en_US';
        insert DummyUser;
        
        QIPP_Contacts__c con = new QIPP_Contacts__c();
        con.Name = 'Srikanth';
        con.Email__c = 'Srikanth.sree@igate.com';
        con.Contact_State__c = 'Active';
        con.NSN_ID_Text__c = '12234345';
        insert con;
        
        QIPP_Portfolio__c portfolio = new QIPP_Portfolio__c();
        portfolio.Name = 'Test Portfolio1';
        portfolio.Portfolio_Owner__c = con.id;
        portfolio.ownerId = DummyUser.Id;
        portfolio.CDT_Lead__c = con.id;
        portfolio.CPVi_Composite__c = 25.0;
        portfolio.CPVi_Past__c = 29.0;
        portfolio.CPVi_Future__c = 55.0; 
        portfolio.CPV_Trend__c  = 'Up';
        portfolio.Portfolio_Status__c = 'Active';
        portfolio.DMAIC_DMADV__c = true;
        portfolio.Lean_including_Kaizen__c = true;
        insert portfolio;
        
        QIPP_Project__c project = new QIPP_Project__c();
        project.Portfolio_Name__c = portfolio.id;
        project.RecordTypeId = RTID_DMAIC;
        project.Project_Completion_Date_Target__c = Date.Today();
        project.Project_Name_Succinct__c = 'Test Project1';
        project.Primary_QLT_Function__c = 'CO';
        project.Project_State__c = 'On hold';
        project.Last_Review_Type__c = 'Final';
        project.Project_Lead__c = con.id;
        project.ownerid = DummyUser.Id;
        project.Report_Name__c = 'Executive Dashboards';
        project.Report_Type__c = 'Summary of Projects by Project Type ';
        insert project;
        
        QIPP_Benefit_Conversion_Table__c conversions = new  QIPP_Benefit_Conversion_Table__c(); 
        conversions.Name = 'KPI1';
        conversions.Benefit_Type__c = 'Operational Savings';
        conversions.Monetization_Calculation_Method__c = 'Manual';
        INSERT conversions;
        
        QIPP_Benefit_Conversion_Table__c conversions2 = new  QIPP_Benefit_Conversion_Table__c(); 
        conversions2.Name = 'KPI2';
        conversions2.Benefit_Type__c = 'Financial Savings';
        conversions2.Monetization_Calculation_Method__c = 'Manual';
        INSERT conversions2;
        
        QIPP_Benefit__c benifit = new QIPP_Benefit__c();
        benifit.Baseline_Rate_N__c = 100;
        benifit.Financial_Type__c = 'Operational Savings';
        benifit.Business_Line__c = 'GSM';
        benifit.Improvement_Measure_KPI__c = conversions.id;         
        benifit.Unit_of_Measure__c = 'Each';
        benifit.Baseline_Period_weeks__c = 4.35;
        benifit.Directional_Indicator__c = 'Higher is Favorable' ;
        Date startdate = Date.newInstance(2013, 01, 01);   
        Date enddate = Date.newInstance(2013, 03, 31);
        benifit.Baseline_Quantity__c = 15;
        benifit.Type_of_Measure__c = 'Weekly Rate' ;
        benifit.Planned_Quanity__c = 500;
        benifit.Planned_Benefit_Period_Weeks__c = 4.33;
        benifit.Planned_Start_Date__c = startdate  ;
        benifit.Planned_End_Date__c = enddate ;
        benifit.Planned_Operational_Manual_Amount__c = 500;
        benifit.Achieved_Quantity__c = 50;
        benifit.Achieved_Start_Date__c = startdate  ;
        benifit.Achieved_Benefit_Period_Weeks__c = 4.33 ;
        benifit.Achieved_End_Date__c = enddate  ;
        benifit.Achieved_Operational_Manual_Amount__c = 500;
        benifit.Future_Quantity__c = 50;
        benifit.Future_Start_Date__c = Date.newInstance(2013, 04, 01);
        benifit.Future_Benefit_Period_Weeks__c = 4.33 ;
        benifit.Future_End_Date__c = Date.newInstance(2013, 04, 31);         
        benifit.Future_Operational_Manual_Amount__c = 500;
        benifit.Unit_of_Measure__c = 'Each';
        benifit.Project_ID__c = project.id;
        insert benifit;
        
        QIPP_BU_Reporting__c benrep1 = new QIPP_BU_Reporting__c ();
        benrep1.Project_ID__c = project.id;
        benrep1.Benefit_ID__c = benifit.id;
        benrep1.Benefit_Condition__c = 'Planned';
        benrep1.Quarters__c = 'Q1';                           
        benrep1.Years__c = '2014';  
        benrep1.Benefit_Savings_Amount__c = 100;   
        insert benrep1; 
        
        GenericHistoryComponentController ghcc = new GenericHistoryComponentController();        
        ghcc.myObject = benifit;
        ghcc.recordLimit = 5;
        ghcc.getObjectHistory();
        ghcc.gotolist();
    } */
    
    static testmethod void GenericHistoryComponentController_2(){ 
    	QIPP_Benefit__c[] benifit ;
        QIPP_Project__c[] projectinfo;
        projectinfo = [select id, Name,Project_Name_Succinct__c from QIPP_Project__c where Project_Name_Succinct__c ='qipp history test' limit 1];          
        if(projectinfo.size()>0){
       		benifit = [select ID ,Project_ID__c,Improvement_Measure_KPI__c,Benefit_Type__c,Improvement_Measure_Name__c from QIPP_Benefit__c where Project_ID__c = :projectinfo[0].id limit 1];
    	}
        if(benifit == null){
            benifit = [select ID ,Improvement_Measure_KPI__c,Benefit_Type__c,Improvement_Measure_Name__c from QIPP_Benefit__c limit 1];
        }
        GenericHistoryComponentController ghcc = new GenericHistoryComponentController();        
        ghcc.myObject = benifit[0];
        ghcc.recordLimit = 5;
        ghcc.getObjectHistory();
        ghcc.gotolist();
    }
    
    static testmethod void QIPP_Benefit_Report_History_Cntr_v2_1(){ 
    	QIPP_BU_Reporting__c[] benifitrep ;
        QIPP_Project__c[] projectinfo;
        list<id> ids = new list<id>();
        projectinfo = [select id, Name,Project_Name_Succinct__c from QIPP_Project__c where Project_Name_Succinct__c ='qipp history test' limit 1];          
        system.debug('projectinfo'+projectinfo);
        if(projectinfo.size()>0){
       		benifitrep = [select id ,Project_ID__c,History_Tracking_For_Initial_Line_Items__c from QIPP_BU_Reporting__c  where Project_ID__c =:projectinfo[0].id limit 5]; 
            system.debug('benifitrep 1 :'+benifitrep);
    	}
        if(benifitrep == null){
            benifitrep = [select id ,Project_ID__c,History_Tracking_For_Initial_Line_Items__c from QIPP_BU_Reporting__c limit 5]; 
            system.debug('benifitrep 2 :'+benifitrep);
        }
        if(benifitrep.size()>0){
            for(QIPP_BU_Reporting__c qbu :benifitrep){
                ids.add(qbu.id);
            }
        }
        QIPP_Benefit_Report_History_Cntr_v2 ghcc = new QIPP_Benefit_Report_History_Cntr_v2();        
        ghcc.myObjectids = ids;
        ghcc.QBR = benifitrep;
        ghcc.recordLimit = 10;
        ghcc.getObjectHistory();
        ghcc.Beginning();
        ghcc.Previous();
        ghcc.next();
        ghcc.end();
        ghcc.getDisablePrevious();
        ghcc.getDisableNext();
        ghcc.getTotal_size();
        ghcc.getPageNumber();
        ghcc.getTotalPages();
    }
}