src/objects/QIRS__c.object
<CustomObject>
    <description>This object is used for collecting the details of the stop shipment.</description>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <inlineHelpText>Delivery Stop if problem affects to customer deliveries. Quality alert if not</inlineHelpText>
        <label>Alert Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quality Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Stop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Owner1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Person responsible for driving actions</inlineHelpText>
        <label>Case Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Nokia QIRS,Nokia QIRS Admin</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>All Status names.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FF0000</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Master Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QIRS</label>
    <nameField>
        <displayFormat>QIRS-{000000}</displayFormat>
        <label>Record Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QIRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QIRS_Action_Plan__c.object
<CustomObject>
    <description>To create different types of action plans for QIRS record.</description>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <picklist>
            <picklistValues>
                <fullName>Containment/Temporal Solution</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Root Cause/Escape Point Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corrective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preventive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM44g</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43i</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM442</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM44C</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM44M</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43p</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43j</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM44W</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM44N</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <label>Approver</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Champion10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43Y</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43O</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion__c</fullName>
        <label>Champion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Comment__c</fullName>
        <label>Implementation Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Implementation_Date__c</fullName>
        <label>Implementation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QIRS__c</fullName>
        <label>QIRS</label>
        <referenceTo>QIRS__c</referenceTo>
        <relationshipLabel>Action Plan</relationshipLabel>
        <relationshipName>QIRS_Action_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason1__c</fullName>
        <label>Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Required_date__c</fullName>
        <label>Required date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Action Type Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FFFF66</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#78C953</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QIRS_Action_Plan</label>
    <nameField>
        <label>Action Plan Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QIRS_Action_Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QIRS_AP_PendingTask_Controller.cls
public class QIRS_AP_PendingTask_Controller {

    public String CurrentID1 {get; set;} 
    public String Type {get; set;} 
    public String QIRS_Action_plan_Tag {get; set;}
    public boolean Approve_Flag {get; set;}
    public boolean Reassign_Flag {get; set;}
    
    public QIRS_AP_PendingTask_Controller() 
    {
        Type = System.currentPagereference().getParameters().get('type');
        if(Type == 'ctask')
        {
            QIRS_Action_plan_Tag = 'Pending Tasks';
           Approve_Flag = true;
            Reassign_Flag = false;
        }
        else if(Type == 'atask')
        {
            QIRS_Action_plan_Tag = 'Task Analysis';
            Approve_Flag = true;
            Reassign_Flag = false;
        }
        else if(Type == 'dtask')
        {
            Approve_Flag = false;
            Reassign_Flag = true;
            QIRS_Action_plan_Tag = 'Delegate My Actions';        
        }
    }
    public List<QIRS_Action_Plan__c> getPendingTask() 
      {
          List<QIRS_Action_Plan__c> accpetedactionplanQirs = new List<QIRS_Action_Plan__c>();
          if(Type == 'ctask')
          {
                    accpetedactionplanQirs = [select Name,QIRS__r.Alert_Type__c,QIRS__r.Process_Owner1__c,Implementation_Comment__c,Implementation_Date__c,CreatedBy.Name, Action_Type__c,Approver__c,Champion__c
                   ,QIRS__c,Reason1__c,Required_date__c,Status__c from QIRS_Action_Plan__c where 
                    ( Champion1__c =: UserInfo.getUserId() or Champion2__c =: UserInfo.getUserId() or
                    Champion3__c =: UserInfo.getUserId() or Champion4__c =: UserInfo.getUserId() or
                    Champion5__c =: UserInfo.getUserId() or Champion6__c =: UserInfo.getUserId() or
                    Champion7__c =: UserInfo.getUserId() or Champion8__c =: UserInfo.getUserId() or
                    Champion9__c =: UserInfo.getUserId() or Champion10__c =: UserInfo.getUserId() )
                    and Status__c =: QIRSBasecontroller.BaseVarPendingforChampion
                    order by Name desc];
          }                
          else if(Type == 'atask')
          {
                    accpetedactionplanQirs = [select Name, QIRS__r.Alert_Type__c,QIRS__r.Process_Owner1__c,Implementation_Comment__c,Implementation_Date__c,CreatedBy.Name,Action_Type__c,Approver__c,Champion__c
                   ,QIRS__c,Reason1__c,Required_date__c,Status__c from QIRS_Action_Plan__c where 
                    ( Approver1__c =: UserInfo.getUserId() or Approver2__c =: UserInfo.getUserId() or
                    Approver3__c =: UserInfo.getUserId() or Approver4__c =: UserInfo.getUserId() or
                    Approver5__c =: UserInfo.getUserId() or Approver6__c =: UserInfo.getUserId() or
                    Approver7__c =: UserInfo.getUserId() or Approver8__c =: UserInfo.getUserId() or
                    Approver9__c =: UserInfo.getUserId() or Approver10__c =: UserInfo.getUserId() 
                    ) 
                    and Status__c =: QIRSBasecontroller.BaseVarImplementedbyChampion order by Name desc];
          }
          else if(Type == 'dtask')
          {
                    accpetedactionplanQirs = [select Name, QIRS__r.Alert_Type__c,QIRS__r.Process_Owner1__c,Implementation_Comment__c,Implementation_Date__c,CreatedBy.Name,Action_Type__c,Approver__c,Champion__c
                   ,QIRS__c,Reason1__c,Required_date__c,Status__c from QIRS_Action_Plan__c where 
                    ( Approver1__c =: UserInfo.getUserId() or Approver2__c =: UserInfo.getUserId() or
                    Approver3__c =: UserInfo.getUserId() or Approver4__c =: UserInfo.getUserId() or
                    Approver5__c =: UserInfo.getUserId() or Approver6__c =: UserInfo.getUserId() or
                    Approver7__c =: UserInfo.getUserId() or Approver8__c =: UserInfo.getUserId() or
                    Approver9__c =: UserInfo.getUserId() or Approver10__c =: UserInfo.getUserId() or
                    Champion1__c =: UserInfo.getUserId() or Champion2__c =: UserInfo.getUserId() or
                    Champion3__c =: UserInfo.getUserId() or Champion4__c =: UserInfo.getUserId() or
                    Champion5__c =: UserInfo.getUserId() or Champion6__c =: UserInfo.getUserId() or
                    Champion7__c =: UserInfo.getUserId() or Champion8__c =: UserInfo.getUserId() or
                    Champion9__c =: UserInfo.getUserId() or Champion10__c =: UserInfo.getUserId() ) 
                    and (Status__c =: QIRSBasecontroller.BaseVarImplementedbyChampion or
                    Status__c =: QIRSBasecontroller.BaseVarPendingforChampion) order by Name desc];
          }
          return accpetedactionplanQirs ;
      }
 public PageReference Reassign()
    {
        String strid = System.currentPagereference().getParameters().get('LQ2');
        PageReference pageRef = new PageReference('/apex/QIRS_Reassigned?id='+strid+'&type='+Type);
        return pageRef;
    }
    public PageReference ApprRej() 
    {
        String id = System.currentPagereference().getParameters().get('LQ1');
        String qirsid = System.currentPagereference().getParameters().get('qirsid');        
         if(Type == 'ctask')
        {
            //String partialURL = '/apex/QIRS_AP_Implement?id=' + id;
            String partialURL = '/apex/QIRS_AP_Implement_test?id=' + id;            
            PageReference pageRef = new PageReference(partialURL);
            pageRef.setRedirect(true);
            return pageRef;
        }
        else
        {
           
            List<ProcessInstanceWorkItem> workItemList =
             [Select p.ProcessInstance.Status, p.ProcessInstance.TargetObjectId,p.ProcessInstanceId
             ,p.OriginalActorId,p.Id,p.ActorId From ProcessInstanceWorkitem p
              where p.ProcessInstance.TargetObjectId = :id and (p.OriginalActorId =: UserInfo.getUserId() or p.ActorId =: UserInfo.getUserId())];
            if(workItemList.size()>0)
            {
            String strAppId = workItemList[0].Id;
            String partialURL = '/p/process/ProcessInstanceWorkitemWizardStageManager?id=' + strAppId+ '&retURL=' +qirsid;
            PageReference pageRef = new PageReference(partialURL);
            pageRef.setRedirect(true);
            return pageRef;
            }
            else
            {
            String partialURL = '/apex/QIRS_AP_AppRjt?id=' + id;            
            PageReference pageRef = new PageReference(partialURL);
            pageRef.setRedirect(true);
            return pageRef;
            }
         }
        return null;
    }
      static testMethod void testQIRS_AP_PendingTask_Controller()
     {
       QIRS_AP_PendingTask_Controller controller = new QIRS_AP_PendingTask_Controller();
       controller.CurrentID1 ='a0GZ0000000Bwm9';
       controller.Type = ApexPages.currentPage().getParameters().put('type', 'ctask');
      
       
       controller.QIRS_Action_plan_Tag ='Pending Tasks';
       controller.Approve_Flag=true;
       controller.Reassign_Flag=false;

     
       
       controller.Type ='ctask';
        controller.getPendingTask(); 
       controller.Type ='atask';
        controller.getPendingTask();         
        controller.Type ='dtask';
        controller.getPendingTask(); 
       ApexPages.currentPage().getParameters().put('LQ2', '005Z0000000Hnsp');
        controller.Reassign();
       controller.Type ='ctask';
       ApexPages.currentPage().getParameters().put('LQ1', 'a0GZ0000000Bwm9');
       ApexPages.currentPage().getParameters().put('qirsid', '005Z0000000Hnsp');      
                controller.ApprRej();
controller.Type ='dtask';
       ApexPages.currentPage().getParameters().put('LQ1', 'a0GZ0000000Bwm9');
       ApexPages.currentPage().getParameters().put('qirsid', '005Z0000000Hnsp');      
                controller.ApprRej();
     }
}