src/objects/QIRS__c.object
<CustomObject>
    <description>This object is used for collecting the details of the stop shipment.</description>
    <fields>
        <fullName>Case_Name__c</fullName>
        <inlineHelpText>Descriptive Name of the case</inlineHelpText>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Approver10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Approver10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRSM4Ha</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Approver1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Approver2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Approver3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Approver3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Approver4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Approver4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Approver5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Approver5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Approver6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Approver6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Approver7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Approver7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Approver8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Approver8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Approver9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Approver9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRSM4HQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Process_Owner1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Person responsible for driving actions</inlineHelpText>
        <label>Case Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Nokia QIRS,Nokia QIRS Admin</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_PN__c</fullName>
        <label>Product PN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RejectedFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RejectedFlag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StatusColor__c</fullName>
        <formula>IF( ISPICKVAL(Status__c,&quot;Open&quot;) ,&quot;red&quot;,IF( ISPICKVAL(Status__c,&quot;Closed&quot;) ,&quot;YellowGreen &quot;, 
IF( ISPICKVAL(Status__c,&quot;Released&quot;) ,&quot;Yellow&quot;,
IF( ISPICKVAL(Status__c,&quot;Submitted to Master Approval&quot;) ,&quot;Orange&quot;,
&quot;Pink&quot;))))</formula>
        <label>StatusColor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>All Status names.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FF0000</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Master Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>View_AP_Color__c</fullName>
        <label>View AP Color</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>QIRS</label>
    <nameField>
        <displayFormat>QIRS-{000000}</displayFormat>
        <label>Record Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QIRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QIRS_Action_Plan__c.object
<CustomObject>
    <description>To create different types of action plans for QIRS record.</description>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <picklist>
            <picklistValues>
                <fullName>Containment/Temporal Solution</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Root Cause/Escape Point Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corrective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preventive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM44g</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43i</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43s</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM442</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM44C</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM44M</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43p</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43j</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM44W</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM44N</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion10__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion10</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43Y</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion6__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion6</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion7__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion7</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion8__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion8</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Champion9__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Champion9</label>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_PlanM43O</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QIRS__c</fullName>
        <label>QIRS</label>
        <referenceTo>QIRS__c</referenceTo>
        <relationshipLabel>Action Plan</relationshipLabel>
        <relationshipName>QIRS_Action_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>StatusColor__c</fullName>
        <formula>IF( ISPICKVAL(Status__c,&quot;Open&quot;) ,&quot;Yellow&quot;,IF( ISPICKVAL(Status__c,&quot;No Action&quot;) ,&quot;Red &quot;, IF( ISPICKVAL(Status__c,&quot;Rejected&quot;),&quot;Pink&quot;, IF( ISPICKVAL(Status__c,&quot;Pending for Champion&quot;),&quot;LightBlue&quot;,IF( ISPICKVAL(Status__c,&quot;Implemented by champion&quot;),&quot;LightGray&quot;,IF( ISPICKVAL(Status__c,&quot;Accepted by Champion&quot;),&quot;LightGreen&quot;, IF( ISPICKVAL(Status__c,&quot;Closed&quot;) ,&quot;Green&quot;,&quot;white&quot;)))))))</formula>
        <label>StatusColor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Action Type Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FFFF66</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#78C953</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QIRS_Action_Plan</label>
    <nameField>
        <label>Action Plan Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QIRS_Action_Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QIRS_Product_Identification__c.object
<CustomObject>
    <description>It will have product details like Technology, Group, Name, APC(account product code), catalog user.</description>
    <fields>
        <fullName>QIRS__c</fullName>
        <label>QIRS</label>
        <referenceTo>QIRS__c</referenceTo>
        <relationshipName>Product_Identification</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Release_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Release Product</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Identification</label>
    <nameField>
        <label>Product PN</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Identification</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QIRSHomeController.cls
public class QIRSHomeController {


   
            
   public QIRSHomeController()
     {
         integer Count =0;
         Count= [select Count() from QIRS_Action_Plan__c where 
          ( Champion1__c =: UserInfo.getUserId() or Champion2__c =: UserInfo.getUserId() or
                    Champion3__c =: UserInfo.getUserId() or Champion4__c =: UserInfo.getUserId() or
                    Champion5__c =: UserInfo.getUserId() or Champion6__c =: UserInfo.getUserId() or
                    Champion7__c =: UserInfo.getUserId() or Champion8__c =: UserInfo.getUserId() or
                    Champion9__c =: UserInfo.getUserId() or Champion10__c =: UserInfo.getUserId() )
          and Status__c = : 'Rejected'];
         TaskReview = String.ValueOf(Count);
         
          Count= [select Count() from QIRS_Action_Plan__c where 
                    ( Champion1__c =: UserInfo.getUserId() or Champion2__c =: UserInfo.getUserId() or
                    Champion3__c =: UserInfo.getUserId() or Champion4__c =: UserInfo.getUserId() or
                    Champion5__c =: UserInfo.getUserId() or Champion6__c =: UserInfo.getUserId() or
                    Champion7__c =: UserInfo.getUserId() or Champion8__c =: UserInfo.getUserId() or
                    Champion9__c =: UserInfo.getUserId() or Champion10__c =: UserInfo.getUserId() )
                    and Status__c =: QIRSBasecontroller.BaseVarPendingforChampion];
          Pendingtask = String.ValueOf(Count); 
          
          Count = [select Count() from QIRS_Action_Plan__c where 
                    ( Approver1__c =: UserInfo.getUserId() or Approver2__c =: UserInfo.getUserId() or
                    Approver3__c =: UserInfo.getUserId() or Approver4__c =: UserInfo.getUserId() or
                    Approver5__c =: UserInfo.getUserId() or Approver6__c =: UserInfo.getUserId() or
                    Approver7__c =: UserInfo.getUserId() or Approver8__c =: UserInfo.getUserId() or
                    Approver9__c =: UserInfo.getUserId() or Approver10__c =: UserInfo.getUserId() 
                    ) 
                    and Status__c =: QIRSBasecontroller.BaseVarImplementedbyChampion];         
             TaskAnalysis = String.ValueOf(Count);
             
              Count = [select  Count() from QIRS__c where 
              Process_Owner1__c =: UserInfo.getUserId() and RejectedFlag__c = true
              and Status__c =: QIRSBasecontroller.BaseVarQIRSLifted];
             MasterRejection =String.ValueOf(Count);
             
              Count = [select  Count() from QIRS__c where 
             ( Master_Approver1__c =: UserInfo.getUserId() or Master_Approver2__c =: UserInfo.getUserId() or
                    Master_Approver3__c =: UserInfo.getUserId() or Master_Approver4__c =: UserInfo.getUserId() or
                    Master_Approver5__c =: UserInfo.getUserId() or Master_Approver6__c =: UserInfo.getUserId() or
                    Master_Approver7__c =: UserInfo.getUserId() or Master_Approver8__c =: UserInfo.getUserId() or
                    Master_Approver9__c =: UserInfo.getUserId() or Master_Approver10__c =: UserInfo.getUserId() )
             and Status__c =: QIRSBasecontroller.BaseVarQIRSSubmitForApproval];
              MasterAnalysis = String.ValueOf(Count);
              
              string[] SelectedStatus =  new String[]{'Open','Pending for Champion','Implemented by Champion','Rejected'};
               Count = [select Count() from QIRS_Action_Plan__c where CreatedById =: UserInfo.getUserId() and Status__c In : SelectedStatus];
               SubmittedTasks = String.ValueOf(Count);
               Business = 'All';
               BusinessGroup='All';
               Sites = 'All';
               Alerttype = 'All';
               Status = 'All';
               ProcessOwner = 'All';
                     
     }
   

//    public  { get; set; }
    public String Business { get; set; }
    public String BusinessGroup {get; set;}
    public String Sites {get; set;}
    public String Alerttype {get; set;} 
    public String Status {get; set;} 
    public String ProcessOwner {get; set;}
    public String RecordCode { get; set; } 
    public String TaskReview { get; set; } 
    public String Pendingtask { get; set; } 
    public String TaskAnalysis { get; set; } 
    public String MasterAnalysis { get; set; }             
    public String SubmittedTasks{ get; set; }  
    public String MasterRejection{ get; set; } 
         
    public List<QIRS__c> lstQirs = new List<QIRS__c>();

               
    public List<SelectOption> getBusinessDD() 
    {
        return QIRSBasecontroller.getBusinessList(true);
    }
    public List<SelectOption> getBusinessGrpDD()
    {
        return QIRSBasecontroller.getBusinessGrpList();
    }
  
    public List<SelectOption> getSitesDD() 
    {
        return QIRSBasecontroller.getSitesList(true);
    }
    public List<SelectOption> getAlertTypesDD() 
    {
        return QIRSBasecontroller.getAlertTypesList(true);
    }

    public List<SelectOption> getStatusDD() 
    {
        return QIRSBasecontroller.getStatusList(true);
    }
            
    public List<SelectOption> getProcessOwnersDD()
    {
        return QIRSBasecontroller.getProcessOwnersList();        
    } 

       public List<QIRS__c> getshowQIRS() 
       {
            string bs = Business ;
            string bgrp = BusinessGroup ;
            string si = Sites ;
            string al = Alerttype;
            string st = Status ;
            string po = ProcessOwner ;
            string rc = RecordCode  ;
            String Closed = 'Closed';
            String Cancelled = 'Canceled';
            //String Closed = 'All';
            date myDate = date.today();
            date newDate = mydate.addDays(-14);
            // date newDate = mydate.addDays(0);
            //  String Closed = 'Closed';                                   
           String Query ='select Name,Case_Name__c,View_AP_Color__c,Product_PN__c,(select Release_Product__c,Name From Product_Identification__r), (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r),Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,StatusColor__c,Process_Owner1__c ,Issue_Level__c, Defective_Part__c, Symptom__c, CreatedDate, IssueLevelColor__c,View_Product_Name__c, Watchlist__c, MCAR__c, Closed_Date1__c from QIRS__c where ((Status__c =:Closed and Closed_Date1__c >=:newDate) Or (Status__c !=:Closed and Status__c !=:Cancelled))'; 
           //String Query ='select Name,View_AP_Color__c,Product_PN__c,(select Release_Product__c,Name From Product_Identification__r), (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r),Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,StatusColor__c,Process_Owner1__c ,Issue_Level__c, Defective_Part__c, Symptom__c, CreatedDate, IssueLevelColor__c,View_Product_Name__c, Watchlist__c, MCAR__c, Closed_Date1__c from QIRS__c where Status__c !=:Closed';            
        if(st != 'All')
          {
               Query =Query +' AND Status__c =: st';
          }
          if(al != 'All')
           Query = Query + ' AND Alert_Type__c =: al';  
          if(bgrp != 'All')           
            Query = Query + ' AND Business_Group__c INCLUDES(:bgrp)';    
             if(bs != 'All')
            Query = Query + ' AND Business__c =: bs';   
            
            if(si != 'All')
            Query = Query + ' AND Site1__c  INCLUDES(:si)'; 
            if(po != 'All')
            Query = Query + ' AND Process_Owner1__c =:po';             
           Query = Query +' Order by CreatedDate desc,Name desc';                           
            lstQirs  = Database.query(Query); 

         /*  String Query1 ='select Name,View_AP_Color__c,Product_PN__c,(select Release_Product__c,Name From Product_Identification__r), (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r),Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,StatusColor__c,Process_Owner1__c ,Issue_Level__c, Defective_Part__c, Symptom__c, CreatedDate, IssueLevelColor__c,View_Product_Name__c, Watchlist__c, MCAR__c, Closed_Date1__c from QIRS__c where Status__c !=: Closed'; 
        if(st != 'All')
          {
               Query1 =Query1 +' AND Status__c =: st';
          }
          if(al != 'All')
           Query1 = Query1 + ' AND Alert_Type__c =: al';  
          if(bgrp != 'All')           
            Query1 = Query1 + ' AND Business_Group__c =: bgrp';   
             if(bs != 'All')
            Query1 = Query1 + ' AND Business__c =: bs';   
            
            if(si != 'All')
            Query1 = Query1 + ' AND Site1__c  INCLUDES(:si)'; 
            if(po != 'All')
            Query1 = Query1 + ' AND Process_Owner1__c =:po';             
           Query1= Query1 +' Order by CreatedDate desc,Name desc';                           
            
           List<QIRS__c> lstQirs1  = Database.query(Query1); 
          for (Integer j=0;j<lstQirs1.size();j++)
          {
              lstQirs.add(lstQirs1[j]);
          }
           superSort.sortList(lstQirs,'Name','desc');*/
           
           
           
           lstQirs= QIRSBasecontroller.getAPColorCode(lstQirs);
                return  lstQirs;                      
     } 
     static testMethod void QIRSHomeController()
     {
      QIRSHomeController controller = new QIRSHomeController();
       controller.getBusinessDD();
        controller.getBusinessGrpDD();
        controller.getSitesDD();   
        controller.getAlertTypesDD();     
        controller.getStatusDD();             
        controller.getProcessOwnersDD();    

        controller.getshowQIRS();                   
                                 
     }     
        
}