src/objects/QIRS__c.object
<CustomObject>
    <description>This object is used for collecting the details of the stop shipment.</description>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <inlineHelpText>Delivery Stop if problem affects to customer deliveries. Quality alert if not</inlineHelpText>
        <label>Alert Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quality Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Stop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Group__c</fullName>
        <description>Business group pick list values.</description>
        <inlineHelpText>Business Line under Business Unit</inlineHelpText>
        <label>Business Line</label>
        <picklist>
            <picklistValues>
                <fullName>3G Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baseband Platform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud IMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud SDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HetRAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IoT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LTE-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LTE-N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF and Advanced Antennas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Cell and WiFi Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>X-Haul</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzBBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzCDMA/LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzCET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzCore Platforms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzDNW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzGlobal LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzGSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzMWT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzOptical Networks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzPacket Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzPacket Networks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzPerfect Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzRadio Platforms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzSmall Cell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzVIPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzWCDMA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <description>Business name pick list values.</description>
        <inlineHelpText>Nokia Business Unit</inlineHelpText>
        <label>Business</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced Mobile Network Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Networks Global Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Networks Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzCustomer Experience Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzGlobal Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzMobile Broadband</fullName>
                <default>true</default>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Closed_Date1__c</fullName>
        <label>Closed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimated_close_date__c</fullName>
        <description>Date to have the stop shipment closed (process and products released).</description>
        <inlineHelpText>Enter estimated close date for this record</inlineHelpText>
        <label>Estimated close date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lock_Points_SH_Shipping__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field to determine the sub-process that must be locked.</description>
        <inlineHelpText>Select Shipping</inlineHelpText>
        <label>Shipping</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MCAR__c</fullName>
        <inlineHelpText>Only numeric value</inlineHelpText>
        <label>MCAR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Problem_Description1__c</fullName>
        <label>Problem Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_to_Stop__c</fullName>
        <formula>&apos;Shipping (&apos;+ Site_Filter__c +&apos;)&apos;</formula>
        <label>Process to Stop</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_PN__c</fullName>
        <label>Product PN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusColor__c</fullName>
        <formula>IF( ISPICKVAL(Status__c,&quot;Open&quot;) ,&quot;red&quot;,IF( ISPICKVAL(Status__c,&quot;Closed&quot;) ,&quot;YellowGreen &quot;, 
IF( ISPICKVAL(Status__c,&quot;Released&quot;) ,&quot;Yellow&quot;,
IF( ISPICKVAL(Status__c,&quot;Submitted to Master Approval&quot;) ,&quot;Orange&quot;,
&quot;Pink&quot;))))</formula>
        <label>StatusColor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>All Status names.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FF0000</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Master Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>View_Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>View_Release_Product__c</fullName>
        <label>View Release Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>QIRS</label>
    <nameField>
        <displayFormat>QIRS-{000000}</displayFormat>
        <label>Record Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QIRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QIRS_Action_Plan__c.object
<CustomObject>
    <description>To create different types of action plans for QIRS record.</description>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <picklist>
            <picklistValues>
                <fullName>Containment/Temporal Solution</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Root Cause/Escape Point Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corrective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preventive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QIRS__c</fullName>
        <label>QIRS</label>
        <referenceTo>QIRS__c</referenceTo>
        <relationshipLabel>Action Plan</relationshipLabel>
        <relationshipName>QIRS_Action_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reassign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reassign</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Nokia QIRS, Nokia QIRS Admin</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS_Action_Plan</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StatusColor__c</fullName>
        <formula>IF( ISPICKVAL(Status__c,&quot;Open&quot;) ,&quot;Yellow&quot;,IF( ISPICKVAL(Status__c,&quot;No Action&quot;) ,&quot;Red &quot;, IF( ISPICKVAL(Status__c,&quot;Rejected&quot;),&quot;Pink&quot;, IF( ISPICKVAL(Status__c,&quot;Pending for Champion&quot;),&quot;LightBlue&quot;,IF( ISPICKVAL(Status__c,&quot;Implemented by champion&quot;),&quot;LightGray&quot;,IF( ISPICKVAL(Status__c,&quot;Accepted by Champion&quot;),&quot;LightGreen&quot;, IF( ISPICKVAL(Status__c,&quot;Closed&quot;) ,&quot;Green&quot;,&quot;white&quot;)))))))</formula>
        <label>StatusColor</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Action Type Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FFFF66</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#78C953</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QIRS_Action_Plan</label>
    <nameField>
        <label>Action Plan Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QIRS_Action_Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QIRSRecordsController.cls
public class QIRSRecordsController {
  public QIRSRecordsController()
     {
            
             
     }
    public QIRSRecordsController(ApexPages.StandardController controller) {

    }
    
    
    
    public String Stop_Ship_Code {get; set;}
    public date myDate = date.today();
    public date newDate = mydate.addDays(-14);
    public String Status {get; set;} 
         
    public List<SelectOption> getItem() 
    {
        return QIRSBasecontroller.getStatusList(true);
    }
    List<User> users = new List<User>();
            
    
    public PageReference getPageDetails() 
    {
        List<QIRS__c> lstQirs = new List<QIRS__c>();
        if(Stop_Ship_Code == '' || Stop_Ship_Code == null)
        {
            if(Status == 'All' )
             {
                  lstQirs = [select Product_PN__c,MCAR__c,View_Product_Name__c,View_Release_Product__c, (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,CreatedDate,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where CreatedBy.ManagerID  =:  UserInfo.getUserId() AND (Status__c != 'Closed' OR Closed_Date1__c >:newDate) order by CreatedDate desc];                                     
             }
           else
             {
                if(Status == 'Closed')
                    lstQirs = [select Product_PN__c,MCAR__c, View_Product_Name__c ,View_Release_Product__c, (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,CreatedDate ,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where Closed_Date1__c >:newDate and CreatedBy.ManagerID  =:  UserInfo.getUserId() order by CreatedDate desc];
                else
                    lstQirs = [select Product_PN__c,MCAR__c, View_Product_Name__c ,View_Release_Product__c, (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,CreatedDate ,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where Status__c =: Status and CreatedBy.ManagerID  =:  UserInfo.getUserId() order by CreatedDate desc];
             }
        }
        else
        {
            lstQirs = [select Product_PN__c,MCAR__c, View_Product_Name__c ,View_Release_Product__c,(Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,CreatedDate ,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c 
            from QIRS__c where CreatedBy.ManagerID  =:  UserInfo.getUserId() and Name =: Stop_Ship_Code AND (Status__c != 'Closed' OR Closed_Date1__c >:newDate)]; 
        }
        if(lstQirs.size()>0)        
        {
           PageReference pageRef = new PageReference('/' + lstQirs[0].id);
             pageRef.setRedirect(true);
             return pageRef; 
        }
        else
        {
            return null;
        }
    }
    
    public List<QIRS__c> getshowQIRS() 
                {
        
                string st = Status ;
               
                List<QIRS__c> lstQirs = new List<QIRS__c>();
                                                             
                   if(st != null )
                   {
                           if(st == 'All' )
                             {
                                    if( Stop_Ship_Code == '' ||  Stop_Ship_Code == null)
                                    {
                                         lstQirs = [select Product_PN__c,View_AP_Color__c, MCAR__c, View_Product_Name__c ,View_Release_Product__c, (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,CreatedDate,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where CreatedBy.ManagerID  =:  UserInfo.getUserId() AND (Status__c != 'Closed' OR Closed_Date1__c >:newDate) order by CreatedDate desc];                                     
                                    }
                                    else
                                    {
                                         lstQirs = [select Product_PN__c,View_AP_Color__c, MCAR__c, View_Product_Name__c ,View_Release_Product__c, (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,CreatedDate,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where CreatedBy.ManagerID  =:  UserInfo.getUserId() and Name =: Stop_Ship_Code AND (Status__c != 'Closed' OR Closed_Date1__c >:newDate) order by CreatedDate desc];                                                                         
                                    }
                             }
                           else
                             {
                                if(st == 'Closed')
                                {
                                    if(Stop_Ship_Code == '' ||  Stop_Ship_Code == null)
                                    {
                                        lstQirs = [select Product_PN__c,View_AP_Color__c, MCAR__c, View_Product_Name__c ,View_Release_Product__c, (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,CreatedDate ,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where Closed_Date1__c >:newDate and CreatedBy.ManagerID  =:  UserInfo.getUserId() order by CreatedDate desc];
                                    }
                                    else
                                    {
                                        lstQirs = [select Product_PN__c,View_AP_Color__c, MCAR__c, View_Product_Name__c ,View_Release_Product__c, (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,CreatedDate ,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where Closed_Date1__c >:newDate and CreatedBy.ManagerID  =:  UserInfo.getUserId() and Name =: Stop_Ship_Code order by CreatedDate desc];                                    
                                    }
                                }
                                else
                                {
                                    if(Stop_Ship_Code == '' ||  Stop_Ship_Code == null)
                                    {
                                        lstQirs = [select Product_PN__c,View_AP_Color__c, MCAR__c, View_Product_Name__c ,View_Release_Product__c, (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,CreatedDate ,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where Status__c =: st and CreatedBy.ManagerID  =:  UserInfo.getUserId() order by CreatedDate desc];
                                    }
                                    else
                                    {
                                        lstQirs = [select Product_PN__c,View_AP_Color__c, MCAR__c, View_Product_Name__c ,View_Release_Product__c, (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,CreatedDate ,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where Status__c =: st and CreatedBy.ManagerID  =:  UserInfo.getUserId() and Name =: Stop_Ship_Code order by CreatedDate desc];                                    
                                    }
                                }
                             }
                   }
        
               else
                 {
                     st = 'All';
                      if(Stop_Ship_Code == '' ||  Stop_Ship_Code == null)
                      {
                             lstQirs = [select Product_PN__c,View_AP_Color__c, CreatedDate ,MCAR__c, View_Product_Name__c ,View_Release_Product__c, (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where (Status__c != 'Closed' OR Closed_Date1__c >:newDate) and CreatedBy.ManagerID  =:  UserInfo.getUserId() order by CreatedDate desc];     
                      }
                      else
                      {
                             lstQirs = [select Product_PN__c,View_AP_Color__c,CreatedDate ,MCAR__c,View_Product_Name__c ,  (Select id,Name,Status__c,StatusColor__c,Action_Type__c From QIRS_Action_Plan__r), Closed_Date1__c, Process_to_Stop__c, Estimated_close_date__c, CreatedBy.Name, Problem_Description1__c, Lock_Points_SH_Shipping__c,Name, Business__c, Alert_Type__c,Business_Group__c,Site1__c,Status__c,Process_Owner1__c from QIRS__c where CreatedBy.ManagerID  =:  UserInfo.getUserId() and Name =: Stop_Ship_Code AND (Status__c != 'Closed' OR Closed_Date1__c >:newDate) order by CreatedDate desc];                                   
                      }
                 }
                  lstQirs= QIRSBasecontroller.getAPColorCode(lstQirs);
                  return  lstQirs;// QIRSBasecontroller.getProductName(lstQirs);
               }
}