src/objects/QIRS__c.object
<CustomObject>
    <description>This object is used for collecting the details of the stop shipment.</description>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <inlineHelpText>Delivery Stop if problem affects to customer deliveries. Quality alert if not</inlineHelpText>
        <label>Alert Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quality Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Stop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business_Group__c</fullName>
        <description>Business group pick list values.</description>
        <inlineHelpText>Business Line under Business Unit</inlineHelpText>
        <label>Business Line</label>
        <picklist>
            <picklistValues>
                <fullName>3G Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baseband Platform</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud IMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cloud SDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HetRAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IoT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LTE-A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LTE-N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF and Advanced Antennas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Cell and WiFi Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>X-Haul</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzBBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzCDMA/LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzCET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzCore Platforms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzDNW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzGlobal LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzGSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzMWT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzOptical Networks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzPacket Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzPacket Networks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzPerfect Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzRadio Platforms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzSmall Cell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzVIPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzWCDMA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <description>Business name pick list values.</description>
        <inlineHelpText>Nokia Business Unit</inlineHelpText>
        <label>Business</label>
        <picklist>
            <picklistValues>
                <fullName>Advanced Mobile Network Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Networks Global Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Networks Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzCustomer Experience Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzGlobal Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>zzMobile Broadband</fullName>
                <default>true</default>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <inlineHelpText>Descriptive Name of the case</inlineHelpText>
        <label>Case Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <inlineHelpText>Enter multiple customers by using a comma</inlineHelpText>
        <label>Customer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Factory__c</fullName>
        <description>Factory which is effected (can be many)</description>
        <inlineHelpText>Factory which is effected (can be many)</inlineHelpText>
        <label>Factory</label>
        <picklist>
            <picklistValues>
                <fullName>Celestica Sriracha, Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eu-Einea Eu, France</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flextronics Austin, US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flextronics Guadalajara North, Mexico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flextronics Ibaraki, Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flextronics Sorocaba, Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flextronics Tczew, Poland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flextronics Timisoara, Romania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flextronics Wuzhong, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foxconn Shanghai, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jabil Tianjin, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jabil T-town, Hungary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nokia Beijing, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nokia Berlin, Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nokia Chennai, India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nokia Oulu, Finland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nokia Shanghai, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nokia Suzhou, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSB Shanghai, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OMP, Italy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sanmina Carrolton, US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sanmina Chennai, India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sanmina Guadalajara, Mexico</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sanmina Haukipudas, Finland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sanmina Kunshan, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sanmina Miscolk, Hungary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sanmina Pathum Thani, Thailand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sanmina Quianjing, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sanmina Tatabanya, Hungary</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Issue_Level__c</fullName>
        <description>Severity of the created record.</description>
        <inlineHelpText>Management escalation means that the case must be communicated to OPS LT</inlineHelpText>
        <label>Issue Level</label>
        <picklist>
            <controllingField>Alert_Type__c</controllingField>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continue Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stop Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Launch Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiver Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production Stop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Problem_Description1__c</fullName>
        <label>Problem Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_Owner1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Person responsible for driving actions</inlineHelpText>
        <label>Case Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Nokia QIRS,Nokia QIRS Admin</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site1__c</fullName>
        <inlineHelpText>Enter the site that found the issue</inlineHelpText>
        <label>Site</label>
        <picklist>
            <picklistValues>
                <fullName>Aichi Japan (Flextronic)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alsdorf</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APW India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arden Hills (Celestica)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arlington Heights (IL75)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangkok (Benchmark)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beijing, China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berlin, Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Berlin CP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bruchsal, Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Celestica Czechia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ceragon Isreal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai, India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai (Flextronics)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chennai Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chihuahua (Foxconn)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Copenhagen (Denmark)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTS - Matamoras</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTS - TJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech (Foxconn)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dallas Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dongguan (Accton)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dongguan (Aztech)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doumen (Flextronics)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drop Ship Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dubai Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Düsseldorf, Germany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elcoteq Bangalore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elgin (After Market) - Illinois</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>QIRS</label>
    <nameField>
        <displayFormat>QIRS-{000000}</displayFormat>
        <label>Record Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QIRS</pluralLabel>
    <recordTypes>
        <fullName>Asia</fullName>
        <active>true</active>
        <label>Asia</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/QIRS_Create_Controller_test.cls
@istest
public class QIRS_Create_Controller_test 
{
	static testmethod void test()
    {
       List<String> strNSNQIRS =new List<String>();
         List<Profile> tempprofile = new List<Profile>(); 
         String[] Profile = new String[] {'Nokia QIRS Admin','Nokia QIRS'};
         tempprofile=[SELECT Id,Name from Profile where Name In : Profile];          
           for (Integer j=0;j<tempprofile.size();j++)
            {
              strNSNQIRS.add(tempprofile[j].Id);
            }
          
          List<User> userlist= new List<User>();
          userlist= [select Id,Name from User where 
           ProfileId In: strNSNQIRS and IsActive = true order by Name];   
        
        
                   QIRS__c objqirs = new QIRS__c();
        	objqirs.Case_Name__c = 'case 1';
           objqirs.Site1__c = 'Alsdorf';
           objqirs.Process_Owner1__c = userlist[0].Id;           
           objqirs.Business__c = 'zzGlobal Services';           
           objqirs.Business_Group__c = 'zzBBA';           
           objqirs.Alert_Type__c = 'Quality Alert';           
           objqirs.Issue_Level__c = 'Medium';                                            
             objqirs.Factory__c ='Nokia Berlin, Germany';
           objqirs.Problem_Description1__c = 'Networks Systems';           
           objqirs.Customer__c = 'CDMA';           
           objqirs.Defective_Part__c = 'Design';           
           objqirs.Symptom__c = 'Hardware';                                            
           objqirs.Projected_Lift_Date__c  =Date.today(); 
           objqirs.Estimated_close_date__c = Date.today();
                   objqirs.Impacted_Region__c = 'Asia Pacific';           
           objqirs.Countries__c = 'China';           
             insert objqirs;
         test.startTest();
         ApexPages.StandardController sc = new ApexPages.StandardController(objqirs);
         QIRS_Create_Controller controller = new  QIRS_Create_Controller(sc);
        test.stopTest();
        

        
    }
    static testmethod void test1()
    {
       List<String> strNSNQIRS =new List<String>();
         List<Profile> tempprofile = new List<Profile>(); 
         String[] Profile = new String[] {'Nokia QIRS Admin','Nokia QIRS'};
         tempprofile=[SELECT Id,Name from Profile where Name In : Profile];          
           for (Integer j=0;j<tempprofile.size();j++)
            {
              strNSNQIRS.add(tempprofile[j].Id);
            }
          
          List<User> userlist= new List<User>();
          userlist= [select Id,Name from User where 
           ProfileId In: strNSNQIRS and IsActive = true order by Name];   
        
        
                   QIRS__c objqirs = new QIRS__c();
        	objqirs.Case_Name__c = 'case 1';
          objqirs.Site1__c = 'Alsdorf';
           objqirs.Process_Owner1__c = userlist[0].Id;           
           objqirs.Business__c = 'zzGlobal Services';           
           objqirs.Business_Group__c = 'zzBBA';           
           objqirs.Alert_Type__c = 'Quality Alert';           
           objqirs.Issue_Level__c = 'Medium';                                            
             objqirs.Factory__c ='Nokia Berlin, Germany';
           objqirs.Problem_Description1__c = 'Networks Systems';           
           objqirs.Customer__c = 'CDMA';           
           objqirs.Defective_Part__c = 'Design';           
           objqirs.Symptom__c = 'Hardware';                                            
           objqirs.Projected_Lift_Date__c  =Date.today(); 
           objqirs.Estimated_close_date__c = Date.today();
                   objqirs.Impacted_Region__c = 'Asia Pacific';           
           objqirs.Countries__c = 'China';           
             //insert objqirs;
         test.startTest();
         ApexPages.StandardController sc = new ApexPages.StandardController(objqirs);
         QIRS_Create_Controller controller = new  QIRS_Create_Controller(sc);
        test.stopTest();        
    }
}