src/objects/QIRS__c.object
<CustomObject>
    <description>This object is used for collecting the details of the stop shipment.</description>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <inlineHelpText>Delivery Stop if problem affects to customer deliveries. Quality alert if not</inlineHelpText>
        <label>Alert Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quality Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Stop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Owner1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Person responsible for driving actions</inlineHelpText>
        <label>Case Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Nokia QIRS,Nokia QIRS Admin</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>All Status names.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FF0000</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Master Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QIRS</label>
    <nameField>
        <displayFormat>QIRS-{000000}</displayFormat>
        <label>Record Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QIRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QIRS_Action_Plan__c.object
<CustomObject>
    <description>To create different types of action plans for QIRS record.</description>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <picklist>
            <picklistValues>
                <fullName>Containment/Temporal Solution</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Root Cause/Escape Point Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corrective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preventive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <label>Approver</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Champion__c</fullName>
        <label>Champion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Comment__c</fullName>
        <label>Implementation Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Implementation_Date__c</fullName>
        <label>Implementation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QIRS__c</fullName>
        <label>QIRS</label>
        <referenceTo>QIRS__c</referenceTo>
        <relationshipLabel>Action Plan</relationshipLabel>
        <relationshipName>QIRS_Action_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason1__c</fullName>
        <label>Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Required_date__c</fullName>
        <label>Required date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Action Type Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FFFF66</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#78C953</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QIRS_Action_Plan</label>
    <nameField>
        <label>Action Plan Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QIRS_Action_Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QIRS_Admin_Profile__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to store QIRS Admin profile ID which is going to refer in code.</description>
    <fields>
        <fullName>QIRS_Admin_Profile_ID__c</fullName>
        <label>QIRS Admin Profile ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>QIRS Admin Profile</label>
</CustomObject>

src/classes/QIRS_AP_MA_PendingTask_Controller.cls
public with sharing class QIRS_AP_MA_PendingTask_Controller {
	public boolean isNokiaQIRSAdminprofileUser	{get;set;}
	public String actionPlanStatus				{get;set;}
	
	public QIRS_AP_MA_PendingTask_Controller(ApexPages.StandardController controller){
		isNokiaQIRSAdminprofileUser = false;
		actionPlanStatus = 'Open';
		QIRS_Admin_Profile__c qirsAdmProfile = QIRS_Admin_Profile__c.getValues('QIRSAdminProfileIDValue');
		isNokiaQIRSAdminprofileUser = UserInfo.getProfileId() == qirsAdmProfile.QIRS_Admin_Profile_ID__c;
	}
	
	public List<QIRS_Action_Plan__c> getOpenQIRSActionPlanForMA(){
		if(!isNokiaQIRSAdminprofileUser) return null;
		return [select Name,QIRS__r.Alert_Type__c,QIRS__r.Process_Owner1__c, Implementation_Comment__c,Implementation_Date__c,
					CreatedBy.Name,Action_Type__c, Approver__c,Champion__c,QIRS__c,Reason1__c,Required_date__c,Status__c 
				from QIRS_Action_Plan__c 
				where Status__c =: actionPlanStatus and Action_Type__c =: 'Containment/Temporal Solution' order by Name desc];
	}
	
	public list<SelectOption> getMA_APStatus(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Open','Open'));
        options.add(new SelectOption('Closed','Closed'));
        return options;
    }
}