src/objects/QIRS__c.object
<CustomObject>
    <description>This object is used for collecting the details of the stop shipment.</description>
    <fields>
        <fullName>Alert_Type__c</fullName>
        <inlineHelpText>Delivery Stop if problem affects to customer deliveries. Quality alert if not</inlineHelpText>
        <label>Alert Type</label>
        <picklist>
            <picklistValues>
                <fullName>Quality Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Stop</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Process_Owner1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Person responsible for driving actions</inlineHelpText>
        <label>Case Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>Nokia QIRS,Nokia QIRS Admin</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>QIRS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>All Status names.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#B6E32E</color>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FF0000</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Master Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QIRS</label>
    <nameField>
        <displayFormat>QIRS-{000000}</displayFormat>
        <label>Record Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QIRS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QIRS_Action_Plan__c.object
<CustomObject>
    <description>To create different types of action plans for QIRS record.</description>
    <fields>
        <fullName>Action_Type__c</fullName>
        <label>Action Type</label>
        <picklist>
            <picklistValues>
                <fullName>Containment/Temporal Solution</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Root Cause/Escape Point Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corrective</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preventive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <label>Approver</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Champion__c</fullName>
        <label>Champion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Comment__c</fullName>
        <label>Implementation Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Implementation_Date__c</fullName>
        <label>Implementation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QIRS__c</fullName>
        <label>QIRS</label>
        <referenceTo>QIRS__c</referenceTo>
        <relationshipLabel>Action Plan</relationshipLabel>
        <relationshipName>QIRS_Action_Plan</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reason1__c</fullName>
        <label>Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Required_date__c</fullName>
        <label>Required date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Action Type Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FFFF66</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
                <color>#78C953</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>QIRS_Action_Plan</label>
    <nameField>
        <label>Action Plan Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QIRS_Action_Plan</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QIRS_Action_Plan_Submition_Controller.cls
public class QIRS_Action_Plan_Submition_Controller {
	public String QIRS_Action_plan_Tag {get; set;}
	public String QIRS_Action_plan_Status {get; set;}
	public boolean QIRS_Action_plan_Flag {get; set;}
	public string[] SelectedStatus{get;set;}
	public String Type {get; set;}
    
    public QIRS_Action_Plan_Submition_Controller(ApexPages.StandardController controller){
    	Type = System.currentPagereference().getParameters().get('type');
        if(Type == 'stask'){
			QIRS_Action_plan_Tag = 'Submitted tasks';
            QIRS_Action_plan_Flag = true;
            SelectedStatus = new String[]{'Open','Rejected'}; 
		}
        QIRS_Action_plan_Status ='Pending';
    }
     
	public List<QIRS_Action_Plan__c> getshowQIRSActionPlan(){
		String st = QIRS_Action_plan_Status;
    	list<QIRS_Action_Plan__c> lstQirs = new list<QIRS_Action_Plan__c>();
		if(Type == 'stask'){
			if(st == 'Pending'){
				lstQirs= [select Name,QIRS__r.Alert_Type__c,QIRS__r.Process_Owner1__c, Implementation_Comment__c,Implementation_Date__c,
							CreatedBy.Name,Action_Type__c, Approver__c,Champion__c,QIRS__c,Reason1__c,Required_date__c,Status__c 
							from QIRS_Action_Plan__c 
							where CreatedById =: UserInfo.getUserId() and Status__c In : SelectedStatus order by Name desc];
			}else{
				lstQirs= [select Name,QIRS__r.Alert_Type__c,QIRS__r.Process_Owner1__c, Implementation_Comment__c,Implementation_Date__c,
							CreatedBy.Name,Action_Type__c,Approver__c,Champion__c,QIRS__c,Reason1__c,Required_date__c,Status__c 
							from QIRS_Action_Plan__c 
							where CreatedById =: UserInfo.getUserId() and Status__c =: 'Closed' order by Name desc];
			}
		}
		return lstQirs;
	}
	
	public List<SelectOption> getQIRS_Action_plan_Item(){
	        return QIRSBasecontroller.getAPStatus();
	}
}