src/objects/SPE2_LanguageList__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains list of languages</description>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE2_LanguageList</label>
</CustomObject>

src/objects/SPE_SurveyAnswer__c.object
<CustomObject>
    <description>For each Survey Question this object defines multiple Answers. The Answers have different types (Ex. Free text, Picklist, single answer etc.).</description>
    <fields>
        <fullName>Choices__c</fullName>
        <description>Choices for the particular question.</description>
        <inlineHelpText>User can have choices for a particular question.</inlineHelpText>
        <label>Choices</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderNumber__c</fullName>
        <description>To show answers in order.</description>
        <inlineHelpText>To show answers in order.</inlineHelpText>
        <label>Order Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PrimarySurvey_Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PrimarySurvey Answer</label>
        <referenceTo>SPE_SurveyAnswer__c</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Survey_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>Based on the answer it will update the Score.</description>
        <inlineHelpText>Based on users answer it will update the Score.</inlineHelpText>
        <label>Values</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Secondary_Language__c</fullName>
        <description>To store secondary Language</description>
        <label>Secondary Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <description>Automatically captures Questions while creating answers under Question Object.</description>
        <inlineHelpText>User can select questions for which they are creating answers.</inlineHelpText>
        <label>SurveyQuestion</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipName>SPE_SurveyAnswers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>Ans-{00000}</displayFormat>
        <label>Answers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_SurveyQuestion__c.object
<CustomObject>
    <customHelpPage>SPE_QuestionBank_Survey_Help_Page</customHelpPage>
    <description>SurveyQuestion object contains Question banks for the survey.</description>
    <fields>
        <fullName>AnswerType__c</fullName>
        <description>Answer type is required to base on Questions</description>
        <inlineHelpText>Select appropriate type of answer</inlineHelpText>
        <label>Answer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Picklist</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Free Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checkbox is TRUE to show question on survey page.</description>
        <inlineHelpText>It will show question on survey page if it is true</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>In order to make question required.</description>
        <inlineHelpText>To show whether question required .</inlineHelpText>
        <label>Is Required ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Translated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Alternate Language</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaxScore__c</fullName>
        <label>Max Score</label>
        <summaryForeignKey>SPE_SurveyAnswer__c.SurveyQuestion__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PIData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Data</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>Question Bank</relationshipLabel>
        <relationshipName>Question_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Survey_Question__c</fullName>
        <label>Parent Survey Question</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>QuestionLabel__c</fullName>
        <label>Question Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Question Bank</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipLabel>Alternate Language Question Bank</relationshipLabel>
        <relationshipName>Question_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Language__c</fullName>
        <label>Alternate Language</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <description>Question which will appear on Survey page</description>
        <inlineHelpText>Enter your question</inlineHelpText>
        <label>Survey Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question Bank</label>
    <nameField>
        <label>Questions ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE2_translateSurveyQuestionController.cls
public class SPE2_translateSurveyQuestionController {
    
    public string selectedValue {get;set;}
    public List<SelectOption> statusOptions {get;set;}
    public boolean showOption {get;set;}
    public boolean showquestion {get;set;}
    public boolean abc{get;set;}
    public id questionId {get;set;}
    public list<ansWrapperCls> listansWrapperCls {get;set;}
    Private List<SPE2_LanguageList__c> languages;
    
    /*
    objects question and answer retrieved for translation
    */
        public SPE_SurveyQuestion__c qestionTransReq {get;set;}
        public list<SPE_SurveyAnswer__c> answerTransreq {get;set;}
    
    /*
    objects Question and answers are stored after translation
    */
        public SPE_SurveyQuestion__c translatedQuestion {get;set;}
        public list<SPE_SurveyAnswer__c> translatedAnswers{get;set;}
   
    /*
    Question already translated
    */
        public SPE_SurveyQuestion__c presenttranslatedQuestion {get;set;}
        public list<SPE_SurveyAnswer__c> presenttranslatedAnswers {get;set;}


public SPE2_translateSurveyQuestionController(ApexPages.StandardController st) {
           
            showquestion =false;
            abc=false;
            listansWrapperCls= new list<ansWrapperCls>();
            
            
            questionId= st.getId();
            
            translatedQuestion= new SPE_SurveyQuestion__c();
            translatedAnswers=new List<SPE_SurveyAnswer__c>();
            //Question and Answers Need to be transalted
            qestionTransReq= [select id,QuestionLabel__c, name,SurveyQuestion__c,AnswerType__c,IsActive__c,MaxScore__c,IsRequired__c,
                                                           Question_Bank__c ,PIData__c,Is_Translated__c,Parent_Survey_Question__c  from SPE_SurveyQuestion__c where id=:questionId];
            system.debug('test tran'+qestionTransReq.Is_Translated__c);
            //if(qestionTransReq.Is_Translated__c!=true){
            showOption =true;
            answerTransreq= [select id,Choices__c,OrderNumber__c,Score__c from SPE_SurveyAnswer__c where SurveyQuestion__c=:questionId];
            
            
            //listansWrapperCls.add(answerTransreq);
           //section for populating the Language field.
            statusOptions = new list<SelectOption>();
            languages =SPE2_LanguageList__c.getall().values();
            languages.sort();
            for(SPE2_LanguageList__c lang : languages ){
                 statusOptions.add(new SelectOption(lang.Name,lang.Language__c));    
            }
            
            /*    Schema.DescribeFieldResult fieldResult = User.LanguageLocaleKey.getDescribe();
                    for (Schema.PicklistEntry picklistEntry : fieldResult.getPicklistValues()){
                    if(pickListEntry.getLabel() != 'English')
                        statusOptions.add(new SelectOption(pickListEntry.getLabel(),pickListEntry.getLabel()));
                }*/
             //}   
   /*else{
       ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: This is a translated Question');
            ApexPages.addMessage(myMsg);
       }*/       
    }
    
    
    
    
  public void Next() {
       showOption =false;
       showquestion =true;
       presenttranslatedQuestion =new SPE_SurveyQuestion__c();
       presenttranslatedAnswers= new list<SPE_SurveyAnswer__c>();
                   try{
                           presenttranslatedQuestion = [select id,QuestionLabel__c, name,SurveyQuestion__c,AnswerType__c,IsRequired__c,IsActive__c,MaxScore__c,
                                                       PIData__c,Parent_Survey_Question__c  from SPE_SurveyQuestion__c where Question_Bank__c=:questionId 
                                                       AND Secondary_Language__c=: selectedValue];
                       }
                   catch(Exception e){
                       presenttranslatedQuestion = null;
                   }
            
                        if(presenttranslatedQuestion!=NULL)
                            {
                               abc=true;
                               presenttranslatedAnswers= [select id,Choices__c,OrderNumber__c,Score__c,PrimarySurvey_Answer__c,
                                                          PrimarySurvey_Answer__r.Choices__c,PrimarySurvey_Answer__r.Score__c
                                                          From SPE_SurveyAnswer__c Where SurveyQuestion__c=:presenttranslatedQuestion.id];
                               if(presenttranslatedAnswers.size()>0){
                                  
                                       for(SPE_SurveyAnswer__c testvariable :presenttranslatedAnswers)
                                       {
                                            ansWrapperCls aa = new ansWrapperCls();
                                            aa.answerID=testvariable.id;
                                            aa.AnswerChoices = testvariable.PrimarySurvey_Answer__r.Choices__c;
                                            aa.AnswerValue =  testvariable.PrimarySurvey_Answer__r.Score__c;
                                            aa.SecondaryChoices=testvariable.Choices__c;
                                            aa.primaryAnswerId = testvariable.id;
                                            listansWrapperCls.add(aa);
                                       }
                                }
                                system.debug('enter at 91'+presenttranslatedAnswers);
                            }
                            else
                             {
                               system.debug('Test Else part'+answerTransreq);
                                   for(SPE_SurveyAnswer__c testvariable :answerTransreq)
                                   {
                                        ansWrapperCls aa = new ansWrapperCls();
                                        aa.AnswerChoices = testvariable.Choices__c;
                                        aa.AnswerValue =  testvariable.Score__c;
                                        aa.primaryAnswerId = testvariable.id;
                                        listansWrapperCls.add(aa);
                                    }
                               }    
                
            }
    
    public pageReference save()
        {
        if(abc==true){
            
            presenttranslatedQuestion.Is_Translated__c=true;
            update presenttranslatedQuestion; 
            //update listansWrapperCls;
            //update presenttranslatedAnswers;
            for(ansWrapperCls listoftranslatedanswers : listansWrapperCls ){
                      SPE_SurveyAnswer__c Translateans= new SPE_SurveyAnswer__c();
                       Translateans.id=listoftranslatedanswers.answerID;
                       Translateans.Choices__c= listoftranslatedanswers.SecondaryChoices;
                       Translateans.Secondary_Language__c=selectedValue;
                       Translateans.Score__c=listoftranslatedanswers.AnswerValue;
                       translatedAnswers.add(Translateans);
                }
             update translatedAnswers;  
            //PageReference pgref = new PageReference('/' + presenttranslatedQuestion.id);
            PageReference pgref = new PageReference('/' + questionId);
                pgref.setRedirect(true);
                return pgref;
        }
        else{
            
                translatedQuestion.QuestionLabel__c=qestionTransReq.QuestionLabel__c;
                translatedQuestion.PIData__c=qestionTransReq.PIData__c;
                translatedQuestion.Question_Bank__c=questionId;
                translatedQuestion.Secondary_Language__c=selectedValue;               
                translatedQuestion.Is_Translated__c=true;
              //  translatedQuestion.MaxScore__c=qestionTransReq.MaxScore__c;
                translatedQuestion.AnswerType__c=qestionTransReq.AnswerType__c; 
                translatedQuestion.IsRequired__c=qestionTransReq.IsRequired__c;
                translatedQuestion.Parent_Survey_Question__c = qestionTransReq.SurveyQuestion__c;
                insert translatedQuestion;
                
                for(ansWrapperCls listoftranslatedanswers : listansWrapperCls ){
                      SPE_SurveyAnswer__c Translateans= new SPE_SurveyAnswer__c();
                       Translateans.Choices__c= listoftranslatedanswers.SecondaryChoices;
                       Translateans.Secondary_Language__c=selectedValue;
                       Translateans.SurveyQuestion__c=translatedQuestion.id;
                       Translateans.PrimarySurvey_Answer__c = listoftranslatedanswers.primaryAnswerId;
                       Translateans.Score__c = listoftranslatedanswers.AnswerValue;
                       translatedAnswers.add(Translateans);
                }
              
               insert translatedAnswers; 
            //PageReference pgref = new PageReference('/' + translatedQuestion.id);
            PageReference pgref = new PageReference('/' + questionId);
                pgref.setRedirect(true);
                return pgref;
            }
        
        }
    
    public pageReference Cancel()
    {
     PageReference pgref = new PageReference('/' + questionId);
        pgref.setRedirect(true);
        return pgref;
    }
    
    public class ansWrapperCls 
        {            
             public String AnswerChoices{get;set;}
             public String SecondaryChoices{get;set;}
             public Decimal AnswerValue{get;set;}
             public String SecondaryLanguage{get;set;}
             public id primaryAnswerId{get;set;}
             public id answerID{get;set;}
        }
     
}