src/objects/SPE2_Language_KPI__c.object
<CustomObject>
    <description>Object for storing language versions of KPI</description>
    <fields>
        <fullName>Alternate_Language_Corrective_Action_Ins__c</fullName>
        <label>Alternate Language Corrective Action Ins</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alternate_Language_Description__c</fullName>
        <label>Alternate Language Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alternate_Language_Preventive_Action_Ins__c</fullName>
        <label>Alternate Language Preventive Action Ins</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alternate_Language_RCA_Instructions__c</fullName>
        <label>Alternate Language RCA Instructions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>English_Language_Corrective_Action_Ins__c</fullName>
        <label>English Language Corrective Action Ins</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>English_Language_Description__c</fullName>
        <label>English Language Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>English_Language_Preventive_Action_Ins__c</fullName>
        <label>English Language Preventive Action Ins</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>English_Language_RCA_Instructions__c</fullName>
        <label>English Language RCA Instructions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>English_Version__c</fullName>
        <label>English Version</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Alternate KPI Languages</relationshipLabel>
        <relationshipName>SPE2_Language_KPI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language_Version__c</fullName>
        <encrypted>true</encrypted>
        <label>Alternate Language KPI Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Alternate Language</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Alternate KPI Language</label>
    <nameField>
        <displayFormat>Lang-KPI-{0000}</displayFormat>
        <label>Alternate KPI Language ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternate KPI Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE2_LanguageList__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains list of languages</description>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE2_LanguageList</label>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>CorrectiveActionInstructions__c</fullName>
        <description>Corrective Action Instructions for Supplier</description>
        <inlineHelpText>Corrective Action Instructions for Supplier</inlineHelpText>
        <label>Corrective Action Instructions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>255 Character Limit</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>KPIVersion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Version</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI</relationshipLabel>
        <relationshipName>KPI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of KPI 
(Standard Name field of KPI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreventiveActionInstructions__c</fullName>
        <description>Preventive Action instructions for supplier</description>
        <inlineHelpText>Preventive Action instructions for supplier</inlineHelpText>
        <label>Preventive Action Instructions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RCAInstructions__c</fullName>
        <description>RCA instructions for supplier</description>
        <inlineHelpText>RCA instructions for supplier</inlineHelpText>
        <label>RCA Instructions</label>
        <type>TextArea</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE2_AddLanguageKPIExt.cls
public class SPE2_AddLanguageKPIExt{
    
    public SPE_KPIDefinition__c objKPI {get;set;}
    public String isLanguageAccessGranted{get;set;}
    public String isKPIFieldValuesAvailable{get;set;}
    public List<SPE2_Language_KPI__c> lstKPIAltLang {get;set;}
    public SPE2_Language_KPI__c objKPIAltLang {get;set;}
    public String inputLanguage {get;set;}
    public boolean showNext{get;set;}
    private List<SPE2_LanguageList__c> languages;
    public id idKPIRecId{get;set;}
    public SPE2_AddLanguageKPIExt(ApexPages.StandardController st){
        
        idKPIRecId = st.getId();
        objKPI = new SPE_KPIDefinition__c();
        objKPIAltLang = new SPE2_Language_KPI__c();
        lstKPIAltLang = new List<SPE2_Language_KPI__c>();
        isLanguageAccessGranted = 'false';
        isKPIFieldValuesAvailable = 'true';
        showNext = false;
        if(st.getId()!=null){
            objKPI = [SELECT ownerId,KPI_Title__c,Description__c,PreventiveActionInstructions__c,RCAInstructions__c,CorrectiveActionInstructions__c FROM SPE_KPIDefinition__c where id = :st.getId()];
        }
        system.debug('objKPI.Description__c----' + objKPI.Description__c);
        if(objKPI != null){
            if(userInfo.getUserId() == objKPI.OwnerId){
                isLanguageAccessGranted = 'true';
            }
            if(isLanguageAccessGranted == 'true'){
                if(objKPI.Description__c == '' || objKPI.Description__c == null || objKPI.PreventiveActionInstructions__c == '' || objKPI.PreventiveActionInstructions__c == null || objKPI.RCAInstructions__c == '' || objKPI.RCAInstructions__c == null || objKPI.CorrectiveActionInstructions__c == '' || objKPI.CorrectiveActionInstructions__c == null)
                    isKPIFieldValuesAvailable = 'false';
            }
        }
    }
    
    public List<SelectOption> getLanguageValues(){
    
        List<SelectOption> options = new List<SelectOption>();
        languages =SPE2_LanguageList__c.getall().values();
        languages.sort();
        for(SPE2_LanguageList__c lang : languages ){
            options.add(new SelectOption(lang.Name,lang.Language__c));    
        }  
        return options; 
     }
    
    public void showNext(){
        showNext = true;
        if(isLanguageAccessGranted == 'true' && isKPIFieldValuesAvailable == 'true'){
            lstKPIAltLang = [select 
                                Id,Name,Language__c,Alternate_Language_Corrective_Action_Ins__c,
                                Alternate_Language_Description__c,Language_Version__c,Alternate_Language_Preventive_Action_Ins__c,
                                Alternate_Language_RCA_Instructions__c,English_Version__c,KPI__c,KPI__r.KPI_Title__c 
                             FROM
                                 SPE2_Language_KPI__c
                             WHERE
                                 Language__c =: inputLanguage AND KPI__c =: idKPIRecId
                             ];
            if(!lstKPIAltLang.isEmpty()){
                objKPIAltLang = lstKPIAltLang[0];
               
                     
            }
            else{
                objKPIAltLang = new SPE2_Language_KPI__c();
            }
        }
    }  
    public pageReference saveChanges(){
        objKPIAltLang.English_Language_Corrective_Action_Ins__c = objKPI.CorrectiveActionInstructions__c;
        objKPIAltLang.English_Language_Description__c = objKPI.Description__c;
        objKPIAltLang.English_Language_Preventive_Action_Ins__c = objKPI.PreventiveActionInstructions__c;
        objKPIAltLang.English_Language_RCA_Instructions__c = objKPI.RCAInstructions__c;
        objKPIAltLang.Language__c = inputLanguage;
        objKPIAltLang.English_Version__c = objKPI.KPI_Title__c;
        objKPIAltLang.KPI__c = idKPIRecId;
        if(objKPIAltLang != null){
         if(objKPIAltLang.Alternate_Language_Corrective_Action_Ins__c=='' || objKPIAltLang.Alternate_Language_Description__c==''
                    || objKPIAltLang.Alternate_Language_Preventive_Action_Ins__c=='' || objKPIAltLang.Alternate_Language_RCA_Instructions__c==''
                    || objKPIAltLang.Language_Version__c=='' ){
                 ApexPages.Message myMsg = new ApexPages.message(ApexPages.severity.ERROR,'All the fields are mandatory to be filled.Please enter some values.');
                 ApexPages.addMessage(myMsg); 
            }
            try{
            
                upsert objKPIAltLang;
                PageReference pg = new Pagereference('/' + idKPIRecId);
                return pg;
            }
            catch(exception ex){
                return null;
            }
        }
        else{
            return null;
        }
    }
}