src/objects/SPE2_Question_Survey_Association__c.object
<CustomObject>
    <fields>
        <fullName>PIData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Data</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>Survey</relationshipLabel>
        <relationshipName>SPE2_Question_Survey_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionLabel__c</fullName>
        <label>Question Label</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipName>SPE2_Question_Survey_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <label>Survey Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>SPE2Survey__c</referenceTo>
        <relationshipLabel>PI Data</relationshipLabel>
        <relationshipName>SPE2_Question_Survey_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SPE2_Question_Survey_Association</label>
    <nameField>
        <displayFormat>Survey-Ques-{0000}</displayFormat>
        <label>SPE2 Question Survey Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE2Survey__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryArea__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FrequencyInMonths__c</fullName>
        <inlineHelpText>Survey frequency as in “once every xx months</inlineHelpText>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MarketUnit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>Survey-{0000}</displayFormat>
        <label>Survey Sequential Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standalone Surveys</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <inlineHelpText>Relevant org/group for this data</inlineHelpText>
        <label>Organization/Group</label>
        <picklist>
            <picklistValues>
                <fullName>INDIRECT PROCUREMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRODUCT PROCUREMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICES PROCUREMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTNERING ORGANIZATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOBILE BROADBAND</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DataAcquisitionMethod__c</fullName>
        <inlineHelpText>Identify how this data is acquired</inlineHelpText>
        <label>Data Acquisition Method</label>
        <picklist>
            <picklistValues>
                <fullName>Data Load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standalone Survey</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>PI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of PI 
(Standard Name field of PI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>PI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceDataOwner__c</fullName>
        <description>Name of the person who supplies the data</description>
        <inlineHelpText>Source of Input Data (80 Character Limit)</inlineHelpText>
        <label>Source Data</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Required if Data Acquisition Method = Survey</inlineHelpText>
        <label>Question ID</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipLabel>PI Data</relationshipLabel>
        <relationshipName>PI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Specify domain of this PI</inlineHelpText>
        <label>PI Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SurveyQuestion__c.object
<CustomObject>
    <customHelpPage>SPE_QuestionBank_Survey_Help_Page</customHelpPage>
    <description>SurveyQuestion object contains Question banks for the survey.</description>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Data</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>Question Bank</relationshipLabel>
        <relationshipName>Question_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIType__c</fullName>
        <label>PI Type</label>
        <picklist>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QuestionLabel__c</fullName>
        <label>Question Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Question Bank</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipLabel>Alternate Language Question Bank</relationshipLabel>
        <relationshipName>Question_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <description>Question which will appear on Survey page</description>
        <inlineHelpText>Enter your question</inlineHelpText>
        <label>Survey Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question Bank</label>
    <nameField>
        <label>Questions ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE2_ConvertQuestionToPIDataExt.cls
public class SPE2_ConvertQuestionToPIDataExt
{
    public SPE2_Question_Survey_Association__c speQuestions {get;set;}
    public SPE_SurveyQuestion__c speQue {get;set;}
    public SPE2Survey__c surveyObj;
    public boolean flag{get;set;}
    public SPE_PIDefinition__c PIDef {get;set;}
    public Id SId;
    public Id CurrentUserId {get;set;}
    public ID RecordOwnerId {get;set;}
    public SPE2_ConvertQuestionToPIDataExt( ApexPages.StandardController controller )
    {   
        
        flag =false;
        SId = ApexPages.currentPage().getParameters().get('sid');
        ID Qid = ApexPages.currentPage().getParameters().get('QID');
        surveyObj = new SPE2Survey__c();
        speQuestions = [SELECT ID,Question_Bank__c,Survey__c,Survey__r.FrequencyInMonths__c,PIData__c,PIData__r.DataAcquisitionMethod__c,Question_Bank__r.Name,
                         Question_Bank__r.QuestionLabel__c,Question_Bank__r.SurveyQuestion__c,Question_Bank__r.PIData__c,Survey__r.OwnerId,
                         Question_Bank__r.OwnerId,Question_Bank__r.PIType__c,Question_Bank__r.Business__c,
                         Question_Bank__r.GeoScope__c,Question_Bank__r.BUScope__c,Question_Bank__r.CategoryScope__c from SPE2_Question_Survey_Association__c
                         where Survey__c = :SId and Question_Bank__c =:Qid];
        speQue = [Select ID from SPE_SurveyQuestion__c where ID = :Qid];  
        surveyObj = [SELECT ID,BusinessLine__c,BusinessUnit__c,Category__c,CategoryArea__c,CategoryGroup__c,Country__c,Market__c,
                    MarketUnit__c,Product__c,Project__c from SPE2Survey__c where id = :SId];  
        CurrentUserId = UserInfo.getUserId();
         RecordOwnerId = [Select Id, ownerId from SPE2Survey__C
                          WHERE Id =: SId].ownerId;
                                 
        PIDef = new SPE_PIDefinition__c();             
        if(surveyObj!=null){
              if(surveyObj.CategoryArea__c == 'All Category Areas'){
                  PIDef.CategoryScope__c = 'All Categories';
       
               }
       
           if(surveyObj.CategoryArea__c != 'All Category Areas' && surveyObj.CategoryGroup__c == 'All Category Groups'){
                PIDef.CategoryScope__c = 'Category Area';
           
           }
           
           if(surveyObj.CategoryArea__c != 'All Category Areas' && surveyObj.CategoryGroup__c != 'All Category Groups' && surveyObj.Category__c== 'All Categories'){
               PIDef.CategoryScope__c = 'Category Group';
           
           }
           
            if(surveyObj.CategoryArea__c != 'All Category Areas' && surveyObj.CategoryGroup__c != 'All Category Groups' && surveyObj.Category__c != 'All Categories'){
                PIDef.CategoryScope__c = 'Category';
           
           }
           
           
           if(surveyObj.BusinessUnit__c == 'All Business Units'){
               PIDef.BUScope__c = 'All Products';
           
           }
           
           if(surveyObj.BusinessUnit__c != 'All Business Units' && surveyObj.BusinessLine__c == 'All Business Lines'){
               PIDef.BUScope__c = 'Business Unit';
           
           }
           
            if(surveyObj.BusinessUnit__c != 'All Business Units' && surveyObj.BusinessLine__c != 'All Business Lines' && surveyObj.Product__c == 'All Products'){
                PIDef.BUScope__c = 'Business Line';
           
           }
           
           if(surveyObj.BusinessUnit__c != 'All Business Units' && surveyObj.BusinessLine__c != 'All Business Lines' && surveyObj.Product__c != 'All Products'){
                PIDef.BUScope__c = 'Product';
           
           }
           
            if(surveyObj.Market__c == 'All Markets'){
               PIDef.GeoScope__c ='All Markets';
           
           }
           
           if(surveyObj.Market__c != 'All Markets' && surveyObj.MarketUnit__c == 'All Market Units'){
               PIDef.GeoScope__c ='Market';
           
           }
           
           if(surveyObj.Market__c != 'All Markets' && surveyObj.MarketUnit__c != 'All Market Units' && surveyObj.Country__c == 'All Countries'){
               PIDef.GeoScope__c ='Market Unit';
           
           }
            if(surveyObj.Market__c != 'All Markets' && surveyObj.MarketUnit__c != 'All Market Units' && surveyObj.Country__c != 'All Countries' && surveyObj.Project__c == 'All Projects'){
               PIDef.GeoScope__c ='Country';
           
           }
           
           if(surveyObj.Market__c != 'All Markets' && surveyObj.MarketUnit__c != 'All Market Units' && surveyObj.Country__c != 'All Countries' && surveyObj.Project__c != 'All Projects'){
               PIDef.GeoScope__c ='Project';
           
           }
            
        
        }                       
        
       if(speQuestions.Question_Bank__r.PIData__c != null){
            flag=true;
        }                  
       
        
        //*********Changes for Encryption*************//
        //PIDef.Name= speQuestions.SurveyQuestion__c;
        PIDef.PI_Title__c = speQuestions.Question_Bank__r.SurveyQuestion__c;
        //**********End****************//
        
        PIDef.OwnerId = speQuestions.Survey__r.OwnerId;
        PIDef.LifecycleStage__c = 'Draft';
        PIDef.SourceDataOwner__c = 'Survey';
        PIDef.ValuesType__c = 'Number';
        PIDef.Type__c = speQuestions.Question_Bank__r.PIType__c;
        PIDef.DataAcquisitionMethod__c = 'Standalone Survey';
        PIDef.UoM__c = 'Number';
        PIDef.Business__c = speQuestions.Question_Bank__r.Business__c;
       // PIDef.GeoScope__c = speQuestions.Question_Bank__r.GeoScope__c;
       // PIDef.BUScope__c = speQuestions.Question_Bank__r.BUScope__c;
       // PIDef.CategoryScope__c = speQuestions.Question_Bank__r.CategoryScope__c;
        PIDef.SurveyQuestion__c = speQuestions.Question_Bank__r.Id;
      //  PIDef.Frequency__c = speQuestions.Survey__r.FrequencyInMonths__c;
        
    }
    
    
    public pageReference PICancel(){
        pageReference pg = new pageReference('/apex/SPE2_ValidateQuestionInSurvey?id='+SId);
        return pg;
    }
    public pageReference PISave(){
        try{
            insert PIDef;
            speQuestions.PIData__c=PIDef.Id;
            upsert speQue;
            upsert speQuestions;
            pageReference pg = new pageReference('/apex/SPE2_ValidateQuestionInSurvey?id='+SId);
            return pg;
        }catch(System.DmlException ex){
            String err = ex.getMessage();
            ApexPages.Message msg = new Apexpages.Message(ApexPages.Severity.Error,ex.getDmlMessage(0));
            Apexpages.addMessage(msg);
            return null;
        }
        return null;
        
    }
    
}