src/objects/SPE2_Question_Survey_Association__c.object
<CustomObject>
    <fields>
        <fullName>PIData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Data</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>Survey</relationshipLabel>
        <relationshipName>SPE2_Question_Survey_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionLabel__c</fullName>
        <label>Question Label</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipName>SPE2_Question_Survey_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <label>Survey Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>SPE2Survey__c</referenceTo>
        <relationshipLabel>PI Data</relationshipLabel>
        <relationshipName>SPE2_Question_Survey_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ordernumber__c</fullName>
        <label>ordernumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SPE2_Question_Survey_Association</label>
    <nameField>
        <displayFormat>Survey-Ques-{0000}</displayFormat>
        <label>SPE2 Question Survey Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>DataAcquisitionMethod__c</fullName>
        <inlineHelpText>Identify how this data is acquired</inlineHelpText>
        <label>Data Acquisition Method</label>
        <picklist>
            <picklistValues>
                <fullName>Data Load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standalone Survey</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Required if Data Acquisition Method = Survey</inlineHelpText>
        <label>Question ID</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipLabel>PI Data</relationshipLabel>
        <relationshipName>PI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SurveyQuestion__c.object
<CustomObject>
    <customHelpPage>SPE_QuestionBank_Survey_Help_Page</customHelpPage>
    <description>SurveyQuestion object contains Question banks for the survey.</description>
    <fields>
        <fullName>PIData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Data</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>Question Bank</relationshipLabel>
        <relationshipName>Question_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionLabel__c</fullName>
        <label>Question Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Question Bank</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipLabel>Alternate Language Question Bank</relationshipLabel>
        <relationshipName>Question_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <description>Question which will appear on Survey page</description>
        <inlineHelpText>Enter your question</inlineHelpText>
        <label>Survey Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question Bank</label>
    <nameField>
        <label>Questions ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE2ReorderQuestionExt.cls
public class SPE2ReorderQuestionExt{
    public List<SPE2_Question_Survey_Association__c> lstSurveyQuesAssoc {get;set;}
    Id RecordId; 
    public String newOrderW {get;set;}
    
    public SPE2ReorderQuestionExt(ApexPages.StandardController st){
        RecordId = st.getID();
        lstSurveyQuesAssoc = new List<SPE2_Question_Survey_Association__c>();
        lstSurveyQuesAssoc = [SELECT ID,Question_Bank__c,Survey__c,PIData__c,PIData__r.DataAcquisitionMethod__c,Question_Bank__r.Name,
                             Question_Bank__r.QuestionLabel__c,ordernumber__c,Question_Bank__r.surveyQuestion__C from SPE2_Question_Survey_Association__c where Survey__c = :RecordId order by ordernumber__c];
                             
        if(lstSurveyQuesAssoc.size()>0){
        
        }
    }
    
     public PageReference updateOrderList()
  {
    if(newOrderW.length() <= 0)
    {
        return null;
        system.debug('neworder--null');
    }
    system.debug('newOrderW ::'+newOrderW);
    newOrderW = newOrderW.substring(0, newOrderW.length() -1);
    
    List<String> idsToUpdate = newOrderW.split(',',-1);
    List<SPE2_Question_Survey_Association__c> qsToUpdate = new List<SPE2_Question_Survey_Association__c>();
    
    Map<Id,SPE2_Question_Survey_Association__c> questionMap = new Map<Id,SPE2_Question_Survey_Association__c>([select Id, OrderNumber__c from SPE2_Question_Survey_Association__c where Id in :idsToUpdate]);
       system.debug('questionMap'+questionMap);
       system.debug('id to update--'+idsToUpdate);
    SPE2_Question_Survey_Association__c sqToUpdate;
    
    for (Integer i = 0; i < idsToUpdate.size(); i++)
    {
        sqToUpdate = questionMap.get(idsToUpdate.get(i));
        system.debug('sqtoUpdate'+sqToUpdate);
        system.debug('order number ---'+i);
        sqToUpdate.OrderNumber__c = i;
        qsToUpdate.add(sqToUpdate);
    }
    
    system.debug('lst to update'+qsToUpdate);
    update qsToUpdate;
    
    PageReference pg = new PageReference('/'+RecordId);
    return pg;
    

  } 
  
  
  
    
public class QuestionSurveyWrapper implements Comparable{
     public SPE2_Question_Survey_Association__c quesSurvey {get;set;}
     public Boolean isSelected {get;set;}
     public Boolean isInvalid {get;set;} 
     
     public QuestionSurveyWrapper(SPE2_Question_Survey_Association__c qu,Boolean x){
         quesSurvey = qu;
         isSelected = x;
       //  isInvalid = y;
         
     
     }  
     
      public Integer compareTo(Object compareTo) {
         QuestionSurveyWrapper compareToSupp = (QuestionSurveyWrapper)compareTo;
        if (quesSurvey.Question_Bank__r.Name== compareToSupp.quesSurvey.Question_Bank__r.Name) return 0;
        if (quesSurvey.Question_Bank__r.Name> compareToSupp.quesSurvey.Question_Bank__r.Name) return 1;
        return -1;        
    }
        
        
 }       
    


}