src/objects/SPE2_Language_KPI__c.object
<CustomObject>
    <description>Object for storing language versions of KPI</description>
    <fields>
        <fullName>Alternate_Language_Corrective_Action_Ins__c</fullName>
        <label>Alternate Language Corrective Action Ins</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alternate_Language_Description__c</fullName>
        <label>Alternate Language Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alternate_Language_Preventive_Action_Ins__c</fullName>
        <label>Alternate Language Preventive Action Ins</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Alternate_Language_RCA_Instructions__c</fullName>
        <label>Alternate Language RCA Instructions</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>English_Language_Corrective_Action_Ins__c</fullName>
        <label>English Language Corrective Action Ins</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>English_Language_Description__c</fullName>
        <label>English Language Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>English_Language_Preventive_Action_Ins__c</fullName>
        <label>English Language Preventive Action Ins</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>English_Language_RCA_Instructions__c</fullName>
        <label>English Language RCA Instructions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>English_Version__c</fullName>
        <label>English Version</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Alternate KPI Languages</relationshipLabel>
        <relationshipName>SPE2_Language_KPI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Language_Version__c</fullName>
        <encrypted>true</encrypted>
        <label>Alternate Language KPI Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Alternate Language</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Alternate KPI Language</label>
    <nameField>
        <displayFormat>Lang-KPI-{0000}</displayFormat>
        <label>Alternate KPI Language ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternate KPI Languages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE2_LanguageList__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains list of languages</description>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE2_LanguageList</label>
</CustomObject>

src/objects/SPE_ConsequenceManagement__c.object
<CustomObject>
    <fields>
        <fullName>CorrectiveActionInstructions__c</fullName>
        <formula>KPIName__r.CorrectiveActionInstructions__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Corrective Action Instructions</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <formula>KPIName__r.Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPIName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Name</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Consequence Managements</relationshipLabel>
        <relationshipName>Consequence_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPITitle__c</fullName>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreventiveActionInstructions__c</fullName>
        <formula>KPIName__r.PreventiveActionInstructions__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Preventive Action Instructions</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RCAInstructions__c</fullName>
        <formula>KPIName__r.RCAInstructions__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RCA Instructions</label>
        <type>Text</type>
    </fields>
    <label>Consequence Management</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Consequence Management ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consequence Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>CorrectiveActionInstructions__c</fullName>
        <description>Corrective Action Instructions for Supplier</description>
        <inlineHelpText>Corrective Action Instructions for Supplier</inlineHelpText>
        <label>Corrective Action Instructions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>255 Character Limit</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>KPI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of KPI 
(Standard Name field of KPI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreventiveActionInstructions__c</fullName>
        <description>Preventive Action instructions for supplier</description>
        <inlineHelpText>Preventive Action instructions for supplier</inlineHelpText>
        <label>Preventive Action Instructions</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RCAInstructions__c</fullName>
        <description>RCA instructions for supplier</description>
        <inlineHelpText>RCA instructions for supplier</inlineHelpText>
        <label>RCA Instructions</label>
        <type>TextArea</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE2_CMAlternateLanguageExt.cls
public without sharing class SPE2_CMAlternateLanguageExt{
   
    public string selectedValue {get;set;}
    public List<SelectOption> statusOptions {get;set;}
    public boolean showOptions {get;set;}
    public List<SPE2_Language_KPI__c> altrLang{get;set;}
    Private List<SPE2_LanguageList__c> languages;   
    private Id idCMRecord;
    public SPE_ConsequenceManagement__c objCM{get;set;}
    public SPE2_CMAlternateLanguageExt(ApexPages.StandardController con){
        showOptions=false;
        statusOptions = new list<SelectOption>();
        languages =SPE2_LanguageList__c.getall().values();
        languages.sort();
        
        statusOptions.add(new SelectOption('English','English'));
        for(SPE2_LanguageList__c lang : languages ){
            
            statusOptions.add(new SelectOption(lang.Name,lang.Language__c));  
        }
        
        idCMRecord = con.getId();
        objCM = [select Id,Name,CorrectiveActionInstructions__c,Description__c,KPIName__c,KPIName__r.Kpi_Title__c,KPITitle__c,PreventiveActionInstructions__c,RCAInstructions__c from SPE_ConsequenceManagement__c WHERE Id =:idCMRecord];
        System.debug('objCM @@@@@@@@@@@@@@@@@@@'+objCM );
    
    }
      
     public void refreshLanguage(){
         
          altrLang = [Select id,KPI__c,Language__c,English_Language_RCA_Instructions__c,English_Language_Description__c,English_Language_Preventive_Action_Ins__c,English_Language_Corrective_Action_Ins__c,
             English_Version__c,Language_Version__c,Alternate_Language_Corrective_Action_Ins__c,Alternate_Language_Description__c,Alternate_Language_Preventive_Action_Ins__c,Alternate_Language_RCA_Instructions__c
             from SPE2_Language_KPI__c 
             where KPI__c=: objCM.KPIName__c and Language__c =: selectedValue ];
          System.debug('altrLang @@@@@@@@@@@@@@@@@@@'+altrLang );
          
          if(altrLang.size()>0){
              showOptions=true;
          }
          else{
              showOptions=false;
              if(selectedValue != 'English')
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,'Alternate Language Not Available for '+(selectedValue ))); 
          }
     
     } 
  
     
}