src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Master_KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI (Master KPI)</relationshipLabel>
        <relationshipName>KPI1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VerNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <label>VerNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>&apos;Version-&apos;+TEXT(VerNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Obsolete</fullName>
        <active>true</active>
        <description>Change the record type to Obsolete when lifecycle stage is obsolete</description>
        <label>Obsolete</label>
    </recordTypes>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_VersionInlineExt.cls
public class SPE_VersionInlineExt 
{
    
    public SPE_KPIDefinition__c KPI{get;set;}
    public Id KPIid{get;set;}
    public List<SPE_KPIDefinition__c> KPIList{get;set;}
    public List<SPE_KPIDefinition__c> KPIDraftList{get;set;}
    public List<SPE_KPIDefinition__c> KPIPilotList{get;set;}
    public List<SPE_KPIDefinition__c> KPIPublishedList{get;set;}
    public List<SPE_KPIDefinition__c> KPIObsoleteList{get;set;}
    public integer draft{get;set;}
    public integer pilot{get;set;}
    public integer published{get;set;}
    public integer obsolete{get;set;}
    public string pilotReport{get;set;}
    public string publishedReport{get;set;}
    public string AllReport{get;set;}
    
    public SPE_VersionInlineExt(ApexPages.StandardController con) 
    {
        
        KPI = new SPE_KPIDefinition__c();
        KPIList = new List<SPE_KPIDefinition__c>();
        KPIDraftList = new List<SPE_KPIDefinition__c>();
        KPIPilotList = new List<SPE_KPIDefinition__c>();
        KPIPublishedList = new List<SPE_KPIDefinition__c>();
        KPIObsoleteList = new List<SPE_KPIDefinition__c>();
        KPIid=con.getId();
        KPI = [select id,Master_KPI__c,version__c from SPE_KPIDefinition__c where id=: con.getId()];
        
        
        
        if(KPI.id != null && kpi.Master_KPI__c != null)
        {
            KPIList = [select id,LifecycleStage__c,Version__c,Owner.name,VerNumber__c from SPE_KPIDefinition__c where (Master_KPI__c =: kpi.Master_KPI__c OR id=: kpi.Master_KPI__c) and LifecycleStage__c =:'Draft' order by VerNumber__c];
            
            KPIPilotList = [select id,LifecycleStage__c,Version__c,Owner.name,VerNumber__c from SPE_KPIDefinition__c where (Master_KPI__c =: kpi.Master_KPI__c OR id=: kpi.Master_KPI__c) and LifecycleStage__c =:'Pilot' order by VerNumber__c];
            
            KPIPublishedList = [select id,LifecycleStage__c,Version__c,Owner.name,VerNumber__c from SPE_KPIDefinition__c where (Master_KPI__c =: kpi.Master_KPI__c OR id=: kpi.Master_KPI__c) and LifecycleStage__c =:'Published' order by VerNumber__c];
            
            KPIObsoleteList = [select id,LifecycleStage__c,Version__c,Owner.name,VerNumber__c from SPE_KPIDefinition__c where (Master_KPI__c =: kpi.Master_KPI__c OR id=: kpi.Master_KPI__c) and LifecycleStage__c =:'Obsolete' order by VerNumber__c];
            
        }
        if(KPI.id != null && kpi.Master_KPI__c == null)
        {
            KPIList = [select id,LifecycleStage__c,Version__c,Owner.name,VerNumber__c from SPE_KPIDefinition__c where (id =: con.getId() OR Master_KPI__c =: con.getId()) and LifecycleStage__c =:'Draft' order by VerNumber__c];
            
            KPIPilotList = [select id,LifecycleStage__c,Version__c,Owner.name,VerNumber__c from SPE_KPIDefinition__c where (id =: con.getId() OR Master_KPI__c =: con.getId()) and LifecycleStage__c =:'Pilot' order by VerNumber__c];
            
            KPIPublishedList = [select id,LifecycleStage__c,Version__c,Owner.name,VerNumber__c from SPE_KPIDefinition__c where (id =: con.getId() OR Master_KPI__c =: con.getId())  and LifecycleStage__c =:'Published' order by VerNumber__c];
            
            KPIObsoleteList = [select id,LifecycleStage__c,Version__c,Owner.name,VerNumber__c from SPE_KPIDefinition__c where (id =: con.getId() OR Master_KPI__c =: con.getId()) and LifecycleStage__c =:'Obsolete' order by VerNumber__c];
        }
        
        draft=KPIList.size();
        pilot=KPIPilotList.size();
        published=KPIPublishedList.size();
        obsolete=KPIObsoleteList.size();
        
        if(pilot>0)
        pilotReport=String.valueOf(KPIPilotList[pilot-1].Id).substring(0, 15);
        
        if(published>0)
        publishedReport=String.valueOf(KPIPublishedList[published-1].Id).substring(0, 15);
        
        AllReport='';
        for(SPE_KPIDefinition__c k:KPIPilotList)
        AllReport=AllReport+String.valueOf(k.Id).substring(0, 15)+',';
        
        for(SPE_KPIDefinition__c k: KPIPublishedList)
        AllReport=AllReport+String.valueOf(k.Id).substring(0, 15)+',';
        
    }
    
    

}