src/objects/SPE_KPICalculation__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>KPI Calculation</label>
    <nameField>
        <displayFormat>KCal-{00000}</displayFormat>
        <label>KPI Calculation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Additional_Days__c</fullName>
        <description>Additional days for PI upload due date</description>
        <label>Additional Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_ScoringTemplate__c.object
<CustomObject>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>Scoring Templates</relationshipLabel>
        <relationshipName>Scoring_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scoring Template</label>
    <nameField>
        <label>Scoring Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPEKPIMap__c.object
<CustomObject>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE KPI Maps</relationshipLabel>
        <relationshipName>SPE_KPI_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SPE KPI Map</label>
    <nameField>
        <displayFormat>SKMI-{00000}</displayFormat>
        <label>SPE KPI Map Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE KPI Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPEPlan__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Additional_Days__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Buffer Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Month__c</fullName>
        <label>End Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Year__c</fullName>
        <label>End Year</label>
        <picklist>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2024</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2026</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2027</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2028</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2029</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2030</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2031</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2032</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Computed_Day__c</fullName>
        <label>Next Computed Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPEScoringTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SPE Scoring Template</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
            <filterItems>
                <field>SPE_ScoringTemplate__c.Stage__c</field>
                <operation>equals</operation>
                <value>Pilot, Published</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>SPE Key Users</value>
            </filterItems>
            <filterItems>
                <field>SPE_ScoringTemplate__c.Stage__c</field>
                <operation>equals</operation>
                <value>Published,Pilot</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>SPE User</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>SPE_ScoringTemplate__c.Stage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_ScoringTemplate__c</referenceTo>
        <relationshipLabel>SPE Plans</relationshipLabel>
        <relationshipName>SPE_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE Plans</relationshipLabel>
        <relationshipName>SPE_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Month__c</fullName>
        <label>Start Month</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Year__c</fullName>
        <label>Start Year</label>
        <picklist>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2024</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2025</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2026</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2027</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2028</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2029</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2030</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2031</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2032</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>identifierParam__c</fullName>
        <label>identifierParam</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE Plan</label>
    <nameField>
        <displayFormat>SPE - {00000}</displayFormat>
        <label>SPE Plan Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE2_PlanChangeDate.cls
public with sharing class SPE2_PlanChangeDate{
    private ApexPages.StandardController standardController;
    public List<SPE_SPEPlan__c> spePlanList{get;set;}
    public List<SPE_SPEPlan__c> spePlanDate{get;set;}
    public String spePlanIdentifier{get;set;}
    public SPE_SPEPlan__c spePlan{get;set;}
    public Set<string> selectedPlanIds{get;set;}
    public Date new_st_date;
    public Date new_end_date;
    public List<SPE_KPICalculation__c> kpiCals;
    public Map<String,Integer> mapMonthName{get;set;}
    public SPE2_PlanChangeDate(ApexPages.StandardController standardController){
        
        spePlan = new SPE_SPEPlan__c();
        spePlanList = new List<SPE_SPEPlan__c>();
        selectedPlanIds = new Set<String>();
        
        mapMonthName = new Map<String,Integer>();
        mapMonthName.put('January',1);
        mapMonthName.put('February',2);
        mapMonthName.put('March',3);
        mapMonthName.put('April',4);
        mapMonthName.put('May',5);
        mapMonthName.put('June',6);
        mapMonthName.put('July',7);
        mapMonthName.put('August',8);
        mapMonthName.put('September',9);
        mapMonthName.put('October',10);
        mapMonthName.put('November',11);
        mapMonthName.put('December',12);
        
        new_st_date = Date.newinstance(1960, 1, 1);
        new_end_date = Date.newinstance(1960, 1, 1);
        
        spePlanIdentifier = apexpages.currentpage().getparameters().get('planIdentifier');           
        spePlanList = [Select Id,Name,SPEScoringTemplate__c,Start_Month__c,Start_Year__c,
                        End_Month__c,End_Year__c,Next_Computed_Day__c,Additional_Days__c From SPE_SPEPlan__c 
                      Where identifierParam__c =:spePlanIdentifier];
                      
        system.debug('spePlanList ::'+spePlanList);
        Set<ID> scortempID = new Set<ID>();
        
        if(spePlanList.size() > 0){
            for(SPE_SPEPlan__c sp: spePlanList){
                scortempID.add(sp.SPEScoringTemplate__c);
            }
        }
                      
        List<SPE_ScoringTemplate__c> scoringTemplates = [SELECT SPETemplate__c 
                                                         FROM SPE_ScoringTemplate__c
                                                         WHERE Id IN: scortempID]; 
                                                         
        system.debug('scoringTemplates ::'+scoringTemplates);
        Set<ID> spetempID = new Set<ID>();
        
        for(SPE_ScoringTemplate__c sc: scoringTemplates){
            spetempID.add(sc.SPETemplate__c);
        }
                                                                                         
        List<SPE_SPEKPIMap__c> speKPIMapList = [SELECT Id,SPETemplate__c,KPIDefinition__c,KPIDefinition__r.ScheduledDate__c 
                                                    from SPE_SPEKPIMap__c where SPETemplate__c IN: spetempID];
                                                    
        Set<ID> kpiID = new Set<ID>();        
        for (SPE_SPEKPIMap__c speKPIMap :speKPIMapList){  
            kpiID.add(speKPIMap.KPIDefinition__c);            
        } 
        
        system.debug('kpiID ::'+kpiID);
                                                                                                         
        kpiCals = [Select Id,PIDefination__c,PIDefination__r.DataAcquisitionMethod__c,
                   PIDefination__r.PIUploadDuedate__c,KPIDefinition__c,KPIDefinition__r.ScheduledDate__c,
                   KPIDefinition__r.FrequencyinMonth__c,PIDefination__r.Frequency__c,
                   PrevKPIDefination__c,PrevKPIDefination__r.ScheduledDate__c,PrevKPIDefination__r.FrequencyinMonth__c
                   From SPE_KPICalculation__c Where KPIDefinition__c IN :kpiID 
                   AND PIDefination__r.DataAcquisitionMethod__c = 'Data Load'];
                   
        system.debug('kpiCals ::'+kpiCals); 
                                                               
    }
    public PageReference returnbackToPlan(){
        Schema.DescribeSObjectResult r = SPE_SPEPlan__c.sObjectType.getDescribe();
        String keyPrefix = r.getKeyPrefix();
        Pagereference pr =new Pagereference('/'+keyPrefix);
        return pr;
    }
    public PageReference updateSPEPlans(){       
        for(SPE_KPICalculation__c kp: kpiCals){
           if(kp.PIDefination__r.PIUploadDuedate__c != null && mapMonthName.get(spePlan.Start_Month__c) == kp.PIDefination__r.PIUploadDuedate__c.Month() && Integer.ValueOf(spePlan.Start_Year__c) == kp.PIDefination__r.PIUploadDuedate__c.Year()){
               if(kp.PIDefination__r.PIUploadDuedate__c > new_st_date){
                   new_st_date = kp.PIDefination__r.PIUploadDuedate__c;
               }
            } 
        }
        
        system.debug('new_st_date ::'+new_st_date ); 
        if(kpiCals.size() == 0 || new_st_date == Date.newinstance(1960, 1, 1)){
            if(spePlan.Start_Year__c != null && spePlan.Start_Month__c != null){
                new_st_date = Date.NewInstance(Integer.ValueOf(spePlan.Start_Year__c),mapMonthName.get(spePlan.Start_Month__c),1);
            }
        }
        system.debug('new_st_date ::'+new_st_date );
        
        if(spePlan.End_Month__c != null && spePlan.End_Year__c != null){
            new_end_date = Date.NewInstance(Integer.ValueOf(spePlan.End_Year__c),mapMonthName.get(spePlan.End_Month__c),1);
            new_end_date = new_end_date.addMonths(1);
            new_end_date = new_end_date.addDays(-1);
        }
       
        for(SPE_SPEPlan__c pl :spePlanList){            
            if(pl.Additional_Days__c != Null && new_st_date != Date.newinstance(1960, 1, 1)){
                Integer additional_days = Integer.ValueOf(pl.Additional_Days__c);
                new_st_date = new_st_date.addDays(additional_days);
            }
            
            if(new_st_date != Date.newinstance(1960, 1, 1)){
                pl.StartDate__c = new_st_date;
                if(pl.Next_Computed_Day__c < new_st_date){
                  pl.Next_Computed_Day__c =  new_st_date; 
                }
            }
            
            if(spePlan.Start_Month__c != null && spePlan.Start_Year__c != null){
                pl.Start_Month__c = spePlan.Start_Month__c;
                pl.Start_Year__c = spePlan.Start_Year__c;
            }
            
            if(spePlan.End_Month__c != null && spePlan.End_Year__c != null){
                pl.End_Month__c = spePlan.End_Month__c;
                pl.End_Year__c  = spePlan.End_Year__c;
            }
            
            if(new_end_date != Date.newinstance(1960, 1, 1)){
                pl.EndDate__c = new_end_date;
            }
            
        }
        try{
            update spePlanList;
        }catch(Exception e){}
        
        if(new_st_date != Date.newinstance(1960, 1, 1) || new_end_date != Date.newinstance(1960, 1, 1)){
            SPE2_ChangeTrackerBatch dtBatch = new SPE2_ChangeTrackerBatch(spePlanIdentifier);
            database.executebatch(dtBatch,1);
        }
        
        Schema.DescribeSObjectResult r = SPE_SPEPlan__c.sObjectType.getDescribe();
        String keyPrefix = r.getKeyPrefix();
        Pagereference pr =new Pagereference('/'+keyPrefix);
        return pr;
    }
}