src/objects/SPE_ScorecardSPETemplateMap__c.object
<CustomObject>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>Scorecard SPE Template Maps</relationshipLabel>
        <relationshipName>Scorecard_SPE_Template_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScorecardTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scorecard Template</label>
        <referenceTo>SPE_ScorecardTemplate__c</referenceTo>
        <relationshipLabel>Scorecard SPE Template Maps</relationshipLabel>
        <relationshipName>Scorecard_SPE_Template_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scorecard SPE Template Map</label>
    <nameField>
        <displayFormat>SST-{00000}</displayFormat>
        <label>Scorecard SPE Template Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard SPE Template Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPETemplate__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>SPE Template can not be Published without a Scoring Template</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SPE Template</label>
    <nameField>
        <label>SPE Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Templates</pluralLabel>
    <recordTypes>
        <fullName>Obsolete</fullName>
        <active>true</active>
        <description>Obsolete record type for Obsolete lifecylce.</description>
        <label>Obsolete</label>
    </recordTypes>
    <recordTypes>
        <fullName>Pilot</fullName>
        <active>true</active>
        <description>Change the record type to Pilot when lifecycle stage is pilot</description>
        <label>Pilot</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_ScorecardTemplateLifecycleEXT.cls
public with sharing class SPE_ScorecardTemplateLifecycleEXT{
public boolean draft{get;set;}
public boolean published{get;set;}
public boolean obsolete{get;set;}
public boolean pilot{get;set;}
public boolean IsAccess{get;set;}
Public Id RecordId{get;set;}
public string stage{get;set;}
public String SobjectName{get;set;}
public boolean isSuccess{get;set;}
public Sobject CurrRecord{get;set;}
public List<SPE_ScorecardSPETemplateMap__c> lstScoreSPETempMap;
public String alertflag {get;set;}

public SPE_ScorecardTemplateLifecycleEXT(ApexPages.StandardController controller) {
       
       lstScoreSPETempMap = new List<SPE_ScorecardSPETemplateMap__c>();
       
       published=true;
       draft=true;
       obsolete=true;
       pilot=true;
       isSuccess=false;
       alertflag = 'false';
       
       
       if(controller.getid()!=Null || controller.getid()!='')
       IsAccess=[SELECT recordId,HasEditAccess FROM UserRecordAccess WHERE UserId =:UserInfo.getUserId() AND RecordId =:controller.getid()].HasEditAccess ; 
       SobjectName=(Id.valueOf(controller.getid()).getSObjectType().getDescribe().getName());
       system.debug('******SobjectName'+SobjectName);
      

       if(IsAccess) {
            map<String,String> n= new Map<string,string>();   
            Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();  
            Map<String, Schema.SObjectField> M = (gd.get(Id.valueOf(controller.getid()).getSObjectType().getDescribe().getName())).getDescribe().fields.getMap();
               for (Schema.SObjectField field : m.values())
                {
                    n.put(field.getDescribe().getLabel(), field.getDescribe().getName());
                    
                }
              RecordId = Id.valueOf(controller.getId());
              stage=n.get('Stage');
              String query='select id,'+stage+' from '+SobjectName+' where id=: RecordId '; 
              currRecord=database.query(query);
              
              //##################
         lstScoreSPETempMap = [select SPETemplate__c,SPETemplate__r.Stage__c from SPE_ScorecardSPETemplateMap__c where ScorecardTemplate__c = :RecordId];

       Map<String,Id> maptempSPEMap = new Map<String,Id> ();
      if(lstScoreSPETempMap.size()>0){
          for(SPE_ScorecardSPETemplateMap__c temp :lstScoreSPETempMap){
              maptempSPEMap.put(temp.SPETemplate__r.Stage__c,temp.SPETemplate__c);
                 
              }
              system.debug('map is'+maptempSPEMap);
         if(maptempSPEMap.containskey('Draft'))
         alertflag = 'true';
      }
/////////////////////////////
              
                     
              if(currRecord.get(stage)=='Draft') {
              draft=false;
              Published=false;
              obsolete=false;
              Pilot=true;
              
              }
              if(currRecord.get(stage)=='Pilot') {
              draft=false;
              pilot=false;
              Published=true;
              obsolete=true;
              
              }
              if(currRecord.get(stage)=='Published') {
              draft=false;
              pilot=false;
              Published=false;
              obsolete=true;
              
              }
              if(currRecord.get(stage)=='obsolete') {
              draft=false;
              pilot=false;
              Published=false;
              obsolete=false;
              
              }
              

                }


        }
        
      public void StagePublished() {
      
      if(alertflag=='false'){
      currRecord.put(stage,'Published');
      update currRecord;    
      } 
      }
      
       public void StageObsolete() {
       currRecord.put(stage,'obsolete');
       update currRecord; 
      }
      
      public void StagePilot() {
       currRecord.put(stage,'Pilot');
       update currRecord; 
      }
}