src/objects/SPE_SPEPlan__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE Plans</relationshipLabel>
        <relationshipName>SPE_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>See SPE Process Guidelines</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SPE Plan</label>
    <nameField>
        <displayFormat>SPE - {00000}</displayFormat>
        <label>SPE Plan Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPETemplate__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>SPE Template can not be Published without a Scoring Template</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SPE Template</label>
    <nameField>
        <label>SPE Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Templates</pluralLabel>
    <recordTypes>
        <fullName>Obsolete</fullName>
        <active>true</active>
        <description>Obsolete record type for Obsolete lifecylce.</description>
        <label>Obsolete</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPETracker__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>SPEPlan__c</fullName>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>SPE Trackers</relationshipLabel>
        <relationshipName>SPE_Trackers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE Trackers</relationshipLabel>
        <relationshipName>SPE_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SPE Tracker</label>
    <nameField>
        <label>SPE Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SPE_SPEPlanTrigger.cls
public with sharing class SPE_SPEPlanTrigger
{
	public static void DeleteValidation(List<SPE_SPEPlan__c> oldSPEPlan)
	{
		for(SPE_SPEPlan__c rec : oldSPEPlan)
	    {
	    	List < SPE_SPETracker__c > lstTracker = [ Select Status__c FROM SPE_SPETracker__c where SPEPlan__c =: rec.id  ];
			
			for (SPE_SPETracker__c  tracker : lstTracker )
			{
				if (tracker.Status__c ==  'Completed')
				{
					rec.addError('You cannot delete SPE Plan for competed tracker status');
					break;
				}
			}
	    }
	}
	
	public static void UpdateSPETemplate(List<SPE_SPEPlan__c> newSPEPlans, Map<Id, SPE_SPEPlan__c> oldSPEPlanMaps)
	{	
		Set<Id> speTempIds = new Set<Id>();
		
		List<SPE_SPETracker__c> toBeUpdatedTracker = new List<SPE_SPETracker__c>();
		
		List<SPE_SPETemplate__c> toBeUpdatedSPETemplate = new List<SPE_SPETemplate__c>();
			
		for (SPE_SPEPlan__c spe : newSPEPlans)
		{
			if (spe.Stage__c == 'Published' && spe.Stage__c != oldSPEPlanMaps.get(spe.Id).Stage__c )
			{
				speTempIds.add(spe.SPETemplate__c);
			}
			
			else if (spe.Stage__c ==  'Obsolete')
			{
				List <SPE_SPETracker__c> lstTracker = [ Select Status__c FROM SPE_SPETracker__c where SPEPlan__c =: spe.id  ];
				
				for (SPE_SPETracker__c  tracker : lstTracker )
				{
					if (tracker.Status__c ==  'Pending')
                	{
                		tracker.Status__c = 'Abandoned';
                		
                		toBeUpdatedTracker.add(tracker);
                	}
				}
				
			}
		}
		
		if (speTempIds.size() > 0)
		{
			for (SPE_SPETemplate__c speTemplates : [SELECT Id, Stage__c FROM SPE_SPETemplate__c WHERE Id In: speTempIds AND Stage__c = 'Draft'])
			{
				SPE_SPETemplate__c speTemp = new SPE_SPETemplate__c();
				speTemp.Id = speTemplates.Id;
				speTemp.Stage__c = 'Published';
				
				toBeUpdatedSPETemplate.add(speTemp);
			}
		}
		
		update toBeUpdatedSPETemplate;
		update toBeUpdatedTracker;
	}
}