src/objects/SPE_Report_Parameter__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>CategoryCluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>SubRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE Report Parameter</label>
    <nameField>
        <displayFormat>PN-{00000000}</displayFormat>
        <label>Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Report Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_Scorecard_Report__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPE_Report_Parameter__c</fullName>
        <label>SPE Report Parameter</label>
        <referenceTo>SPE_Report_Parameter__c</referenceTo>
        <relationshipLabel>SPE_Scorecard_Report</relationshipLabel>
        <relationshipName>SPE_Scorecard_Report</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SPE_Tracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Tracker</label>
        <referenceTo>SPE_SPETracker__c</referenceTo>
        <relationshipLabel>SPE_Scorecard_Report</relationshipLabel>
        <relationshipName>SPE_Scorecard_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SPE_Scorecard_Report</relationshipLabel>
        <relationshipName>SPE_Scorecard_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>SPE_Scorecard_Report</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>SPE_Scorecard_Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE_Scorecard_Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_SPETracker__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <picklist>
            <picklistValues>
                <fullName>Global Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Planning and Optimization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mature Software Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Support Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEDIA AND ENTERTAINMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Broadband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio Frequency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single RAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio Cluster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM and Mature Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mature Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfect Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquid Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Creation Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FDD LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TD LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core Cluster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEM and OSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Cell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3G Core</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>GLOBAL SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATURE SOFTWARE PRODUCTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOBILE BROADBAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPTICAL NETWORKS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE Tracker</label>
    <nameField>
        <label>SPE Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SPEReportHybridLogic.cls
global class SPEReportHybridLogic{
    global List<AggregateResult> lstscorecardReport; 
    global String RepParam;
    global String negoResParam;
    global void hybridLogicCalc(String reportParamID, String negoResponsible){
        RepParam = reportParamID;
        negoResParam = negoResponsible;
        List<spe_scorecard_report__c> lstScorecardtoInsert = new List<spe_scorecard_report__C>();
        List<spe_scorecard_report__c> lstScorecardtoDelete = new List<spe_scorecard_report__C>();
        lstscorecardReport = new List<AggregateResult>();
        for(AggregateResult ar:[select avg(Score__c) avgscore,supplier__c supp,spe_tracker__r.BusinessLine__c BL,spe_tracker__r.BusinessUnit__c BU,
                                spe_tracker__r.Category__c Cat,spe_tracker__r.CategoryCluster__c CatArea,spe_tracker__r.CategoryGroup__c CGroup,
                                spe_tracker__r.Region__c Mkt,spe_tracker__r.SubRegion__c subMkt,spe_tracker__r.Country__c Cntry,spe_tracker__r.Product__c Prod,
                                spe_tracker__r.Project__c Proj
                                from spe_scorecard_report__c
                                where spe_tracker__r.Project__c!='All Projects' AND SPE_Report_Parameter__c = :reportParamID
                                group by supplier__c,spe_tracker__r.BusinessLine__c,spe_tracker__r.BusinessUnit__c,
                                spe_tracker__r.Category__c,spe_tracker__r.CategoryCluster__c,spe_tracker__r.CategoryGroup__c,
                                spe_tracker__r.Region__c,spe_tracker__r.SubRegion__c,spe_tracker__r.Country__c,spe_tracker__r.Product__c,
                                spe_tracker__r.Project__c]){
                                
                                
            lstScorecardtoInsert.add(new spe_scorecard_report__c(
                                     Score__c = (decimal)ar.get('avgscore'),SPE_Report_Parameter__c = reportParamID,
                                     Supplier__c = (String)ar.get('supp'),Weight__c = 1,
                                     Business_Line__c = (String)ar.get('BL'),Business_Unit__c = (String)ar.get('BU'),
                                     Category__c = (String)ar.get('Cat'),Category_Area__c = (String)ar.get('CatArea'),
                                     Category_Group__c = (String)ar.get('CGroup'),Country__c = (String)ar.get('Cntry'),
                                     Market__c = (String)ar.get('Mkt'),Market_Unit__c = (String)ar.get('subMkt'),
                                     Product__c = (String)ar.get('Prod'),Project__c = (String)ar.get('Proj')                                                                         
                                     ));                        
        
                                    
        }
        
        if(lstScorecardtoInsert.size() > 0){
            insert lstScorecardtoInsert;
        }
        
        
        
        // delete all the records except all projects
        
        lstScorecardtoDelete = [Select Id from spe_scorecard_report__c
                                where spe_tracker__r.Project__c!='All Projects' 
                                AND SPE_Report_Parameter__c = :reportParamID]; 
        if(lstScorecardtoDelete.size()>0){
            delete lstScorecardtoDelete;
          }  
        
        // execute the batch class for spend calculation
        
        SPE_SpendHybridLogicCalcBatch hybridbatch = new SPE_SpendHybridLogicCalcBatch(RepParam,negoResponsible);
        Database.executeBatch(hybridbatch,90);
        
                                
    }
    
    

}