src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Additional_Days__c</fullName>
        <description>Additional days for PI upload due date</description>
        <label>Additional Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Additional_Days_for_week__c</fullName>
        <label>Additional Days for week</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Day_name_of_upload_week__c</fullName>
        <description>Set a day of any week for PI upload</description>
        <label>Day name of upload week</label>
        <picklist>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Till this date PI upload will recur.</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Frequency with which the data is generally refreshed. Same as due date</description>
        <inlineHelpText>Specifies how often the data is posted or updated, i.e. monthly, annually, etc.</inlineHelpText>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>PI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Month_Upload_Day__c</fullName>
        <label>Month Upload Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_Value__c</fullName>
        <label>Month Value</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIUploadDuedate__c</fullName>
        <label>PI Upload Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of PI 
(Standard Name field of PI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>PI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurrence_Pattern__c</fullName>
        <description>This field holds the data for monthly/yearly child radio options to check which option is chosen.</description>
        <label>Recurrence Pattern</label>
        <picklist>
            <picklistValues>
                <fullName>DayPerMonth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeekPerMonth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DayPerYear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WeekPerYear</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recurrence_frequency_type__c</fullName>
        <description>Used in selection page of PI upload recurrence. It has two values- Monthly and Yearly.</description>
        <label>Recurrence frequency type</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Upload_Day__c</fullName>
        <description>PI upload day of any month.</description>
        <label>Upload Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_Count__c</fullName>
        <description>It holds week of any month</description>
        <label>Week Count</label>
        <picklist>
            <picklistValues>
                <fullName>First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fourth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Yearly_Day_Name_of_Upload_Week__c</fullName>
        <label>Yearly Day Name of Upload Week</label>
        <picklist>
            <picklistValues>
                <fullName>Sunday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tuesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wednesday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thursday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saturday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Yearly_Week_Count__c</fullName>
        <description>This field is used for Yearly Recurrence pattern.</description>
        <label>Yearly Week Count</label>
        <picklist>
            <picklistValues>
                <fullName>First</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fourth</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE2_PIUploadDateUpdateBatchTest.cls
@isTest(seeAllData=False)
public class SPE2_PIUploadDateUpdateBatchTest {
 

    
    public static testmethod void SPE2_PIUploadDateUpdateBatchTest1(){
 
        List<SPE_PIDefinition__c> lstPIDefObj = new List<SPE_PIDefinition__c>();
        for(Integer i=0;i<2;i++){
        SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
    
       
    PIDefObj.PIUploadDuedate__c = Date.newInstance(2016,2,15);
        PIDefObj.PI_Title__c = 'Test PI Definition+i';
         PIDefObj.Additional_Days__c = 2;
          
             PIDefObj.Day_name_of_upload_week__c ='';
             PIDefObj.Frequency__c ='2';
             PIDefObj.End_Date__c =Date.newInstance(2020,3,14);
             PIDefObj.Upload_Day__c =2;
            PIDefObj.Week_Count__c = 'Second';
           PIDefObj.Yearly_Day_Name_of_Upload_Week__c ='Wednesday';
           PIDefObj.Recurrence_frequency_type__c ='Monthly';
           PIDefObj.Additional_Days_for_week__c =3;
           PIDefObj.Yearly_Week_Count__c ='Fourth';
           PIDefObj.Month_Upload_Day__c =2;
           
           
          PIDefObj.Month_Value__c = 'September';
        PIDefObj.Recurrence_Pattern__c ='DayPerMonth';
       
        
        PIDefObj.LifecycleStage__c = 'Draft';
        lstPIDefObj.add(PIDefObj);
       }
        insert lstPIDefObj;

        for(Integer i=0;i<2;i++){
        lstPIDefObj[i].LifecycleStage__c= 'Pilot';
        lstPIDefObj[i].PIUploadDuedate__c = Date.newinstance(2020,01,15);
        }
        
        update lstPIDefObj;
          
    
        
      Test.startTest();
        
        SPE2_PIUploadDateUpdateBatch obj = new SPE2_PIUploadDateUpdateBatch();
        SchedulableContext scb = null;
        Database.BatchableContext bcb;
        obj.start(bcb);
        obj.execute(bcb,lstPIDefObj);
      
        obj.finish(bcb);
        
        Test.stopTest();    
    }
    
        
        
        public static testmethod void SPE2_PIUploadDateUpdateBatchTest2(){
 
        List<SPE_PIDefinition__c> lstPIDefObj2 = new List<SPE_PIDefinition__c>();
        for(Integer i=0;i<2;i++){
        SPE_PIDefinition__c PIDefObj2 = new SPE_PIDefinition__c();
    
       
    PIDefObj2.PIUploadDuedate__c = Date.newInstance(2016,2,15);
        PIDefObj2.PI_Title__c = 'Test PI Definition+i';
         PIDefObj2.Additional_Days__c = 2;
          
             PIDefObj2.Day_name_of_upload_week__c ='';
             PIDefObj2.Frequency__c ='2';
             PIDefObj2.End_Date__c =Date.newInstance(2020,3,14);
             PIDefObj2.Upload_Day__c =2;
            PIDefObj2.Week_Count__c = 'Second';
           PIDefObj2.Yearly_Day_Name_of_Upload_Week__c ='Wednesday';
           PIDefObj2.Recurrence_frequency_type__c ='Monthly';
           PIDefObj2.Additional_Days_for_week__c =3;
           PIDefObj2.Yearly_Week_Count__c ='Fourth';
           PIDefObj2.Month_Upload_Day__c =2;
           
           
          PIDefObj2.Month_Value__c = 'September';
        PIDefObj2.Recurrence_Pattern__c ='WeekPerMonth';
       
        
        PIDefObj2.LifecycleStage__c = 'Draft';
        lstPIDefObj2.add(PIDefObj2);
       }
        insert lstPIDefObj2;

        for(Integer i=0;i<2;i++){
        lstPIDefObj2[i].LifecycleStage__c= 'Pilot';
        lstPIDefObj2[i].PIUploadDuedate__c = Date.newinstance(2020,01,15);
        }
        
        update lstPIDefObj2;
          
    
        
      Test.startTest();
        
        SPE2_PIUploadDateUpdateBatch obj = new SPE2_PIUploadDateUpdateBatch();
        SchedulableContext scb = null;
        Database.BatchableContext bcb;
        obj.start(bcb);
        obj.execute(bcb,lstPIDefObj2);
      
        obj.finish(bcb);
        
        Test.stopTest();   
        
       
    }
    
     public static testmethod void SPE2_PIUploadDateUpdateBatchTest4(){
 
        List<SPE_PIDefinition__c> lstPIDefObj3 = new List<SPE_PIDefinition__c>();
        for(Integer i=0;i<2;i++){
        SPE_PIDefinition__c PIDefObj3 = new SPE_PIDefinition__c();
    
       
    PIDefObj3.PIUploadDuedate__c = Date.newInstance(2016,2,15);
        PIDefObj3.PI_Title__c = 'Test PI Definition+i';
         PIDefObj3.Additional_Days__c = 2;
          
             PIDefObj3.Day_name_of_upload_week__c ='';
             PIDefObj3.Frequency__c ='2';
             PIDefObj3.End_Date__c =Date.newInstance(2020,3,14);
             PIDefObj3.Upload_Day__c =2;
            PIDefObj3.Week_Count__c = 'Second';
           PIDefObj3.Yearly_Day_Name_of_Upload_Week__c ='Wednesday';
           PIDefObj3.Recurrence_frequency_type__c ='Yearly';
           PIDefObj3.Additional_Days_for_week__c =3;
           PIDefObj3.Yearly_Week_Count__c ='Second';
           PIDefObj3.Month_Upload_Day__c =2;
           
           
          PIDefObj3.Month_Value__c = 'September';
        PIDefObj3.Recurrence_Pattern__c ='WeekPerYear';
       
        
        PIDefObj3.LifecycleStage__c = 'Draft';
        lstPIDefObj3.add(PIDefObj3);
       }
        insert lstPIDefObj3;

        for(Integer i=0;i<2;i++){
        lstPIDefObj3[i].LifecycleStage__c= 'Pilot';
        lstPIDefObj3[i].PIUploadDuedate__c = Date.newinstance(2020,01,15);
        }
        
        update lstPIDefObj3;
          
    
        
      Test.startTest();
        
        SPE2_PIUploadDateUpdateBatch obj = new SPE2_PIUploadDateUpdateBatch();
        SchedulableContext scb = null;
        Database.BatchableContext bcb;
        obj.start(bcb);
        obj.execute(bcb,lstPIDefObj3);
      
        obj.finish(bcb);
        
        Test.stopTest();   
        
       
    } 
    public static testmethod void SPE2_PIUploadDateUpdateBatchTest3(){
 
        List<SPE_PIDefinition__c> lstPIDefObj3 = new List<SPE_PIDefinition__c>();
        for(Integer i=0;i<2;i++){
        SPE_PIDefinition__c PIDefObj3 = new SPE_PIDefinition__c();
    
       
    PIDefObj3.PIUploadDuedate__c = Date.newInstance(2016,2,15);
        PIDefObj3.PI_Title__c = 'Test PI Definition+i';
         PIDefObj3.Additional_Days__c = 2;
          
             PIDefObj3.Day_name_of_upload_week__c ='';
             PIDefObj3.Frequency__c ='2';
             PIDefObj3.End_Date__c =Date.newInstance(2020,3,14);
             PIDefObj3.Upload_Day__c =2;
            PIDefObj3.Week_Count__c = 'Second';
           PIDefObj3.Yearly_Day_Name_of_Upload_Week__c ='Wednesday';
           PIDefObj3.Recurrence_frequency_type__c ='Yearly';
           PIDefObj3.Additional_Days_for_week__c =3;
           PIDefObj3.Yearly_Week_Count__c ='Second';
           PIDefObj3.Month_Upload_Day__c =2;
           
           
          PIDefObj3.Month_Value__c = 'September';
        PIDefObj3.Recurrence_Pattern__c ='DayPerYear';
       
        
        PIDefObj3.LifecycleStage__c = 'Draft';
        lstPIDefObj3.add(PIDefObj3);
       }
        insert lstPIDefObj3;

        for(Integer i=0;i<2;i++){
        lstPIDefObj3[i].LifecycleStage__c= 'Pilot';
        lstPIDefObj3[i].PIUploadDuedate__c = Date.newinstance(2020,01,15);
        }
        
        update lstPIDefObj3;
          
    
        
      Test.startTest();
        
        SPE2_PIUploadDateUpdateBatch obj = new SPE2_PIUploadDateUpdateBatch();
        SchedulableContext scb = null;
        Database.BatchableContext bcb;
        obj.start(bcb);
        obj.execute(bcb,lstPIDefObj3);
      
        obj.finish(bcb);
        
        Test.stopTest();   
        
       
    } 

}