src/objects/SPE_ScoreCard__c.object
<CustomObject>
    <label>ScoreCard</label>
    <nameField>
        <label>Score Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScoreCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_ScorecardTempValues__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>SPE_ScorecardTempValues</relationshipLabel>
        <relationshipName>SPE_ScorecardTempValues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPE_TemplateName__c</fullName>
        <label>SPE Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScoreCard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ScoreCard</label>
        <referenceTo>SPE_ScoreCard__c</referenceTo>
        <relationshipLabel>SPE_ScorecardTempValues</relationshipLabel>
        <relationshipName>SPE_ScorecardTempValues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score_Weight__c</fullName>
        <formula>IF( ISNULL(Weight__c ) || ISBLANK(Weight__c ),  Score1__c ,  Weight__c * Score1__c)</formula>
        <label>Score*Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <formula>SPETracker__r.Score__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>SPE_ScorecardTempValues</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>SPE_ScorecardTempValues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE_ScorecardTempValues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_ScorecardValues__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>SPE ScorecardValues</relationshipLabel>
        <relationshipName>SPE_ScorecardValues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPE_Template_Name__c</fullName>
        <label>SPE Template Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScoreCard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ScoreCard</label>
        <referenceTo>SPE_ScoreCard__c</referenceTo>
        <relationshipLabel>SPE ScorecardValues</relationshipLabel>
        <relationshipName>SPE_ScorecardValues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>SPE ScorecardValues</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE ScorecardValues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_BatchScorecardGenerateTempValues3.cls
global class SPE_BatchScorecardGenerateTempValues3 implements Database.Batchable<sObject>,Schedulable  {


    global void execute(SchedulableContext sc) 
    {
        Database.executebatch(this,integer.valueOf(1));
    }

    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        
        Date dddd=system.today()-1;
        String query = 'SELECT Id FROM SPE_ScoreCard__c where createdDate>=:dddd';
        return Database.getQueryLocator(query);
    }




    global void execute(Database.BatchableContext BC, List <SPE_ScoreCard__c> scope) 
    {
       list<SPE_ScorecardTempValues__c> temp=new list<SPE_ScorecardTempValues__c>();
      temp=[select id from SPE_ScorecardTempValues__c where ScoreCard__c=:scope[0].id and Weight__c=Null];  
      
      if (temp.size()==0){
      list<SPE_ScorecardValues__c> tobeinserted= new list<SPE_ScorecardValues__c >();
   
    AggregateResult[] groupedResults =new List<AggregateResult>(); 
    groupedResults =[SELECT SPE_TemplateName__c,KPI__c,SUM(Score_Weight__c) sum,SUM(Weight__c) weight FROM SPE_ScorecardTempValues__c where ScoreCard__c=:scope[0].id and KPI__c!=Null GROUP BY SPE_TemplateName__c,KPI__c ];    
   
    for (AggregateResult ar : groupedResults)  {
        SPE_ScorecardValues__c s= new SPE_ScorecardValues__c();
        s.SPE_Template_Name__c=String.valueOf(ar.get('SPE_TemplateName__c'));
        s.score__c=Decimal.valueOf(String.valueOf(ar.get('sum')))/ Decimal.valueOf(String.valueOf(ar.get('weight')));
        s.scorecard__c=scope[0].id;
        s.kpi__c=String.valueOf(ar.get('KPI__c'));
        tobeinserted.add(s);
        }

    groupedResults = [SELECT SPE_TemplateName__c,Group__c,SUM(Score_Weight__c) sum,SUM(Weight__c) weight FROM SPE_ScorecardTempValues__c where ScoreCard__c=:scope[0].id and KPI__c=Null and Group__c!=Null GROUP BY SPE_TemplateName__c,Group__c ];    
   
    for (AggregateResult ar : groupedResults)  {
        SPE_ScorecardValues__c s= new SPE_ScorecardValues__c();
        s.SPE_Template_Name__c=String.valueOf(ar.get('SPE_TemplateName__c'));
        s.score__c=Decimal.valueOf(String.valueOf(ar.get('sum')))/ Decimal.valueOf(String.valueOf(ar.get('weight')));
        s.scorecard__c=scope[0].id;
        s.Group__c=String.valueOf(ar.get('Group__c'));
        tobeinserted.add(s);
        }
    
    
    groupedResults = [SELECT SPE_TemplateName__c,SUM(Score_Weight__c) sum,SUM(Weight__c) weight FROM SPE_ScorecardTempValues__c where ScoreCard__c=:scope[0].id and KPI__c=Null and Group__c=Null GROUP BY SPE_TemplateName__c ];    
   
    for (AggregateResult ar : groupedResults)  {
        SPE_ScorecardValues__c s= new SPE_ScorecardValues__c();
        s.SPE_Template_Name__c=String.valueOf(ar.get('SPE_TemplateName__c'));
        s.score__c=Decimal.valueOf(String.valueOf(ar.get('sum')))/ Decimal.valueOf(String.valueOf(ar.get('weight')));
        s.scorecard__c=scope[0].id;
        tobeinserted.add(s);
        }
       
        if(tobeinserted.size()>0)
           {
           delete [select id from SPE_ScorecardValues__c where ScoreCard__c=:scope[0].id];
           insert tobeinserted;
           }
        }
        
           
    }
    
    
    
    
    
    
    
    
    
    
    
    
    global void finish(Database.BatchableContext BC) 
    {        
    }
 }