src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>KPI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of KPI 
(Standard Name field of KPI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>See Guidelines; sets the number of buckets or scores.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PlanKPIMap__c.object
<CustomObject>
    <fields>
        <fullName>CMTicket__c</fullName>
        <label>CM Ticket Type</label>
        <picklist>
            <picklistValues>
                <fullName>Develop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Watchlist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>KPIScoreThreshold__c</fullName>
        <label>KPI Score Threshold</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>SPE Plan KPI Maps</relationshipLabel>
        <relationshipName>SPE_Plan_KPI_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PeriodRange__c</fullName>
        <defaultValue>3</defaultValue>
        <label>Period Range</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPEPlan__c</fullName>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>SPE Plan KPI Maps</relationshipLabel>
        <relationshipName>SPE_Plan_KPI_Maps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SPE Plan KPI Map</label>
    <nameField>
        <displayFormat>SPK-{000000}</displayFormat>
        <label>SPE Plan KPI Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plan KPI Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_SPEKPIMap__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>KPI Definition</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SPE_KPIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <filterItems>
                <field>SPE_KPIDefinition__c.PI_Data__r.ValuesType__c</field>
                <operation>notEqual</operation>
                <value>Boolean, String, Date</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>SPE KPI Maps</relationshipLabel>
        <relationshipName>SPE_KPI_Maps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE KPI Maps</relationshipLabel>
        <relationshipName>SPE_KPI_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SPE KPI Map</label>
    <nameField>
        <displayFormat>SKMI-{00000}</displayFormat>
        <label>SPE KPI Map Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE KPI Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPEPlan__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>AutoTicket__c</fullName>
        <label>Auto-Ticket</label>
        <picklist>
            <picklistValues>
                <fullName>OFF</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ON</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SPEPlanName__c</fullName>
        <label>SPE Plan Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE Plans</relationshipLabel>
        <relationshipName>SPE_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SPE Plan</label>
    <nameField>
        <displayFormat>SPE - {00000}</displayFormat>
        <label>SPE Plan Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_SPEPlanAutoCMTicketExt.cls
public with sharing class SPE_SPEPlanAutoCMTicketExt 
{
  public SPE_SPEPlan__c spePlan {get;set;}
  public List<SPE_PlanKPIMap__c> spePlanKPIMaps {get;set;}
  
  public SPE_SPEPlanAutoCMTicketExt (ApexPages.StandardController std)
  {
    std.addFields(new List<String>{'SPEPlanName__c', 'SPETemplate__c', 'AutoTicket__c'});
    this.spePlan = (SPE_SPEPlan__c)std.getRecord();
    
    spePlanKPIMaps = new List<SPE_PlanKPIMap__c>();
    initialize();
  }
  
  private void initialize()
  {
    //****************************************Changes For Encryption********************************//
    List<SPE_SPEKPIMap__c> spekpidef =[SELECT ID, KPIDefinition__c, KPIDefinition__r.Name,KPIDefinition__r.KPI_Title__c, KPIDefinition__r.Level__c 
                                           FROM SPE_SPEKPIMap__c 
                                           WHERE SPETemplate__c=:spePlan.SPETemplate__c];
    //****************************************END********************************//
    
    List<SPE_PlanKPIMap__c> planKPIs =[SELECT ID, CMTicket__c, KPI__c, KPIScoreThreshold__c, PeriodRange__c, SPEPlan__c
                                           FROM SPE_PlanKPIMap__c 
                                           WHERE SPEPlan__c=:spePlan.Id];
    
    Set<Id> kpiIds = new Set<Id>();
    
    for (SPE_PlanKPIMap__c spk: planKPIs)
    {
      SPE_PlanKPIMap__c planKPI = spk;
      kpiIds.add(spk.KPI__c);
      
      spePlanKPIMaps.add(planKPI);
    }
    for (SPE_SPEKPIMap__c sk : spekpidef)
    {
      if (! kpiIds.contains(sk.KPIDefinition__c))
      {
        SPE_PlanKPIMap__c planKPI = new SPE_PlanKPIMap__c();
        
        planKPI.KPI__c = sk.KPIDefinition__c;
        planKPI.SPEPlan__c = spePlan.Id; 
        
        spePlanKPIMaps.add(planKPI);  
      }
    }
  }
  
  public PageReference  Save()
  {
    upsert spePlanKPIMaps;
    update spePlan;
    
    return new ApexPages.StandardController(spePlan).view();
  }

}