src/objects/SPE_SurveyAnswer__c.object
<CustomObject>
    <description>For each Survey Question this object defines multiple Answers. The Answers have different types (Ex. Free text, Picklist, single answer etc.).</description>
    <fields>
        <fullName>Choices__c</fullName>
        <description>Choices for the particular question.</description>
        <inlineHelpText>User can have choices for a particular question.</inlineHelpText>
        <label>Choices</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrimarySurvey_Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PrimarySurvey Answer</label>
        <referenceTo>SPE_SurveyAnswer__c</referenceTo>
        <relationshipLabel>Survey Answers</relationshipLabel>
        <relationshipName>Survey_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Language__c</fullName>
        <description>To store secondary Language</description>
        <label>Secondary Language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <description>Automatically captures Questions while creating answers under Question Object.</description>
        <inlineHelpText>User can select questions for which they are creating answers.</inlineHelpText>
        <label>SurveyQuestion</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipName>SPE_SurveyAnswers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Answer</label>
    <nameField>
        <displayFormat>Ans-{00000}</displayFormat>
        <label>Answers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_SurveyQuestion__c.object
<CustomObject>
    <customHelpPage>SPE_QuestionBank_Survey_Help_Page</customHelpPage>
    <description>SurveyQuestion object contains Question banks for the survey.</description>
    <fields>
        <fullName>Parent_Survey_Question__c</fullName>
        <label>Parent Survey Question</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Question Bank</label>
        <referenceTo>SPE_SurveyQuestion__c</referenceTo>
        <relationshipLabel>Alternate Language Question Bank</relationshipLabel>
        <relationshipName>Question_Bank</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Language__c</fullName>
        <label>Alternate Language</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SurveyQuestion__c</fullName>
        <description>Question which will appear on Survey page</description>
        <inlineHelpText>Enter your question</inlineHelpText>
        <label>Survey Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question Bank</label>
    <nameField>
        <label>Questions ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE2_AddQuestionAnswerExtTest.cls
@isTest(SeeAllData = true) 
private class SPE2_AddQuestionAnswerExtTest {
    boolean cloneAltrLang{get;set;}
    static testMethod void positiveMethod()
    {       
        SPE_SurveyQuestion__c surQues=SPE_TestObjectCreator.CreateSurveyQuestion();
        insert surQues;
        SPE_SurveyAnswer__c surAns1=SPE_TestObjectCreator.CreateSurveyAnswer();
        surAns1.SurveyQuestion__c=surQues.Id;
        insert surAns1;
        SPE_SurveyAnswer__c surAns2=SPE_TestObjectCreator.CreateSurveyAnswer();
        surAns2.SurveyQuestion__c=surQues.Id;
        insert surAns2;
              
        SPE_SurveyQuestion__c altrSurveyQues1=SPE_TestObjectCreator.CreateSurveyQuestion(); 
        altrSurveyQues1.Parent_Survey_Question__c = surQues.SurveyQuestion__c;
        altrSurveyQues1.Question_Bank__c=surQues.Id;
        altrSurveyQues1.Secondary_Language__c='Albanian';
        insert altrSurveyQues1;
        
        SPE_SurveyAnswer__c altrSurAns1=SPE_TestObjectCreator.CreateSurveyAnswer();
        altrSurAns1.SurveyQuestion__c=altrSurveyQues1.Id;
        altrSurAns1.PrimarySurvey_Answer__c=surAns1.Id;
        insert altrSurAns1; 
        SPE_SurveyAnswer__c altrSurAns2=SPE_TestObjectCreator.CreateSurveyAnswer();
        altrSurAns2.SurveyQuestion__c=surQues.Id;
        insert altrSurAns2;
        
        altrSurAns1.Choices__c='white';
        update altrSurAns1;
       
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(surQues);
        SPE2_AddQuestionAnswerExt addQueAns = new SPE2_AddQuestionAnswerExt(stCon);
        Apexpages.currentPage().getParameters().put('isClone', 'true'); 
            
        addQueAns.speSurvey = SPE_TestObjectCreator.CreateSurveyQuestion();
        addQueAns.addAnswers();      
        addQueAns.speAnswers[0] = SPE_TestObjectCreator.CreateSurveyAnswer();
        
        addQueAns.speAnswers[1] = SPE_TestObjectCreator.CreateSurveyAnswer();
        
        Apexpages.currentPage().getParameters().put('rowIndex', '1');
        
        addQueAns.deleteQuestionAnswer();
        
        addQueAns.addAnswers();      
        addQueAns.speAnswers[0] = SPE_TestObjectCreator.CreateSurveyAnswer();
     
        addQueAns.speAnswers[1] = SPE_TestObjectCreator.CreateSurveyAnswer();
  
        Apexpages.currentPage().getParameters().put('rowIndex', '1');
        addQueAns.cloneAltrLang=true;
        addQueAns.addAnswers();
        addQueAns.addAnswers();
        
        addQueAns.save();
        addQueAns.cancelQuestion();
        List<SPE_SurveyAnswer__c> ansList=new List<SPE_SurveyAnswer__c>();
        ansList.add(surAns1);
        ansList.add(surAns2);
        
        
        
        addQueAns.deleteAllAnswer();   
        
    }
    static testMethod void NegativeMethod()
    {
         Apexpages.currentPage().getParameters().put('isClone', 'false');
        SPE_SurveyQuestion__c surQue=SPE_TestObjectCreator.CreateSurveyQuestion();
        
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(surQue);
        SPE2_AddQuestionAnswerExt addQuesAns = new SPE2_AddQuestionAnswerExt(stCon);
   
        addQuesAns.isDuplicate = true;
                     
        SPE_SurveyQuestion__c surQues=SPE_TestObjectCreator.CreateSurveyQuestion();
        insert surQues;
        SPE_SurveyAnswer__c surAns1=SPE_TestObjectCreator.CreateSurveyAnswer();
        surAns1.SurveyQuestion__c=surQues.Id;
        insert surAns1;
        SPE_SurveyAnswer__c surAns2=SPE_TestObjectCreator.CreateSurveyAnswer();
        surAns2.SurveyQuestion__c=surQues.Id;
        insert surAns2;
        surAns2.Choices__c='White';
        update surAns2;
        
        SPE_SurveyQuestion__c altrSurveyQues1=SPE_TestObjectCreator.CreateSurveyQuestion(); 
        altrSurveyQues1.Parent_Survey_Question__c = surQues.SurveyQuestion__c;
        altrSurveyQues1.Question_Bank__c=surQues.Id;
        altrSurveyQues1.Secondary_Language__c='Albanian';
        insert altrSurveyQues1;
        
        SPE_SurveyAnswer__c altrSurAns1=SPE_TestObjectCreator.CreateSurveyAnswer();
        altrSurAns1.SurveyQuestion__c=altrSurveyQues1.Id;
        altrSurAns1.PrimarySurvey_Answer__c=surAns1.Id;
        insert altrSurAns1;
        
        list<SPE_SurveyQuestion__c> QuestList=[select Id,Question_Bank__c from SPE_SurveyQuestion__c where Question_Bank__c= :surQues.Id];
        list<SPE_SurveyQuestion__c> QuestListClone= QuestList.deepClone();
       
                    
        Apexpages.Standardcontroller stCon1 =  new Apexpages.Standardcontroller(surQues);
        Apexpages.currentPage().getParameters().put('isClone', 'false');
        
        SPE2_AddQuestionAnswerExt addQueAns = new SPE2_AddQuestionAnswerExt(stCon1);
         
        addQueAns.isDuplicate = true;
        addQueAns.save();

    }
     static testMethod void cloneQuestionAns()
    {
       
        SPE_SurveyQuestion__c surQues=SPE_TestObjectCreator.CreateSurveyQuestion();
        insert surQues;
        SPE_SurveyAnswer__c surAns1=SPE_TestObjectCreator.CreateSurveyAnswer();
        surAns1.SurveyQuestion__c=surQues.Id;
        surAns1.Choices__c = 'White';
        insert surAns1;
        SPE_SurveyAnswer__c surAns2=SPE_TestObjectCreator.CreateSurveyAnswer();
        surAns2.SurveyQuestion__c=surQues.Id;
        surAns2.Choices__c = 'Black';
        insert surAns2;
              
        SPE_SurveyQuestion__c altrSurveyQues1=SPE_TestObjectCreator.CreateSurveyQuestion(); 
        altrSurveyQues1.Parent_Survey_Question__c = surQues.SurveyQuestion__c;
        altrSurveyQues1.Question_Bank__c=surQues.Id;
        altrSurveyQues1.Secondary_Language__c='Albanian';
        insert altrSurveyQues1;
        
        SPE_SurveyAnswer__c altrSurAns1=SPE_TestObjectCreator.CreateSurveyAnswer();
        altrSurAns1.SurveyQuestion__c=altrSurveyQues1.Id;
        altrSurAns1.PrimarySurvey_Answer__c=surAns1.Id;
        insert altrSurAns1; 
        SPE_SurveyAnswer__c altrSurAns2=SPE_TestObjectCreator.CreateSurveyAnswer();
        altrSurAns2.SurveyQuestion__c=altrSurveyQues1.Id;
        altrSurAns2.PrimarySurvey_Answer__c=surAns2.Id;
        insert altrSurAns2;
        
        Apexpages.currentPage().getParameters().put('isClone', 'true'); 
       
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(surQues);
        SPE2_AddQuestionAnswerExt addQueAns = new SPE2_AddQuestionAnswerExt(stCon);
        addQueAns.cloneAltrLang=true;
        
        addQueAns.save();
        addQueAns.addAnswers();
        addQueAns.cancelQuestion();
      
    }
     static testMethod void NegativeClone()
    {
        SPE_SurveyQuestion__c surQ = SPE_TestObjectCreator.CreateSurveyQuestion();
        insert surQ;
        Apexpages.Standardcontroller stCon =  new Apexpages.Standardcontroller(surQ);               
        SPE2_AddQuestionAnswerExt addQueAns = new SPE2_AddQuestionAnswerExt(stCon);
        
        addQueAns.save();
        addQueAns.addAnswers();
        addQueAns.cancelQuestion();              
    }
}