src/objects/SPE_ScorecardGenerator__c.object
<CustomObject>
    <fields>
        <fullName>Aggregation_Period_Adhoc__c</fullName>
        <label>Aggregation Period</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isAdhoc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isAdhoc?</label>
        <type>Checkbox</type>
    </fields>
    <label>Scorecard Generator</label>
    <nameField>
        <label>Generate Score Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scorecard Generators</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_ScorecardTracker__c.object
<CustomObject>
    <fields>
        <fullName>DateOfExecution__c</fullName>
        <label>Date Of Execution</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ScorecardGenerator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scorecard Generator</label>
        <referenceTo>SPE_ScorecardGenerator__c</referenceTo>
        <relationshipLabel>Scorecard Trackers</relationshipLabel>
        <relationshipName>Scorecard_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tracker_Identifier__c</fullName>
        <label>Tracker Identifier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Scorecard Tracker</label>
    <nameField>
        <label>Scorecard Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scorecard Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE2PastTrckrExecBatch.cls
global class SPE2PastTrckrExecBatch implements Database.Batchable<sObject>{
    global String query;
    global String scIdentifier;
    global SPE2PastTrckrExecBatch(String identifier){
        query = 'select Id,ScorecardGenerator__r.isAdhoc__c,Name,ScorecardGenerator__r.Aggregation_Period_Adhoc__c,Tracker_Identifier__c, DateOfExecution__c FROM SPE_ScorecardTracker__c Where Tracker_Identifier__c ='+'\''+identifier+'\'';
        scIdentifier = identifier;
        //system.now()+';'+userInfo.getUserId();                                                                        
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('query:12:'+query);
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<sObject>scope){
        for(sobject obj :scope){
            SPE_ScorecardTracker__c trkr = (SPE_ScorecardTracker__c)obj;
            ApexPages.StandardController sc = new ApexPages.StandardController(trkr);
            SPE2_ScorecardTrackerExecutionExt trck = new SPE2_ScorecardTrackerExecutionExt(sc); 
            trck.fetchTrackers(scIdentifier,false);
        }        
    }
    global void finish(Database.BatchableContext BC){
        if(!Test.isRunningTest()){
            SPE2_AutoScorecardGenerate dtbatch= new SPE2_AutoScorecardGenerate(scIdentifier);
            database.executebatch(dtBatch,1);
        }
        //SPE2_ScorecardAutoGenerateValues dtbatch= new SPE2_ScorecardAutoGenerateValues(scIdentifier);
        //database.executebatch(dtBatch,1);
    }
}