src/objects/SPE_ScorecardTemplate__c.object
<CustomObject>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <picklist>
            <picklistValues>
                <fullName>All Project</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AF AWCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMC 2G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL VODAFONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL M4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL PLUS Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ Ooredoo Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ.Orascom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria Telecom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTi Movil ARG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Telefonica Panama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR CTi Movil 3G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR Cablevision NGN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR Telecom Personal 3G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR Telecom PDH/SDH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR Claro Argentina SWAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR TECO TDM Evolution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nextel Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM Orange</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vodafone Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU DoT DTRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU NBN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT H3G Old</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT Netco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT Caldera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT H3G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT A1 Austria Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT Orange Austria Care</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScorecardTemplateId__c</fullName>
        <displayFormat>STMP-{000000}</displayFormat>
        <label>Scorecard Template Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>See SPE Process Guidelines</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Market Unit</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Scorecard Template</label>
    <nameField>
        <label>Scorecard Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scorecard Templates</pluralLabel>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <label>Draft</label>
    </recordTypes>
    <recordTypes>
        <fullName>Obsolete</fullName>
        <active>true</active>
        <label>Obsolete</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_ScorecardTemplateBulkUpdateExt.cls
public with sharing class SPE_ScorecardTemplateBulkUpdateExt 
{
    public List<Selectoption> fromStageList {get;set;}
    public List<Selectoption> toStageList {get;set;}
    
    public String fromStage {get;set;}
    public String toStage {get;set;}
    
     transient public Boolean sendNotification {get;set;} 
    
    public List<ScorecardTempTempWrapper> ScorecardTempWrapperList {get;set;}
    
    public SPE_ScorecardTemplateBulkUpdateExt (Apexpages.StandardSetcontroller stCon)
    {
        fromStage = 'Draft';
    
        initialize();
        searchScorecardTemps();
    }
    
    public void initialize()
    {
        ScorecardTempWrapperList= new List<ScorecardTempTempWrapper>();
        
        fromStageList = new List<SelectOption>();
        fromStageList.add(new SelectOption('Draft','Draft'));
        fromStageList.add(new SelectOption('Published','Published'));
        
        toStageList = new List<SelectOption>();
        toStageList.add(new SelectOption('Published','Published'));
        toStageList.add(new SelectOption('Obsolete','Obsolete'));
    }
    
    public void searchScorecardTemps()
    {
        ScorecardTempWrapperList.clear();
        
        for (SPE_ScorecardTemplate__c k : [SELECT Id, Name,OwnerId,Stage__c,Category__c,CategoryGroup__c,CategoryCluster__c,Region__c,SubRegion__c,Country__c,Project__c,ScorecardTemplateId__c
                                       FROM SPE_ScorecardTemplate__c
                                       WHERE  Stage__c=: fromStage LIMIT 100])
        {
            
            ScorecardTempTempWrapper kw = new ScorecardTempTempWrapper(k);  
            ScorecardTempWrapperList.add(kw);
        }
    }
    
    public void updateScorecardTemps ()
    {
        List<SPE_ScorecardTemplate__c> toBeUpdateScorecardTempDefinitions=  new List<SPE_ScorecardTemplate__c>();
        
        if(sendNotification)
        {
            List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
            OrgWideEmailAddress owe = [SELECT ID,IsAllowAllProfiles,DisplayName,Address FROM OrgWideEmailAddress Where DisplayName like 'SPE Admin' ];
            EmailTemplate emailTemplate =[Select id,Name from EmailTemplate where name=:'SPE_ScorecardTemplateStageChangeNotification'];
        
        for (ScorecardTempTempWrapper  kw : ScorecardTempWrapperList)
        {
             Messaging.SingleEmailMessage mail =  new Messaging.SingleEmailMessage();
             
            if (kw.isChecked)
            {
                SPE_ScorecardTemplate__c updatedScorecardTemp = new SPE_ScorecardTemplate__c();
                updatedScorecardTemp = kw.ScoreTemp;
                updatedScorecardTemp.Stage__c= toStage;
                
                mail.setTargetObjectId(kw.ownerId);
                    mail.setOrgWideEmailAddressId(owe.Id);
                    
                    System.debug('UserId======>' + kw.ownerId);
                    
                    mail.setTemplateId(emailTemplate.id);
                    mail.setSaveAsActivity(false);
                    mail.setUseSignature(false);
                    System.debug('UserId======>' + kw.kpiId);
                    mail.setWhatId(kw.kpiId);
                    mails.add(mail);
                
                toBeUpdateScorecardTempDefinitions.add(updatedScorecardTemp);           
            }
        }
        
        update toBeUpdateScorecardTempDefinitions;
        
             Messaging.sendEmail(mails);
             mails.clear();
        }
        else
        {
            for (ScorecardTempTempWrapper  kw : ScorecardTempWrapperList)
            {
                if (kw.isChecked)
                {
                   SPE_ScorecardTemplate__c updatedScorecardTemp = new SPE_ScorecardTemplate__c();
                   updatedScorecardTemp = kw.ScoreTemp;
                   updatedScorecardTemp.Stage__c= toStage;
                    
                    toBeUpdateScorecardTempDefinitions.add(updatedScorecardTemp);
                }
            }
            update toBeUpdateScorecardTempDefinitions;
        }
        
        sendNotification = false;
        initialize();
        searchScorecardTemps();
    }
    
    public class ScorecardTempTempWrapper
    {
        public SPE_ScorecardTemplate__c ScoreTemp {get;set;}
        public Boolean isChecked {get;set;}
        public Id ownerId {get;set;}
        public Id kpiId {get;set;}
        
        public ScorecardTempTempWrapper(SPE_ScorecardTemplate__c Kpis)
        {
            ScoreTemp = Kpis;
            isChecked = false;
            this.ownerId = kpis.OwnerId;
            kpiId = kpis.Id;
        }
    }
}