src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>See Guidelines; sets the number of buckets or scores.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Master_KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI (Master KPI)</relationshipLabel>
        <relationshipName>KPI1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VerNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <label>VerNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>&apos;Version-&apos;+TEXT(VerNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_ScoringTemplate__c.object
<CustomObject>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>Scoring Templates</relationshipLabel>
        <relationshipName>Scoring_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Scoring Template</label>
    <nameField>
        <label>Scoring Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPEKPIMap__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>KPI Definition</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SPE_KPIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <filterItems>
                <field>SPE_KPIDefinition__c.PI_Data__r.ValuesType__c</field>
                <operation>notEqual</operation>
                <value>Boolean, String, Date</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>SPE KPI Maps</relationshipLabel>
        <relationshipName>SPE_KPI_Maps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE KPI Maps</relationshipLabel>
        <relationshipName>SPE_KPI_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>KPIDefinition__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <label>SPE KPI Map</label>
    <nameField>
        <displayFormat>SKMI-{00000}</displayFormat>
        <label>SPE KPI Map Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE KPI Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPETemplate__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>SPE Template can not be Published without a Scoring Template</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SPE Template</label>
    <nameField>
        <label>SPE Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Templates</pluralLabel>
    <recordTypes>
        <fullName>Pilot</fullName>
        <active>true</active>
        <description>Change the record type to Pilot when lifecycle stage is pilot</description>
        <label>Pilot</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_versionLinkageExt.cls
public class SPE_versionLinkageExt 
{
    public String versionId{get;set;}
    public string Lifecycle{get;set;}
    public String SobjectName{get;set;}
    public List<SPE_SPEKPIMap__c> kpimap{get;set;}
    public SPE_KPIDefinition__c kdef{get;set;}
    public String msg{get;set;}
    public List<VersionLinkageWrapper> linkList{get;set;}
    
    
    public SPE_versionLinkageExt()
    {    
        
        linkList = new List<VersionLinkageWrapper>();
        versionId=apexpages.currentpage().getparameters().get('id');
        Lifecycle=apexpages.currentpage().getparameters().get('Lifecycle');
        
        SobjectName=(Id.valueOf(versionId).getSObjectType().getDescribe().getName());
        
        if(SobjectName=='SPE_KPIDefinition__c') { 
          
          kdef = new SPE_KPIDefinition__c();
          List<SPE_KPIDefinition__c> KpidefntList = new List<SPE_KPIDefinition__c>();
           kpimap = new List<SPE_SPEKPIMap__c>();
          
           kdef = [select id,Master_KPI__c,VerNumber__c,Version__c,LifecycleStage__c,Level__c from SPE_KPIDefinition__c where id =: versionId];
           
           if(Lifecycle=='Pilot'){
               if(kdef.Master_KPI__c != null)
               {
                   KpidefntList = [select id,Master_KPI__c,Version__c,VerNumber__c from SPE_KPIDefinition__c where Master_KPI__c =: kdef.Master_KPI__c and (LifecycleStage__c ='Pilot' or LifecycleStage__c ='Published') order by VerNumber__c DESC];
                   system.debug('*******KPILIST********' + KpidefntList );
               }
               
               if(KpidefntList.size() > 0 && KpidefntList[0].VerNumber__c < kdef.VerNumber__c)
               {
                   kpimap = [select id,SPETemplate__r.name,SPETemplate__c,Owner.name,SPETemplate__r.Stage__c,KPIDefinition__c  from SPE_SPEKPIMap__c where KPIDefinition__c =: KpidefntList[0].id and SPETemplate__r.Stage__c = 'Pilot'];
                   system.debug('*******SPETEMPLATE********' + kpimap);               
               }
               
           }
           
           if(Lifecycle=='Published'){
               if(kdef.Master_KPI__c != null)
               {
                   KpidefntList = [select id,Master_KPI__c,Version__c,VerNumber__c from SPE_KPIDefinition__c where Master_KPI__c =: kdef.Master_KPI__c and LifecycleStage__c ='Published' order by VerNumber__c DESC];
                   system.debug('*******KPILIST********' + KpidefntList );
               }
               
               if(KpidefntList.size() > 0 && KpidefntList[0].VerNumber__c < kdef.VerNumber__c)
               {
                   kpimap = [select id,SPETemplate__r.name,SPETemplate__c,Owner.name,SPETemplate__r.Stage__c,KPIDefinition__c from SPE_SPEKPIMap__c where KPIDefinition__c =: KpidefntList[0].id and SPETemplate__r.Stage__c = 'Published'];
                   system.debug('*******SPETEMPLATE********' + kpimap);               
               }
               
           }
           
           for(SPE_SPEKPIMap__c kmap : kpimap)
               {
                   linkList.add(new VersionLinkageWrapper(kmap.SPETemplate__c,kmap.SPETemplate__r.name,kmap.Owner.name,kmap.SPETemplate__r.Stage__c,kmap.KPIDefinition__c,kdef.Level__c));
               }
        }
    } 
    
    public void updateKPI()
    {        
               kdef.LifecycleStage__c =Lifecycle;
               update kdef;
             
    }
    
    
    public class VersionLinkageWrapper
    {
        public List<SPE_ScoringTemplate__c> ScorTmpList{get;set;}
        public string SPETempName{get;set;}
        public string SpeOwner{get;set;}
        public string Stage{get;set;}
        public Id sptemId{get;set;}
        public boolean Redcolor{get;set;}
        public VersionLinkageWrapper(Id SPETempId,String SPEName,String own,String Stg,Id KPIDef,string currlevels)
        {   
            integer cLevels=0;
            integer eleves=0;
            Redcolor=false;
            SPE_KPIDefinition__c ExistingKPIdef = new SPE_KPIDefinition__c();
            ExistingKPIdef =[select id,level__c from SPE_KPIDefinition__c where id=:KPIDef];
            Redcolor=false;
            list<string> ExisLevels=(ExistingKPIdef.level__c).split(';');
            list<string> currentLevels=(currlevels).split(';');
            if(currentLevels.size()!=ExisLevels.size()){
                Redcolor=true;
            }
            else{
            for(string s:currentLevels)
                cLevels=cLevels+integer.valueof(s);
             for(string s:ExisLevels)
                eleves=eleves+integer.valueof(s);    
            
            if(cLevels!=eleves)
                Redcolor=true;
            }
            
            SPETempName= SPEName;
            SpeOwner= own;
            Stage= stg;
            sptemId = SPETempId;
            ScorTmpList = new List<SPE_ScoringTemplate__c>();
            
            ScorTmpList = [select id,name,Stage__c,Owner.name from SPE_ScoringTemplate__c where SPETemplate__c =: SPETempId];
        }
    }
}