src/objects/SPE_KPICalculation__c.object
<CustomObject>
    <fields>
        <fullName>Aggregation__c</fullName>
        <label>Aggregation</label>
        <picklist>
            <picklistValues>
                <fullName>Min</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Min( Across Suppliers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max( Across Suppliers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg( Across Suppliers)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ConstantValue__c</fullName>
        <label>Constant Value</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDefination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Defination</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please Select a Published PI</errorMessage>
            <filterItems>
                <field>SPE_PIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeFrame__c</fullName>
        <label>Time Frame (In Months)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KPI Calculation</label>
    <nameField>
        <displayFormat>KCal-{00000}</displayFormat>
        <label>KPI Calculation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPEKPIBatchSize__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To set the size of the KPI Batch</description>
    <fields>
        <fullName>Size__c</fullName>
        <inlineHelpText>Enter the Batch size in number . It should be less than 2000</inlineHelpText>
        <label>Size</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SPE KPI Batch Size</label>
</CustomObject>

src/objects/Supplier_KPI_Calculation_Adhoc__c.object
<CustomObject>
    <fields>
        <fullName>KPI_Calculation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Calculation</label>
        <referenceTo>SPE_KPICalculation__c</referenceTo>
        <relationshipLabel>Supplier KPI Calculation Adhoc</relationshipLabel>
        <relationshipName>Supplier_KPI_Calculation_Adhoc</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Supplier KPI Calculation Adhoc</relationshipLabel>
        <relationshipName>Supplier_KPI_Calculation_Adhoc</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier KPI Calculation Adhoc</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>Supplier KPI Calculation Adhoc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier KPI Calculation Adhoc</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_KPISchedulebatch3Adhoc.cls
global class SPE_KPISchedulebatch3Adhoc implements Database.Batchable <sObject> , Schedulable 
{
    
    global Id kpiIds;
    
    public SPE_KPISchedulebatch3Adhoc (String s)
    {
        kpiIds = s;
    }
    
    
    global void execute(SchedulableContext sc) 
    {
        Database.executebatch(this,10000);
    }

    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        Date d=system.today();
        Set<string> k=new set<string>();
        k.add('Constant');
        k.add('Min( Across Suppliers)');
        k.add('Max( Across Suppliers)');
        k.add('Avg( Across Suppliers)');
        
        Id kpiId = this.kpiIds;
        
        String query='select id,PIDefination__c,TimeFrame__c,ConstantValue__c,KPIDefinition__c,Aggregation__c,index__c from SPE_KPICalculation__c where KPIDefinition__c =: kpiId and Aggregation__c NOT IN:k';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List <SPE_KPICalculation__c> scope) 
    {
        List<Supplier_KPI_Calculation_Adhoc__c> skc= new list<Supplier_KPI_Calculation_Adhoc__c>();
        for(SPE_KPICalculation__c k:scope)
        {
            Supplier_KPI_Calculation_Adhoc__c p = new Supplier_KPI_Calculation_Adhoc__c();
            
            p.KPI__c=k.KPIDefinition__c;
            p.KPI_Calculation__c=k.id;
            skc.add(p);
        }
      
        insert skc;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
     
        SPE_KPIScheduleFinalbatchAdhoc dtBatch= new SPE_KPIScheduleFinalbatchAdhoc(kpiIds); 
        if(!Test.isRunningTest()){
        database.executebatch(dtBatch,Integer.valueof((SPEKPIBatchSize__c.getInstance('KPI Batch Size')).Size__c)); 
        }
    }
}