src/objects/SPE_SPETracker__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>DateOfExecution__c</fullName>
        <label>Date Of Execution</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE Trackers</relationshipLabel>
        <relationshipName>SPE_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score_1_Upper_Bound__c</fullName>
        <label>Score 1 Upper Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_2_Lower_Bound__c</fullName>
        <label>Score 2 Lower Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_2_Upper_Bound__c</fullName>
        <label>Score 2 Upper Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_3_Loewr_Bound__c</fullName>
        <label>Score 3 Loewr Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_3_Upper_Bound__c</fullName>
        <label>Score 3 Upper Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_4_Lower_Bound__c</fullName>
        <label>Score 4 Lower Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_4_Upper_Bound__c</fullName>
        <label>Score 4 Upper Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE Tracker</label>
    <nameField>
        <label>SPE Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_TrackerScore__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Pillar</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>SPETracker__r.Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>SPETracker__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPETracker__c</fullName>
        <label>SPE Tracker</label>
        <referenceTo>SPE_SPETracker__c</referenceTo>
        <relationshipLabel>Tracker Scores</relationshipLabel>
        <relationshipName>Tracker_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SPE_Rank__c</fullName>
        <label>SPE Rank</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPE_TemplateName__c</fullName>
        <formula>SPETracker__r.SPETemplate__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SPE Template Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Tracker Score</label>
    <nameField>
        <displayFormat>Score-{0000}</displayFormat>
        <label>Tracker Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracker Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_TrackerValues__c.object
<CustomObject>
    <fields>
        <fullName>Avg_Piller_Score__c</fullName>
        <label>Avg Pillar Score</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DataLogic__c</fullName>
        <label>Data Logic</label>
        <picklist>
            <picklistValues>
                <fullName>Actual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Derived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assumed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indicator</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DateOfExecution__c</fullName>
        <formula>SPETracker__r.DateOfExecution__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DateOfExecution</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EncryptedEnterpriseId__c</fullName>
        <encrypted>true</encrypted>
        <label>Enterprise ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseId__c</fullName>
        <formula>&apos;True&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enterprise ID DeprecatedDoNotUse</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <formula>TEXT(KPIDefinition__r.Group1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Tracker Value</relationshipLabel>
        <relationshipName>Tracker_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPIGroup__c</fullName>
        <label>Group</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogicAnnotation__c</fullName>
        <label>Logic Annotation</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MAX_Piller_score__c</fullName>
        <label>MAX Pillar score</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Piller_Score__c</fullName>
        <label>Min Pillar Score</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MissingDatalogic__c</fullName>
        <label>Missing Data logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Percentile__c</fullName>
        <formula>IF(Score__c  == 0, 0,(( Score__c )/ 5 ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Percentile</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Pillar_Rank__c</fullName>
        <label>Pillar Rank</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Piller__c</fullName>
        <formula>TEXT(KPIDefinition__r.Group1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pillar</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Piller_score__c</fullName>
        <formula>( Vlauecalculation__c/ Sumofpillerweight__c)*100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pillar score</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <formula>SPETracker__r.Product__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>SPETracker__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>SPETracker__r.Region__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPEPlanId__c</fullName>
        <formula>SPETracker__r.SPEPlan__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SPE Plan Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <formula>CASESAFEID(SPETracker__r.SPETemplate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SPE Template</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPETracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Tracker</label>
        <referenceTo>SPE_SPETracker__c</referenceTo>
        <relationshipLabel>Tracker Value</relationshipLabel>
        <relationshipName>Tracker_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPE_Rank__c</fullName>
        <label>SPE Rank</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPE_Score__c</fullName>
        <label>SPE Score</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPE_TemplateName__c</fullName>
        <formula>SPETracker__r.SPETemplate__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SPE Template Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score1__c</fullName>
        <label>Score1</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ScoreResult__c</fullName>
        <formula>If(Score__c == 1.00,&apos;Un accepatble&apos;,IF(Score__c == 2.00, &apos;NI&apos; ,IF(Score__c == 3.00, &apos;Meets req.&apos;, IF(Score__c == 4.00, &apos;Good&apos;,&apos;&apos;))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Score Result</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score_1_Lower_Bound__c</fullName>
        <label>Score 1 Lower Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_1_Upper_Bound__c</fullName>
        <label>Score 1 Upper Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_2_Lower_Bound__c</fullName>
        <label>Score 2 Lower Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_2_Upper_Bound__c</fullName>
        <label>Score 2 Upper Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_3_Loewr_Bound__c</fullName>
        <label>Score 3 Loewr Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_3_Upper_Bound__c</fullName>
        <label>Score 3 Upper Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_4_Lower_Bound__c</fullName>
        <label>Score 4 Lower Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_4_Upper_Bound__c</fullName>
        <label>Score 4 Upper Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SpendWeightageScore__c</fullName>
        <formula>Spend__c  *  Score1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Spend Weightage Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spend__c</fullName>
        <label>Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <formula>SPETracker__r.SubRegion__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sumofpillerweight__c</fullName>
        <label>Sumofpillerweight</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WeightageScore__c</fullName>
        <formula>Score1__c * Weight__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Weightage Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>salesforceid__c</fullName>
        <formula>Supplier__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SalesforceEnterprise ID</label>
        <type>Text</type>
    </fields>
    <label>Tracker Value</label>
    <nameField>
        <displayFormat>Tracker-{00000}</displayFormat>
        <label>Tracker Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracker Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_SPETrackerBatch1.cls
global class SPE_SPETrackerBatch1 implements Database.Batchable<sObject>
{

    global Id speTrackerIds;
    
     public SPE_SPETrackerBatch1 (String speTrackerId)
    {
        speTrackerIds = speTrackerId;
        
    }   

    global Database.QueryLocator start(Database.BatchableContext bc ){
    
     Id speTrackerIds = this.speTrackerIds;
     system.debug('speTrackerIdsspeTrackerIds '+speTrackerIds );
    
    String query1 = 'select id, Avg_Piller_Score__c,DataLogic__c,DateOfExecution__c,EncryptedEnterpriseId__c,EnterpriseId__c,Group__c,KPIGroup__c,KPIDefinition__c,LogicAnnotation__c,MAX_Piller_score__c,Min_Piller_Score__c,MissingDatalogic__c,Percentile__c,Piller__c,Pillar_Rank__c, Piller_score__c,Product__c,Project__c, Region__c,salesforceid__c,Score__c,Score1__c,Score_1_Lower_Bound__c,Score_1_Upper_Bound__c,Score_2_Lower_Bound__c,Score_2_Upper_Bound__c,Score_3_Loewr_Bound__c,Score_3_Upper_Bound__c,Score_4_Lower_Bound__c,Score_4_Upper_Bound__c,ScoreResult__c,Spend__c,SpendWeightageScore__c,SPEPlanId__c,SPE_Rank__c,SPE_Score__c,SPETemplate__c,SPE_TemplateName__c,SPETracker__c,SubRegion__c,Sumofpillerweight__c,Weight__c,Supplier__c,SurveyComments__c,Value__c,value1__c,Vlauecalculation__c,WeightageScore__c from SPE_TrackerValues__c WHERE SPETracker__c	 =:speTrackerIds';
    
    return Database.getQueryLocator(query1);
      }
    global void execute(Database.BatchableContext be, list<SPE_TrackerValues__c> trackvallist)
    {
    list<SPE_TrackerValues__c> pillersaggregate = new list<SPE_TrackerValues__c>();
    list<SPE_TrackerValues__c> pilleraggresult1 = new list<SPE_TrackerValues__c>();
    list<SPE_TrackerValues__c> pilleraggresult2 = new list<SPE_TrackerValues__c>();
    for(SPE_TrackerValues__c  spetrack1 :  trackvallist){
          pillersaggregate =  [select value1__C, Weight__c from SPE_TrackerValues__c where  SPETracker__c=:spetrack1.SPETracker__c and supplier__C=:spetrack1.Supplier__c and piller__c=:spetrack1.piller__C];
          pilleraggresult2 =  [select value1__C, Weight__c from SPE_TrackerValues__c where  SPETracker__c=:spetrack1.SPETracker__c and supplier__C=:spetrack1.Supplier__c and piller__c=:spetrack1.piller__C and value1__C!=0 and value1__C!=null];
            //system.debug('test test' + test4);
            Decimal Sum;
            Decimal Sum1;
            sum =0;
            sum1=0;
        if(pillersaggregate.size()==pilleraggresult2.size()){
        for(SPE_TrackerValues__c tracker : pillersaggregate){
           sum+= tracker.value1__C;
           sum1+= tracker.Weight__c;          
           }
            spetrack1.Vlauecalculation__c = sum;
            spetrack1.Sumofpillerweight__c = sum1;
            pilleraggresult1.add(spetrack1);
            } 
        else{
            spetrack1.Vlauecalculation__c = 0;
            spetrack1.Sumofpillerweight__c = 0;
            pilleraggresult1.add(spetrack1);
        }
    }
        try{
            update pilleraggresult1;
        }catch(Exception e){}
        //-------------------------------update pillar max, min, avg-----------------------------------------------------------------
        //--------------------------------spe score for supplier wise----------------------------------------------------------
           for(SPE_TrackerValues__c  spescore : trackvallist)
       {
			system.debug('My flag..');
           List<AggregateResult> speresult = [select SPETracker__c,SUM(value1__c) sum from SPE_TrackerValues__c where SPETracker__c =: spescore.SPETracker__c and supplier__C=:spescore.supplier__C group by SPETracker__c];
          
            Decimal sum;
           	
           if(speresult.size()!=0){
      for(AggregateResult ag : speresult){
   
           sum = (Decimal)ag.get('sum');
          
         }
          spescore.SPE_Score__c = sum; 
          update spescore;
        }
       }
        
        //------------------------------------------
        list<SPE_TrackerScore__c> spelist = new list<SPE_TrackerScore__c>();
        spelist = [select id, SPETracker__c from SPE_TrackerScore__c where SPEScore__c = true and SPETracker__c =:speTrackerIds ];
        list<AggregateResult> spresult = new  list<AggregateResult>();
        spresult = [select  SPETracker__c,MIN(Score__c) speminVal, MAX(Score__c) spemaxVal, AVG(Score__c) speavgScore from SPE_TrackerScore__c where SPEScore__c = true and SPETracker__c =:speTrackerIds  group by SPETracker__c];
 
        set<Id> spetracker1_Ids = new set<id>();
        list<SPE_SPETracker__c> spetracker1_ls = new list<SPE_SPETracker__c>();
        for(SPE_TrackerScore__c tra : spelist){
              for(AggregateResult ag : spresult){
                SPE_SPETracker__c spetracker1 = new SPE_SPETracker__c();
                spetracker1.id = (id)ag.get('SPETracker__c');                               
                spetracker1.Avg_SPE_Score__c = (Decimal)ag.get('speavgScore');
                spetracker1.MAX_Score__c = (Decimal)ag.get('spemaxVal');
                spetracker1.Min_SPE_Score__c = (Decimal)ag.get('speminVal');
                  //update spetracker1;
                  if(spetracker1_Ids.add(spetracker1.id))
                  spetracker1_ls.add(spetracker1);
               }       
          }
        update spetracker1_ls;
        
        //-----------------------------SPE Ranks-------------------------------
        list<SPE_TrackerScore__c> speranks = new list<SPE_TrackerScore__c>();
               
        set<string> block9temp1 = new set<string>();        
        
        speranks = [select Score__c,SPE_Rank__c from SPE_TrackerScore__c where SPETracker__c=:speTrackerIds  and Score__c!=0 and SPEScore__c = true and Score__c != null order by Score__c DESC];
        if(!speranks.isEmpty()){
            decimal temp1 = 0;
            integer count1 = 0;
            for(integer i =0; i<speranks.size();i++){
                decimal val1 = speranks[i].Score__c;
                if(Val1!=0){
                if(temp1==0){
                    count1 = count1+1;
               speranks[i].spe_rank__C = count1;  
                   temp1 = speranks[i].Score__c;
                }else if(temp1==val1){
                   speranks[i].spe_rank__C = count1;  
                   temp1 = speranks[i].Score__c; 
                }else{
                    count1 = count1+1;
               speranks[i].spe_rank__c = count1;  
               temp1 = speranks[i].Score__c;
                }
                }
            }
            update speranks;
           
        }
        
        
        //------------------------------------------
    }  
      
    global void finish(Database.BatchableContext bc){
    SPE_SPETrackerBatch2 b2 = new SPE_SPETrackerBatch2(speTrackerIds);
        Database.executeBatch(b2, 1);
    }  
}