src/objects/SPE_Report_Configs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used for controlling Scope filters for Spend and Volume weight calculation</description>
    <fields>
        <fullName>Product_Filter_For_Spend__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Product Filter For Spend</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Report Configs</label>
</CustomObject>

src/objects/SPE_Report_Parameter__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE Report Parameter</label>
    <nameField>
        <displayFormat>PN-{00000000}</displayFormat>
        <label>Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Report Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_Scorecard_Report__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Area__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Unit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period_Text__c</fullName>
        <formula>SPE_Tracker__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPE_Report_Parameter__c</fullName>
        <label>SPE Report Parameter</label>
        <referenceTo>SPE_Report_Parameter__c</referenceTo>
        <relationshipLabel>SPE_Scorecard_Report</relationshipLabel>
        <relationshipName>SPE_Scorecard_Report</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SPE_Scorecard_Report</relationshipLabel>
        <relationshipName>SPE_Scorecard_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>SPE_Scorecard_Report</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>SPE_Scorecard_Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE_Scorecard_Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_Spend__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryArea__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EnterpriseId</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Spends</relationshipLabel>
        <relationshipName>Spends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nego_Responsible__c</fullName>
        <label>Nego Responsible</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>R+G</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spend__c</fullName>
        <label>Spend</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Spend</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>SpendId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPETracker__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <formula>SurveyExecutionBeforeIndays__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE Tracker</label>
    <nameField>
        <label>SPE Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SPE_SpendHybridLogicCalcBatch.cls
global class SPE_SpendHybridLogicCalcBatch implements Database.Batchable<sObject>{
    global String query;
    global List<SPE_SPETracker__c> speTrackerList;
    global String aggrType;
    global Map<String,List<decimal>> speTrackerToWeigtage = new Map<String,List<decimal>>();
    global Map<String,decimal> trackerToWeightageSum;
    global Id ParamId;
    global Date startrangeDate;
    global Date endRangeDate;
    global String negoResParam;
    //global Set<String> spetrackers = new Set<String>();
    global SPE_SpendHybridLogicCalcBatch (String reportparamId, String negoResponsible){
        paramId = reportparamId;
        negoResParam = negoResponsible;
        query = 'SELECT Period_Text__c,Score__c,SPE_Report_Parameter__c,Business_Line__c ,Business_Unit__c,Product__c,Category__c,Category_Group__c ,Category_Area__c ,Project__c,Market__c,Market_Unit__c,Country__c,Supplier__c,Weight__c FROM SPE_Scorecard_Report__c WHERE SPE_Report_Parameter__c ='+'\''+ParamId+'\''; 
        
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator(query);        
    }
    
    global void execute(Database.BatchableContext BC, List<sObject>scope){ 
        Integer monthVal;
        Integer yearVal;
        Integer noOfDays;
        Map<String,decimal> trackerToWeightage = new Map<String,decimal>();
        List<String> periodVals = new List<String>();
        Map<String,Integer> monthMap = new Map<String,Integer>();
        monthMap.put('January',01);
        monthMap.put('February',02);
        monthMap.put('March',03);
        monthMap.put('April',04);
        monthMap.put('May',05);
        monthMap.put('June',06);
        monthMap.put('July',07);
        monthMap.put('August',08);
        monthMap.put('September',09);
        monthMap.put('October',10);
        monthMap.put('November',11);
        monthMap.put('December',12);
        system.debug('enter at hybridBatch::'+negoResParam+'****'+paramId);
        SPE_Report_Configs__c reportConfig = SPE_Report_Configs__c.getInstance('Filter for Spend and Volume');
        List <SPE_Scorecard_Report__c> sReportList = new list<SPE_Scorecard_Report__c>();
        for(sobject obj :scope){
            SPE_Scorecard_Report__c rObj = (SPE_Scorecard_Report__c)obj;
            periodVals = rObj.Period_Text__c.replace(' ','').split('-');
            monthVal = monthMap.get(periodVals[0]); 
            yearVal = integer.valueOf(periodVals[1]);
            
            noOfDays = date.daysInMonth(yearVal,monthVal);
            startrangeDate = date.newInstance(yearVal,monthVal,1);
            endRangeDate = date.newInstance(yearVal,monthVal,noOfDays);
            List<AggregateResult> spendList = new List<AggregateResult>();
            //SPE_Scorecard_Report__c sReport = new SPE_Scorecard_Report__c();
            String spendSoql = 'Select SUM(Spend__c) total FROM SPE_Spend__c where EnterpriseId__c = '+'\''+rObj.supplier__c+'\'';
            if(reportConfig.Product_Filter_For_Spend__c){
                if(!spendSoql.contains( ' where ' ) && rObj.Business_Line__c !='All Business Lines'){
                    spendSoql +=' where ' + 'Business_Line__c='+'\''+rObj.Business_Line__c+'\'';
                }
                else if(spendSoql.contains( ' where ' ) && rObj.Business_Line__c !='All Business Lines'){
                    spendSoql +=' AND' + ' Business_Line__c='+'\''+rObj.Business_Line__c+'\'';
                } 
            }
            //-----Business line ends----
            
            if(!spendSoql.contains( ' where ' ) && rObj.Market__c!='All Markets'){
                spendSoql +=' where ' + 'Region__c='+'\''+rObj.Market__c+'\'';
            }
            else if(spendSoql.contains( ' where ' ) && rObj.Market__c!='All Markets'){
                spendSoql +=' AND' + ' Region__c='+'\''+rObj.Market__c+'\'';
            } 
            
            //------Market Ends-----
            
            if(!spendSoql.contains( ' where ' ) && rObj.Market_Unit__c!='All Market Units'){
                spendSoql +=' where ' + 'Sub_Region__c='+'\''+rObj.Market_Unit__c+'\'';
            }
            else if(spendSoql.contains( ' where ' ) && rObj.Market_Unit__c!='All Market Units'){
                spendSoql +=' AND' + ' Sub_Region__c='+'\''+rObj.Market_Unit__c+'\'';
            } 
            
            //-----Market Unit ends------
            
            
            if(!spendSoql.contains( ' where ' ) && rObj.Country__c!='All Countries'){
                spendSoql +=' where ' + 'Country__c='+'\''+rObj.Country__c+'\'';
            }
            else if(spendSoql.contains( ' where ' ) && rObj.Country__c!='All Countries'){
                spendSoql +=' AND' + ' Country__c='+'\''+rObj.Country__c+'\'';
            } 
            
            //-----Country Ends-----
            
             if(!spendSoql.contains( ' where ' ) && rObj.Project__c!='All Projects'){
                spendSoql +=' where ' + 'Project__c='+'\''+rObj.Project__c+'\'';
            }
            else if(spendSoql.contains( ' where ' ) && rObj.Project__c!='All Projects'){
                spendSoql +=' AND' + ' Project__c='+'\''+rObj.Project__c+'\'';
            } 
            
            //----- Project Ends-----
            if(reportConfig.Product_Filter_For_Spend__c){
                if(!spendSoql.contains( ' where ' ) && rObj.Business_Unit__c!='All Business Units'){
                    spendSoql +=' where ' + 'Business_Unit__c='+'\''+rObj.Business_Unit__c+'\'';
                }
                else if(spendSoql.contains( ' where ' ) && rObj.Business_Unit__c!='All Business Units'){
                    spendSoql +=' AND' + ' Business_Unit__c='+'\''+rObj.Business_Unit__c+'\'';
                } 
            }
            //------Business Unit ends-----
            if(reportConfig.Product_Filter_For_Spend__c){
                if(!spendSoql.contains( ' where ' ) && rObj.Product__c!='All Products'){
                    spendSoql +=' where ' + 'Product__c='+'\''+rObj.Product__c+'\'';
                }
                else if(spendSoql.contains( ' where ' ) && rObj.Product__c!='All Products'){
                    spendSoql +=' AND' + ' Product__c='+'\''+rObj.Product__c+'\'';
                } 
            }
            //------Product Ends----
            
             if(!spendSoql.contains( ' where ' ) && rObj.Category__c!='All Categories'){
                spendSoql +=' where ' + 'Category__c='+'\''+rObj.Category__c+'\'';
            }
            else if(spendSoql.contains( ' where ' ) && rObj.Category__c!='All Categories'){
                spendSoql +=' AND' + ' Category__c='+'\''+rObj.Category__c+'\'';
            } 
            
            //--------Category Ends-----
            
             if(!spendSoql.contains( ' where ' ) && rObj.Category_Group__c!='All Category Groups'){
                spendSoql +=' where ' + 'CategoryGroup__c='+'\''+rObj.Category_Group__c+'\'';
            }
            else if(spendSoql.contains( ' where ' ) && rObj.Category_Group__c!='All Category Groups'){
                spendSoql +=' AND' + ' CategoryGroup__c='+'\''+rObj.Category_Group__c+'\'';
            } 
            
            //----------Category Group Ends-----
            
            if(!spendSoql.contains( ' where ' ) && rObj.Category_Area__c !='All Category Areas'){
                spendSoql +=' where ' + 'CategoryArea__c='+'\''+rObj.Category_Area__c +'\'';
            }
            else if(spendSoql.contains( ' where ' ) && rObj.Category_Area__c !='All Category Areas'){
                spendSoql +=' AND' + ' CategoryArea__c='+'\''+rObj.Category_Area__c +'\'';
            } 
            
            //------Category Area ends----
            if(!spendSoql.contains( ' where ' ) ){ 
                spendSoql += ' where '+'Period__c >='+string.valueOf(startrangeDate) + ' AND Period__c <='+string.valueOf(endRangeDate);
            }
            else if(spendSoql.contains( ' where ' )){
              spendSoql += ' AND'+' Period__c >='+string.valueOf(startrangeDate) + ' AND Period__c <='+string.valueOf(endRangeDate);
            }
            // ------ nego responsible check ----
            if(!spendSoql.contains( ' where ' ) ){ 
                spendSoql += ' where Nego_Responsible__c='+ '\''+negoResParam+'\'' ;
            }
            else if(spendSoql.contains( ' where ' )){
              spendSoql += ' AND Nego_Responsible__c='+ '\''+negoResParam+'\'';
            }
             
            system.debug('spendsoql::'+spendsoql);
            spendList = database.query(spendsoql);
                                           
                
            rObj.Weight__c = (decimal)spendList[0].get('total');
            sReportList.add(rObj);
        }
        update sReportList;
        
    }
    
    global void finish(Database.BatchableContext BC){
       
    }
}