src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>FromDate__c</fullName>
        <description>Date field to enter from Date</description>
        <label>From Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ToDate__c</fullName>
        <description>Date field to enter To Date</description>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_KPIValue__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI Values</relationshipLabel>
        <relationshipName>KPI_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <label>KPI Value</label>
    <nameField>
        <displayFormat>KVI-{00000}</displayFormat>
        <label>KPI Value Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_PIEqualsKPISchedulebatch1Adhoc.cls
global class SPE_PIEqualsKPISchedulebatch1Adhoc implements Database.Batchable <sObject>,Schedulable 
{
    global Id kpiIds;
    global Date fromDate;
    global Date toDate;
    
    public SPE_PIEqualsKPISchedulebatch1Adhoc (String s)
    {
        kpiIds = s;
        List<SPE_KPIDefinition__c> lstKPIDef = [SELECT Id, FromDate__c,ToDate__c FROM SPE_KPIDefinition__c where ID=:s];
        fromDate = lstKPIDef[0].FromDate__c;
        toDate = lstKPIDef[0].ToDate__c;
    }

    global void execute(SchedulableContext sc) 
    {
        Database.executebatch(this,integer.valueOf(10000));
         if(!Test.isRunningTest()){
        system.abortJob(sc.getTriggerId());
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        Id kpiId = this.kpiIds;
        String query = 'SELECT ID,Period__c FROM SPE_KPIValue__c WHERE KPIDefinition__c =: kpiId AND Period__c >= :fromDate AND Period__c <= :toDate' ;
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List <SPE_KPIValue__c> scope) 
    {
        
        delete scope;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
        
          if(!Test.isRunningTest())
        {
        SPE_PIEqualsKPISchedulebatch2Adhoc dtBatch = new SPE_PIEqualsKPISchedulebatch2Adhoc(kpiIds); 
        database.executebatch(dtBatch,10000);
        }
        
    }
}