src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Master_KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI (Master KPI)</relationshipLabel>
        <relationshipName>KPI1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VerNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <label>VerNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPEKPIMap__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>KPI Definition</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SPE_KPIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <filterItems>
                <field>SPE_KPIDefinition__c.PI_Data__r.ValuesType__c</field>
                <operation>notEqual</operation>
                <value>Boolean, String, Date</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>SPE KPI Maps</relationshipLabel>
        <relationshipName>SPE_KPI_Maps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UseLatestKPIVersion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is used to add latest KPI Version to SPE Template</description>
        <label>UseLatestKPIVersion</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE KPI Map</label>
    <nameField>
        <displayFormat>SKMI-{00000}</displayFormat>
        <label>SPE KPI Map Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE KPI Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_SPEKPIMapTrigger.cls
public with Sharing class SPE_SPEKPIMapTrigger {

    public static void updateKPI(List<SPE_SPEKPIMap__c> KPIMap){
    
        List<SPE_KPIDefinition__c> lstKPIDef = new List<SPE_KPIDefinition__c>();
        List<SPE_KPIDefinition__c> lstKPIDefMaster = new List<SPE_KPIDefinition__c>();
        
        Map<Id,SPE_KPIDefinition__c> mapKPIID = new Map<Id,SPE_KPIDefinition__c>();
        Map<Id,Id> masterMap = new Map<Id,Id>();
     //   Map<Id,SPE_KPIDefinition__c> mapKPIID = new Map<Id,SPE_KPIDefinition__c>();
        Set<Id> KPIDefIDSet = new Set<Id>(); //Set to hold KPI Map ID
        Set<Id> masterKPIIdSet = new Set<Id>(); 
     
     
      for(SPE_SPEKPIMap__c s:KPIMap){
            KPIDefIDSet.add(s.KPIDefinition__c);
        }
        
     lstKPIDef = [Select id,VerNumber__c,Master_KPI__c from SPE_KPIDefinition__c where id in :KPIDefIDSet];
     system.debug('list value is'+lstKPIDef);
     
     for(SPE_KPIDefinition__c s : lstKPIDef){
          mapKPIID.put(s.Id,s);   
     
     }
        
    system.debug('values in map is'+mapKPIID);
    
    lstKPIDefMaster = [SELECT Master_KPI__c from SPE_KPIDefinition__c where id in :KPIDefIDSet];
    
    for(Integer i=0;i<lstKPIDefMaster.size();i++)
    {
        if(lstKPIDefMaster[i].Master_KPI__c!=null){
            masterKPIIdSet.add(lstKPIDefMaster[i].Master_KPI__c);
        }
        else{
            masterKPIIdSet.add(lstKPIDefMaster[i].Id);
        }
    
    }
    system.debug('masterKPI values'+masterKPIIdSet);
    
    List<SPE_KPIDefinition__c> lstKPIAll = [Select id,VerNumber__c,Master_KPI__c from SPE_KPIDefinition__c where Master_KPI__c in :masterKPIIdSet and (LifecycleStage__c='Pilot' Or LifecycleStage__c='Published')];
    
    system.debug('All KPI List**'+lstKPIAll);
    
    for(ID ob : masterKPIIdSet){
        Decimal latestver = 0;
        Id latestverID;
        for(SPE_KPIDefinition__c s : lstKPIAll){
            if(s.Master_KPI__c == ob){
                if(s.VerNumber__c > latestver){
                    latestver = s.VerNumber__c;
                    latestverID = s.Id;
                }
                
            }
            
        }
        
        masterMap.put(ob,latestverID);
    }
    
    system.debug('masterMap value is'+masterMap);
    
    for(SPE_SPEKPIMap__c sobj : KPIMap){
        if(sobj.UseLatestKPIVersion__c==true){
        for(Id testId : KPIDefIDSet){
            if(masterMap.containsKey(mapKPIID.get(testId).Master_KPI__c))
                sobj.KPIDefinition__c = masterMap.get(mapKPIID.get(testId).Master_KPI__c);
            else
                sobj.KPIDefinition__c = masterMap.get(mapKPIID.get(testId).Id);
        system.debug('final value is'+masterMap.get(sobj.KPIDefinition__r.Master_KPI__c));
        
        
        }
    }
   }
    
    }
}