src/objects/SPE_ScoringTemplate__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NETWORK IMPLEMENTATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SYSTEMS INTEGRATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUSINESS SUPPORT SYSTEMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEDIA AND ENTERTAINMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3G CORE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARCHITECTURE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEM AND OSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FDD LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LIQUID CORE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATURE PRODUCTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOBILE BROADBAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM PRODUCTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PERFECT VOICE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SECURITY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SINGLE RAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMALL CELL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TD LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AGGREGATION</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>GLOBAL SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATURE SOFTWARE PRODUCTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOBILE BROADBAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPTICAL NETWORKS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Area</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>PRODUCT PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNREPORTED SPEND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDIRECT PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICES PROCUREMENT OPERATIONS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Hierarchy__c</fullName>
        <label>Category Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Geo_Hierarchy__c</fullName>
        <description>Field to store the Geo Hierarchy</description>
        <label>Geo Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>Product Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <picklistValues>
                <fullName>CHARGING GATEWAY CG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGING GATEWAY CG SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHARGING@VANTAGE SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CIRCUIT SWITCHED DATA SERVER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLASSROOM TRAINING OPEN SEAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMD SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS-8200</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS-8200 DRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS-8200 DRA SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS-8200 HSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS-8200 HSS SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMX5000 SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-NTDB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-NTDB HW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C-NTDB SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CODE SOLUTION PLANNING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMISSIONING OF X</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMON MANAGEMENT SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMON RACK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMUNICATION SUITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMUNICATIONS INTERFACE SERVER (CIS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMUNITY SERVICE DATA MANAGER (CSDM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMUNITY SERVICE DATA MANAGER (CSDM) HW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMMUNITY SERVICE DATA MANAGER (CSDM) SW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPACT DX MSC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPAQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPETENCE DEVELOPMENT SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPETENCE TESTING SERVICE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COMPTEL INSTANTLINK (SAFIR) PROVISIONING TOOL</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <picklist>
            <controllingField>Country__c</controllingField>
            <picklistValues>
                <fullName>All Project</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AF AWCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMC 2G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL VODAFONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL M4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL PLUS CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ OOREDOO ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ.ORASCOM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA TELECOM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTI MOVIL ARG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TELEFONICA PANAMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR CTI MOVIL 3G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR CABLEVISION NGN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR TELECOM PERSONAL 3G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR TELECOM PDH/SDH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR CLARO ARGENTINA SWAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR TECO TDM EVOLUTION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEXTEL ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM ORANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPTUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VODAFONE AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU DOT DTRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU NBN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT H3G OLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT NETCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT CALDERA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT H3G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT A1 AUSTRIA CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT ORANGE AUSTRIA CARE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Market Unit</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Scoring Template</label>
    <nameField>
        <label>Scoring Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_ScoringTemplateTrigger.cls
public with sharing class SPE_ScoringTemplateTrigger{

public static void updateHierarchyFields(List<SPE_ScoringTemplate__c> newSPETemps){
        
        for(SPE_ScoringTemplate__c spe :newSPETemps){
            spe.Geo_Hierarchy__c = spe.Region__c+'-->'+spe.SubRegion__c+'-->'+spe.Country__c+'-->'+spe.Project__c;
            spe.Product_Hierarchy__c = spe.BusinessUnit__c+'-->'+spe.BusinessLine__c+'-->'+spe.Product__c;
            spe.Category_Hierarchy__c = spe.CategoryCluster__c+'-->'+spe.CategoryGroup__c+'-->'+spe.Country__c;
           
        }    
   
   }
  }