src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>KPI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of KPI 
(Standard Name field of KPI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>&apos;Version-&apos;+TEXT(VerNumber__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPEKPIMap__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>KPI Definition</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SPE_KPIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <filterItems>
                <field>SPE_KPIDefinition__c.PI_Data__r.ValuesType__c</field>
                <operation>notEqual</operation>
                <value>Boolean, String, Date</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>SPE KPI Maps</relationshipLabel>
        <relationshipName>SPE_KPI_Maps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPIGroup1__c</fullName>
        <formula>TEXT(KPIDefinition__r.Group1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pillar</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPIGroup2__c</fullName>
        <formula>TEXT(KPIDefinition__r.Group2__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>KPI Group2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE KPI Maps</relationshipLabel>
        <relationshipName>SPE_KPI_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UseLatestKPIVersion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field is used to add latest KPI Version to SPE Template</description>
        <label>UseLatestKPIVersion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>KPIDefinition__r.Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>SPE KPI Map</label>
    <nameField>
        <displayFormat>SKMI-{00000}</displayFormat>
        <label>SPE KPI Map Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE KPI Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_SPETemplateInlineExt.cls
public class SPE_SPETemplateInlineExt 
 {
        public List < SPE_SPEKPIMap__c > lstSpeKpi{ get; set; }
        
        public  Map <String, Decimal> gruop1Map{ get; set; }
        
        public  Map <String, Decimal> gruop2Map{ get; set; }
        
        public SPE_SPETemplateInlineExt (ApexPages.StandardController controller )
        {
        
            //****************Changes For Encryption*****************//
            lstSpeKpi = [SELECT Id, KPIDefinition__r.Id, KPIDefinition__r.Name,KPIDefinition__r.KPI_Title__c, KPIGroup1__c, KPIGroup2__c, Weight__c ,UseLatestKPIVersion__c,Version__c
                         FROM SPE_SPEKPIMap__c 
                         WHERE SPETemplate__c =: controller.getId()];
            //***************END******************//             
            
            gruop1Map = new Map <String, Decimal> ();
            gruop2Map = new Map <String, Decimal> ();
             
            for (SPE_SPEKPIMap__c SpeKpi : lstSpeKpi) 
            {
                if(gruop1Map.get(SpeKpi.KPIGroup1__c) == null )
                {
                    gruop1Map.put(SpeKpi.KPIGroup1__c, SpeKpi.Weight__c);
                }
                else
               {
                   Decimal totalWeight = gruop1Map.get(SpeKpi.KPIGroup1__c);
                   totalWeight = totalWeight + SpeKpi.Weight__c;
                   gruop1Map.put(SpeKpi.KPIGroup1__c, totalWeight);
               }
            }
            for (SPE_SPEKPIMap__c SpeKpi : lstSpeKpi) 
            {
                if(gruop2Map.get(SpeKpi.KPIGroup2__c) == null )
                {
                    gruop2Map.put(SpeKpi.KPIGroup2__c, SpeKpi.Weight__c);
                }
                else
               {
                   Decimal totalWeight = gruop2Map.get(SpeKpi.KPIGroup2__c);
                   totalWeight = totalWeight + SpeKpi.Weight__c;
                   gruop2Map.put(SpeKpi.KPIGroup2__c, totalWeight);
               }
            }
       }
      
}