src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/thresholdscopeAttributeMap.cls
public class thresholdscopeAttributeMap{
    public Map<String,Boolean> enableattributesMap = new Map<String,Boolean>();        
    public Map<String,Boolean> initializeMapValue(){
        enableattributesMap.put('Market',true);
        enableattributesMap.put('Market Unit',true);
        enableattributesMap.put('Country',true);
        enableattributesMap.put('Project',true);
        enableattributesMap.put('Category Area',true);
        enableattributesMap.put('Category Group',true);
        enableattributesMap.put('Category',true);
        enableattributesMap.put('Business Unit',true);
        enableattributesMap.put('Business Line',true);
        enableattributesMap.put('Product',true);        
        return enableattributesMap;
    }
    
    public Map<String,Boolean> qualifyScopeAttributes(SPE_KPIDefinition__c kpiDef){
        //Map<String,Boolean> enableattributesMap = new Map<String,Boolean>();   
        // For Geography Scope Attributes values
        if(kpiDef.GeoScope__c ==SPE_Constants.ALL_GEOSCOPE){
            enableattributesMap.put('Market',false);
            enableattributesMap.put('Market Unit',false);
            enableattributesMap.put('Country',false);
            enableattributesMap.put('Project',false);            
        }
        if(kpiDef.GeoScope__c ==SPE_Constants.MARKET_GEOSCOPE){
            enableattributesMap.put('Market Unit',false);
            enableattributesMap.put('Country',false);
            enableattributesMap.put('Project',false);            
        }
        if(kpiDef.GeoScope__c ==SPE_Constants.MU_GEOSCOPE){
            enableattributesMap.put('Country',false);
            enableattributesMap.put('Project',false);            
        }
        if(kpiDef.GeoScope__c ==SPE_Constants.COUNTRY_GEOSCOPE ){
            enableattributesMap.put('Project',false);            
        }
        
           // For Category Scope Attributes values
        if(kpiDef.Categoryscope__c ==SPE_Constants.ALL_CATSCOPE ){
            enableattributesMap.put('Category Area',false);
            enableattributesMap.put('Category Group',false);
            enableattributesMap.put('Category',false);            
        }
        if(kpiDef.Categoryscope__c ==SPE_Constants.AREA_CATSCOPE ){
            enableattributesMap.put('Category Group',false);
            enableattributesMap.put('Category',false);            
        }
        if(kpiDef.Categoryscope__c  ==SPE_Constants.GROUP_CATSCOPE ){
            enableattributesMap.put('Category',false);            
        }
        
           // For Product Scope Attributes values
        if(kpiDef.BUScope__c ==SPE_Constants.ALL_BUSCOPE){
            enableattributesMap.put('Business Unit',false);
            enableattributesMap.put('Business Line',false);
            enableattributesMap.put('Product',false);            
        }
        if(kpiDef.BUScope__c ==SPE_Constants.BU_BUSCOPE){
            enableattributesMap.put('Business Line',false);
            enableattributesMap.put('Product',false);            
        }
        if(kpiDef.BUScope__c ==SPE_Constants.BL_BUSCOPE){
            enableattributesMap.put('Product',false);            
        }
        return enableattributesMap;
    }
}