src/objects/SPE_Spend__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryArea__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EnterpriseId</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Spends</relationshipLabel>
        <relationshipName>Spends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nego_Responsible__c</fullName>
        <label>Nego Responsible</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>R+G</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPEPeriod__c</fullName>
        <label>SPE Period</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Spend__c</fullName>
        <label>Spend</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Region__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WBSElements__c</fullName>
        <label>WBS Elements</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Spend</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>SpendId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SpendCoverage__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryArea__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Scope Field</description>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketUnit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NegoResponsible__c</fullName>
        <label>Nego Responsible</label>
        <picklist>
            <picklistValues>
                <fullName>R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPEPeriod__c</fullName>
        <label>SPE Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SpendNumber__c</fullName>
        <label>Spend</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Spend__c</fullName>
        <description>Object to get spend for each supplier</description>
        <label>Spend</label>
        <referenceTo>SPE_Spend__c</referenceTo>
        <relationshipLabel>Spend Coverages</relationshipLabel>
        <relationshipName>Spend_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Spend Coverages</relationshipLabel>
        <relationshipName>Spend_Coverages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WBSElements__c</fullName>
        <label>WBS Elements</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Spend Coverage</label>
    <nameField>
        <displayFormat>SPC-{00000}</displayFormat>
        <label>Spend Cov Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spend Coverages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SPE_SpendTrigger.cls
public with sharing class SPE_SpendTrigger 
{
    public static void spendCoverageCreate(List<SPE_Spend__c> spends)
    {
        List<SPE_SpendCoverage__c> toBeInstredSpendCoverages = new List<SPE_SpendCoverage__c>();
        for (SPE_Spend__c s: spends)
        {
            SPE_SpendCoverage__c sc = new SPE_SpendCoverage__c();
            
            sc.Spend__c = s.Id;
            sc.Market__c = s.Region__c;
            sc.MarketUnit__c = s.Sub_Region__c;
            sc.Country__c = s.Country__c;
            sc.Project__c = s.Project__c;
            sc.CategoryArea__c = s.CategoryArea__c;
            sc.CategoryGroup__c = s.CategoryGroup__c;
            sc.Category__c = s.Category__c;
            sc.BusinessUnit__c = s.Business_Unit__c;
            sc.BusinessLine__c = s.Business_Line__c;
            sc.Product__c = s.Product__c;
            sc.WBSElements__c = s.WBSElements__c;
            sc.NegoResponsible__c = s.Nego_Responsible__c;
            
            sc.Period__c = s.Period__c;
            if (sc.Period__c != null)
            {
                sc.SPEPeriod__c = SPE_Utility.monthsMap.get(sc.Period__c.month()) + ' - '+ String.valueOf(sc.Period__c.year());
            }
            sc.SpendNumber__c = s.Spend__c;
            sc.Supplier__c = s.EnterpriseId__c;
            
            toBeInstredSpendCoverages.add(sc);
        }
        
        insert toBeInstredSpendCoverages;
    }
}