src/objects/SPE_KPICalculation__c.object
<CustomObject>
    <fields>
        <fullName>Aggregation__c</fullName>
        <label>Aggregation</label>
        <picklist>
            <picklistValues>
                <fullName>Min</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Min( Across Suppliers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max( Across Suppliers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg( Across Suppliers)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ConstantValue__c</fullName>
        <label>Constant Value</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDefination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Defination</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please Select a Published PI</errorMessage>
            <filterItems>
                <field>SPE_PIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeFrame__c</fullName>
        <label>Time Frame (In Months)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KPI Calculation</label>
    <nameField>
        <displayFormat>KCal-{00000}</displayFormat>
        <label>KPI Calculation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Adhoc_Date__c</fullName>
        <label>Adhoc Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Aggregation__c</fullName>
        <label>Aggregation</label>
        <picklist>
            <picklistValues>
                <fullName>AVG</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PITempValue__c.object
<CustomObject>
    <fields>
        <fullName>ExecutionPeriod__c</fullName>
        <label>Execution Period</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <formula>KPICalculation__r.Index__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Index</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsConstant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Constant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KPICalculation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Calculation</label>
        <referenceTo>SPE_KPICalculation__c</referenceTo>
        <relationshipLabel>PI Temp Values</relationshipLabel>
        <relationshipName>PI_Temp_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>PI Temp Values</relationshipLabel>
        <relationshipName>PI_Temp_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIValue__c</fullName>
        <label>PI Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ValueType__c</fullName>
        <label>Value Type</label>
        <picklist>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PI Temp Value</label>
    <nameField>
        <displayFormat>PTVI-{00000}</displayFormat>
        <label>PI Temp Values Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Temp Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_KPISchedulebatch2Adhoc.cls
global class SPE_KPISchedulebatch2Adhoc implements Database.Batchable <sObject> , Schedulable 
{
    global Id kpiIds;
    
    public SPE_KPISchedulebatch2Adhoc (String s)
    {
        kpiIds = s;
    }
    
    global void execute(SchedulableContext sc) 
    {
        Database.executebatch(this,integer.valueOf(2000));
    }

    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        Id kpiId = this.kpiIds;
    
        System.debug('=========>'+kpiId);   
        string k='Constant';
        String query='select id, PIDefination__c, TimeFrame__c, ConstantValue__c, KPIDefinition__c, Aggregation__c, index__c from SPE_KPICalculation__c where KPIDefinition__c =:kpiId  and Aggregation__c=:k';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List <SPE_KPICalculation__c> scope) 
    {
        List<SPE_PITempValue__c> tobeinserted= new List<SPE_PITempValue__c> ();
        SPE_KPIDefinition__c kpi= new SPE_KPIDefinition__c ();
        kpi=[select id,Adhoc_Date__c from SPE_KPIDefinition__c where Id =: kpiIds ] ;
    
        for(SPE_KPICalculation__c s:scope)
        {
            SPE_PITempValue__c piTempValue = new SPE_PITempValue__c();
            piTempValue.ExecutionPeriod__c =SPE_Utility.monthsMap.get((kpi.adhoc_date__c.addMonths(-1)).month())+' - '+ String.valueOf((kpi.adhoc_date__c.addMonths(-1)).year());
            piTempValue.PIValue__c =String.valueOf(s.ConstantValue__c);
            piTempValue.Valuetype__c = 'Number';
            piTempValue.KPIDefinition__c = s.KPIDefinition__c; 
            piTempValue.KPICalculation__c = s.id;
            piTempValue.IsConstant__c=true;
            piTempValue.Period__c = kpi.adhoc_date__c.addMonths(-1);
            tobeinserted.add(piTempValue);
        }
        
        insert tobeinserted;
    }
    
    global void finish(Database.BatchableContext BC) 
    {
        System.debug('=========>'+kpiIds);  
           if(!test.isRunningTest()){
        SPE_KPISchedulePrebatch3Adhoc dtBatch= new SPE_KPISchedulePrebatch3Adhoc(kpiIds);
        database.executebatch(dtBatch,2000);
        }
    }
}