src/objects/SPE_CMKPITrend__c.object
<CustomObject>
    <fields>
        <fullName>ConsequenceManagement__c</fullName>
        <label>Consequence Management</label>
        <referenceTo>SPE_ConsequenceManagement__c</referenceTo>
        <relationshipLabel>CM KPI Trends</relationshipLabel>
        <relationshipName>CM_KPI_Trends</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DateofExecution__c</fullName>
        <label>Date of Execution</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPETracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Tracker</label>
        <referenceTo>SPE_SPETracker__c</referenceTo>
        <relationshipLabel>CM KPI Trends</relationshipLabel>
        <relationshipName>CM_KPI_Trends</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TrackerValue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tracker Value</label>
        <referenceTo>SPE_TrackerValues__c</referenceTo>
        <relationshipLabel>CM KPI Trends</relationshipLabel>
        <relationshipName>CM_KPI_Trends</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CM KPI Trend</label>
    <nameField>
        <displayFormat>KT-{0000}</displayFormat>
        <label>CM KPI Trend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CM KPI Trends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_ConsequenceManagement__c.object
<CustomObject>
    <fields>
        <fullName>DateofExecution__c</fullName>
        <formula>SPETracker__r.DateOfExecution__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date of Execution</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KPIName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Name</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Consequence Managements</relationshipLabel>
        <relationshipName>Consequence_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LatestKPITrend__c</fullName>
        <label>Latest KPI Trend</label>
        <summarizedField>SPE_CMKPITrend__c.DateofExecution__c</summarizedField>
        <summaryForeignKey>SPE_CMKPITrend__c.ConsequenceManagement__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>SPEPlan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>Consequence Management</relationshipLabel>
        <relationshipName>Consequence_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPETracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Tracker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SPE_SPETracker__c.Status__c</field>
                <operation>equals</operation>
                <value>Pending, Completed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_SPETracker__c</referenceTo>
        <relationshipLabel>Consequence Managements</relationshipLabel>
        <relationshipName>Consequence_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Supplier that is the focus of this case</inlineHelpText>
        <label>Enterprise ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consequence Managements</relationshipLabel>
        <relationshipName>Consequence_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TicketStatus__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Trouble Found</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TrackerValue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tracker Value</label>
        <referenceTo>SPE_TrackerValues__c</referenceTo>
        <relationshipLabel>Consequence Management</relationshipLabel>
        <relationshipName>Consequence_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Consequence Management</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Consequence Management ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consequence Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPEPlan__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <label>SPE Plan</label>
    <nameField>
        <displayFormat>SPE - {00000}</displayFormat>
        <label>SPE Plan Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPETracker__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>DateOfExecution__c</fullName>
        <label>Date Of Execution</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPEPlan__c</fullName>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>SPE Trackers</relationshipLabel>
        <relationshipName>SPE_Trackers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SPE Tracker</label>
    <nameField>
        <label>SPE Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_TrackerValues__c.object
<CustomObject>
    <fields>
        <fullName>DateOfExecution__c</fullName>
        <formula>SPETracker__r.DateOfExecution__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DateOfExecution</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Tracker Value</relationshipLabel>
        <relationshipName>Tracker_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPEPlanId__c</fullName>
        <formula>SPETracker__r.SPEPlan__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SPE Plan Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPETracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Tracker</label>
        <referenceTo>SPE_SPETracker__c</referenceTo>
        <relationshipLabel>Tracker Value</relationshipLabel>
        <relationshipName>Tracker_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracker Value</relationshipLabel>
        <relationshipName>Tracker_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tracker Value</label>
    <nameField>
        <displayFormat>Tracker-{00000}</displayFormat>
        <label>Tracker Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracker Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_KPITrendScoreBatchScheduler.cls
public class SPE_KPITrendScoreBatchScheduler Implements Database.Batchable<sObject>, Schedulable, Database.Stateful
{
    Date trendingDate;
    Id cmId;
    Boolean isTrendingForPast;
    
    public SPE_KPITrendScoreBatchScheduler()
    {
    }
    
    public void execute(SchedulableContext sc) 
    {
        Database.executeBatch(this, 1);
    }
    
    public SPE_KPITrendScoreBatchScheduler(Date d, Id cmId, Boolean isTrendingForPast)
    {
        trendingDate = d;
        this.cmId = cmId;
        this.isTrendingForPast = isTrendingForPast;
    }
     
    public Database.queryLocator start(Database.BatchableContext bc)
    {
        String var = 'open';
        String SOQL;
        
        if (cmId != null)
        {
            SOQL = 'SELECT SPETracker__c, SPETracker__r.SPEPlan__r.Id, KPIName__c, Supplier__c, DateofExecution__c,  LatestKPITrend__c FROM SPE_ConsequenceManagement__c WHERE ID =: cmId AND SPETracker__c != null';
        }
        else
        {
            SOQL = 'SELECT SPETracker__c, SPETracker__r.SPEPlan__r.Id, KPIName__c, Supplier__c, DateofExecution__c,  LatestKPITrend__c FROM SPE_ConsequenceManagement__c WHERE TicketStatus__c =: var AND SPETracker__c != null';
        }
        
        return Database.getQueryLocator(SOQL);
    }

    public void execute(Database.BatchableContext bc, List<SPE_ConsequenceManagement__c > scope)
    {
        String PlanId = scope[0].SPETracker__r.SPEPlan__r.Id;
        
        String planid15Digit = PlanId.substring(0, 15);
        
        List<SPE_TrackerValues__c> trackerValues;
        
        if (trendingDate == null && !isTrendingForPast)
        {
            trackerValues = [SELECT Id, SPETracker__c FROM SPE_TrackerValues__c WHERE Supplier__c =: scope[0].Supplier__c
                             AND SPEPlanId__c =: planid15Digit  AND KPIDefinition__c =: scope[0].KPIName__c
                             AND DateOfExecution__c >= : scope[0].DateofExecution__c];
        }
        
        else if (isTrendingForPast)
        {
            trackerValues = [SELECT Id, SPETracker__c, DateOfExecution__c FROM SPE_TrackerValues__c WHERE Supplier__c =: scope[0].Supplier__c
                             AND SPEPlanId__c =: planid15Digit  AND KPIDefinition__c =: scope[0].KPIName__c
                             AND DateOfExecution__c <= : scope[0].DateofExecution__c ORDER BY DateOfExecution__c ASC];
            
            List<SPE_CMKPITrend__c> trendValuesToBeDeleted = [SELECT Id FROM SPE_CMKPITrend__c WHERE ConsequenceManagement__c =: scope[0].Id AND DateOfExecution__c <= : scope[0].DateofExecution__c];
            
            Delete trendValuesToBeDeleted;
            
        }
        
        else
        {
            trackerValues = [SELECT Id, SPETracker__c, DateOfExecution__c FROM SPE_TrackerValues__c WHERE Supplier__c =: scope[0].Supplier__c
                             AND SPEPlanId__c =: planid15Digit  AND KPIDefinition__c =: scope[0].KPIName__c
                             AND DateOfExecution__c = : trendingDate ORDER BY DateOfExecution__c ASC LIMIT 1];
        }
        
        List<SPE_CMKPITrend__c> trendValues = new List<SPE_CMKPITrend__c>();
        
        for (SPE_TrackerValues__c tv : trackerValues )
        {
            SPE_CMKPITrend__c trendValue = new SPE_CMKPITrend__c ();
            trendValue.ConsequenceManagement__c = scope[0].Id;
            trendValue.TrackerValue__c = tv.Id;
            trendValue.SPETracker__c = tv.SPETracker__c;
            trendValues.add(trendValue);
        }
        
        insert trendValues ;
        
    }

    public void finish(Database.BatchableContext bc) 
    {
    }
}