src/objects/SPE_ScorecardTracker__c.object
<CustomObject>
    <fields>
        <fullName>ScorecardGenerator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scorecard Generator</label>
        <referenceTo>SPE_ScorecardGenerator__c</referenceTo>
        <relationshipLabel>Scorecard Trackers</relationshipLabel>
        <relationshipName>Scorecard_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Scorecard Tracker</label>
    <nameField>
        <label>Scorecard Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scorecard Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_ScoreCardAbandonedExt.cls
public with sharing class SPE_ScoreCardAbandonedExt 
{   
    private Id scoreCardId;
    
    public SPE_ScoreCardAbandonedExt( ApexPages.StandardController st)
    {
        scoreCardId= st.getId();
    }
    
    public PageReference abandoned()
    {
       List<SPE_ScorecardTracker__c> toBeAbandonedTracker = [SELECT Id, ScorecardGenerator__c, Status__c 
                                                          FROM SPE_ScorecardTracker__c
                                                          WHERE Status__c =:SPE_Constants.STATUS_PENDING  AND  ScorecardGenerator__c=: scoreCardId];
                                                          
        for (SPE_ScorecardTracker__c tracker : toBeAbandonedTracker)
        {
            tracker.Status__c = SPE_Constants.STATUS_ABANDONED;
            //toBeInsertedSPETracker.add(tracker);
        }
        update toBeAbandonedTracker;
        
        PageReference pg = new PageReference('/'+scoreCardId);
        
        return pg;
       
    }
}