src/objects/SPE_ConsequenceManagement__c.object
<CustomObject>
    <fields>
        <fullName>KPIName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Name</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Consequence Managements</relationshipLabel>
        <relationshipName>Consequence_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MasterCM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master CM</label>
        <referenceTo>SPE_ConsequenceManagement__c</referenceTo>
        <relationshipLabel>Child Ticket</relationshipLabel>
        <relationshipName>Consequence_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPETracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Tracker</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SPE_SPETracker__c.Status__c</field>
                <operation>equals</operation>
                <value>Pending, Completed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_SPETracker__c</referenceTo>
        <relationshipLabel>Consequence Managements</relationshipLabel>
        <relationshipName>Consequence_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier_Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier Address</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Consequence Management (Supplier Address)</relationshipLabel>
        <relationshipName>Consequence_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Supplier that is the focus of this case</inlineHelpText>
        <label>Enterprise ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Consequence Managements</relationshipLabel>
        <relationshipName>Consequence_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Consequence Management Name</description>
        <inlineHelpText>Consequence Management Name</inlineHelpText>
        <label>Title</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Consequence Management</label>
    <nameField>
        <displayFormat>CM-{00000}</displayFormat>
        <label>Consequence Management ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consequence Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>KPI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of KPI 
(Standard Name field of KPI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_CMBulkDeLink.cls
public Class SPE_CMBulkDeLink
{
    public String supplierName{get; set;}
    public List<SPE_ConsequenceManagement__c> cmList {get;set;}
    
    public SPE_CMBulkDeLink()
    {
        cmList = new List<SPE_ConsequenceManagement__c>();
        supplierName = '';
        searchMatchingTicket();
    }
    
    public void searchMatchingTicket()
    {
        String supplierNameSearchString = '%'+supplierName+'%';
       
       String currentUser = userinfo.getuserid();
    //***************************Changes For Encryption*****************************// 
         Pattern MySupplierPattern = Pattern.compile('.*'+supplierName+'.*');       
      
        /*String queryString  = 'SELECT Id, Name, Title__c, SPETracker__c, KPIName__c, Supplier__c,Supplier__r.Name, ' +
        ' (SELECT Id, Name, Title__c, SPETracker__c, KPIName__c, Supplier__c, Supplier__r.Name FROM Consequence_Management__r )a ' +
        'FROM SPE_ConsequenceManagement__c WHERE '+
        ' Supplier__r.Name LIKE : supplierNameSearchString';*/
        
        String queryString  = 'SELECT Id, Name, Title__c, SPETracker__c, KPIName__c, KPIName__r.KPI_Title__c, Supplier__c,Supplier__r.Name, ' +
        ' (SELECT Id, Name, Title__c, SPETracker__c, KPIName__c, KPIName__r.KPI_Title__c, Supplier__c, Supplier__r.Name FROM Consequence_Management__r )a ' +
        'FROM SPE_ConsequenceManagement__c where OwnerId=:currentUser';
    //***************************END*****************************//
        
        cmList.clear();
        List<SPE_ConsequenceManagement__c> dupCMList = Database.query(queryString);
    
    //***************************Changes For Encryption*****************************//    
        for (SPE_ConsequenceManagement__c cm : dupCMList )
            {
              if  (cm.Consequence_Management__r.size() > 0)
                  { 
                      String ssupplier = cm.Supplier__r.Name;
                      Matcher MySupplierMatcher = MySupplierPattern.matcher(ssupplier);
                      
                       if (MySupplierMatcher.find())
                           { 
                                if  (cm.Consequence_Management__r.size() > 0)
                                    {
                                        cmList.add(cm);
                                    }
                           }
                  }   
            }
     //***************************END*****************************//       
    }
    
    public void deLinkParentTicket()
    {
        Id cmId = ApexPages.currentPage().getParameters().get('Id');
        
        SPE_ConsequenceManagement__c cm = new SPE_ConsequenceManagement__c();
        cm.Id = cmId;
        cm.MasterCM__c = null;
        
        update cm;
        
        searchMatchingTicket();
    }
    
    public void deLinkChildTicket()
    {
        Id cmId = ApexPages.currentPage().getParameters().get('Id');
        
        List<SPE_ConsequenceManagement__c> toBeUpdateCM = [SELECT Id, MasterCM__c FROM SPE_ConsequenceManagement__c WHERE MasterCM__c =:cmId];
        
        for (SPE_ConsequenceManagement__c cm : toBeUpdateCM)
        {
            cm.MasterCM__c = null;
        }
        
        update toBeUpdateCM;
        searchMatchingTicket();
    }
}