src/objects/SPE_ScoreCard__c.object
<CustomObject>
    <fields>
        <fullName>isScoreGenerated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isScoreGenerated</label>
        <type>Checkbox</type>
    </fields>
    <label>ScoreCard</label>
    <nameField>
        <label>Score Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScoreCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_BatchScorecardUpdate.cls
global class SPE_BatchScorecardUpdate implements Database.Batchable<sObject>,Schedulable {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT CreatedDate,Id,isScoreGenerated__c FROM SPE_ScoreCard__c WHERE CreatedDate = today';
        return Database.getQueryLocator(query);
    }
    
    global void execute(SchedulableContext sc) 
    {
        Database.executebatch(this,integer.valueOf(1));
    }
    
    global void execute(Database.BatchableContext BC, List<SPE_ScoreCard__c> scope) {
         for(SPE_ScoreCard__c a : scope)
         {
             a.isScoreGenerated__c= true;            
         }
         update scope;
    }   
    
    global void finish(Database.BatchableContext BC) {
    }
}