src/objects/SPE_ScoreCard__c.object
<CustomObject>
    <fields>
        <fullName>AggregationRule__c</fullName>
        <label>Aggregation Rule</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nego_Responsible__c</fullName>
        <label>Nego Responsible</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>All CO Region</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>NAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Market Unit</label>
        <picklist>
            <controllingField>Region__c</controllingField>
            <picklistValues>
                <fullName>All CO Subregion</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EE-RUB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JAPAN-JP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEE-CE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEE-CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEE-IB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEE-IM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEE-MED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEE-TCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE-GP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE-N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE-NOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE-UI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WE-W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INDIA-IND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAT-AND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAT-MCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LAT-S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEA-CEWA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEA-KSA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEA-LGIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEA-NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEA-SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEA-SKIL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAM-US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC-ANO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC-ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC-ASO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enterprise ID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ScoreCards</relationshipLabel>
        <relationshipName>ScoreCards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ScoreCard</label>
    <nameField>
        <label>Score Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ScoreCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_ScorecardTempValues__c.object
<CustomObject>
    <fields>
        <fullName>DateOfExecution__c</fullName>
        <formula>if( Tracker_Score__c==&apos;&apos;, SPETracker__r.SPETracker__r.DateOfExecution__c, Tracker_Score__r.SPETracker__r.DateOfExecution__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DateOfExecution</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPE_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>SPE_ScorecardTempValues</relationshipLabel>
        <relationshipName>SPE_ScorecardTempValues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScoreCard__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ScoreCard</label>
        <referenceTo>SPE_ScoreCard__c</referenceTo>
        <relationshipLabel>SPE_ScorecardTempValues</relationshipLabel>
        <relationshipName>SPE_ScorecardTempValues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SPE_ScorecardTempValues</relationshipLabel>
        <relationshipName>SPE_ScorecardTempValues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tracker_Score__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tracker Score</label>
        <referenceTo>SPE_TrackerScore__c</referenceTo>
        <relationshipLabel>SPE_ScorecardTempValues</relationshipLabel>
        <relationshipName>SPE_ScorecardTempValues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>SPE_ScorecardTempValues</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>SPE_ScorecardTempValues Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE_ScorecardTempValues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_Spend__c.object
<CustomObject>
    <fields>
        <fullName>Nego_Responsible__c</fullName>
        <label>Nego Responsible</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>R+G</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Spend</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>SpendId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPEPlan__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>AggregationDuration__c</fullName>
        <label>Aggregation Duration</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Market Unit</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SEE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SPE Plan</label>
    <nameField>
        <displayFormat>SPE - {00000}</displayFormat>
        <label>SPE Plan Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_Volume__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Sub Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Volume</label>
    <nameField>
        <displayFormat>VolumeId-{00000}</displayFormat>
        <label>VolumeId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_BatchScorecardGenerateTempValues2.cls
global class SPE_BatchScorecardGenerateTempValues2 implements Database.Batchable<sObject>,Schedulable  {


    global void execute(SchedulableContext sc) 
    {
        Database.executebatch(this,integer.valueOf(1));
    }

    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        set<id> scorecardId= new set<id>();
         Date dddd=system.today()-1;
        for(SPE_ScoreCard__c s:[select id from SPE_ScoreCard__c where createdDate>=:dddd]) {
           scorecardId.add(s.id);  
        } 
        
        String query = 'SELECT Id,ScoreCard__r.Nego_Responsible__c,Supplier__c,SPE_Plan__c ,DateOfExecution__c,ScoreCard__r.AggregationRule__c, Tracker_Score__c,Weight__c FROM SPE_ScorecardTempValues__c WHERE ScoreCard__c IN: scorecardId ';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List <SPE_ScorecardTempValues__c > scope) 
    {
         // Simple average
     if(scope[0].ScoreCard__r.AggregationRule__c=='Simple Average'){
      scope[0].Weight__c=1;
     }
     
     
     // Spend Calculations
     if(scope[0].ScoreCard__r.AggregationRule__c=='Weighted Average by Spend'){
         list<SPE_SPEPlan__c> plans=new list<SPE_SPEPlan__c>();
            plans=[select id from SPE_SPEPlan__c];
            String project;
            String Country;
            String SubRegion;
            String Region;
            String CategoryArea;
            String CategoryGroup;
            String Category;
              
              
            id SupplierId=scope[0].Supplier__c;
            Date dd=scope[0].DateOfExecution__c.addMonths(-1);
            integer noOfDays = Date.daysInMonth(dd.year(), dd.month());
            Date EndDate= Date.newInstance( dd.year(), dd.month(), noOfDays);
            Date startDate= Date.newInstance( dd.year(), dd.month(), 1);
            SPE_SPEPlan__c planDetail= new SPE_SPEPlan__c ();
            planDetail=[select Region__c,AggregationDuration__c,SubRegion__c,Country__c,Project__c,CategoryCluster__c,CategoryGroup__c,Category__c from SPE_SPEPlan__c where id=:scope[0].SPE_Plan__c ] ;      
            if(integer.valueOf(planDetail.AggregationDuration__c)>1)
            {
            Date ddd=scope[0].DateOfExecution__c.addMonths(-integer.valueOf(planDetail.AggregationDuration__c));
            startDate= Date.newInstance( ddd.year(), ddd.month(), 1);  
            }
            string nego='';
            string nego1='';
            string q='SELECT Spend__c FROM SPE_Spend__c where EnterpriseId__c=:SupplierId and Period__c>=:startDate and Period__c<=:EndDate';
            
            if(!(planDetail.project__c).containsIgnoreCase('All')){
                project=planDetail.project__c;
                q=q+' and Project__c=:project';
                }
            if(!(planDetail.Country__c).containsIgnoreCase('All')){
                Country=planDetail.Country__c;
                q=q+' and Country__c=:Country';
                }
            if(!(planDetail.SubRegion__c).containsIgnoreCase('All')){
                SubRegion=planDetail.SubRegion__c;
                q=q+' and Sub_Region__c=:SubRegion';
                }
            if(!(planDetail.Region__c).containsIgnoreCase('All')){
                Region=planDetail.Region__c;
                if(Scope[0].ScoreCard__r.Nego_Responsible__c=='' || Scope[0].ScoreCard__r.Nego_Responsible__c=='R')
                 {nego='R';
                     q=q+' and Region__c=:Region and Nego_Responsible__c=:nego';
                 }
                 else if(Scope[0].ScoreCard__r.Nego_Responsible__c=='G') {
                 nego='R';
                 q=q+' and Region__c=:Region and Nego_Responsible__c=:nego';            
                 }
                 
                 else if(Scope[0].ScoreCard__r.Nego_Responsible__c=='R+G') {
                 nego='R';
                 nego1='G';
                 q=q+' and Region__c=:Region and (Nego_Responsible__c=:nego OR Nego_Responsible__c=:nego1)'; 
                 }            
                }
            if(!(planDetail.CategoryCluster__c).containsIgnoreCase('All')){
                CategoryArea=planDetail.CategoryCluster__c;
                q=q+' and CategoryArea__c=:CategoryArea';
                }
            if(!(planDetail.CategoryGroup__c).containsIgnoreCase('All')){
                CategoryGroup=planDetail.CategoryGroup__c;
                q=q+' and CategoryGroup__c=:CategoryGroup';
                }
            if(!(planDetail.Category__c ).containsIgnoreCase('All')){
                Category=planDetail.Category__c ;
                q=q+' and Category__c=:Category';
                }    
            
            
            
            decimal Spend=0.0;
            for(SPE_Spend__c s:Database.query(q)){
            spend=spend+ s.spend__c;
            }
            
            if(spend!=0.0)
            scope[0].Weight__c=spend;
        }
        
        
        
        
        
        
     // Spend Calculations
     if(scope[0].ScoreCard__r.AggregationRule__c=='Weighted Average by Volume'){
                  
            String CategoryArea;
            String CategoryGroup;
            String Category;
              
              
            id SupplierId=scope[0].Supplier__c;
            Date dd=scope[0].DateOfExecution__c.addMonths(-1);
            integer noOfDays = Date.daysInMonth(dd.year(), dd.month());
            Date EndDate= Date.newInstance( dd.year(), dd.month(), noOfDays);
            Date startDate= Date.newInstance( dd.year(), dd.month(), 1);
            SPE_SPEPlan__c planDetail= new SPE_SPEPlan__c ();
            planDetail=[select Region__c,AggregationDuration__c,SubRegion__c,Country__c,Project__c,CategoryCluster__c,CategoryGroup__c,Category__c from SPE_SPEPlan__c where id=:scope[0].SPE_Plan__c ] ;      
          
            if(integer.valueOf(planDetail.AggregationDuration__c)>1)
            {
            Date ddd=scope[0].DateOfExecution__c.addMonths(-integer.valueOf(planDetail.AggregationDuration__c));
            startDate= Date.newInstance( ddd.year(), ddd.month(), 1);  
            } 
            
            string q='SELECT Volume__c FROM SPE_Volume__c where EnterpriseId__c=:SupplierId and Period__c>=:startDate and Period__c<=:EndDate';
            
            if(!(planDetail.CategoryCluster__c).containsIgnoreCase('All')){
                CategoryArea=planDetail.CategoryCluster__c;
                q=q+' and CategoryCluster__c=:CategoryArea';
                }
            if(!(planDetail.CategoryGroup__c).containsIgnoreCase('All')){
                CategoryGroup=planDetail.CategoryGroup__c;
                q=q+' and Category_Group__c=:CategoryGroup';
                }
            if(!(planDetail.Category__c ).containsIgnoreCase('All')){
                Category=planDetail.Category__c ;
                q=q+' and Category__c=:Category';
                }    
            
            
            
            decimal volume=0.0;
            for(SPE_Volume__c  s:Database.query(q)){
            volume=volume+ s.Volume__c ;
            }
            
            if(volume!=0.0)
            scope[0].Weight__c=volume;
        }
        
        
        
        // logic 4
        if(scope[0].ScoreCard__r.AggregationRule__c=='BW with Project Simple Average') {
            list<SPE_SPEPlan__c> plans=new list<SPE_SPEPlan__c>();
            plans=[select id from SPE_SPEPlan__c];
            String project;
            String Country;
            String SubRegion;
            String Region;
            String CategoryArea;
            String CategoryGroup;
            String Category;
              
              
            id SupplierId=scope[0].Supplier__c;
            Date dd=scope[0].DateOfExecution__c.addMonths(-1);
            integer noOfDays = Date.daysInMonth(dd.year(), dd.month());
            Date EndDate= Date.newInstance( dd.year(), dd.month(), noOfDays);
            Date startDate= Date.newInstance( dd.year(), dd.month(), 1);
            SPE_SPEPlan__c planDetail= new SPE_SPEPlan__c ();
            planDetail=[select Region__c,SubRegion__c,Country__c,Project__c,CategoryCluster__c,CategoryGroup__c,Category__c from SPE_SPEPlan__c where id=:scope[0].SPE_Plan__c ] ;      
          
            
            string q='SELECT Spend__c FROM SPE_Spend__c where EnterpriseId__c=:SupplierId and Period__c>=:startDate and Period__c<=:EndDate';
            
            
                
            if(!(planDetail.Country__c).containsIgnoreCase('All')){
                Country=planDetail.Country__c;
                q=q+' and Country__c=:Country';
                }
            if(!(planDetail.SubRegion__c).containsIgnoreCase('All')){
                SubRegion=planDetail.SubRegion__c;
                q=q+' and Sub_Region__c=:SubRegion';
                }
            if(!(planDetail.Region__c).containsIgnoreCase('All')){
                Region=planDetail.Region__c;
                q=q+' and Region__c=:Region';            
                }
            if(!(planDetail.CategoryCluster__c).containsIgnoreCase('All')){
                CategoryArea=planDetail.CategoryCluster__c;
                q=q+' and CategoryArea__c=:CategoryArea';
                }
            if(!(planDetail.CategoryGroup__c).containsIgnoreCase('All')){
                CategoryGroup=planDetail.CategoryGroup__c;
                q=q+' and CategoryGroup__c=:CategoryGroup';
                }
            if(!(planDetail.Category__c ).containsIgnoreCase('All')){
                Category=planDetail.Category__c ;
                q=q+' and Category__c=:Category';
                }    
            
            
            
            decimal Spend=0.0;
            for(SPE_Spend__c s:Database.query(q)){
            spend=spend+ s.spend__c;
            }
            
            if(spend!=0.0){
            scope[0].Weight__c=spend;
            }
           
        }
     
     update scope[0];   
           
    }
    
    
    
    
    
    
    
    
    
    
    
    
    global void finish(Database.BatchableContext BC) 
    {
    SPE_BatchScorecardGenerateTempValues3 dt= new SPE_BatchScorecardGenerateTempValues3 ();
    database.executebatch(dt,1);        
    }
 }