src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PIValues__c.object
<CustomObject>
    <fields>
        <fullName>PIDefination__c</fullName>
        <label>PI Defination</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>PI Values</relationshipLabel>
        <relationshipName>PI_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PI Values</label>
    <nameField>
        <displayFormat>PVI-{00000}</displayFormat>
        <label>PI Values ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SPE_PIValuesDeleteCon.cls
public class SPE_PIValuesDeleteCon
{	
	public SPE_PIDefinition__c PIDef{get; set;}
    private Id piDefinitionId;
    
    public SPE_PIValuesDeleteCon()
    {
         piDefinitionId = ApexPages.currentPage().getParameters().get('Id');
         PIDef = [SELECT ID FROM SPE_PIDefinition__c WHERE Id =: piDefinitionId];
    }
    
    public Pagereference deletePIValues()
    {
        List<SPE_PIValues__c> toBeDeletedPIValues = [Select Id 
                                                     FROM SPE_PIValues__c 
                                                     WHERE PIDefination__c =: piDefinitionId 
                                                     LIMIT 10000];
        
        
        Database.delete(toBeDeletedPIValues);
    
        Pagereference pg = new Pagereference('/'+piDefinitionId);
        
        return pg;
    }
}