src/objects/SPE_KPICalculation__c.object
<CustomObject>
    <fields>
        <fullName>Aggregation__c</fullName>
        <label>Aggregation</label>
        <picklist>
            <picklistValues>
                <fullName>Min</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Count</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Min( Across Suppliers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Max( Across Suppliers)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avg( Across Suppliers)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ConstantValue__c</fullName>
        <label>Constant Value</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Index__c</fullName>
        <label>Index</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PIDefination__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Defination</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please Select a Published PI</errorMessage>
            <filterItems>
                <field>SPE_PIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TimeFrame__c</fullName>
        <label>Time Frame (In Months)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>KPI Calculation</label>
    <nameField>
        <displayFormat>KCal-{00000}</displayFormat>
        <label>KPI Calculation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Aggregation__c</fullName>
        <label>Aggregation</label>
        <picklist>
            <picklistValues>
                <fullName>AVG</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAX</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <description>Enter date when the KPI will be calculated (for data) or scheduled (for survey)</description>
        <inlineHelpText>This is an auto computed date looking at the underlying PI definitions (latest PI upload date + buffer days). This refreshes in batches and not instantaneously.</inlineHelpText>
        <label>Next Scheduled Date</label>
        <type>Date</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Supplier_KPI_Callculation__c.object
<CustomObject>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <encrypted>true</encrypted>
        <label>EnterpriseID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI_Calculation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Calculation</label>
        <referenceTo>SPE_KPICalculation__c</referenceTo>
        <relationshipName>Supplier_KPI_Callculation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>KPI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipName>Supplier_KPI_Callculation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Supplier KPI Calculation</label>
    <nameField>
        <displayFormat>ID-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier KPI Calculation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_KPISchedulePrebatch3.cls
global class SPE_KPISchedulePrebatch3 implements Database.Batchable <sObject> , Schedulable {

    global void execute(SchedulableContext sc) {
        Database.executebatch(this,10000);
    }

    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        Date d=system.today();
        d=d.addDays(integer.valueOf(Label.SPE_ScheduleDateModifier));
        Set<string> k=new set<string>();
        k.add(SPE_Constants.KPICALC_MINSUPPLIER_AGGREGATION);
        k.add(SPE_Constants.KPICALC_MAXSUPPLIER_AGGREGATION);
        k.add(SPE_Constants.KPICALC_AVGSUPPLIER_AGGREGATION );


        String query='select id,PIDefination__c,TimeFrame__c,ConstantValue__c,KPIDefinition__c,Aggregation__c,index__c from SPE_KPICalculation__c where KPIDefinition__r.ScheduledDate__c=:d and Aggregation__c IN:k  AND (KPIDefinition__r.LifecycleStage__c = \'Published\' OR  KPIDefinition__r.LifecycleStage__c = \'Pilot\')';
        return Database.getQueryLocator(query);
        
    }

    global void execute(Database.BatchableContext BC, List <SPE_KPICalculation__c> scope) {
    
        
        
        List<Supplier_KPI_Callculation__c> skc= new list<Supplier_KPI_Callculation__c>();
        for(SPE_KPICalculation__c k:scope)
         {
            Supplier_KPI_Callculation__c p = new Supplier_KPI_Callculation__c();
            p.enterpriseId__c= SPE_Constants.ENTERPRISEVALUEACROSS;
            p.KPI__c=k.KPIDefinition__c;
            p.KPI_Calculation__c=k.id;
            skc.add(p);
            }
         
      
            
        insert skc;

    }
    
    global void finish(Database.BatchableContext BC) {
      if(!Test.isRunningTest()){
     SPE_KPISchedulePrebatch3Exec dtBatch= new SPE_KPISchedulePrebatch3Exec (); 
     database.executebatch(dtBatch,1); 
          }
    }
}