src/objects/SPE_ScorecardTemplate__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>See SPE Process Guidelines</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pilot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Scorecard Template</label>
    <nameField>
        <label>Scorecard Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scorecard Templates</pluralLabel>
    <recordTypes>
        <fullName>Draft</fullName>
        <active>true</active>
        <label>Draft</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_ScorecardTemplateLifecycleEXTTest.cls
@isTest

public class SPE_ScorecardTemplateLifecycleEXTTest{

public static  testMethod void  SPE_ScorecardTemplateLifecycleEXTTest(){

    Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
  
    User u = new User(Alias = 'standt', Email='standarduser@abctestorg.com', 
    EmailEncodingKey='UTF-8', LastName='Testing User', LanguageLocaleKey='en_US', 
    LocaleSidKey='en_US', ProfileId = p.Id, 
    TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testabcorg.com');
    insert u;   
     
    SPE_ScorecardTemplate__c sc = new SPE_ScorecardTemplate__c();
    sc.Name = 'Test ScoreTemplate';
    sc.Stage__c = 'Draft';
    insert sc;
    
    
    Test.setCurrentPage(Page.SPE_ScorecardTemplateLifecycleButtons);
    ApexPages.StandardController stdController = new ApexPages.StandardController(sc);
    SPE_ScorecardTemplateLifecycleEXT ext = new SPE_ScorecardTemplateLifecycleEXT(stdController);
    sc.Stage__c = 'Published';
    update sc;
   
    ext.StagePublished();
    ext.StageObsolete();
    
    

 }
}