src/objects/SPE_PIValues__c.object
<CustomObject>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>FACILITY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT PROCUREMENT &amp; TELECOMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LOGISTICS SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PROFESSIONAL SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D SUBCONTRACTING</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRAVEL &amp; FLEET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INTERCONNECT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MECHANICS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPTICAL COMPONENTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEMICONDUCTOR AND RF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STANDARD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CARE SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXTERNAL WORKFORCE SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI MATERIALS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBCONTRACTING MS NPO &amp; SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TESTING MANUFACTURING &amp; MEASUREMENT EQUIPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BUSINESS INCUBATION &amp; E2E SOLUTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ELECTRONIC MANUFACTURING SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBCONTRACTING TELECOM IMPLEMENTATION SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SUBCONTRACTING OTHER NI SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEACTIVATED STRUCTURES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISCONTINUED BUSINESS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EXPENDITURES REPORTED ERRONEOUSLY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NON-MANAGED EXPENDITURES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NOT ASSIGNED SPEND GROUP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UNREPORTED SPEND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D SOLUTIONS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TESTING AND MANUFACTURING EQUIPMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MECHANICS &amp; RF PRODUCTS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <encrypted>true</encrypted>
        <label>Enterprise ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberValue__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PIDefination__c</fullName>
        <label>PI Defination</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>PI Values</relationshipLabel>
        <relationshipName>PI_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>PI Values</label>
    <nameField>
        <displayFormat>PVI-{00000}</displayFormat>
        <label>PI Values ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SPE_RemoveDuplicateFromPivalues.cls
global class SPE_RemoveDuplicateFromPivalues implements Database.Batchable <sObject>,Schedulable 
{
    global Id piIds;
  
    global void execute(SchedulableContext sc) 
    {
        Database.executebatch(this);

    }

    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        Id ID='a1QZ0000003PDbL';
        String query = 'select id,Period__c,EnterpriseID__c,CategoryGroup__c,NumberValue__c from SPE_PIValues__c where PIDefination__c=:ID';
        system.debug('Query*********'+query);
        return Database.getQueryLocator(query);
        
    }

    global void execute(Database.BatchableContext BC, List <SPE_PIValues__c> scope) 
    {
            list<SPE_PIValues__c> p=new list<SPE_PIValues__c>();
            p=[select id,Period__c,EnterpriseID__c,CategoryGroup__c,NumberValue__c from SPE_PIValues__c where PIDefination__c='a1QZ0000003PDbL'];
            
            set<String> setStr= new set<String>();    
            set<id> dup= new set<Id>();
            
            integer k=0;
            for(integer l=0;l<p.size();l++) {
              string s=String.valueOf(p[l].period__c)+String.valueOf(p[l].EnterpriseID__c)+String.valueOf(p[l].CategoryGroup__c)+String.valueOf(p[l].NumberValue__c);         
              if(setStr.contains(s)){
                 dup.add(p[l].id);
                
              }
              else {
              setStr.add(s);
              }
              
            }
           
            
            system.debug('*******dupsize'+dup.size());
            delete[select id from SPE_PIValues__c where id IN: Dup];
            

    }
    
    global void finish(Database.BatchableContext BC) 
    {
         
    }
}