src/objects/SPE_ScorecardGenerator__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Days__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Buffer Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FrequencyInMonths__c</fullName>
        <label>Frequency In Months</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Computed_Day__c</fullName>
        <inlineHelpText>Next Computed Day is computed from the Date Of Execution of related SPE Trackers.</inlineHelpText>
        <label>Next Computed Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ScorecardTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scorecard Template</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>SPE_ScorecardTemplate__c.Stage__c</field>
                <operation>equals</operation>
                <value>Published</value>
            </filterItems>
            <filterItems>
                <field>SPE_ScorecardTemplate__c.Stage__c</field>
                <operation>equals</operation>
                <value>Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_ScorecardTemplate__c</referenceTo>
        <relationshipLabel>Scorecard Generators</relationshipLabel>
        <relationshipName>Scorecard_Generators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Scorecard Generator</label>
    <nameField>
        <label>Generate Score Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scorecard Generators</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_ScorecardSPETemplateMap__c.object
<CustomObject>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>Scorecard SPE Template Maps</relationshipLabel>
        <relationshipName>Scorecard_SPE_Template_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScorecardTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scorecard Template</label>
        <referenceTo>SPE_ScorecardTemplate__c</referenceTo>
        <relationshipLabel>Scorecard SPE Template Maps</relationshipLabel>
        <relationshipName>Scorecard_SPE_Template_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scorecard SPE Template Map</label>
    <nameField>
        <displayFormat>SST-{00000}</displayFormat>
        <label>Scorecard SPE Template Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard SPE Template Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPEPlan__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Additional_Days__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Buffer Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <inlineHelpText>On what date with the SPE Plan no longer be used</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FrequencyInMonths__c</fullName>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Computed_Day__c</fullName>
        <label>Next Computed Day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE Plans</relationshipLabel>
        <relationshipName>SPE_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <inlineHelpText>When during the period the SPE Tracker will be computed</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>SPE Plan</label>
    <nameField>
        <displayFormat>SPE - {00000}</displayFormat>
        <label>SPE Plan Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPETracker__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>DateOfExecution__c</fullName>
        <label>Date Of Execution</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <formula>SurveyExecutionBeforeIndays__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SPEPlan__c</fullName>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>SPE Trackers</relationshipLabel>
        <relationshipName>SPE_Trackers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE Trackers</relationshipLabel>
        <relationshipName>SPE_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abandoned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SPE Tracker</label>
    <nameField>
        <label>SPE Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SPE2SGNewComputedDateUpdateBatch_new.cls
global class SPE2SGNewComputedDateUpdateBatch_new implements Database.Batchable<sObject>{
    global String query;
    global Date kpiDay;
    
    global SPE2SGNewComputedDateUpdateBatch_new(){
        query='SELECT Name,Additional_Days__c,Next_Computed_Day__c,StartDate__c,FrequencyInMonths__c,ScorecardTemplate__c,';
        query+='EndDate__c FROM SPE_ScorecardGenerator__c where ((Next_Computed_Day__c < today OR Next_Computed_Day__c = Null) AND EndDate__c > today AND FrequencyInMonths__c != Null)';      
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject>scope){
           
        List<SPE_ScorecardGenerator__c>  sptemp = new List<SPE_ScorecardGenerator__c>();
        Date mydate = System.Today();
        Integer monthvalue = mydate.Month();       
        kpiDay = System.Today();
        
        for(SObject obj:scope){  
           SPE_ScorecardGenerator__c sgdata = (SPE_ScorecardGenerator__c)obj;   
           Id templateId = sgdata.ScorecardTemplate__c;
           List<SPE_ScorecardSPETemplateMap__c> scorecardTemplatelist = [SELECT SPETemplate__c,ScorecardTemplate__c
                                                                         FROM SPE_ScorecardSPETemplateMap__c
                                                                         WHERE ScorecardTemplate__c =: templateId];
                                                         
            //sgdata.ScorecardTemplate__c = scorecardTemplates[0].ScorecardTemplate__c;
            List<Id> spetemplatesID = new List<ID>();
            for(SPE_ScorecardSPETemplateMap__c ssspe: scorecardTemplatelist){
                spetemplatesID.add(ssspe.SPETemplate__c);
            }
            
            List<SPE_SPEPlan__c> spePlanMapList = [SELECT Id,SPETemplate__c,Next_Computed_Day__c from SPE_SPEPlan__c where SPETemplate__c IN:spetemplatesID];
            List<ID> speplanID = new List<ID>();
            for(SPE_SPEPlan__c spp: spePlanMapList){
                speplanID.add(spp.ID);
            }
            
            //List<SPE_SPETracker__c> spetrackList = [Select ID,Name,DateOfExecution__c,SPEPlan__c,Period__c from SPE_SPETracker__c where SPEPlan__c IN:speplanID order by DateOfExecution__c asc];
            List<SPE_SPETracker__c> spetrackList = [Select ID,Name,DateOfExecution__c,SPEPlan__c,Period__c from SPE_SPETracker__c where SPEPlan__c IN:speplanID AND Status__c = 'Pending'];
            
            for(SPE_SPETracker__c speTrackMap : spetrackList)
            {  
                if (speTrackMap.DateOfExecution__c != null && monthvalue == speTrackMap.DateOfExecution__c.Month() && System.Today().Year() == speTrackMap.DateOfExecution__c.Year())
                {
                    if(speTrackMap.DateOfExecution__c > kpiDay){
                        kpiDay = speTrackMap.DateOfExecution__c;
                    }                               
                }
            }
       
            if(kpiDay == Date.newinstance(1960, 1, 1) || kpiDay < System.Today()){
               kpiDay = System.Today(); 
            }
             
            if(sgdata.Additional_Days__c != Null){
                Integer additional_days = Integer.ValueOf(sgdata.Additional_Days__c);
                kpiDay = kpiDay.addDays(additional_days);
            }
            
            if(kpiDay < System.Today()){
                if(sgdata.FrequencyInMonths__c != Null){
                   Integer additional_months = Integer.ValueOf(sgdata.FrequencyInMonths__c);
                   kpiDay = kpiDay.addMonths(additional_months); 
                }
            }
            
            if(kpiDay < sgdata.EndDate__c && kpiDay > sgdata.StartDate__c && kpiDay >= System.Today()){
                sgdata.Next_Computed_Day__c = kpiday;
            }
            else if(kpiDay < sgdata.EndDate__c && kpiDay < sgdata.StartDate__c && kpiDay >= System.Today()){
                //sgdata.Next_Computed_Day__c = sgdata.StartDate__c;
                Date calNCD = Date.NewInstance(sgdata.StartDate__c.Year(),sgdata.StartDate__c.Month(),kpiday.Day());
                if(calNCD >= sgdata.StartDate__c){
                    sgdata.Next_Computed_Day__c = calNCD;
                }
                else{            
                    sgdata.Next_Computed_Day__c = sgdata.StartDate__c;
                }
            }
            else if(kpiDay < sgdata.EndDate__c && kpiDay > sgdata.StartDate__c && kpiDay < System.Today()){
                Integer additional_days = Integer.ValueOf(sgdata.Additional_Days__c);
                sgdata.Next_Computed_Day__c = System.Today().addDays(additional_days);
            }
            else if(kpiDay < sgdata.EndDate__c && kpiDay < sgdata.StartDate__c && kpiDay < System.Today()){
                //sgdata.Next_Computed_Day__c = sgdata.StartDate__c;
                Date calNCD = Date.NewInstance(sgdata.StartDate__c.Year(),sgdata.StartDate__c.Month(),kpiday.Day());
                if(calNCD >= sgdata.StartDate__c){
                    sgdata.Next_Computed_Day__c = calNCD;
                }
                else{            
                    sgdata.Next_Computed_Day__c = sgdata.StartDate__c;
                }
            }
            
           sptemp.add(sgdata);    
            
         }   
        
        try{
            update sptemp;
        }catch(Exception e){}
  
    }
    
    global void finish(Database.BatchableContext BC){
    }
}