src/objects/SPE_KPICalculation__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>KPI Calculations</relationshipLabel>
        <relationshipName>KPI_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>KPI Calculation</label>
    <nameField>
        <displayFormat>KCal-{00000}</displayFormat>
        <label>KPI Calculation Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>AbbreviatedName__c</fullName>
        <inlineHelpText>10 character limit.  Applicable for all languages.</inlineHelpText>
        <label>KPI Abbreviation</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ActualCalculation__c</fullName>
        <label>Actual Calculation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AggregationScope__c</fullName>
        <label>Aggregation Scope</label>
        <picklist>
            <picklistValues>
                <fullName>Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sub Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CalculationFormula__c</fullName>
        <label>Calculation Formula</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <inlineHelpText>Relevant org/group for this data</inlineHelpText>
        <label>Organization/Group</label>
        <picklist>
            <picklistValues>
                <fullName>INDIRECT PROCUREMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRODUCT PROCUREMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SERVICES PROCUREMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTNERING ORGANIZATION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOBILE BROADBAND</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Confidential__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this checkbox is checked then this KPI wont be visible to supplier on scorecards.</description>
        <inlineHelpText>Not to be communicated to supplier.</inlineHelpText>
        <label>Internal Use Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FrequencyinMonth__c</fullName>
        <label>Frequency in Month</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GeoScope__c</fullName>
        <label>Geography Scope</label>
        <picklist>
            <picklistValues>
                <fullName>All Markets</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Market Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group1__c</fullName>
        <inlineHelpText>See Guidelines</inlineHelpText>
        <label>Pillar</label>
        <picklist>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sustainability</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Group2__c</fullName>
        <inlineHelpText>See Guidelines</inlineHelpText>
        <label>Group 2</label>
        <picklist>
            <picklistValues>
                <fullName>Hard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Soft</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsHighBetter__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is High Better ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KPI_Description_Language_1__c</fullName>
        <label>KPI Description Language 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>KPI_Description_Language_2__c</fullName>
        <label>KPI Description Language 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>KPI_Description_Language_3__c</fullName>
        <label>KPI Description Language 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>KPI_Description_Language_4__c</fullName>
        <label>KPI Description Language 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>KPI_Description_Language_5__c</fullName>
        <label>KPI Description Language 5</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>KPI_Title_Language_1__c</fullName>
        <encrypted>true</encrypted>
        <label>KPI Title Language 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI_Title_Language_2__c</fullName>
        <encrypted>true</encrypted>
        <label>KPI Title Language 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI_Title_Language_3__c</fullName>
        <encrypted>true</encrypted>
        <label>KPI Title Language 3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI_Title_Language_4__c</fullName>
        <encrypted>true</encrypted>
        <label>KPI Title Language 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI_Title_Language_5__c</fullName>
        <encrypted>true</encrypted>
        <label>KPI Title Language 5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KPI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of KPI 
(Standard Name field of KPI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>KPI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <inlineHelpText>See Guidelines; sets the number of buckets or scores.</inlineHelpText>
        <label>Level</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MissingDatalogic__c</fullName>
        <inlineHelpText>Please Click on the Help Link on the top of this page</inlineHelpText>
        <label>Missing Data logic</label>
        <picklist>
            <picklistValues>
                <fullName>Past Data or Category Average</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPE Invalid</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OperationalType__c</fullName>
        <label>Operational Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lagging PI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leading PI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PI_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Data</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select a PI which is Number type,Data Acquisition Method is Data Load and Stage should be Published</errorMessage>
            <filterItems>
                <field>SPE_PIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>KPI</relationshipLabel>
        <relationshipName>KPI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurposeAndObjective__c</fullName>
        <inlineHelpText>255 Character Limit</inlineHelpText>
        <label>Purpose And Objective</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SchedulePeriod__c</fullName>
        <label>Schedule Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ScheduledDate__c</fullName>
        <description>Enter date when the KPI will be calculated (for data) or scheduled (for survey)</description>
        <inlineHelpText>This is an auto computed date looking at the underlying PI definitions (latest PI upload date + buffer days). This refreshes in batches and not instantaneously.</inlineHelpText>
        <label>Next Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Operational, Commercial, or Strategic</inlineHelpText>
        <label>KPI Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Operational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>i.e. Days, Units, %, Euros, etc.</inlineHelpText>
        <label>Unit of Measure</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_CreateKPIVersion.cls
public with sharing class SPE_CreateKPIVersion{
   
    public SPE_KPIDefinition__c objKPIDef{get;set;}
    private SPE_KPIDefinition__c objKPIDefCloned;
    private ID MasterKPIID;
    private List<SPE_KPICalculation__c> lstKPICalc;
    private List<SPE_KPICalculation__c> lstKPICalcCloned;
    public SPE_CreateKPIVersion(ApexPages.StandardController con){
        objKPIDef = new SPE_KPIDefinition__c();
        objKPIDefCloned = new SPE_KPIDefinition__c();
        lstKPICalc = new List<SPE_KPICalculation__c>();
        lstKPICalcCloned = new List<SPE_KPICalculation__c>();
        MasterKPIID = con.getId();
        if(con.getId() !=  null){
        
        //***************************Changes For Encryption*************************//
            objKPIDef = [select id, Name,KPI_Title__c,ActualCalculation__c,AggregationScope__c,CalculationFormula__c,CategoryScope__c ,
                            FrequencyinMonth__c,
                            GeoScope__c,Group1__c,Group2__c,Confidential__c,IsHighBetter__c,AbbreviatedName__c,
                            KPI_Description_Language_1__c,KPI_Description_Language_2__c,KPI_Description_Language_3__c,
                            KPI_Description_Language_4__c,KPI_Description_Language_5__c,Type__c,KPI_Title_Language_1__c,
                            KPI_Title_Language_2__c,KPI_Title_Language_3__c,KPI_Title_Language_4__c,KPI_Title_Language_5__c,
                            Level__c,MissingDatalogic__c,ScheduledDate__c,OperationalType__c,Cluster__c,PI_Data__c,
                            BUScope__c,PurposeAndObjective__c,SchedulePeriod__c,LifecycleStage__c,UoM__c,Master_KPI__c,RPNExpression__c
                    From
                        SPE_KPIDefinition__c
                    Where
                        Id =: con.getId()];
          //**********************************END*******************************//
            
            lstKPICalc = [select id,Aggregation__c,ConstantValue__c,Filter1__c,filter10__c,Filter2__c,Filter3__c,Filter4__c,
                            Filter5__c,Filter6__c,Filter7__c,Filter8__c,filter9__c,flag__c,Index__c,IndexName__c,KPIDefinition__c,
                            PIDefination__c,PrevKPIDefination__c,QuestionName__c,SurveyQuestion__c,TimeFrame__c
                     From SPE_KPICalculation__c
                     Where
                         KPIDefinition__c = : con.getId()];
            lstKPICalcCloned = lstKPICalc.deepClone();
        }
        else{
            objKPIDef = new SPE_KPIDefinition__c();
        }
       objKPIDef.lifecyclestage__c='Draft'; 
    }
    
    public pageReference SaveKPI(){
        try{
            if(objKPIDef != null){
                objKPIDefCloned = objKPIDef.clone(false,true);
            }
            if(objKPIDefCloned != null && objKPIDefCloned.Id != null)
                objKPIDefCloned.Id = null;
            
            if(objKPIDefCloned != null)
                if(objKPIDef.Master_KPI__c == null)
                {
                    objKPIDefCloned.Master_KPI__c=MasterKPIID;
                }
                else{
                    objKPIDefCloned.Master_KPI__c = objKPIDef.Master_KPI__c;
                }
                
                objKPIDefCloned.LifecycleStage__c = 'Draft';
                objKPIDefCloned.RPNExpression__c=objKPIDef.RPNExpression__c;
                insert objKPIDefCloned;
                
               
            
            if(objKPIDefCloned.id != null){
                for(SPE_KPICalculation__c objKPIC : lstKPICalcCloned){
                    objKPIC.Id = null;
                    objKPIC.KPIDefinition__c = objKPIDefCloned.id;
                }
                
                if(!lstKPICalcCloned.isEmpty())
                    insert lstKPICalcCloned;
            }
            
        }
        catch(Exception ex){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, ex.getMessage()));
            return null;
        }
        
        Pagereference pr = new Pagereference('/'+objKPIDefCloned.id);
      
        return pr;
    }
   
}