src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>BUScope__c</fullName>
        <label>Product Scope</label>
        <picklist>
            <picklistValues>
                <fullName>Business Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Products</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryScope__c</fullName>
        <label>Category scope</label>
        <picklist>
            <picklistValues>
                <fullName>Category Area</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Category</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All Categories</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of PI 
(Standard Name field of PI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>PI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_PiValueTemp__c.object
<CustomObject>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <encrypted>true</encrypted>
        <label>Enterprise ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketUnit__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberValue__c</fullName>
        <label>Number Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PIDefination__c</fullName>
        <label>PI Defination</label>
        <referenceTo>SPE_PIDefinition__c</referenceTo>
        <relationshipLabel>SPE_PiValueTemps</relationshipLabel>
        <relationshipName>SPE_PiValueTemps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueIdentifier__c</fullName>
        <label>Unique Identifier</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValidateCategory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ValidateCategory</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Verified_BU__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Verified BU</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Verified_Geo__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Verified Geo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VerrifiedEnterpriseID__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VerrifiedEnterpriseID</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE_PiValueTemp</label>
    <nameField>
        <displayFormat>PV-{0000}</displayFormat>
        <label>SPE_PiValueTemp Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE_PiValueTemps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/spe_verifycategoryExt.cls
public with sharing class spe_verifycategoryExt
{
    
    Public List<SPE_PiValueTemp__c> CategoryList1{get;set;}
    Public Boolean validCat {get;set;}
    Public Boolean CatArea{get;set;}
    Public Boolean CatGrp{get;set;}
    Public Boolean Cat{get;set;}
    public integer sizei{get;set;}
    public integer totalCount{get;set;}
    public String uniqueID;
    
    public spe_verifycategoryExt()
    {
        validCat =  true;
        CatArea = false;
        CatGrp = false;
        Cat = false;
        uniqueID = ApexPages.currentPage().getParameters().get('uID');
        
         //******************Changes For Encryption*****************// 
        CategoryList1 = [select id,name,BusinessLine__c,BusinessUnit__c,Category__c,Cluster__c,CategoryGroup__c,Period__c,
                    Country__c,EnterpriseID__c,Market__c,MarketUnit__c,NumberValue__c,PIDefination__r.PI_Title__c,PIDefination__r.name,Product__c,
                    Project__c,ValidateCategory__c,Verified__c,VerrifiedEnterpriseID__c,Verified_Geo__c,Verified_BU__c,PIDefination__r.BUScope__c,PIDefination__r.CategoryScope__c from SPE_PiValueTemp__c where ValidateCategory__c = :false and CreatedBy.id = :UserInfo.getUserId() and UniqueIdentifier__c =: uniqueID limit 999];              
        //********************END**********************//
        
        //-----------------------------------------------------------below line for error count---------------------------------------
        //        sizei = CategoryList1.size();
        
            sizei = [select count() from SPE_PiValueTemp__c  where ValidateCategory__c = :false and CreatedBy.id = :UserInfo.getUserId() and UniqueIdentifier__c =: uniqueID];
        //------------------------------------------------------------------------------------------------------------------------------
        
        for(AggregateResult ar:[SELECT count(id),UniqueIdentifier__c FROM SPE_PiValueTemp__c where CreatedBy.id = :UserInfo.getUserId() and UniqueIdentifier__c =: uniqueID GROUP BY UniqueIdentifier__c ])
        {
          totalCount=integer.valueOf(ar.get('expr0'));  
        }                          
                    
         for(SPE_PiValueTemp__c PiValtmp : CategoryList1)
         {
             if(PiValtmp.PIDefination__r.CategoryScope__c == 'Category')
             {
                 cat = true;
             }
             if(PiValtmp.PIDefination__r.CategoryScope__c == 'Category Area')
             {
                 CatArea = true;
             }
             if(PiValtmp.PIDefination__r.CategoryScope__c == 'Category Group')
             {
                 CatGrp = true;
             }
         }
                 
    }
    
    public pagereference updateCat()
    {
        update CategoryList1;
        pagereference  p= new pagereference('/apex/spe_verifyCategory?uID='+uniqueID);
        p.setRedirect(true);
        return p;
    }
    
     public pagereference validateGeography()
    {         
        pagereference  p= new pagereference('/apex/spe_verifyGeography?uID='+uniqueID);
        p.setRedirect(true);
        return p;             
    }
    public pagereference BatchUpload()
    {
        
        pagereference  p= new pagereference('/apex/SPE_FinalInsert_dataupload?uID='+uniqueID);
        p.setRedirect(true);
        return p;

    }
    
    public pagereference skiptoNxtVal()
    {
        pagereference  p= new pagereference('/apex/spe_verifyGeography?uID='+uniqueID);
        p.setRedirect(true);
        return p;
    }
    
}