src/objects/SPE_SPEPlan__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>See SPE Process Guidelines</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>identifierParam__c</fullName>
        <label>identifierParam</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE Plan</label>
    <nameField>
        <displayFormat>SPE - {00000}</displayFormat>
        <label>SPE Plan Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE2_PlanChangeStage.cls
public with sharing class SPE2_PlanChangeStage{
    private ApexPages.StandardController standardController;
    public List<SPE_SPEPlan__c> spePlanList{get;set;}
    public String spePlanIdentifier{get;set;}
    public SPE_SPEPlan__c spePlan{get;set;}
    public SPE2_PlanChangeStage(ApexPages.StandardController standardController){
        spePlan = new SPE_SPEPlan__c();
        spePlanList = new List<SPE_SPEPlan__c>();
        spePlanIdentifier = apexpages.currentpage().getparameters().get('planIdentifier');
        spePlanList = [Select Id,Name,identifierParam__c,Stage__c From SPE_SPEPlan__c 
                      Where identifierParam__c =:spePlanIdentifier];
        
    }
    public PageReference returnbackToPlan(){
        Schema.DescribeSObjectResult r = SPE_SPEPlan__c.sObjectType.getDescribe();
        String keyPrefix = r.getKeyPrefix();
        Pagereference pr =new Pagereference('/'+keyPrefix);
        return pr;
    }
    public PageReference updateSPEPlanStage(){
        for(SPE_SPEPlan__c pl :spePlanList){
            pl.Stage__c = spePlan.Stage__c;
        }
        try{
            update spePlanList;
        }catch(Exception e){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error, e.getMessage()));
        }
        Schema.DescribeSObjectResult r = SPE_SPEPlan__c.sObjectType.getDescribe();
        String keyPrefix = r.getKeyPrefix();
        Pagereference pr =new Pagereference('/'+keyPrefix);
        return pr;
    }
}