src/objects/SPE_PITempValue__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>PI Temp Values</relationshipLabel>
        <relationshipName>PI_Temp_Values</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PI Temp Value</label>
    <nameField>
        <displayFormat>PTVI-{00000}</displayFormat>
        <label>PI Temp Values Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Temp Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE2_DeletePITempValues.cls
global class SPE2_DeletePITempValues implements Database.Batchable<sObject>{
    global String kpiDefinationID; 
    global String query;
     global SPE2_DeletePITempValues(String kpiDefinationID){
        this.kpiDefinationID = kpiDefinationID;
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        query = 'Select ID from SPE_PITempValue__c WHERE KPIDefinition__c =: kpiDefinationID';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC,List<SPE_PITempValue__c> scope){ 
        delete scope;        
    }          
    global void finish(Database.BatchableContext BC){}
}