src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>DataAcquisitionMethod__c</fullName>
        <inlineHelpText>Identify how this data is acquired</inlineHelpText>
        <label>Data Acquisition Method</label>
        <picklist>
            <picklistValues>
                <fullName>Data Load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standalone Survey</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <description>Frequency with which the data is generally refreshed. Same as due date</description>
        <inlineHelpText>Specifies how often the data is posted or updated, i.e. monthly, annually, etc.</inlineHelpText>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LastPIImportDate__c</fullName>
        <label>Last PI Import Date</label>
        <summarizedField>SPE_PIValues__c.CreatedDate</summarizedField>
        <summaryForeignKey>SPE_PIValues__c.PIDefination__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>PI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PIUploadDuedate__c</fullName>
        <label>PI Upload Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of PI 
(Standard Name field of PI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>PI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PriorValue_Last_PI_Import_Date__c</fullName>
        <description>This is use for internal purpose only.</description>
        <label>PriorValue Last PI Import Date</label>
        <type>DateTime</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_SchedulePIDataBatchEmail.cls
/* ******************************** Schedule class for sending notification email to user ***************************************
    Createdby : Amjad khan                     Createddate : 12/03/2015                               
*/
Global class SPE_SchedulePIDataBatchEmail implements Database.batchable<sObject>, Schedulable
{
    global void execute(SchedulableContext sc) 
    {
        Database.executebatch(this,200);
    }

    Global Database.QueryLocator Start(Database.BatchableContext BC)
    {
        List<String> stage = new List<String>();
        stage.add(SPE_Constants.PUBLISHED_LIFECYCLESTAGE);
        stage.add(SPE_Constants.PILOT_LIFECYCLESTAGE); 
        
        String dataAcquisitionMethod = SPE_Constants.DATALOAD_DATAACQUISITION;
        
      //*****************************Changes For Encryption***********************//  
        String query = 'SELECT Id, Name,PI_Title__c,PIUploadDuedate__c,LastPIImportDate__c,OwnerId,CreatedBy.Email,PriorValue_Last_PI_Import_Date__c,Frequency__c '+ 
                       'FROM SPE_PIDefinition__c WHERE LifecycleStage__c In:stage AND DataAcquisitionMethod__c =: dataAcquisitionMethod';
      //*****************************END***********************//  
        return Database.getQueryLocator(query);
    }
    
    Global void execute(Database.BatchableContext BC, List<SPE_PIDefinition__c> scope)
    {
        
        List<Messaging.singleEmailMessage> mails = new List<Messaging.singleEmailMessage>();
        Date LastDUploadPI;
        Date DUploadPI;
        EmailTemplate reminderEmailTemplate =[Select id from EmailTemplate where name=:SPE_Constants.SPE_PIDATABATCHEMAILTEMPLATE];
        
        Map<Id,SPE_PIDefinition__c> PIMap=new Map<Id,SPE_PIDefinition__c>();
        for(SPE_PIDefinition__c PI : Scope)
        {
            
            if( PI.PIUploadDuedate__c !=null && PI.Frequency__c !=null)
            { 
                if(PI.LastPIImportDate__c!=null)
                {
                    LastDUploadPI=Date.newinstance(PI.LastPIImportDate__c.year(),PI.LastPIImportDate__c.month(),PI.LastPIImportDate__c.day());
                }
                
                if (PI.Frequency__c  == null || PI.Frequency__c == '0' || PI.Frequency__c == '')
                {
                    PI.Frequency__c = '1';
                }
                
                DUploadPI = PI.PIUploadDuedate__c.addMonths(-Integer.valueof(PI.Frequency__c));
                
                Date TODAYs = Date.today();
        
                string numberOfDays = Label.SPE_ScheduleDateModifier == null ? '0' : Label.SPE_ScheduleDateModifier;

                Integer addDay = integer.valueOf(numberOfDays) == null ? 0 : integer.valueOf(numberOfDays);
                
                TODAYs = TODAYs.addDays(addDay);
                
                if(TODAYs.adddays(7)==PI.PIUploadDuedate__c && (PI.LastPIImportDate__c==null || LastDUploadPI <= DUploadPI))
                { 
                      Messaging.singleEmailMessage mail = new Messaging.singleEmailMessage();
                      mail.setTargetObjectId(PI.ownerid);
                      mail.setWhatId(PI.id);
                      //mail.setCcAddresses(CcAdd);
                      mail.settemplateid(reminderEmailTemplate.id);
                      mail.setSaveAsActivity(false);
                      mails.add(mail);
                } 
            }
        }
        
        Messaging.sendEmail(mails);
        
        List<SPE_PIDefinition__c> UpdateListofPI= new List<SPE_PIDefinition__c>();
        for(SPE_PIDefinition__c PI : Scope)
        {
            if(date.today()==PI.PIUploadDuedate__c)
            {
                PI.PIUploadDuedate__c=PI.PIUploadDuedate__c.addmonths(Integer.valueof(PI.Frequency__c));
                UpdateListofPI.add(PI);
            }
        }
        
        update UpdateListofPI; 
    }
         
    Global void finish(Database.BatchableContext BC) 
    {
    } 
}