src/objects/SPE_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Error Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DmlFieldNames__c</fullName>
        <label>DmlFieldNames</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Error_Cause__c</fullName>
        <label>Error Cause</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Line__c</fullName>
        <label>Error Line</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SPE_Error_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SPE2 Error Log</label>
    <nameField>
        <displayFormat>EL-{00000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE2 Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE2ErrorLogCapture.cls
public class SPE2ErrorLogCapture{
    public Static SPE_Error_Log__c errorLogCapture(Exception e){
        SPE_Error_Log__c errorLog = new SPE_Error_Log__c();
        errorLog.Related_User__c = UserInfo.getUserId();
        errorLog.Error_Line__c = e.getLineNumber();
        errorLog.Exception_Type__c = e.getTypeName();
        //errorLog.Error_Cause__c = e.getCause().getMessage();
        errorLog.Description__c = e.getMessage();
        /*if(e.getNumDML() > 0){
            for(integer i = 0; i < e.getNumDML(); i++){
                errorLog.DmlFieldNames__c += e.getDmlFieldNames(i) + ';';
            }
        }*/
        
        return errorLog;
    }
}