src/objects/SPE_PIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_PI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>PI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PI_Title__c</fullName>
        <description>This field will be replaced with Standard Name field of PI 
(Standard Name field of PI is now auto number.)</description>
        <encrypted>true</encrypted>
        <label>PI Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValuesType__c</fullName>
        <description>To describe PI values data type</description>
        <inlineHelpText>Specify type of data values for this PI</inlineHelpText>
        <label>Values Type</label>
        <picklist>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>String</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PI Data</label>
    <nameField>
        <displayFormat>PI-{000000}</displayFormat>
        <label>PI Data Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PI Data</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_DataLoaderExtTest.cls
@isTest

public class SPE_DataLoaderExtTest {
    static testmethod void testSPE_DataLoaderExt() {
        test.startTest();
        SPE_PIDefinition__c PIDefObj = new SPE_PIDefinition__c();
        PIDefObj = SPE_TestObjectCreator.CreatePIDefinition();
        
        //***************Changes for Encryption****************//
        //PIDefObj.Name = 'Test PI Definition';
        PIDefObj.PI_Title__c = 'Test PI Definition';
        //*************End******************//
        
        PIDefObj.LifecycleStage__c = 'Draft';
        
        insert PIDefObj;
        
        //-----update PI Definition data ----
        
        PIDefObj.LifecycleStage__c= 'Published';
        update PIDefObj;
        
        system.assertequals(PIDefObj.LifecycleStage__c,'Published');
        ApexPages.StandardController sc = new ApexPages.StandardController(PIDefObj);
        SPE_DataLoaderExt objDtLoader = new SPE_DataLoaderExt(sc); 
        
        PIDefObj.ValuesType__c= 'Date';
        update PIDefObj;
        ApexPages.StandardController sc1 = new ApexPages.StandardController(PIDefObj);
        SPE_DataLoaderExt objDtLoader1 = new SPE_DataLoaderExt(sc1);
        system.assertEquals(objDtLoader1.strValueType, 'DateValue__c');
        
        PIDefObj.ValuesType__c= 'String';
        update PIDefObj;
        ApexPages.StandardController sc2 = new ApexPages.StandardController(PIDefObj);
        SPE_DataLoaderExt objDtLoader2 = new SPE_DataLoaderExt(sc2);
        system.assertEquals(objDtLoader2.strValueType, 'StringValue__c');
        PIDefObj.ValuesType__c= 'Boolean';
        update PIDefObj;
        ApexPages.StandardController sc3 = new ApexPages.StandardController(PIDefObj);
        SPE_DataLoaderExt objDtLoader3 = new SPE_DataLoaderExt(sc3);
        system.assertEquals(objDtLoader3.strValueType, 'BooleanValue__c');
        test.stopTest();
    }
}