src/objects/SPE_Report_Configs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used for controlling Scope filters for Spend and Volume weight calculation</description>
    <fields>
        <fullName>Market_Filter_For_Volume__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Market Filter For Volume</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Filter_For_Volume__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Product Filter For Volume</label>
        <type>Checkbox</type>
    </fields>
    <label>SPE Report Configs</label>
</CustomObject>

src/objects/SPE_Report_Parameter__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>CategoryCluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>SubRegion</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE Report Parameter</label>
    <nameField>
        <displayFormat>PN-{00000000}</displayFormat>
        <label>Parameter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Report Parameters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_Scorecard_Report__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period_Text__c</fullName>
        <formula>SPE_Tracker__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SPE_Report_Parameter__c</fullName>
        <label>SPE Report Parameter</label>
        <referenceTo>SPE_Report_Parameter__c</referenceTo>
        <relationshipLabel>SPE_Scorecard_Report</relationshipLabel>
        <relationshipName>SPE_Scorecard_Report</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SPE_Tracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Tracker</label>
        <referenceTo>SPE_SPETracker__c</referenceTo>
        <relationshipLabel>SPE_Scorecard_Report</relationshipLabel>
        <relationshipName>SPE_Scorecard_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SPE_Scorecard_Report</relationshipLabel>
        <relationshipName>SPE_Scorecard_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tracker_Score__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tracker Score</label>
        <referenceTo>SPE_TrackerScore__c</referenceTo>
        <relationshipLabel>SPE_Scorecard_Report</relationshipLabel>
        <relationshipName>SPE_Scorecard_Report</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>SPE_Scorecard_Report</label>
    <nameField>
        <displayFormat>R-{0000000000}</displayFormat>
        <label>SPE_Scorecard_Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE_Scorecard_Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_SPETracker__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <picklist>
            <picklistValues>
                <fullName>Global Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Implementation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems Integration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Planning and Optimization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mature Software Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Support Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MEDIA AND ENTERTAINMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mediate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Broadband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio Frequency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single RAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Radio Cluster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM and Mature Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OEM Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mature Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSMR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perfect Voice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquid Core</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Creation Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FDD LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TD LTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Core Cluster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Module</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEM and OSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Cell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3G Core</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>GLOBAL SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATURE SOFTWARE PRODUCTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOBILE BROADBAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPTICAL NETWORKS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <formula>SurveyExecutionBeforeIndays__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Market Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SPE Tracker</label>
    <nameField>
        <label>SPE Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_Volume__c.object
<CustomObject>
    <fields>
        <fullName>Business_Line__c</fullName>
        <label>Business Line</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Cluster</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category_Group__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EnterpriseID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EnterpriseID</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.ParentId</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Volume</relationshipLabel>
        <relationshipName>Volume</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Period</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Sub Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>Volume</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Volume</label>
    <nameField>
        <displayFormat>VolumeId-{00000}</displayFormat>
        <label>VolumeId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Volume</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_VolumeCalculateBatch.cls
global class SPE_VolumeCalculateBatch implements Database.Batchable<sObject>{
    global String query;
    global List<SPE_SPETracker__c> speTrackerList;
    global String aggrType;
    global Map<String,List<decimal>> speTrackerToWeigtage = new Map<String,List<decimal>>();
    global Map<String,decimal> trackerToWeightageSum;
    global Id ParamId;
    global Date startrangeDate;
    global Date endRangeDate;
    //global Set<String> spetrackers = new Set<String>();
    global SPE_VolumeCalculateBatch(String reportparamId){
        paramId = reportparamId;
        query = 'SELECT Period_Text__c,Score__c,Period__c,SPE_Report_Parameter__c,SPE_Tracker__c,SPE_Tracker__r.BusinessLine__c,SPE_Tracker__r.BusinessUnit__c,SPE_Tracker__r.Product__c,SPE_Tracker__r.Category__c,SPE_Tracker__r.CategoryGroup__c,SPE_Tracker__r.CategoryCluster__c,SPE_Tracker__r.Project__c,SPE_Tracker__r.Region__c,SPE_Tracker__r.SubRegion__c,SPE_Tracker__r.Country__c,Supplier__c,Tracker_Score__c,Weight__c FROM SPE_Scorecard_Report__c WHERE SPE_Report_Parameter__c ='+'\''+ParamId+'\''; 
        
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator(query);        
    }
    
    global void execute(Database.BatchableContext BC, List<sObject>scope){ 
        Integer monthVal;
        Integer yearVal;
        Integer noOfDays;
        Map<String,decimal> trackerToWeightage = new Map<String,decimal>();
        List<String> periodVals = new List<String>();
        Map<String,Integer> monthMap = new Map<String,Integer>();
        monthMap.put('January',01);
        monthMap.put('February',02);
        monthMap.put('March',03);
        monthMap.put('April',04);
        monthMap.put('May',05);
        monthMap.put('June',06);
        monthMap.put('July',07);
        monthMap.put('August',08);
        monthMap.put('September',09);
        monthMap.put('October',10);
        monthMap.put('November',11);
        monthMap.put('December',12);
        SPE_Report_Configs__c reportConfig = SPE_Report_Configs__c.getInstance('Filter for Spend and Volume');
        List <SPE_Scorecard_Report__c> sReportList = new list<SPE_Scorecard_Report__c>();
        for(sobject obj :scope){
            SPE_Scorecard_Report__c rObj = (SPE_Scorecard_Report__c)obj;
            periodVals = rObj.Period_Text__c.replace(' ','').split('-');
            monthVal = monthMap.get(periodVals[0]); 
            yearVal = integer.valueOf(periodVals[1]); 
            noOfDays = date.daysInMonth(yearVal,monthVal);
            startrangeDate = date.newInstance(yearVal,monthVal,1);
            endRangeDate = date.newInstance(yearVal,monthVal,noOfDays);
            List<AggregateResult> volList = new List<AggregateResult>();
            //SPE_Scorecard_Report__c sReport = new SPE_Scorecard_Report__c();
            String volSoql = 'Select SUM(Volume__c) total FROM SPE_Volume__c where EnterpriseID__c = '+'\''+rObj.supplier__c+'\'';
            if(reportConfig.Product_Filter_For_Volume__c){
                if(!volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.BusinessLine__c!='All Business Lines'){
                    volSoql +=' where ' + 'Business_Line__c='+'\''+rObj.SPE_Tracker__r.BusinessLine__c+'\'';
                }
                else if(volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.BusinessLine__c!='All Business Lines'){
                    volSoql +=' AND' + ' Business_Line__c='+'\''+rObj.SPE_Tracker__r.BusinessLine__c+'\'';
                } 
            }
            //-----Business line ends----
            if(reportConfig.Market_Filter_For_Volume__c){
                if(!volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.Region__c!='All Markets'){
                    volSoql +=' where ' + 'Region__c='+'\''+rObj.SPE_Tracker__r.Region__c+'\'';
                }
                else if(volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.BusinessLine__c!='All Markets'){
                    volSoql +=' AND' + ' Region__c='+'\''+rObj.SPE_Tracker__r.Region__c+'\'';
                } 
            }
            //------Market Ends-----
            if(reportConfig.Market_Filter_For_Volume__c){
                if(!volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.SubRegion__c!='All Market Units'){
                    volSoql +=' where ' + 'SubRegion__c='+'\''+rObj.SPE_Tracker__r.SubRegion__c+'\'';
                }
                else if(volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.SubRegion__c!='All Market Units'){
                    volSoql +=' AND' + ' SubRegion__c='+'\''+rObj.SPE_Tracker__r.SubRegion__c+'\'';
                } 
            }
            //-----Market Unit ends------
            
            if(reportConfig.Market_Filter_For_Volume__c){
                if(!volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.Country__c!='All Countries'){
                    volSoql +=' where ' + 'Country__c='+'\''+rObj.SPE_Tracker__r.Country__c+'\'';
                }
                else if(volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.Country__c!='All Countries'){
                    volSoql +=' AND' + ' Country__c='+'\''+rObj.SPE_Tracker__r.Country__c+'\'';
                } 
            }
            //-----Country Ends-----
            if(reportConfig.Market_Filter_For_Volume__c){
                if(!volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.Project__c!='All Projects'){
                    volSoql +=' where ' + 'Project__c='+'\''+rObj.SPE_Tracker__r.Project__c+'\'';
                }
                else if(volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.Project__c!='All Projects'){
                    volSoql +=' AND' + ' Project__c='+'\''+rObj.SPE_Tracker__r.Project__c+'\'';
                } 
            }
            //----- Project Ends-----
            if(reportConfig.Product_Filter_For_Volume__c){
                if(!volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.BusinessUnit__c!='All Business Units'){
                    volSoql +=' where ' + 'Business_Unit__c='+'\''+rObj.SPE_Tracker__r.BusinessUnit__c+'\'';
                }
                else if(volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.BusinessUnit__c!='All Business Units'){
                    volSoql +=' AND' + ' Business_Unit__c='+'\''+rObj.SPE_Tracker__r.BusinessUnit__c+'\'';
                } 
            }
            //------Business Unit ends-----
            if(reportConfig.Product_Filter_For_Volume__c){
                if(!volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.Product__c!='All Products'){
                    volSoql +=' where ' + 'Product__c='+'\''+rObj.SPE_Tracker__r.Product__c+'\'';
                }
                else if(volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.Product__c!='All Products'){
                    volSoql +=' AND' + ' Product__c='+'\''+rObj.SPE_Tracker__r.Product__c+'\'';
                } 
            }
            //------Product Ends----
            
             if(!volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.Category__c!='All Categories'){
                volSoql +=' where ' + 'Category__c='+'\''+rObj.SPE_Tracker__r.Category__c+'\'';
            }
            else if(volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.Category__c!='All Categories'){
                volSoql +=' AND' + ' Category__c='+'\''+rObj.SPE_Tracker__r.Category__c+'\'';
            } 
            
            //--------Category Ends-----
            
             if(!volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.CategoryGroup__c!='All Category Groups'){
                volSoql +=' where ' + 'Category_Group__c='+'\''+rObj.SPE_Tracker__r.CategoryGroup__c+'\'';
            }
            else if(volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.CategoryGroup__c!='All Category Groups'){
                volSoql +=' AND' + ' Category_Group__c='+'\''+rObj.SPE_Tracker__r.CategoryGroup__c+'\'';
            } 
            
            //----------Category Group Ends-----
            
            if(!volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.CategoryCluster__c!='All Category Areas'){
                volSoql +=' where ' + 'CategoryCluster__c='+'\''+rObj.SPE_Tracker__r.CategoryCluster__c+'\'';
            }
            else if(volSoql.contains( ' where ' ) && rObj.SPE_Tracker__r.CategoryCluster__c!='All Category Areas'){
                volSoql +=' AND' + ' CategoryCluster__c='+'\''+rObj.SPE_Tracker__r.CategoryCluster__c+'\'';
            } 
            
            //------Category Area ends----
            
             if(!volSoql.contains( ' where' ) ){ 
            volSoql += ' where '+' Period__c >='+string.valueOf(startrangeDate) + ' AND Period__c <='+string.valueOf(endRangeDate);
             }
             else if(volSoql.contains( ' where' )){
          //query += ' AND'+' Supplier__c!=null';
              volSoql += ' AND'+' Period__c >='+string.valueOf(startrangeDate) + ' AND Period__c <='+string.valueOf(endRangeDate);
             } 
            system.debug('volSoql::'+volSoql);
            volList = database.query(volSoql);
                                           
            if(volList.size() > 0){
                trackerToWeightage.put(rObj.SPE_Tracker__c,(decimal)volList[0].get('total'));
            }    
            rObj.Weight__c = (decimal)volList[0].get('total');
            sReportList.add(rObj);
        }
        update sReportList;
        System.debug('ANVCD**'+trackerToWeightage);
    }
    
    global void finish(Database.BatchableContext BC){
       //SPE_ScorecardReportupdateFinalBatch finalbatch = new SPE_ScorecardReportupdateFinalBatch(trackerToWeightageSum,ParamId);
       //database.executeBatch(finalbatch,100);
    }
}