src/objects/SPE_CategoryInfo__c.object
<CustomObject>
    <fields>
        <fullName>CategoryCluster__c</fullName>
        <label>Category Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CategoryGroup__c</fullName>
        <label>Category Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Categories_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <label>Category Group</label>
        <picklist>
            <picklistValues>
                <fullName>All Category Groups</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Logistics Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Travel &amp; Fleet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R&amp;D and IT Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing and Manufacturing Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard and Interconnect Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mechanics &amp; RF Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RF &amp; Custom Components</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Systems and Embedded Power</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NI Materials</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Workforce Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontracting MS, NPO &amp; SI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subcontracting NI Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT HW &amp; Care Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IP Transport</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Repair &amp; Spares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basestation Antennas &amp; IBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnering Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research &amp; Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expenditures reported erroneously</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-managed expenditures</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Categories_Info</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scope Tag</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Category Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scope Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_CategoryInfoEXT.cls
public class SPE_CategoryInfoEXT
{
    public string caVal{get;set;}
    public string cgVal{get;set;}
    public string ctVal{get;set;}
    public SPE_CategoryInfo__c categoryInfo{get;set;}
    
    private String strPIData; 
    
    public SPE_CategoryInfoEXT(ApexPages.StandardController controller) 
    {
        if (controller.getId() == null)
        {
            categoryInfo = (SPE_CategoryInfo__c)controller.getRecord();
            
        }
        
        else
        {
            categoryInfo = [SELECT Id, CategoryCluster__c, CategoryGroup__c,Group__c, Category__c, Supplier__c, Contact__c FROM SPE_CategoryInfo__c WHERE Id =: controller.getId()];
            SPE_MathsUtil.ca1 = categoryInfo.CategoryCluster__c;
            SPE_MathsUtil.cg1 = categoryInfo.CategoryGroup__c;
            SPE_MathsUtil.ct1 = categoryInfo.Category__c;
        }
    }
    
    public PageReference save()
    {
        categoryInfo.CategoryCluster__c = caVal;
        categoryInfo.CategoryGroup__c = cgVal;
        categoryInfo.Category__c = ctVal;
        
        upsert categoryInfo;
        
        PageReference pr;
        
        if (categoryInfo.Supplier__c != null)
        {
            pr = new PageReference('/'+categoryInfo.Supplier__c);
        }
        
        else
        {
            pr = new PageReference('/'+categoryInfo.Contact__c);
        }
        
        return pr;
    }
    
    public PageReference cancel()
    {
        PageReference pr;
        
        if (categoryInfo.Supplier__c != null)
        {
            pr = new PageReference('/'+categoryInfo.Supplier__c);
        }
        
        else
        {
            pr = new PageReference('/'+categoryInfo.Contact__c);
        }
        
        return pr;
    }
}