src/objects/SPE_ScoringCalculation__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Scoring Calculations</relationshipLabel>
        <relationshipName>Scoring_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lower__c</fullName>
        <label>Lower</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ScoringTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scoring Template</label>
        <referenceTo>SPE_ScoringTemplate__c</referenceTo>
        <relationshipLabel>Scoring Calculations</relationshipLabel>
        <relationshipName>Scoring_Calculations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Upper__c</fullName>
        <label>Upper</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Scoring Calculation</label>
    <nameField>
        <displayFormat>SCI-{00000}</displayFormat>
        <label>Scoring Calculation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Calculations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPEPlan__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>SPEScoringTemplate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SPE Scoring Template</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5 AND 6)</booleanFilter>
            <filterItems>
                <field>SPE_ScoringTemplate__c.Stage__c</field>
                <operation>equals</operation>
                <value>Pilot, Published</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>SPE Key Users</value>
            </filterItems>
            <filterItems>
                <field>SPE_ScoringTemplate__c.Stage__c</field>
                <operation>equals</operation>
                <value>Published,Pilot</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>SPE User</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <filterItems>
                <field>SPE_ScoringTemplate__c.Stage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_ScoringTemplate__c</referenceTo>
        <relationshipLabel>SPE Plans</relationshipLabel>
        <relationshipName>SPE_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SPE Plan</label>
    <nameField>
        <displayFormat>SPE - {00000}</displayFormat>
        <label>SPE Plan Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPETracker__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>SPEPlan__c</fullName>
        <label>SPE Plan</label>
        <referenceTo>SPE_SPEPlan__c</referenceTo>
        <relationshipLabel>SPE Trackers</relationshipLabel>
        <relationshipName>SPE_Trackers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score_1_Upper_Bound__c</fullName>
        <label>Score 1 Upper Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_2_Lower_Bound__c</fullName>
        <label>Score 2 Lower Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_2_Upper_Bound__c</fullName>
        <label>Score 2 Upper Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_3_Loewr_Bound__c</fullName>
        <label>Score 3 Loewr Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_3_Upper_Bound__c</fullName>
        <label>Score 3 Upper Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_4_Lower_Bound__c</fullName>
        <label>Score 4 Lower Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_4_Upper_Bound__c</fullName>
        <label>Score 4 Upper Bound</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SPE Tracker</label>
    <nameField>
        <label>SPE Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_TrackerScore__c.object
<CustomObject>
    <fields>
        <fullName>SPETracker__c</fullName>
        <label>SPE Tracker</label>
        <referenceTo>SPE_SPETracker__c</referenceTo>
        <relationshipLabel>Tracker Scores</relationshipLabel>
        <relationshipName>Tracker_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SPE_Rank__c</fullName>
        <label>SPE Rank</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>7</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracker Scores</relationshipLabel>
        <relationshipName>Tracker_Scores</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tracker Score</label>
    <nameField>
        <displayFormat>Score-{0000}</displayFormat>
        <label>Tracker Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracker Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SPE_TrackerValues__c.object
<CustomObject>
    <fields>
        <fullName>Avg_Piller_Score__c</fullName>
        <label>Avg Pillar Score</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>KPI Definition</label>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>Tracker Value</relationshipLabel>
        <relationshipName>Tracker_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MAX_Piller_score__c</fullName>
        <label>MAX Pillar score</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Piller_Score__c</fullName>
        <label>Min Pillar Score</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pillar_Rank__c</fullName>
        <label>Pillar Rank</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Piller__c</fullName>
        <formula>TEXT(KPIDefinition__r.Group1__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pillar</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Piller_score__c</fullName>
        <formula>( Vlauecalculation__c/ Sumofpillerweight__c)*100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pillar score</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPETracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Tracker</label>
        <referenceTo>SPE_SPETracker__c</referenceTo>
        <relationshipLabel>Tracker Value</relationshipLabel>
        <relationshipName>Tracker_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPE_Rank__c</fullName>
        <label>SPE Rank</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SPE_Score__c</fullName>
        <label>SPE Score</label>
        <precision>16</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score1__c</fullName>
        <label>Score1</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_1_Lower_Bound__c</fullName>
        <label>Score 1 Lower Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_1_Upper_Bound__c</fullName>
        <label>Score 1 Upper Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_2_Lower_Bound__c</fullName>
        <label>Score 2 Lower Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_2_Upper_Bound__c</fullName>
        <label>Score 2 Upper Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_3_Loewr_Bound__c</fullName>
        <label>Score 3 Loewr Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_3_Upper_Bound__c</fullName>
        <label>Score 3 Upper Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_4_Lower_Bound__c</fullName>
        <label>Score 4 Lower Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_4_Upper_Bound__c</fullName>
        <label>Score 4 Upper Bound</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Supplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tracker Value</relationshipLabel>
        <relationshipName>Tracker_Value</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>value1__c</fullName>
        <formula>(Score1__c)*( Weight__c/100)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>value1</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Tracker Value</label>
    <nameField>
        <displayFormat>Tracker-{00000}</displayFormat>
        <label>Tracker Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracker Value</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SPE_SPETrackerBatch2.cls
global class SPE_SPETrackerBatch2 implements Database.Batchable<sObject>
{

    global Id speTrackerIds;
    
     public SPE_SPETrackerBatch2 (String speTrackerId)
    {
        speTrackerIds = speTrackerId;
        
    }   

    global Database.QueryLocator start(Database.BatchableContext bc ){
    
     Id speTrackerIds = this.speTrackerIds;
     system.debug('speTrackerIdsspeTrackerIds '+speTrackerIds );
    
    String query1 = 'select id, Score1__c,value1__C,piller__C,KPIDefinition__c,supplier__C,Weight__c,SPE_Score__c,SPE_Rank__c,SPETracker__c,Pillar_rank__C from SPE_TrackerValues__c WHERE SPETracker__c     =:speTrackerIds';
    
    return Database.getQueryLocator(query1);
      }
    global void execute(Database.BatchableContext be, list<SPE_TrackerValues__c> trackvallist)
    {
      
        List<AggregateResult> result  = new List<AggregateResult>();
        
        for(SPE_TrackerValues__c  spetrackavg : trackvallist){
         result  = [select SPETracker__c,MIN(value1__C) minval1, AVG(Piller_score__c) avgval,MIN(Piller_score__c) minval, MAX(Piller_score__c) maxval from SPE_TrackerValues__c where SPETracker__c =:spetrackavg.SPETracker__c and Piller__c=:spetrackavg.Piller__c and Piller_score__c!=0 group by SPETracker__c];
            Decimal avg;
            Decimal min;
            Decimal max;   
            Decimal minv1; 
            
      for(AggregateResult ag : result){
   
           avg = (Decimal)ag.get('avgval');
           max = (Decimal)ag.get('maxval');
           min = (Decimal)ag.get('minval');
          minv1 = (Decimal)ag.get('minval1');
         }
          
          spetrackavg.MAX_Piller_score__c = max;
          spetrackavg.min_Piller_score__c = min;
          spetrackavg.avg_Piller_score__c = avg;
          update spetrackavg;
          //spetrackavg_ls.add(spetrackavg);
        }
        
        
        //--------------------------------------pillar ranks
        list<SPE_TrackerValues__c> pillarranks = new list<SPE_TrackerValues__c>();
         for(SPE_TrackerValues__c  traval : trackvallist)
       {
           system.debug('test--test');
          pillarranks = [select Piller_score__c,Pillar_rank__C from SPE_TrackerValues__c where SPETracker__c=:traval.SPETracker__c and Piller__c =:traval.Piller__c and Piller_score__c!=null  order by Piller_score__c DESC];
           
          if(!pillarranks.isEmpty()){
           
                system.debug('test1-test1');
           decimal 	temp = 0;
           integer count = 0;
           for(integer i =0;i<pillarranks.size();i++){
            decimal  val   = pillarranks[i].piller_score__C;
               if(val!=0){
               if(temp==0){
                   count = count+1;
               pillarranks[i].pillar_rank__C = count;  
                   temp = pillarranks[i].piller_score__C;
               }else if(temp== val){
                 pillarranks[i].pillar_rank__C = count; 
                     temp = pillarranks[i].piller_score__C;
               }else{
                    count = count+1;
               pillarranks[i].pillar_rank__C = count;  
               temp = pillarranks[i].piller_score__C;
               }	
               }}
           update pillarranks;            
            
           }
           
       }  
        //----------------------------
         /*list<SPE_TrackerScore__c> speranks = new list<SPE_TrackerScore__c>();
         list<SPE_TrackerValues__c> tralist = new list<SPE_TrackerValues__c>();
        list<SPE_TrackerValues__c> tralist1 = new list<SPE_TrackerValues__c>();
         speranks = [select Score__c,SPE_Rank__c,supplier__C from SPE_TrackerScore__c where  SPE_Rank__c != null and SPETracker__c=:speTrackerIds ];
        
        for(SPE_TrackerScore__c spe : speranks){
            tralist = [select id,supplier__C,SPE_Rank__c from SPE_TrackerValues__c where supplier__C=:spe.Supplier__c and SPETracker__c=:speTrackerIds];
            for(SPE_TrackerValues__c tra : tralist){
                if(tra.supplier__C == spe.Supplier__c) {
                    tra.SPE_Rank__c = spe.SPE_Rank__c;
                    tralist1.add(tra);
                }               
            }
        }
        update tralist1;*/
        
        Set<Id> suppid = new Set<Id>();
        list<SPE_TrackerValues__c> tralist = new list<SPE_TrackerValues__c>();
         list<SPE_TrackerValues__c> tralist1 = new list<SPE_TrackerValues__c>();
        tralist = [select id,supplier__C,SPE_Rank__c from SPE_TrackerValues__c where  SPETracker__c=:speTrackerIds];
        for(SPE_TrackerValues__c t : tralist){
            suppid.add(t.supplier__C);
        }
        List<SPE_TrackerScore__c> traslist = [select Score__c,SPE_Rank__c,supplier__C from SPE_TrackerScore__c where  SPE_Rank__c != null and SPETracker__c=:speTrackerIds and supplier__C in :suppid];
        Map<Id,SPE_TrackerScore__c> trackerscoreMap = new Map<Id,SPE_TrackerScore__c>();
        for (SPE_TrackerScore__c tra: traslist) {
        trackerscoreMap.put(tra.supplier__C, tra);
        }
       
       for (SPE_TrackerValues__c t1: tralist) {
           
       SPE_TrackerScore__c tras = trackerscoreMap.get(t1.supplier__C);
           try{
           if (t1.supplier__C == tras.Supplier__c) {
          t1.SPE_Rank__c = tras.SPE_Rank__c;
          tralist1.add(t1);
       } 
           }catch(exception e){}
      }
      update tralist1;
        //threshold 
      list<SPE_SPETracker__c> spetraclist = new list<SPE_SPETracker__c>();
      list<SPE_SPEPlan__c> speplanlist = new list<SPE_SPEPlan__c>();
      list<SPE_ScoringCalculation__c> Thresholdscore = new list<SPE_ScoringCalculation__c>();
      spetraclist = [select name,SPEPlan__c from SPE_SPETracker__c where id =:speTrackerIds]; 
        
        set<id> temptrackerId = new set<id>();
        for(SPE_SPETracker__c spetracker : spetraclist)
        {
         	temptrackerId.add(spetracker.SPEPlan__c);
        }
       	speplanlist = [select name,SPEScoringTemplate__c from SPE_SPEPlan__c where id IN:temptrackerId];  
       system.debug('speplanlistspeplanlist'+speplanlist);
            for(integer j=0;j<speplanlist.size();j++){
                 for(integer i =0;i<trackvallist.size();i++){
           Thresholdscore = [select name,Lower__c,Upper__c,Score__c from SPE_ScoringCalculation__c where KPIDefinition__c=:trackvallist[i].KPIDefinition__c and ScoringTemplate__c=:speplanlist[j].SPEScoringTemplate__c];
    
            }
        }
        system.debug('ThresholdscoreThresholdscore'+Thresholdscore);
        for(SPE_TrackerValues__c spetval : trackvallist){
              system.debug('ThresholdscoreThresholdscore1'+Thresholdscore);
       
        for(SPE_ScoringCalculation__c score : Thresholdscore)
        {
           system.debug('ThresholdscoreThresholdscore1'+Thresholdscore);
            if(score.score__c==1){
                 system.debug('ThresholdscoreThresholdscore1'+Thresholdscore);
               spetval.Score_1_Lower_Bound__c = score.Lower__c;
               spetval.Score_1_Upper_Bound__c = score.Upper__c;
              
               update spetval;
            }
            else if(score.Score__c==2)
           {
              
              spetval.Score_2_Lower_Bound__c = score.Lower__c;
              spetval.Score_2_Upper_Bound__c = score.Upper__c;  
              
               update spetval;
           }
            else if(score.Score__c==3)
            {
              SPE_TrackerValues__c spetrac = new SPE_TrackerValues__c();
              spetval.Score_3_Loewr_Bound__c = score.Lower__c;
              spetval.Score_3_Upper_Bound__c = score.Upper__c;    
               
                update spetval;
            }
            else if(score.Score__c==4)
            {
            
              spetval.Score_4_Lower_Bound__c = score.Lower__c;
              spetval.Score_4_Upper_Bound__c = score.Upper__c;
               
                update spetval;
            }
            else{
              
               spetval.Score_4_Lower_Bound__c = null;
               spetval.Score_4_Upper_Bound__c = null;
              
                update spetval;
            }
        }
           
    }
        
        
        //threshold
    }  
      
    global void finish(Database.BatchableContext bc){
        
        String userEmail =String.valueof(Userinfo.getUserEmail()); 
        String trackerName= [select Name from SPE_SPETracker__c where Id=: speTrackerIds].name;
        String speplanid= [select SPEPlan__r.name,Name from SPE_SPETracker__c where Id=: speTrackerIds].SPEPlan__r.name;
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
        
        String[] toAddresses = new String[] {userEmail}; 
        mail.setToAddresses(toAddresses); 
        mail.setSubject(System.Label.SPE_MailSubjectBatch5); 
        String body = 'SPE Plan-'+speplanid+ 'and SPE Tracker-' +trackerName+' scheduled by '+String.valueof(UserInfo.getFirstName())+' '+String.valueof(UserInfo.getLastName())+ ' is completed successfully.'+ ''+'Please Find The Link:';
        body = body + '  '+URL.getSalesforceBaseUrl().toExternalForm() + '/'+speTrackerIds; 
        mail.setPlainTextBody(body); 
        Messaging.sendEmail(new Messaging.SingleEMailMessage[]{mail});
    
    }  
}