src/objects/SPE_KPIDefinition__c.object
<CustomObject>
    <customHelpPage>SPE_KPI_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <picklist>
            <picklistValues>
                <fullName>BL1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>BU1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BU4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finland</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LifecycleStage__c</fullName>
        <inlineHelpText>KPI can not be used until Published</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>SubRegion</label>
        <picklist>
            <picklistValues>
                <fullName>Eastern Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle Asia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Asia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>KPI</label>
    <nameField>
        <displayFormat>KPI-{000000}</displayFormat>
        <label>KPI Sequential ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>KPI</pluralLabel>
    <recordTypes>
        <fullName>Published</fullName>
        <active>true</active>
        <label>Published</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/SPE_SPEKPIMap__c.object
<CustomObject>
    <fields>
        <fullName>KPIDefinition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>KPI Definition</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SPE_KPIDefinition__c.LifecycleStage__c</field>
                <operation>equals</operation>
                <value>Published, Pilot</value>
            </filterItems>
            <filterItems>
                <field>SPE_KPIDefinition__c.PI_Data__r.ValuesType__c</field>
                <operation>notEqual</operation>
                <value>Boolean, String, Date</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SPE_KPIDefinition__c</referenceTo>
        <relationshipLabel>SPE KPI Maps</relationshipLabel>
        <relationshipName>SPE_KPI_Maps</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SPETemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SPE Template</label>
        <referenceTo>SPE_SPETemplate__c</referenceTo>
        <relationshipLabel>SPE KPI Maps</relationshipLabel>
        <relationshipName>SPE_KPI_Maps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SPE KPI Map</label>
    <nameField>
        <displayFormat>SKMI-{00000}</displayFormat>
        <label>SPE KPI Map Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPE KPI Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SPE_SPETemplate__c.object
<CustomObject>
    <customHelpPage>SPE_SPE_Definition_Help_Page</customHelpPage>
    <fields>
        <fullName>BusinessLine__c</fullName>
        <label>Business Line</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BusinessUnit__c</fullName>
        <label>Business Unit</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>GLOBAL SERVICES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MATURE SOFTWARE PRODUCTS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MOBILE BROADBAND</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPTICAL NETWORKS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Geo_Hierarchy__c</fullName>
        <description>Field to store the Geo Hierarchy</description>
        <label>Geo Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>Product Hierarchy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <picklist>
            <controllingField>Country__c</controllingField>
            <picklistValues>
                <fullName>All Project</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AF AWCC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMC 2G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL VODAFONE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL M4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL PLUS CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ OOREDOO ALGERIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DZ.ORASCOM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ALGERIA TELECOM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CTI MOVIL ARG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TELEFONICA PANAMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR CTI MOVIL 3G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR CABLEVISION NGN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR TELECOM PERSONAL 3G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR TELECOM PDH/SDH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR CLARO ARGENTINA SWAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR TECO TDM EVOLUTION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEXTEL ARGENTINA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM ORANGE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPTUS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VODAFONE AUSTRALIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU DOT DTRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU NBN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT H3G OLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT NETCO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT CALDERA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT TMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT H3G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT A1 AUSTRIA CARE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT ORANGE AUSTRIA CARE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Market</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <inlineHelpText>SPE Template can not be Published without a Scoring Template</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubRegion__c</fullName>
        <label>Market Unit</label>
        <picklist>
            <picklistValues>
                <fullName>--None--</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>SPE Template</label>
    <nameField>
        <label>SPE Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPE Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SPE_SPETemplateTrigger.cls
public with sharing class SPE_SPETemplateTrigger 
{
    public static void DeleteValidation (List<SPE_SPETemplate__c> oldSPETemps)
    {
        for(SPE_SPETemplate__c spe: oldSPETemps)
        {
            if(spe.Stage__c == 'Published')
            {
                spe.addError('You cannot delete SPE Template');
            }
        }
    }
    
    public static void UpdateKPIDefinition(List<SPE_SPETemplate__c> newSPETemps, Map<Id, SPE_SPETemplate__c> oldSPETempMaps)
    {
        Set<Id> speTempIds = new Set<Id>();
        
        for (SPE_SPETemplate__c spe : newSPETemps)
        {
            if (spe.Stage__c == 'Published' && spe.Stage__c != oldSPETempMaps.get(spe.Id).Stage__c )
            {
                speTempIds.add(spe.Id);
            }
        }
        
        if (speTempIds.size() > 0)
        {
            List<SPE_KPIDefinition__c> toBeUpdatedKPI = new List<SPE_KPIDefinition__c>();
            
            for (SPE_SPEKPIMap__c speKPI : [SELECT KPIDefinition__c 
                                             FROM SPE_SPEKPIMap__c 
                                             WHERE SPETemplate__c In: speTempIds 
                                             AND KPIDefinition__r.LifecycleStage__c = 'Draft'])
            {
                SPE_KPIDefinition__c kpi = new SPE_KPIDefinition__c();
                kpi.Id = speKPI.KPIDefinition__c;
                kpi.LifecycleStage__c = 'Published';
                
                toBeUpdatedKPI.add(kpi);
            }
            
            update toBeUpdatedKPI;
        }
    }
    
    public static void updateHierarchyFields(List<SPE_SPETemplate__c> newSPETemps){
        
        for(SPE_SPETemplate__c spe :newSPETemps){
            spe.Geo_Hierarchy__c = spe.Region__c+'-->'+spe.SubRegion__c+'-->'+spe.Country__c+'-->'+spe.Project__c;
            spe.Product_Hierarchy__c = spe.BusinessUnit__c+'-->'+spe.BusinessLine__c+'-->'+spe.Product__c;
            spe.Category_Hierarchy__c = spe.CategoryCluster__c+'-->'+spe.CategoryGroup__c+'-->'+spe.Country__c;
            
        }    
       
         
    }
   
}