src/objects/Trace_Email__c.object
<CustomObject>
    <fields>
        <fullName>Claim_ID__c</fullName>
        <externalId>true</externalId>
        <label>Claim ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Claim__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Claim</label>
        <referenceTo>MCAR_Claim_Management__c</referenceTo>
        <relationshipLabel>Trace Emails</relationshipLabel>
        <relationshipName>Trace_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Time_Opened__c</fullName>
        <label>Last Time Opened</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Number_Of_Times_Email_Opened__c</fullName>
        <label>Number Of Times Email Opened</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Trace Email</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>Email Trace</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trace Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TraceEmailStatus.cls
public without sharing class TraceEmailStatus {
    
    private String claimID;
    
    public TraceEmailStatus()
    {
        claimID = ApexPages.currentPage().getParameters().get('Id');
        System.debug('Claim ');
    }
    
    public void traceEmail(){
        Decimal noOfTimesOpened = 0;
        if(claimID != null){
            list<Trace_Email__c> traceEmailRecord = [select Number_Of_Times_Email_Opened__c from Trace_Email__c where Claim_ID__c =: claimID];
            if(traceEmailRecord != null && !traceEmailRecord.isEmpty()){
                noOfTimesOpened = traceEmailRecord[0].Number_Of_Times_Email_Opened__c;
            }
        }
        Trace_Email__c emailTrace = new Trace_Email__c();
        emailTrace.Number_Of_Times_Email_Opened__c = ++noOfTimesOpened;
        emailTrace.Last_Time_Opened__c = Datetime.now();
        emailTrace.Claim_ID__c  = claimID;
        emailTrace.Claim__c = claimID;
        upsert emailTrace Claim_ID__c;
 
        //You can also modify the code accordingly like to count how many times the same email is opened
    }
}